### ISSUE TITLE
Quick questions 

### ISSUE THREAD

**Issue by ghostyplayz** [UnamSanctam/SilentCryptoMiner#1002]
I'm using pool.hashvault.pro:80 fpr cpu. Do i need to enable nicehash mining?

**Comment by UnamSanctam** [comment]
No you should not use that for hashvault.

**Comment by ghostyplayz** [comment]
thanks for the answer!

Also, every time it gets grabs it works for about >20 minutes then stops. It also doesn't seem to work on there startup. Could i be doing something wrong? (I have everything on bar from shellcode loader, auto-delete, install route kit, pause for obstification, block websites. (not including miner settings they are setup right). Any obvious problem?

**Comment by UnamSanctam** [comment]
Do you have a web panel where you can check your miners? Since otherwise there isn't much information I can work from, and I can't really know of a problem with the setup without getting your full settings (the .xml file when you press "Save" in the "Main" tab). Also, I don't know how many miners you have but HashVault does have a ban on mining with many miners without a proxy as it says on their website:
<img src="https://user-images.githubusercontent.com/10323655/183523899-908d2a09-f844-4cda-8cd2-41e84fe3c826.png">

**Comment by ghostyplayz** [comment]
Trying to set up the web panel now. Any free way I can set up the web panel if I self-host? If not, could you recommend me a good free website to do it from?

Sorry for being such a pain, thanks for all the help.

**Comment by UnamSanctam** [comment]
If you self-host then you can just set up a local webserver and host it from there (for Windows you can use XAMPP or WAMP for really easy setup https://github.com/UnamSanctam/UnamWebPanel#for-local-testing) but if others are going to connect to it then your IP will be exposed of course. There aren't really any free online webhosts though that I know of, most are really bad. There is someone setting up free webhosting for the panel though but he's currently on break for a while.

**Comment by ghostyplayz** [comment]
Could i stop my ip from being exposed just by using a VPN? And is it fine if my pc isn't always on?

**Comment by UnamSanctam** [comment]
Yes you can use a VPN as long as it supports port forwarding, preferably a static port that doesn't change. You don't need the web panel to be running all the time (it's used for monitoring and/or changing settings) so you can just start it whenever needed, though if you use the web panel for configurations then they will only apply while it's running of course.

**Comment by ghostyplayz** [comment]
With doing it this way, can my ISP see anything happening? (just cautious as this is forwarding ports)

**Comment by UnamSanctam** [comment]
Not if you're using a VPN for it.

**Comment by ghostyplayz** [comment]
When using xampp should i connect it to all my public miners as well or will it cause them to stop when my xampp goes down?

**Comment by UnamSanctam** [comment]
If your webserver goes down then they will just ignore it and continue mining, so connecting any to it would be fine.

**Comment by ghostyplayz** [comment]
Currently trying to run xampp but it goes straight to http://localhost/dashboard/ and isn't opening up. ( currently using windscribe as my vpn)

**Comment by UnamSanctam** [comment]
Open the XAMPP control panel and press "Start" next to Apache. Then extract all the web panel files into `C:\xampp\htdocs` (delete all the files already there). Then you should be able to see the web panel when you visit http://localhost/. Then you'll also have to change Apache to use whatever port you set up since Windscribe doesn't allow port 80 and port 443 (default website ports), you can follow this simple guide https://www.phpflow.com/php/how-to-change-xampp-apache-server-port/.

>Also, if my ports get reported could my ip adress company know its me?

I meant that they see the VPN protocol port, for example the port your Windscribe is communicating on, they don't know your port forwarded port.
