### ISSUE TITLE
can i change the miner i.e from XMR to ETC using the API endpoint or using webpannel?

### ISSUE THREAD

**Issue by zanatechnology** [UnamSanctam/SilentCryptoMiner#101]
as you saw dear unam from the title can i use the webpannel to use the methodology of the miner from XMR to ETC or anyother mining algorithms just by using webpannel and second question ill post here too is that does i need remote configuration while i use API endpoint ?

**Comment by UnamSanctam** [comment]
Since there are two "miners" you can switch between either ethash/etchash (ethminer, green GUI) for one and all the other algorithms on the other (XMRig, orange color) depending on what miner it is. You can switch between the algorithms in the same "miner" from the web panel. And no the "Remote Configuration" is not required for the web panel.

**Comment by zanatechnology** [comment]
like if only i installed and ran XMR miner console then the computer is out of my area so i use it back and i want to add ETC can i do via web pannel? @UnamSanctam

**Comment by UnamSanctam** [comment]
No, since you don't have an ethminer embedded into your program.
