### ISSUE TITLE
Questions about defender exclusion

### ISSUE THREAD

**Issue by moasdfkasf** [UnamSanctam/SilentCryptoMiner#1015]
Hi I am currently using a crypter which provides defender exclusion. If I turn on defender exclusion in builder not in crypter. cryptedminer.exe is excluded from defender? I hate defender exclusion option in crypter because It pops up some texts(to notify users that this is a cmd file) to users. 

And what happens If I dont use defender exclusion at all in both of them? Miner does not work after start up?

**Comment by UnamSanctam** [comment]
Windows Defender exclusions means that Windows Defender won't scan any of the files specified in the exclusions. The miners Windows Defender exclusions excludes the entire system drive so that's not a problem, though usually it's better to do the exclusions in the crypter since the crypter runs before the miner (the earlier the better).

If you don't use it in neither then there just won't be any exclusions, so Windows Defender will be free to find and remove files if it can find them.
