### ISSUE TITLE
not mining on vitcims

### ISSUE THREAD

**Issue by okau20** [UnamSanctam/SilentCryptoMiner#1016]
hey i spreaded the .exe (binded it with a csgo cheat) 
a couple of randoms downloaded it and ran it (since they said the cheats worked)
but when i run the minerchecker.exe it does not seem like they are mining anything.

**Comment by UnamSanctam** [comment]
When you run the checker on their computer?

**Comment by okau20** [comment]
no on my computer
does the checker only checks for its own computer?

**Comment by UnamSanctam** [comment]
Yes of course, it's decentralized, if you wanted to check all the miner from your own computer then all the miner would need to connect to your computer (which would expose your IP). Either check if they're mining on the pool itself or you can host a web panel (https://github.com/UnamSanctam/UnamWebPanel/) and connect your miners to that.

**Comment by okau20** [comment]
i checked on the pool and it says i dont have any workers online
that is weird

**Comment by okau20** [comment]
[miner eth.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9303535/miner.eth.zip)
here a zip containing the .xml file which is called miner eth.xml

**Comment by UnamSanctam** [comment]
Since you're mining ETH then to mine the GPU needs at least 5GB of free VRAM which not everyone has which could be the reason. You also don't have Windows Defender exclusions so Windows Defender could have removed it as well if the binder isn't adding exclusions or if you don't have some other way to get around detections. You can find what each function does in the wiki https://github.com/UnamSanctam/SilentCryptoMiner/wiki and you can also see how I've done things in the example settings: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings

**Comment by okau20** [comment]
okay thank you for your answer.
I did add exclusions in the binder but i dont think windows defender is a problem since they know the program is going to be detected anyways, because it is advertised as a cheat.
Do you think mining a cpu coin would be better?

**Comment by UnamSanctam** [comment]
You can mine both at the same time, CPU mining is less profitable but has very low requirements, GPU mining is a lot more profitable but has quite high requirements. Requirements also depends on the algorithm and coin being mined.

**Comment by okau20** [comment]
Okay do you know which coin requires the less to mine?
i would prefer gpu mining, but if only 1 person out of 10 is going to be able to mine.. well

**Comment by UnamSanctam** [comment]
Here is a list of DAG sizes (how much VRAM is required): https://minerstat.com/dag-size-calculator and here is a list of GPU coin profitability: https://whattomine.com/coins where you can enter the GPUs, though don't rely on it too much since the market is quite volatile. The most popular coin to silent mine is probably ETC since it only requires 3GB of VRAM and is very close to ETH in profitability, if you need a really low VRAM coin then you can also mine UBQ which only needs 1.7GB of VRAM.

**Comment by okau20** [comment]
okay im going to load the example full settings
in the miner settings, in wallet adress, at the end of the one that was already written there is something like {COMPUTERNAME}
do i have to keep this part?

**Comment by UnamSanctam** [comment]
No you don't need it, the `{COMPUTERNAME}` is the worker name, entering that will cause the worker name in the pool to become the computers name so that they are unique in the pool. You can remove `.{COMPUTERNAME}` if you want (don't forget to remove the dot (.) before it).

**Comment by okau20** [comment]
okay thank you very much

**Comment by tuluvo345** [comment]
> hey i spreaded the .exe (binded it with a csgo cheat) a couple of randoms downloaded it and ran it (since they said the cheats worked) but when i run the minerchecker.exe it does not seem like they are mining anything.


man how did you mix miner's executor with another executor? Do you have any teaching material?
