### ISSUE TITLE
rootkit

### ISSUE THREAD

**Issue by pcflux** [UnamSanctam/SilentCryptoMiner#1032]
Would you recommend using rootkit or no?
I was using rootkit and lost few miners and im not sure if that was because of AV or rootkit.

**Comment by UnamSanctam** [comment]
It depends, I haven't received any reports (using the latest version) of the rootkit not working but there could be something unreported since the rootkit is quite impactful. Someone just reported a new detection that was added to Windows Defender for the Task Scheduler task in another issue which I'm now investigating, maybe that could be the cause.
