### ISSUE TITLE
Microsoft Defender

### ISSUE THREAD

**Issue by Dlkuric** [UnamSanctam/SilentCryptoMiner#1038]
Hello,

I got attacked by Microsoft Defender today :-)
my cryptominer went from 4000mh/s to 0, so I did various tests.

I understood what is happening, I used to put C:/ in exclusion before running the cryptominer but since yesterday Microsoft defender removes the exclusion of C:/ or C:/windows, I therefore seek to know more precisely which file should be excluded from the anti virus to run the cryptominer?

thank you very much

**Comment by UnamSanctam** [comment]
Yes I noticed that too, exclude the %ProgramFiles% and %UserProfile% for the miner. In the next version it will move away from excluding %SystemDrive% (C:) to %ProgramFiles% and %UserProfile% (already excludes that) instead unless they remove that too. You can exclude the exact file too (though then people will know exactly where it is if they check the exclusions) but then you'll have to get the path from what you choose in the builder.

**Comment by Dlkuric** [comment]
ok thank you

**Comment by Dlkuric** [comment]
hello,

I am struggling a bit in powershell maybe someone will have the answer, to exclude the files I create a .bat which contains:

powershell Add-MpPreference -ExclusionPath %ProgramFiles%

it does not work while it works with other folders like C:/Users, I manage to exclude programFiles if I open cmd manually but not from a .bat.

Do you know how to do it ?

thank

**Comment by UnamSanctam** [comment]
You'll have to replace the environmental variable with its powershell equivalent like:
```
powershell Add-MpPreference -ExclusionPath $env:ProgramFiles
```

**Comment by JosepP2** [comment]
> You'll have to replace the environmental variable with its powershell equivalent like:
> 
> ```
> powershell Add-MpPreference -ExclusionPath $env:ProgramFiles
> ```

that was big mistake when you add C: exclusion, 
i had removed when i saw it. it's not necessarry and it's big fail to get detected yourself .
even you add Randomi().

whats point of that when you add installfolder to exclusion and you adding it extra C:
programfiles and system32 etc.. its easy add only install folder replacing it like #MINERID
im sorry for all your lost people.
i sent you mail to fix this before it late. you didn't respond me from protonmail.

also thanks to you again to making this free project, you saved my life when i was near of mountain i hope mining will remain after eth merge
(you'll remember this word)

**Comment by UnamSanctam** [comment]
> that was big mistake when you add C: exclusion, i had removed when i saw it. it's not necessarry and it's big fail to get detected yourself . even you add Randomi().

It was "necessary" before since it got installed into System32 when "Run as System" was enabled and the System32 exclusion didn't always work, the only problem now was that I didn't add a specific ProgramFiles exclusion when I changed the "Run as System" installation folder to ProgramFiles. It didn't get detected because it added `C:`, it got detected because of a static detection after the base64 decode, but that detection lead to `C:` getting removed which seems to be a new feature. So you can still exclude `C:` just fine, it's just that if you ever get an ExcludeProc detection from anything then it seems to remove the `C:` exclusion as a precaution.

>whats point of that when you add installfolder to exclusion and you adding it extra C:
programfiles and system32 etc.. its easy add only install folder replacing it like #MINERID

Because people have extra files they add and such so then it adds and exclusion to the entire drive as a precaution, but it also makes the originating folder harder to spot for any user that notices the detection (if their binary is undetected and doesn't get detected when the exclusion is removed).

>i sent you mail to fix this before it late. you didn't respond me from protonmail.

I don't think I've ever gotten an email from you, my mail is unams@protonmail.com. Unless it was an email in a long chain of emails between us in case I could have missed the response, other than that I've only ever forgot to respond to the first email from someone once and that didn't have to do with exclusions.

>also thanks to you again to making this free project, you saved my life when i was near of mountain i hope mining will remain after eth merge
(you'll remember this word)

Good to hear, ETC, UBQ and all other ethash coins will still work after the merge so there's not too much to worry about.
