### ISSUE TITLE
Auto Updater & some questions

### ISSUE THREAD

**Issue by varysuzuki** [UnamSanctam/SilentCryptoMiner#1046]
What would be the most optimal, stable & stealthy way to make the miner check for miner updates since rn im temporarily using quasar rat to update it but i dont really like that method, could i by chance make the miner check bitbucket for a encrypted miner, decrypts it then tries to do ReadAllBytes to its own location and compares it, if its different and not 0 it will write itself to temp and open itself, but that seems like a detected way and idk about that and idk what to do

Also, i looked into QuasarRAT's startup code recently since my startup isnt as stable and i wanna know why you dont use schtasks.exe directly and why dont u check the ExitCode value so if its not 0 it will do the registry startup method

Edit:
Also why are u protecting the miner instead of just the watchdog? i thought u said u will protect the watchdog only

**Comment by UnamSanctam** [comment]
>What would be the most optimal, stable & stealthy way to make the miner check for miner updates since rn im temporarily using quasar rat to update it but i dont really like that method, could i by chance make the miner check bitbucket for a encrypted miner, decrypts it then tries to do ReadAllBytes to its own location and compares it, if its different and not 0 it will write itself to temp and open itself, but that seems like a detected way and idk about that and idk what to do

Easiest way to update would be to have some sort of version string inside the miner, then it checks an online text document to see if the version string is different, if it is then download a file from a download link that contains the new miner. Problem is that you would also need the uninstaller unless you incorporate the uninstaller directly into the miner.

>Also, i looked into QuasarRAT's startup code recently since my startup isnt as stable and i wanna know why you dont use schtasks.exe directly and why dont u check the ExitCode value so if its not 0 it will do the registry startup method

Because using schtasks.exe directly like how it was before is very limited and can't customize all the optimal options. There's no real need to check the ExitCode, I haven't ever seen if fail but even then if the miner is running as administrator then it "can't" install using the Registry anyways, since that doesn't support running files as administrator silently. It will always ask the user for permission on each startup if you use the registry, so you'd have to modify the UAC settings and such to disable it. It also means that it would only be able to run on users that have administrator permissions.

>Also why are u protecting the miner instead of just the watchdog? i thought u said u will protect the watchdog only

Because I found a good method of doing it on the miners as well by creating a new library that can be called by the miner installer/injector or uninstaller to protect or unprotect a process. I also changed quite a few things in the miners so that they shouldn't really ever close on their own as well (since it would cause a BSoD).

**Comment by varysuzuki** [comment]
> Easiest way to update would be to have some sort of version string inside the miner, then it checks an online text document to see if the version string is different, if it is then download a file from a download link that contains the new miner. Problem is that you would also need the uninstaller unless you incorporate the uninstaller directly into the miner.

oh yeah the uninstaller part will become a problem but i thought of making it create/obfuscate a new random miner build on a website request and then make the miner have a check if the original miner build time has past a week, since then i dont have to do really anything but it will be really slow i think, another way is yeah what you said but wont that be detected? 

> Because using schtasks.exe directly like how it was before is very limited and can't customize all the optimal options. There's no real need to check the ExitCode, I haven't ever seen if fail but even then if the miner is running as administrator then it "can't" install using the Registry anyways, since that doesn't support running files as administrator silently. It will always ask the user for permission on each startup if you use the registry, so you'd have to modify the UAC settings and such to disable it. It also means that it would only be able to run on users that have administrator permissions.

i meant the windows 7 startup, but ur right. 

> Because I found a good method of doing it on the miners as well by creating a new library that can be called by the miner installer/injector or uninstaller to protect or unprotect a process. I also changed quite a few things in the miners so that they shouldn't really ever close on their own as well (since it would cause a BSoD).

what if they kill the miner? then the watchdog will have no point?

and also is the only way to change the ip of the web panel using a domain? since my vpn is gonna expire and if i dont have money then i wont get my ports back and stuff.

alsooo so you wont release the clipper at all? and hows the stealer

**Comment by shainodev** [comment]
is the sleep time suggested to be 15? i thought it was good at 50 all along

**Comment by shainodev** [comment]
also i have a problem with obfuscating with net reactor, i obfuscate the watchdog with it, it works then i try obfuscating the miner and it gives shit ton of errors

**Comment by UnamSanctam** [comment]
>oh yeah the uninstaller part will become a problem but i thought of making it create/obfuscate a new random miner build on a website request and then make the miner have a check if the original miner build time has past a week, since then i dont have to do really anything but it will be really slow i think, another way is yeah what you said but wont that be detected?

Detections would be the same as any other website request would be.

>what if they kill the miner? then the watchdog will have no point?

Both the miners and watchdog are critical processes so you can't kill either without first removing the critical status, if you succeed in doing that and then kill the miner then the watchdog would just start it up again like always. If they forcefully kill the miner anyways then the computer would just BSoD and restart.

>and also is the only way to change the ip of the web panel using a domain? since my vpn is gonna expire and if i dont have money then i wont get my ports back and stuff.

Yes, how else would you change the IP dynamically? Other than that you can change the web panel URL through the "Remote Configuration" though.

>alsooo so you wont release the clipper at all? and hows the stealer

Not sure, I've been asked by quite a few not to release the clipper, especially on Hack Forums. I think crypto clippers aren't even allowed to be posted there. The stealer is technically working though I haven't implemented the online connection to send things to the web panel and things like that yet, I also haven't made the final GUI for the builder (since that comes last)
.
> is the sleep time suggested to be 15? i thought it was good at 50 all along

Yes because most antivirus sandboxing usually takes around 5-10 seconds on average.

>also i have a problem with obfuscating with net reactor, i obfuscate the watchdog with it, it works then i try obfuscating the miner and it gives shit ton of errors, like it does when its already obfuscated with it

Try disabling the built-in obfuscations in the miner, it's in the "Advanced Options".

**Comment by shainodev** [comment]
> > oh yeah the uninstaller part will become a problem but i thought of making it create/obfuscate a new random miner build on a website request and then make the miner have a check if the original miner build time has past a week, since then i dont have to do really anything but it will be really slow i think, another way is yeah what you said but wont that be detected?
> 
> Detections would be the same as any other website request would be.
> 
> > what if they kill the miner? then the watchdog will have no point?
> 
> Both the miners and watchdog are critical processes so you can't kill either without first removing the critical status, if you succeed in doing that and then kill the miner then the watchdog would just start it up again like always. If they forcefully kill the miner anyways then the computer would just BSoD and restart.
> 
> > and also is the only way to change the ip of the web panel using a domain? since my vpn is gonna expire and if i dont have money then i wont get my ports back and stuff.
> 
> Yes, how else would you change the IP dynamically? Other than that you can change the web panel URL through the "Remote Configuration" though.
> 
> > alsooo so you wont release the clipper at all? and hows the stealer
> 
> Not sure, I've been asked by quite a few not to release the clipper, especially on Hack Forums. I think crypto clippers aren't even allowed to be posted there. The stealer is technically working though I haven't implemented the online connection to send things to the web panel and things like that yet, I also haven't made the final GUI for the builder (since that comes last) .
> 
> > is the sleep time suggested to be 15? i thought it was good at 50 all along
> 
> Yes because most antivirus sandboxing usually takes around 5-10 seconds on average.
> 
> > also i have a problem with obfuscating with net reactor, i obfuscate the watchdog with it, it works then i try obfuscating the miner and it gives shit ton of errors, like it does when its already obfuscated with it
> 
> Try disabling the built-in obfuscations in the miner, it's in the "Advanced Options".

i opened the miner and had critical process and debug on, and i removed the registry startup key and terminated both the watchdog (thats injected) and the miner using process hacker and nothing happened no bsod

**Comment by UnamSanctam** [comment]
>i opened the miner and had critical process and debug on, and i removed the registry startup key and terminated both the watchdog (thats injected) and the miner using process hacker and nothing happened no bsod

Are you running it as administrator? And it waits for 1 seconds before protecting the files in case there's some error during the start of a file.

>edit: also should i make the hosts editor check for admin or not

You need administrator permissions to edit the hosts file.

**Comment by shainodev** [comment]
> Are you running it as administrator? And it waits for 1 seconds before protecting the files in case there's some error during the start of a file.

oh making it critical requires administrator?

> You need administrator permissions to edit the hosts file.

yeah but should i make the code check for admin instead of just using a try catch

**Comment by shainodev** [comment]
and also even though the app is not admin but i will be running it as admin do i need to have -Verb Runas in the start command and stuff?

**Comment by shainodev** [comment]
ALSOO why when i sort status on web panel it doesnt show active it shows 2 offlines first then active

**Comment by UnamSanctam** [comment]
> oh making it critical requires administrator?

Yes, the RtlAdjustPrivilege and NtSetInformationProcess functions used need administrator privileges. There should be an administrator shield icon next to it in the builder, in the first release VS removed the shield icon so I had to choose the images 
in the picture boxes again and rebuild it and then reupload it (VS always does things like that, removes images, buttons, textboxes and labels randomly).

> yeah but should i make the code check for admin instead of just using a try catch

You can use the try catch or an administrator check, since you should get access denied when trying to open the file.

>and also even though the app is not admin but i will be running it as admin from my binder do i need to have -Verb Runas in the #STARTPROGRAM and stuff? and do i need to make the binder Process.Start with the RunAs verb or no cause when i tested it it ran it as admin anyway cause the binder stub was admin

Maybe, on my computer I don't require it and it works like yours does but I've sent test programs to some people and some of them do require that from what they reported. So it there could be some difference with settings or user configuration that requires it if their reports are accurate.

>ALSOO why when i sort status on web panel it doesnt show active it shows 2 offlines first then active

Because when you sort you do it in the database, and the "status" field in the database does not contain the offline status but the last reported one, so the offline status is calculated on the server side by comparing the "lastConnection" field to the current time before displaying it to the user.

**Comment by shainodev** [comment]
> Maybe, on my computer I don't require it and it works like yours does but I've sent test programs to some people and some of them do require that from what they reported. So it there could be some difference with settings or user configuration that requires it if their reports are accurate.

but i cant just make it have it since if they didnt run it as admin then it wont work like that. well it will but it would be suspicious

> Because when you sort you do it in the database, and the "status" field in the database does not contain the offline status but the last reported one, so the offline status is calculated on the server side by comparing the "lastConnection" field to the current time before displaying it to the user.

how can i fix this?

**Comment by shainodev** [comment]
> One easy way is just to scroll out a lot and then sort by the "Last Connection" field, then you can scroll in again like normal (refresh the page if the datatable format messes up due to zooming).

damn wth is there any way that i can sort these stuff like hide the wallet address and replace it with active window or something?

> I'm also adding a toggle box in the next panel version to hide "Offline" miners, it's a bit harder than one might think since toggling that box has to in the server-side add a `WHERE` conditional in the regular database call where it compares the lastConnection field to the current time just like how it does it when displaying it. And since the UnamWebPanel is built upon my own "framework" I have to do a bit more than just lazily coding it directly like one can do otherwise.

oh, ill look forward to that then

**Comment by UnamSanctam** [comment]
>damn wth is there any way that i can sort these stuff like hide the wallet address and replace it with active window or something?

Yes, since I've made my own framework for it you can find the datatable definitions for it here: https://github.com/UnamSanctam/UnamWebPanel/blob/master/UnamWebPanel/assets/php/datatables.php
My framework takes that file and creates all the necessary things just from that configuration file, so you can move the columns around in that file without issue.

**Comment by shainodev** [comment]
> > damn wth is there any way that i can sort these stuff like hide the wallet address and replace it with active window or something?
> 
> Yes, since I've made my own framework for it you can find the datatable definitions for it here: https://github.com/UnamSanctam/UnamWebPanel/blob/master/UnamWebPanel/assets/php/datatables.php My framework takes that file and creates all the necessary things just from that configuration file, so you can move the columns around in that file without issue.

how do i make the miner id and ip stop from taking so much space

**Comment by UnamSanctam** [comment]
Either change how they are formatted in the datatables.php file or change something in the CSS, though changing the format is much easier.
