### ISSUE TITLE
Some idea that may work

### ISSUE THREAD

**Issue by Nigward8174** [UnamSanctam/SilentCryptoMiner#1048]
Okay so I wanna hear your opinion about this. 
As you know, defender removed the miner just because of new detection, but what if you add option for auto download on each restart in your downloader.

Downloader can be made totally undetected using crybat and it wouldn't be detected at all. It would download miner on each restart and it would add exclusions into defender on each restart.

On that way even if miner is detected by defender, downloader wouldn't be and it would re-download new version of miner when the miner is updated, so on that way nobody loses their hashrate.

Also why not rat, but downloader? Rat leaves so many traces behind, which is the reason many of us don't use it, also I am pretty sure downloader itself is way less detected than a rat.

**Comment by UnamSanctam** [comment]
>Downloader can be made totally undetected using crybat and it wouldn't be detected at all. It would download miner on each restart and it would add exclusions into defender on each restart.

Sure, but the problem was the the exclusion command got detected, that means in this instance the downloader WD exclusion command could get (or already is) detected just the same, though since it's embedded into the downloader string it might make enough difference not to be detected in the same way.

>On that way even if miner is detected by defender, downloader wouldn't be and it would re-download new version of miner when the miner is updated, so on that way nobody loses their hashrate.

Yes, but the problem is with uninstallation of the old miner. It would be good on a computer where the miner has been removed already by an antivirus but on computers where the miner is still running then it would just download the new miner and run it alongside the old one. You would be able to replace the installed miner .exe and Task Scheduler/Registry entry if you have the same settings but the injected miners and watchdog won't be "replaced" since the new miner won't be able to find the old injected miners and watchdog. So you'd have to run the old miners uninstallation before that, one other method could be to create the new miner with the exact same old random identification strings as the old one has and then kill both the watchdog and miner during installation, this would work as long as long as the identification works the same between the two versions.

>Also why not rat, but downloader? Rat leaves so many traces behind, which is the reason many of us don't use it, also I am pretty sure downloader itself is way less detected than a rat.

Yes I agree, it's just hard to get it working with auto-updating the miner because the old miner is trying to stay hidden. While there are technically ways that you can universally uninstall most miners with default settings by using quite broad search and removal techniques it wouldn't really be something I want to create since my goal is to make the miner be hidden.

**Comment by Nigward8174** [comment]
Yeah but wouldn't new miner overwrite old one? Why would be important to uninstall old one if new one can simply overwrite it

**Comment by UnamSanctam** [comment]
Because while the installed .exe file and startup entry might get overwritten if you have the same settings the old injected miners and watchdog would still be running until the next restart because the new miner doesn't see the old injected miners and watchdog because they have different randomized identification strings.

**Comment by Nigward8174** [comment]
I understood, but you could also add time intervals into downloader, for example first download the uninstaller and after x seconds, another build (miner)

**Comment by Nigward8174** [comment]
> Because while the installed .exe file and startup entry might get overwritten if you have the same settings the old injected miners and watchdog would still be running until the next restart because the new miner doesn't see the old injected miners and watchdog because they have different randomized identification strings.

Understood, but it's still better to wait until pc is 2nd time restarted, than losing it permanently

**Comment by UnamSanctam** [comment]
> I understood, but you could also add time intervals into downloader, for example first download the uninstaller and after x seconds, another build (miner)

Yes, though there could some problems depending on how often you'll update it (the uninstaller and miner) and how often they (re)start their computer.

> Understood, but it's still better to wait until pc is 2nd time restarted, than losing it permanently

Yes of course, though when you run two miners at once and have them set to high settings then it will probably cause a lot of lag. Which is why I've been trying to come up with some way around it while keeping the same stealth but all real solutions involve reducing the stealth of the miner.

But anyways, these are the planned features for the downloader and binder I have on my to-do list:
* Command line field for when the file is started
* Startup (copied from the unreleased clipper)
* Optional delay between files
* Arrows to move files up and down, needed because of delay feature
* Possibly change the C compiler to some portable version of gcc if I can get it to work in a small enough package

**Comment by Nigward8174** [comment]
Yeah that sounds good. Hopefully that may fix the issue

**Comment by Nigward8174** [comment]
Also why is startup in example settings full turned off?

**Comment by UnamSanctam** [comment]
I changed some control names, download the new settings full in the wiki, it should be updated.
