### ISSUE TITLE
Example settings question

### ISSUE THREAD

**Issue by Trkyyyy** [UnamSanctam/SilentCryptoMiner#1063]
when I open the builder, I get these three options, but when I load your example settings, I only get Program Files and I can't change it, what is better to use? or it doesn't matter
![Screenshot_1](https://user-images.githubusercontent.com/78971154/185968372-32fe0f42-d182-4f94-8983-fc361bb35ae7.png)
![Screenshot_2](https://user-images.githubusercontent.com/78971154/185968380-da62d090-b0a4-4998-885a-95c8de8322eb.png)

**Comment by UnamSanctam** [comment]
It's because you have both "Run as System" and "Run as Administrator" enabled, it won't install in the user folder if you do have both enabled because it's running as the "System" user, so it needs to install it into a common folder and "Program Files" is a good one. Usually having both enabled is the better option.
