### ISSUE TITLE
console

### ISSUE THREAD

**Issue by bvi32** [UnamSanctam/SilentCryptoMiner#1064]
Hello. 
Can I create a miner using the console?
For example, passing the necessary parameters through a space, such as a wallet, a remote configuration url, etc.
Or just passing a json file?

If it's not difficult for you, tell me what other file should be corrected (in the source codes) if I want mining to go to another wallet every ten minutes?

**Comment by bvi32** [comment]
About the second request. I will not turn off your percentage that you receive (if you receive), I respect your work.

**Comment by UnamSanctam** [comment]
>Hello.
Can I create a miner using the console?
For example, passing the necessary parameters through a space, such as a wallet, a remote configuration url, etc.
Or just passing a json file?

You mean if you can build one using console commands? Not really at the moment since it's using WinForms, though you can technically code it to use a console command to load an .xml file with the settings then build it and then close the builder.

>If it's not difficult for you, tell me what other file should be corrected (in the source codes) if I want mining to go to another wallet every ten minutes?

Either you'll have to kill the miner and start a new one with changed parameters every 10 minutes in the code, or you can use the web panel and code it to change the configuration every 10 minutes. Or you can mine to a pool like MoneroOcean (they just recently added ETC mining as well) that allows you to split the profit between wallets.

**Comment by bvi32** [comment]
> You mean if you can build one using console commands? Not really at the moment since it's using WinForms, though you can technically code it to use a console command to load an .xml file with the settings then build it and then close the builder.

Does this require recompilation of the miner? Are you planning to add usage via the console in the future?

> Either you'll have to kill the miner and start a new one with changed parameters every 10 minutes in the code, or you can use the web panel and code it to change the configuration every 10 minutes. Or you can mine to a pool like MoneroOcean (they just recently added ETC mining as well) that allows you to split the profit between wallets.

Substitution of a wallet on the go for a certain period of time is impossible, do I understand correctly? Is it easier to write a script that will kill a process every ninety minutes and run another one?
(I'm sorry, I got confused, I meant that out of every hundred minutes, ten should go to mining on another wallet)
Hmmm... although xmrig does it somehow, and it doesn't seem to be a controlled process

**Comment by bvi32** [comment]
Speaking of xmrig, we mean donating to the developer, one percent will be in any case

**Comment by UnamSanctam** [comment]
>Does this require recompilation of the miner? Are you planning to add usage via the console in the future?

Yes you'd have to change the code, the reason I haven't added it is because it still needs to open the GUI because it's using WinForms, and the GUI appearing isn't ideally what you would want so I'll have to find some way to visually hide it without impacting anything.

>Substitution of a wallet on the go for a certain period of time is impossible, do I understand correctly? Is it easier to write a script that will kill a process every ninety minutes and run another one?
(I'm sorry, I got confused, I meant that out of every hundred minutes, ten should go to mining on another wallet)
Hmmm... although xmrig does it somehow, and it doesn't seem to be a controlled process

Yes neither xmrig nor ethminer supports that by default, to do it flawlessly it would have to be coded directly into the miners. XMRig uses their own DonateStrategy that it switches to from the normal pools after the donate % in minutes has been reached, but neither xmrig nor ethminer (ethminer doesn't have any dev fee system in it as compared to xmrig) has any system for a user to do that. Easiest would be to code a system for that into the watchdog, it depends on what you want to accomplish with it.

**Comment by bvi32** [comment]
> Yes you'd have to change the code, the reason I haven't added it is because it still needs to open the GUI because it's using WinForms, and the GUI appearing isn't ideally what you would want so I'll have to find some way to visually hide it without impacting anything.

I understand that the ability to create a miner without a gui is being worked on? That would be very helpful

> Easiest would be to code a system for that into the watchdog, it depends on what you want to accomplish with it.

Only "watchdog"? "Loader" does not need to be changed?

**Comment by UnamSanctam** [comment]
>I understand that the ability to create a miner without a gui is being worked on? That would be very helpful

Yes, though it will probably have to open the GUI while building, so it would open the GUI, automatically build it and then close down.

>Only "watchdog"? "Loader" does not need to be changed?

If you want to make some system like that then using the watchdog to do it would probably be the easiest, since it's always running. The "Shellcode Loader" is only used to launch the miner using shellcode from a C loader program instead of starting normally.

**Comment by bvi32** [comment]
> Yes, though it will probably have to open the GUI while building, so it would open the GUI, automatically build it and then close down.

Theoretically, this will not interfere with running on the server (win server or linux + wine) in any way?

That is, I can just switch through the "watchdog"? And the second miner "loader" should not run?

**Comment by UnamSanctam** [comment]
>Theoretically, this will not interfere with running on the server (win server or linux + wine) in any way?

As long as it supports opening GUIs it shouldn't.

>That is, I can just switch through the "watchdog"? And the second miner "loader" should not run?

In the watchdog at 90 minutes you can kill the original miner and then inject a new one either in the watchdog or in the Program.cs by using some sort of command line argument when starting it. Then after 10 minutes you can just kill the new one and open the old one.
