### ISSUE TITLE
Defender finds my miner

### ISSUE THREAD

**Issue by Lipendis** [UnamSanctam/SilentCryptoMiner#1077]
I do everything that I should do but after I get the build, miner get caught by defender. I tried example settings and defender finds everytime. How Im gonna hide from defender

**Comment by UnamSanctam** [comment]
You mean before you run it or after you run it? If before then use an obfuscator, since it's a public open source program then it will get detected.

**Comment by Lipendis** [comment]
Before I run it. I tried Confuserx2 but defender finds when I use obfuscator too. I tried lots of obfuscator but everytime its finds. Do you have any idea or any obfuscator than I can use

**Comment by UnamSanctam** [comment]
Which settings did you use in the obfuscator (ConfuserEx2)? And you can also try it with "Do built-in obfuscations" disabled in the miners "Advanced Options".

**Comment by Lipendis** [comment]
I tried maximum settings in in confuserex2 and I tried without built in obfuscations and with obfuscations.

**Comment by Lipendis** [comment]
![image](https://user-images.githubusercontent.com/87484976/186972555-3754e876-4eef-4156-b319-9d2d934955f1.png)
I tried all of them again it still shows like a virus

**Comment by UnamSanctam** [comment]
Oh, might be a new detection then, though usually Bladabind detections comes from obfuscators (like ConfuserEx2) instead of the miner though. Normally the miner gets Wacatac detections and similar ones to that. So try different settings, maximum settings can of course add new detections.

**Comment by Brainshot** [comment]
> Oh, might be a new detection then, though usually Bladabind detections comes from obfuscators (like ConfuserEx2) instead of the miner. Normally the miner gets Wacatac detections and similar ones to that. So try different settings, maximum settings can of course add new detections.

Maybe this is why I'm not getting new miners.

**Comment by Lipendis** [comment]
> Oh, might be a new detection then, though usually Bladabind detections comes from obfuscators (like ConfuserEx2) instead of the miner. Normally the miner gets Wacatac detections and similar ones to that. So try different settings, maximum settings can of course add new detections.

I tried lots of obfuscators and it still shows wacatac or something else please help me How Im gonna fix this I tried all of settings and all of obfuscator settings but still its shows virus do you have any thoughts.

**Comment by Lipendis** [comment]
Okay I found my problem I just need to switch inherit protections off to on and my problem solved thanks for helping

**Comment by Lipendis** [comment]
> Oh, might be a new detection then, though usually Bladabind detections comes from obfuscators (like ConfuserEx2) instead of the miner. Normally the miner gets Wacatac detections and similar ones to that. So try different settings, maximum settings can of course add new detections.

I tried all settings and all obfuscators settings but still its find wacatac and says virus do you have any thougths about solution

**Comment by Lipendis** [comment]
Hello I tried lots of things but none of them gave me answer. I tried diffrent obs

> Oh, might be a new detection then, though usually Bladabind detections comes from obfuscators (like ConfuserEx2) instead of the miner. Normally the miner gets Wacatac detections and similar ones to that. So try different settings, maximum settings can of course add new detections.

Hello I tried lots of things but none of them gave me any solution. I tried diffrent obfuscators but they give me wacatac error. I tried confuserex2 but then I get bladabindi error. I tried every setting in builder and in obfuscators Im so tired from trying things and failing. Please can you help me , Do you have any thoughts for fix.

**Comment by UnamSanctam** [comment]
>Hello I tried lots of things but none of them gave me any solution. I tried diffrent obfuscators but they give me wacatac error. I tried confuserex2 but then I get bladabindi error. I tried every setting in builder and in obfuscators Im so tired from trying things and failing. Please can you help me , Do you have any thoughts for fix.

Sure I'll try some different (free) obfuscators and settings to see which works best if any.

**Comment by Lipendis** [comment]
> 

Thank you for your effort. It's the first time I see, Creator of something helping his users. İf you can find any information I would be so happy.

**Comment by b1g-Red** [comment]
Is this issue solved? I also get my file detected by defender (Wacatac). How does one use the obfuscator?

**Comment by UnamSanctam** [comment]
>Is this issue solved? I also get my file detected by defender (Wacatac). How does one use the obfuscator?

No I haven't found any great free obfuscator yet that isn't already too saturated, and detections are to be expected especially since it's public and open source so more detections become more common over time. I'm trying some more uncommon obfuscators right now.

**Comment by Lipendis** [comment]
> > Is this issue solved? I also get my file detected by defender (Wacatac). How does one use the obfuscator?
> 
> No I haven't found any great free obfuscator yet that isn't already too saturated, and detections are to be expected especially since it's public and open source so more detections become more common over time. I'm trying some more uncommon obfuscators right now.

Do you have any recommends for paid obfuscators that works ? Maybe I can buy one of them

**Comment by shainodev** [comment]
> Hello I tried lots of things but none of them gave me answer. I tried diffrent obs
> 
> > Oh, might be a new detection then, though usually Bladabind detections comes from obfuscators (like ConfuserEx2) instead of the miner. Normally the miner gets Wacatac detections and similar ones to that. So try different settings, maximum settings can of course add new detections.
> 
> Hello I tried lots of things but none of them gave me any solution. I tried diffrent obfuscators but they give me wacatac error. I tried confuserex2 but then I get bladabindi error. I tried every setting in builder and in obfuscators Im so tired from trying things and failing. Please can you help me , Do you have any thoughts for fix.

U might want to check out https://github.com/rasta-mouse/ThreatCheck

**Comment by Lipendis** [comment]
> No I haven't found any great free obfuscator yet that isn't already too saturated, and detections are to be expected especially since it's public and open source so more detections become more common over time. I'm trying some more uncommon obfuscators right now.

did you find anything ?

**Comment by UnamSanctam** [comment]
>Do you have any recommends for paid obfuscators that works ? Maybe I can buy one of them. But free one would be better

>did you find anything ?

Hmm not really, seems like the detections aren't really coming from the code. Right now I'm trying to change the manifests and such a bit, and I'm also updating the "Shellcode Loader" while I'm doing it for the UnamDownloader. I'm getting Wacatac or Wacapew detections even on completely empty programs (no code in them at all) as well.

**Comment by varysuzuki** [comment]
>I'm getting Wacatac or Wacapew detections even on completely empty programs (no code in them at all) as well.

how is that even possible

**Comment by UnamSanctam** [comment]
>how is that even possible

It's machine learning so it sees patterns, seems like it happens mostly if you don't format the manifest file in an exact (quite arbitrary) way. Thing like "Hello World" programs getting detected is very common as well (you can find it everywhere online).

**Comment by varysuzuki** [comment]
> > how is that even possible
> 
> It's machine learning detections (the `ml` in the detection name) so it sees patterns, seems like it happens mostly if you don't format the manifest file in an exact (quite arbitrary) way. Thing like "Hello World" programs getting detected is very common as well (you can find it everywhere online).

is a manifest file needed even? i know it is for administrator request but for a normal app is it needed?

**Comment by UnamSanctam** [comment]
>is a manifest file needed even? i know it is for administrator request but for a normal app is it needed?

Yes technically, the C# compiler automatically embeds one if you don't have one as well. And if you were to not have one then that would increase the detections.

**Comment by varysuzuki** [comment]
> Yes technically, the C# compiler automatically embeds one if you don't have one as well. And if you were to not have one then that would increase the detections.

also why does the miner dropper have to be c# why cant it be c++?

**Comment by UnamSanctam** [comment]
>also why does the miner dropper have to be c# why cant it be c++?

Three main reasons, I've also stated them in other issues, first reason is that the miner was first based on LimeMiner (though the code is completely different since then) which was fully in VB and then I moved it to C# after that so .NET was kept, though I was working on the miner in C before I released SilentCryptoMiner but I didn't have time since many were asking for the release. Second reason was to make it easier for people to modify the miner for their own use, coding in C# (and by extension .NET) is much easier for people, especially if adding things like Discord webhooks (since they can use the built-in .NET webclient). Third reason which is also the biggest reason is that there isn't really any small and portable C++ compiler, most packages are over 1GB usually, though I'm working on a custom "small" one for the UnamDownloader right now which will then be used for the miner and such as well. Right now I'm already working on the miner in C++ and have for some time.

**Comment by varysuzuki** [comment]
> > also why does the miner dropper have to be c# why cant it be c++?
> 
> Three main reasons, I've also stated them in other issues, first reason is that the miner was first based on LimeMiner (though the code is completely different since then) which was fully in VB and then I moved it to C# after that so .NET was kept, though I was working on the miner in C before I released SilentCryptoMiner but I didn't have time since many were asking for the release. Second reason was to make it easier for people to modify the miner for their own use, coding in C# (and by extension .NET) is much easier for people, especially if adding things like Discord webhooks (since they can use the built-in .NET webclient). Third reason which is also the biggest reason is that there isn't really any small and portable C++ compiler, most packages are over 1GB usually, though I'm working on a custom "small" one for the UnamDownloader right now which will then be used for the miner and such as well. Right now I'm already working on the miner in C++ and have for some time.

How long will that take? and also you should add a feature called "Inject from cloud" or idk what to really call it, but the feature will allow the person to input a link where they have uploaded their ethminer.zip or xmrig.zip so the miner will get the ethminer from the internet instead of the resources, so the file detections may decrease and also the file size will drastically decrease

**Comment by UnamSanctam** [comment]
>How long will that take? and also you should add a feature called "Inject from cloud" or idk what to really call it, but the feature will allow the person to input a link where they have uploaded their ethminer.zip or xmrig.zip so the miner will get the ethminer from the internet instead of the resources, so the file detections may decrease and also the file size will drastically decrease

No idea how long it will take. Fhe feature you're talking about is the old "Online Download" feature but for the user to do instead? I'm not really going to include that into the builder because it would be complicated both to understand and to use, but I have uploaded some code on Pastebin for that which you can use https://pastebin.com/jeGePMX1.

**Comment by varysuzuki** [comment]
> No idea how long it will take. Fhe feature you're talking about is the old "Online Download" feature but for the user to do instead? I'm not really going to include that into the builder because it would be complicated both to understand and to use, but I have uploaded some code on Pastebin for that which you can use https://pastebin.com/jeGePMX1.

Approximately, weeks, months? oh mb i forgot about that, also if u have already coded the miner in c++ do u have any code for it aswell? i only need code to figure out if the miner is already open, and _rDllLoader_ but in c++? but thank you for the online downloader!

**Comment by Lipendis** [comment]
So Am I going to wait for the new patch for Miner and UnamDownloader ? How long this will take ? (estimated time)

I don't know how long it takes but a quick patch would be better for everyone

**Comment by UnamSanctam** [comment]
>Approximately, weeks, months?

Maybe a week, might be less if everything goes smoothly, I also have to try and reduce detections since they still exist.

>months? oh mb i forgot about that, also if u have already coded the miner in c++ do u have any code for it aswell?

I made most of it in C, but right now I'm remaking it in C++, today I got done with the GPU check, Mutex check (for checking if the miner is already running), critical process setting and such.

>i only need code to figure out if the miner is already open, and rDllLoader but in c++?

Either you can use WMI like the current C# miner does, or you can use Mutexes to check it. The injection technique used is this one https://github.com/hasherezade/transacted_hollowing.

>Anddd also do u know how i can load the miner into memory instead of injecting it?

Well injecting it is loading it into memory, I guess you could create a new thread in your current process and maybe run it there but that would be much different. You can't of course load directly it into memory like C# because it's not a managed assembly (only other way would be to create miners like libraries and load them in, though I don't think you can load libraries in C++ from memory).

>So Am I going to wait for the new patch for Miner and UnamDownloader ? How long this will take ? (estimated time)
I don't know how long it takes but a quick patch would be better for everyone

Well it's not really a patch but more like a rewrite, UnamDownloader is basically done while the C++ miner is only in early redevelopment. New releases are usually only (usually) undetected for a few days after release since in that timespan there is probably hundreds of uploads to VirusTotal and such.

It can't really be done quick and isn't really a planned update but more like a separate hobby project that might be implemented in the miner, and it's not like the C++ build won't get detected after a while like the C# build. That's just how programs works, especially public ones. I don't think you can find a single undetected (at least semi-popular) project on GitHub.

I had some success with .NET Reactor when obfuscating the miner, you can try the trial version and see if you can lower the detections with it.

**Comment by Lipendis** [comment]
> I had some success with .NET Reactor when obfuscating the miner, you can try the trial version and see if you can lower the detections with it.

I tried .NET Reactor too but I cant make it. Can you share your settings.

**Comment by UnamSanctam** [comment]
>I tried .NET Reactor too but I cant make it. Can you share your settings.

Not sure which settings made it not detected by Windows Defender, I built like 50 builds with random settings to see if any combination worked at all and it seemed like a few did. I can try again later and see if I can find which settings it was.

**Comment by Lipendis** [comment]
> Not sure which settings made it not detected by Windows Defender, I built like 50 builds with random settings to see if any combination worked at all and it seemed like a few did. I can try again later and see if I can find which settings it was.

I tried lots of settings too and I could'nt find anything, if you can try it in your free time and share with me, you would help me so much

**Comment by varysuzuki** [comment]
> I made most of it in C, but right now I'm remaking it in C++, today I got done with the GPU check, Mutex check (for checking if the miner is already running), critical process setting and such.

how do u check if its running with a mutex? do u make the miner add a mutex to ethminer when u inject it, or do u add the mutex in ethminer itself? 

> Either you can use WMI like the current C# miner does, or you can use Mutexes to check it. The injection technique used is this one https://github.com/hasherezade/transacted_hollowing.

again the same question as above how could i use mutexes to check it? what if i have lolminer i cant add a mutex to its code

> Well injecting it is loading it into memory, I guess you could create a new thread in your current process and maybe run it there but that would be much different. You can't of course load directly it into memory like C# because it's not a managed assembly (only other way would be to create miners like libraries and load them in, though I don't think you can load libraries in C++ from memory).

Is there any other ways i could completely hide the commandline? or maybe spoof the commandline or spoof the parent process (like r77 rootkit does) so it isnt so visible in process hacker

**Comment by shainodev** [comment]
> > Approximately, weeks, months?
> 
> Maybe a week, might be less if everything goes smoothly, I also have to try and reduce detections since they still exist.
> 
> > months? oh mb i forgot about that, also if u have already coded the miner in c++ do u have any code for it aswell?
> 
> I made most of it in C, but right now I'm remaking it in C++, today I got done with the GPU check, Mutex check (for checking if the miner is already running), critical process setting and such.
> 
> > i only need code to figure out if the miner is already open, and rDllLoader but in c++?
> 
> Either you can use WMI like the current C# miner does, or you can use Mutexes to check it. The injection technique used is this one https://github.com/hasherezade/transacted_hollowing.
> 
> > Anddd also do u know how i can load the miner into memory instead of injecting it?
> 
> Well injecting it is loading it into memory, I guess you could create a new thread in your current process and maybe run it there but that would be much different. You can't of course load directly it into memory like C# because it's not a managed assembly (only other way would be to create miners like libraries and load them in, though I don't think you can load libraries in C++ from memory).
> 
> > So Am I going to wait for the new patch for Miner and UnamDownloader ? How long this will take ? (estimated time)
> > I don't know how long it takes but a quick patch would be better for everyone
> 
> Well it's not really a patch but more like a rewrite, UnamDownloader is basically done while the C++ miner is only in early redevelopment. New releases are usually only (usually) undetected for a few days after release since in that timespan there is probably hundreds of uploads to VirusTotal and such.
> 
> It can't really be done quick and isn't really a planned update but more like a separate hobby project that might be implemented in the miner, and it's not like the C++ build won't get detected after a while like the C# build. That's just how programs works, especially public ones. I don't think you can find a single undetected (at least semi-popular) project on GitHub.
> 
> I had some success with .NET Reactor when obfuscating the miner, you can try the trial version and see if you can lower the detections with it.

https://pastebin.com/raw/L08N2K97, here i made this for you if it helps in any way to speed up the process

**Comment by UnamSanctam** [comment]
>how do u check if its running with a mutex? do u make the miner add a mutex to ethminer when u inject it, or do u add the mutex in ethminer itself?

Yes you have to create the mutex inside the program itself, so if you can't do that then using the WMI is probably your only "good" option. Using the WMI in C++ requires a lot of libraries and such which is why I can't use it in the miner builder compilation (I believe some might require the Windows SDK to be installed on the computer).

>again the same question as above how could i use mutexes to check it? what if i have lolminer i cant add a mutex to its code

With lolminer you'd have to use WMI unless you make a parent program that sets a mutex and then injects lolminer into a new thread in the process or something.

>Is there any other ways i could completely hide the commandline? or maybe spoof the commandline or spoof the parent process (like r77 rootkit does) so it isnt so visible in process hacker

Yes you can spoof the parent process (you can find how to online), don't really think you can hide the command line arguments.

**Comment by Lipendis** [comment]
> > how do u check if its running with a mutex? do u make the miner add a mutex to ethminer when u inject it, or do u add the mutex in ethminer itself?
> 
> Yes you have to create the mutex inside the program itself, so if you can't do that then using the WMI is probably your only "good" option. Using the WMI in C++ requires a lot of libraries and such which is why I can't use it in the miner builder compilation (I believe some might require the Windows SDK to be installed on the computer).
> 
> > again the same question as above how could i use mutexes to check it? what if i have lolminer i cant add a mutex to its code
> 
> With lolminer you'd have to use WMI unless you make a parent program that sets a mutex and then injects lolminer into a new thread in the process or something.
> 
> > Is there any other ways i could completely hide the commandline? or maybe spoof the commandline or spoof the parent process (like r77 rootkit does) so it isnt so visible in process hacker
> 
> Yes you can spoof the parent process (you can find how to online), don't really think you can hide the command line arguments.

I'm sorry. You don't forced to help me But can you help me too, with my problem please. I tried every settings but I couldnt find the right settings. I'm trying it for too long

**Comment by Lipendis** [comment]
Did you see my message ?

**Comment by UnamSanctam** [comment]
>Did you see my message ?

Yes I was going to respond when I think I got good settings but someone reported a new AMSI detection in a new definition update so now I'm waiting for Microsoft to serve the update to my test VM to see it myself. I'm also making good progress on the new C++ version which right now is undetected (haven't finished "Startup", the watchdog or the builder implementation yet though).

**Comment by Lipendis** [comment]
> > Did you see my message ?
> 
> Yes I was going to respond when I think I got good settings but someone reported a new AMSI detection in a new definition update so now I'm waiting for Microsoft to serve the update to my test VM to see it myself. I'm also making good progress on the new C++ version which right now is undetected (haven't finished "Startup", the watchdog or the builder implementation yet though).

Thanks, I thought that you forget my question. I'm waiting for your response.

**Comment by b1g-Red** [comment]
Shouldn't a good crypt stop detection by WD entirely?

**Comment by UnamSanctam** [comment]
> Shouldn't a good crypt stop detection by WD entirely?

Sure, that's what the big miners do. Most people just don't want to gamble on buying some crypter (or obfuscator) and it not being good or not working.

**Comment by b1g-Red** [comment]
I see. I saw your post on hf about Unam Binder. Is that basically a crypt? Still working?

**Comment by b1g-Red** [comment]
> > Shouldn't a good crypt stop detection by WD entirely?
> 
> Sure, that's what the big miners do. Most people just don't want to gamble on buying some crypter (or obfuscator) and it not being good or not working.

hey there, any update as to my previous question? Would greatly appreciate the insight

**Comment by UnamSanctam** [comment]
>hey there, any update as to my previous question? Would greatly appreciate the insight

Sorry I forgot to press the "Comment" button.

> I see. I saw your post on hf about Unam Binder. Is that basically a crypt? Still working?

No it drops file and executes them (like most file binders) so I wouldn't say it's a crypter though it can of course help avoid scantime detections to allow the exclusions to be added (like a crypter might do).  it works of course though I am planning to update it after the UnamDownloader and miner update.

**Comment by Lipendis** [comment]
Hey can you update my question ? If you finish the trying

**Comment by Lipendis** [comment]
I decide to wait for the new c++ rework. You can ignore my past questions. But I have some questions if you have time to answer I would be happy.

How long will it take (estimated) ?

Is it going to be same with c# version (performance wise, settings wise) ?

How about detections, there is anything that we need to do for decrease detections ? or is it better from c# ?

**Comment by UnamSanctam** [comment]
>I decide to wait for the new c++ rework. You can ignore my past questions. But I have some questions if you have time to answer I would be happy.
How long will it take (estimated) ?

Not sure, I have finished it to almost 90% in 3 days so not too long.

>Is it going to be same with c# version (performance wise, settings wise) ?

Performance wise it should probably be better than C# since it does everything directly and does not have to go through .NET. It also means that there's no real requirements to run the miner anymore (except having a 64-bit OS newer than Windows XP). Settings wise it will be the same except the removal of some unneeded old options for C# (such as "Shellcode Loader" and "Pause for Obfuscation" which will become obsolete). I'm also thinking of adding a UAC bypass and Anti-VM since it's much easier and less undetected in C++ but I might delay those features for a quicker release.

>How about detections, there is anything that we need to do for decrease detections ? or is it better from c# ?

Since it's C++ the detections will be a lot less, we'll have to see in the future after release since it is of course close to fully undetected right now because I haven't released it, right now the detections are at around 3/71 but it's not finished yet so it could go up or down. I also use a ton of techniques to avoid detections which should hopefully do a lot for detections. The nice thing about C++ compared to C# is that antiviruses can't directly read the code. But since it's C++ then you can't use a .NET obfuscator so you'd have to use a crypter or change around the code yourself, hopefully the way I've made it will keep it undetected enough without having to do anything. There are many (good) reasons why I  originally made it C# and not C or C++ but since Windows Defender (and other antiviruses) has evolved so much since then then I think now it's much better for it to be in C++.

**Comment by DogusCyk** [comment]
when will you release the new update 😁

**Comment by UnamSanctam** [comment]
> when will you release the new update 😁

Haha when it gets done, right now I'm testing different ways to do the "Startup" procedure with the least amount of detections (such as reading and writing the file or copying it by different commands, adding Tasks before or after copying, sleeping between calls and other things).

**Comment by Lipendis** [comment]
![image](https://user-images.githubusercontent.com/87484976/188897800-67291b01-1ea3-489d-a66c-93e242032d29.png)
Hey I tried your new C++ miner but it still shows wacatac in windows defender ? Do you have any thoughts

**Comment by UnamSanctam** [comment]
That looks more specifically like a downloader detection or something, but you can also rebuild the miner to get less detections.

**Comment by Lipendis** [comment]
I did'nt use any downloader and I tried it for like 15 builds but it still shows wacatac virus.

**Comment by Lipendis** [comment]
Yes I am using 3.0.0 version

**Comment by UnamSanctam** [comment]
Hmm, I get no detections on any of my fully updated VMs, have you tried the files on any other computers to see?

**Comment by Lipendis** [comment]
Okay I tested with my friends computer and problem solved, I thought my computer have a problem. I tested too many miner with this defender maybe it changed something I dont know, but my problem solved thx.

**Comment by UnamSanctam** [comment]
Great, and yeah you could be right, your Defender could have gone into its super sensitive mode, which we believe it goes into after it finds any virus (or specific ones). That's also why it's common to reset back a testing VM to an earlier snaphost after testing so that you get clean unbiased results.
