### ISSUE TITLE
Disappears hashrate etc.

### ISSUE THREAD

**Issue by Traffer1337** [UnamSanctam/SilentCryptoMiner#1093]
Hello, why on the etc miner does not keep the hashrate, disappears somewhere. And with mining xmr there is no such problem, everything works fine.

**Comment by UnamSanctam** [comment]
They could start something that requires the VRAM or the GPU overall, they could have some program open that you have in "Stealth Targets" if you have different ones from the XMR miner (like games), or if they have a laptop then the GPU could get disabled by Nvidia when no dedicated program is open. Are you checking the hashrate in the web panel or the pool? Since the pool only shows "hashrate" whenever the miner submits a share (and many pools have a very high share difficulty for ETH, ETC and similar coins).

**Comment by parabola20** [comment]
hashrate dropped again... moreover, it does not depend on the opening of programs or something else, because not 100-200 mhs go away, but 2-3 ghs per night. what does it mean?

**Comment by UnamSanctam** [comment]
>hashrate dropped again... moreover, it does not depend on the opening of programs or something else, because not 100-200 mhs go away, but 2-3 ghs per night. what does it mean?

What does your web panel report?

**Comment by parabola20** [comment]
> > hashrate dropped again... moreover, it does not depend on the opening of programs or something else, because not 100-200 mhs go away, but 2-3 ghs per night. what does it mean?
> 
> What does your web panel report?

I don't use the web panel, all the information is on the 2miners pool. you recently updated the miner to protect against the defender, what could be the problem this time?

**Comment by UnamSanctam** [comment]
>I don't use the web panel, all the information is on the 2miners pool. you recently updated the miner to protect against the defender, what could be the problem this time?

No idea, I can't check your miners so I can only guess. Someone reported a new AMSI detection that Microsoft has released but I haven't gotten the update yet I think so I don't get that detection (and so can't test it).

Since Microsoft keeps updating Windows Defender all the time it's getting harder and harder to use C#, which is why I have continued on my project of rewriting the miner in C++. In these last few days I've gotten from maybe 10% done to 90% done (including putting together the compiler package and making all the tools for it) so it's probably not too long until I can release the big rework.
