### ISSUE TITLE
Hashrate drops to 0 when active?

### ISSUE THREAD

**Issue by alam0111** [UnamSanctam/SilentCryptoMiner#1098]
How? It's an rtx3050 btw!
![image](https://user-images.githubusercontent.com/112485952/188143042-ed5ccd6f-995c-4714-9cf7-c567ea41bbac.png)

**Comment by UnamSanctam** [comment]
And it's a miner version 2.6.1? And it's not an RTX 3050 Laptop GPU? Can you expand it (press the blue '+') and show a screenshot of the information?

**Comment by alam0111** [comment]
![image](https://user-images.githubusercontent.com/112485952/188261511-e67698b0-74c3-459b-8291-038cd470747b.png)
I was actually wondering too... Though The cpu was running at a pretty high h/s so I've figured he wouldn't be running something resource expansive. Btw it started working again after a while.

**Comment by UnamSanctam** [comment]
Alright good, since he did start mining then it's probably that he could have had something memory intensive open or his GPU could have gone idle (or been disabled), I've seen it in other injected miners before at least. Or something could have happened to the DAG or something as well (which gets recreated after a while).

**Comment by alam0111** [comment]
Actually could it be possible for the web panel not to see the h/s? I mean when I looked at the chart it showed at some point's it was mining with 56 mh/s yet the webpanel never reported that.

**Comment by UnamSanctam** [comment]
No it's reporting correctly, the pool is just calculating it as the amount of share submitted in a specific interval. So if you mine at 10 MH/s and then luckily finds two shares around the same time then on the pool it could look something like 2 * 27 (example of how much MH/s that one share could represent) = 54 MH/s just because the miner was lucky.

**Comment by alam0111** [comment]
I see thanks for the info!
