### ISSUE TITLE
Can you show me a simple example?

### ISSUE THREAD

**Issue by hara2214** [UnamSanctam/SilentCryptoMiner#1105]
Hello, I am not an English-speaking culture country. 
So I tried to understand Wiki by interpreting it. 
But there is a limit. 

![image](https://user-images.githubusercontent.com/112808776/188312610-e56d2812-f61b-4224-a154-ab69a3a445f9.png)

1.  It says "(dot).{COMPUTERNAME}," but how do I write this? Can you show me a simple example?
2. wiki say 'Most pools do not require any password'. but If you look at the last sentence, It says that the password must be used in Monero Ocean. How should I write it? 

I would appreciate it if you could attach it as a picture.

I'm sorry to ask you so many questions.
I've been working hard for eight hours and it's not working.
Thank you very much for your hard work.

**Comment by hara2214** [comment]
My settings are the same as ExampleSettings_Full.
![image](https://user-images.githubusercontent.com/112808776/188313120-58958255-6f00-4b1b-a816-a69a86f1230f.png)
![image](https://user-images.githubusercontent.com/112808776/188313152-67ef34df-f089-4df8-9f01-78de32d69739.png)

**Comment by UnamSanctam** [comment]
1) How it is in the example is correct, and how you did it in the screenshot is also correct. Except your pool port, since you changed it to port 2222 then make sure that you don't have SSL/TLS enabled because 2222 is the non-SSL port.
2) The pool you're using right now (2miners) does not use the "Password" field so you don't need a password.

To try if it works, load the example settings and then build and test the miner. That miner should work fine, then you can change the things you want and then build it again, if it doesn't work then then some settings you changed is wrong.

**Comment by hara2214** [comment]
thx for ur service. but it's not working..
I called an example and turned off port modification, wallet modification, and ssl.
Is it right that the checker appears like the picture above?
Then it appears for about three seconds in the process and then disappears. Is this normal, too?

**Comment by UnamSanctam** [comment]
No, but currently it could be detected by AMSI which could be the issue, currently I'm working on the newest update so you can try that in a few days if that is the issue.
