### ISSUE TITLE
Windows Defender

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1126]
I check the finished miner and Windows Defender After launch the miner, it destroys. 
![1](https://user-images.githubusercontent.com/36513967/188977182-38bf8c58-31db-496e-b14e-71a46ce23ce7.jpg)
I hastened to write. This discovery was in version 3.0.0. I just checked version 3.0.1 and there is no detection.

I'll post in this thread so I don't create a new one. I downloaded the resources and assembled the builder myself, then the version is displayed as 3.0.0 in the web panel too.

**Comment by UnamSanctam** [comment]
Alright, yeah you have to change the builderVersion string in the builder to 3.0.1, the current file in "Releases" has that but not the code.

**Comment by masterjek** [comment]
Unam tell me if I use version 2.6.0 its launch and implementation is not detected by many antiviruses. As I understand it, I can continue to use it without switching to version 3.0.1. And if I understand correctly, it’s better to rebuild the miner even in version 2.6.0 so that the injection is not in explorer.exe? As I understand it, it is better to choose another target for injection.

**Comment by UnamSanctam** [comment]
Yes if you have a good obfuscator/crypter then you can use 2.6.1, for Windows Defender most things are detected from what I've been told because they recently added a ton more things but the biggest seems like a new AMSI detection. And yes you can change it from explorer.exe if you want to, the reason I switched away from it by default is that it seems like explorer.exe was triggering a lot more `DefenseEvasion` detections then any other.

**Comment by masterjek** [comment]
If I choose an injection target cmd.exe and the console is not running on the computer miner will still start?

**Comment by UnamSanctam** [comment]
Yes it doesn't matter if the target process already running or not, the miner starts its own program.

**Comment by masterjek** [comment]
Thanks a lot for your help and quick replies. I appreciate your work. 
I also want to ask, do you make programs to order for money?

**Comment by masterjek** [comment]
Understood thanks for the answer.
