### ISSUE TITLE
Protection exe file

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1132]
Unam Tell me if there is an easy way to protect the finished exe file? What is the protection so that if the user using hex editor changed file then it didn't start again.

**Comment by UnamSanctam** [comment]
>Unam Tell me if there is an easy way to protect the finished exe file?

Any crypter should work, or you can change around things in the code or even try and use another compiler (since many things change with each compiler).

>What is the protection so that if the user using hex editor changed file then it didn't start again.

Not sure what you're asking, you mean some protection from the file being modified? I guess some sort of MD5 check and a launcher would be needed for that.

**Comment by masterjek** [comment]
> Не уверен, что вы спрашиваете, вы имеете в виду некоторую защиту от изменения файла? Я предполагаю, что для этого потребуется какая-то проверка MD5 и пусковая установка.

Yes, I meant it.
