### ISSUE TITLE
crypter & checker

### ISSUE THREAD

**Issue by gomezemiliano3** [UnamSanctam/SilentCryptoMiner#1133]
if i use a crypter to encript the final .exe and after run the checker to see if the miner is running, i should appear?

this is what the checker show me: 

Watchdog Running: No
Miners:
GPUs:
 Intel(R) Iris(R) Xe Graphics
Compatible GPU found: False

**Comment by UnamSanctam** [comment]
Yes, but keep in mind that if you're using an injection crypter (almost all crypters are) then you can't usually use the miners "Startup" option but have to use the crypters "Startup" option instead. That's why crypters usually have a "Startup"/"Install" option, because they inject the program then the injected program can't install itself because it does not know where it is (because it's injected into another process).

**Comment by UnamSanctam** [comment]
If the crypter injects the miner (I don't know exactly what your crypter does functionally) then the miner has no idea where it is (because it's injected into somewhere else) and thus can't install. So you should disable "Startup" in the miner and enable "Startup" or "Install" in your crypter instead, they usually have an option for that for that reason.

**Comment by UnamSanctam** [comment]
>the options that my crypter have are antidebug, antiVM, Melt File, Run as admin and API unhooking.

Hmm, usually they have a startup option, try disabling "Startup" in the miner and then crypt that. If that works (shows up in the checker) then you'll know the reason is that it can't install. Also, just have to make sure and ask that you actually ran the crypted file after you crypted it?

>If i blind the miner executable into another .exe it should run?

Sure though all a file binder does is usually that they drop the bound files to the disk and then runs them.

**Comment by gomezemiliano3** [comment]
thanks for the quick response! i have one last question
i want to generate a random name when the miner run on another pc, i have to put the adress like  miwalletaddress.{RANDOM} with the . in the middle? thanks

**Comment by UnamSanctam** [comment]
It depends on the pool but for most pools that's how you do i yes.
