### ISSUE TITLE
This is more of a sugestion...

### ISSUE THREAD

**Issue by alam0111** [UnamSanctam/SilentCryptoMiner#1137]
![image](https://user-images.githubusercontent.com/112485952/189206679-6472a84c-7d6d-4e1f-9b23-f88e4a2c91a2.png)
Now this guy has been mining for quiet some time but now for a couple of hours (quiet a few) it's running on 0 so it would be nice if you can add a option to see what exactly is stopping the miner from actually mining (you said it stops if it doesn't have enough vram available). Because as you can see he is running on idle and would be nice to see what program it's at fault here so I can give the command to stop it.

**Comment by UnamSanctam** [comment]
If it's initially due to full VRAM then it will says so (`Not enough free VRAM`), though it can max out in different capacities after allocation, it's quite complicated. And if it's due to "Stealth" then it will also say so. But finding out what other programs are taking up the GPU resources is not really possible to do in Windows (neither CUDA or OpenCL). I guess the biggest possibility is his GPU going idle (GPU gets "disabled") or something using 100% of his GPU (like rendering or something).

Only real method of finding out why would be to have access to the computer and use a few different tools to find out, though even if you have access to the computer it can be hard to find out what's using things when it comes to the GPU.

**Comment by alam0111** [comment]
Yeah I guess if I would have got a rat in... though my presumption is that he just left a game open... now I am trying to find some sort of game process list.
