### ISSUE TITLE
Online/ Offline?

### ISSUE THREAD

**Issue by alam0111** [UnamSanctam/SilentCryptoMiner#1140]
How is this even possible?
![image](https://user-images.githubusercontent.com/112485952/189275398-ac88626b-d98a-442b-bbb5-e6f01a6df57d.png)

**Comment by UnamSanctam** [comment]
GPU could be offline or the GPU could have crashed, do you have the "Watchdog" enabled? If so then the first reason is the most probable.

**Comment by alam0111** [comment]
I didn't know so you can have your pc online while having the gpu only off?

**Comment by UnamSanctam** [comment]
Yes it can happen, you could go into your Device Manager right now and disable your dedicated GPU without problem except if your monitor is connected to it. His GPU drivers could also have crashed or been updated or something similar. He has also switched his IP since then as you can see which could indicate something.

**Comment by alam0111** [comment]
Ahah I see.
