### ISSUE TITLE
error when building .exe

### ISSUE THREAD

**Issue by mortingenstrasse95** [UnamSanctam/SilentCryptoMiner#1143]
<img width="379" alt="image" src="https://user-images.githubusercontent.com/48433244/189336905-b2cc8570-fbbe-470d-8c8e-58405d75f3e0.png">

**Comment by UnamSanctam** [comment]
Open the g++.log file that it says in the message and post what it contains here.

**Comment by mortingenstrasse95** [comment]
<img width="383" alt="image" src="https://user-images.githubusercontent.com/48433244/189338092-7513ec9f-e694-46e2-8a90-700355eb4dac.png">

**Comment by UnamSanctam** [comment]
Yes it's a bug with the XMR miners "GPU Mining", the CUDA library files are too big to compile, it's a known problem but I didn't have time to "fix" it (it's technically just a limit in the compiler) which is why I marked the option red. It works on some computers for some reason which is why it's not disabled.

**Comment by mortingenstrasse95** [comment]
i just tried rvn mining with GPU.

**Comment by UnamSanctam** [comment]
Yes the xmrig CUDA (Nvidia) libraries are too big to compile right now, but I wouldn't really recommend Ravencoin for silent mining anyways due to it using the KawPow algorithm which lags the computer a lot more than other algorithms and also causes a lot more heat (fan sound). Mining KawPow doesn't seems to work on all computers either (with any miner).

**Comment by mortingenstrasse95** [comment]
Which is the most effective mining method you recommend?

**Comment by mortingenstrasse95** [comment]
Does the algo mining work stable?

**Comment by mortingenstrasse95** [comment]
ah sorry, you said ETC above. I'll try it

**Comment by UnamSanctam** [comment]
Haha yes, ETC is the most popular one due to it's relative high profitability and relative low VRAM requirement.
