### ISSUE TITLE
All of my miners stop mining

### ISSUE THREAD

**Issue by Smurfboi007** [UnamSanctam/SilentCryptoMiner#1167]
I have 200 miners and suddenly all of them stopped mining. Why is this?

**Comment by UnamSanctam** [comment]
And you're not mining ETH?

**Comment by Smurfboi007** [comment]
Right, thanks forgot about the merge

**Comment by Smurfboi007** [comment]
Quick question, if this is my remote config:
stratum://`0x000000000000000000000000000000000000000`.{COMPUTERNAME}@eth-eu1.nanopool.org:9999/password

and I wanted to mine Ergo, what would I need to change?

**Comment by UnamSanctam** [comment]
The miner doesn't have the Autolykos algorithm so you can't mine that at the moment. You can mine any coin that uses the ethash, etchash or ubqhash algorithms with the ETH miner at the moment.

**Comment by UnamSanctam** [comment]
ETC, things are also moving up and down all the time so it's hard to tell. Most coins became a lot more unprofitable per GH because the hashrates from ETH moved over. For example ETCs hashrate has quadrupled as you can see https://2miners.com/etc-network-hashrate. So we'll have to see if the prices for the coins move as well or not.

**Comment by conomr011** [comment]
> ethash



> ETC, things are also moving up and down all the time so it's hard to tell. Most coins became a lot more unprofitable per GH because the hashrates from ETH moved over. For example ETCs hashrate has quadrupled as you can see https://2miners.com/etc-network-hashrate. So we'll have to see if the prices for the coins move as well or not.

I suggest :
- adding Ergo to your  miner builder in the next update 
- add the ability to switch between  different algorithm miners  remotely hence, we can  deleting old miner and run another one has different algorithm in case those coins couldn't  be profitable any more

**Comment by UnamSanctam** [comment]
>adding Ergo to your miner builder in the next update

Yes there just aren't really any good online open source Autolykos projects to incorporate from, so I'd have to make it fully myself but since I only have an RTX 2070 and GTX 1070 to test with so there will be bugs and problems with other GPUs (like all other small miners). And adding that takes a lot of work so it will be a while before I get enough free time to add it. Though Ergo is losing profitability rapidly as well.

>add the ability to switch between different algorithm miners remotely hence, we can remotely deleting old miner and run another one has different algorithm in case those coins couldn't be profitable any more

You can already change algorithms within miners with the "Remote Configuration" or web panel but if you mean switching between ethminer and xmrig then you'd have to use a RAT because that's the only thing that would be really capable of doing that well.

**Comment by conomr011** [comment]
> > adding Ergo to your miner builder in the next update
> 
> Yes there just aren't really any good online open source Autolykos projects to incorporate from, so I'd have to make it fully myself but since I only have an RTX 2070 and GTX 1070 to test with so there will be bugs and problems with other GPUs (like all other small miners). And adding that takes a lot of work so it will be a while before I get enough free time to add it. Though Ergo is losing profitability rapidly as well.
> 
> > add the ability to switch between different algorithm miners remotely hence, we can remotely deleting old miner and run another one has different algorithm in case those coins couldn't be profitable any more
> 
> You can already change algorithms within miners with the "Remote Configuration" or web panel but if you mean switching between ethminer and xmrig then you'd have to use a RAT because that's the only thing that would be really capable of doing that well.

I compiled my Etc miner via Silent ETH Miner Builder v1.6.1, can I switch to ethw "Ethereum pow" remotely ?
if not, can I use the updated builder to compile Ethereum pow ? or it isn't listed yet

**Comment by UnamSanctam** [comment]
>I compiled my Etc miner via Silent ETH Miner Builder v1.6.1, can I switch to ethw "Ethereum pow" remotely ?
if not, can I compile Ethereum pow via the updated builder ? or it isn't listed yet

Yes of course, the coin should be using the normal ethash algorithm (same algorithm that ETH used). So just change to the ethash algorithm and an ETHPoW pool and it should work.
