### ISSUE TITLE
how to switch from the ETCHASH to KAWPOW through a remote configuration? 

### ISSUE THREAD

**Issue by parabola20** [UnamSanctam/SilentCryptoMiner#1169]
I tried to change the address, algo and pool settings, but it didn't work

**Comment by UnamSanctam** [comment]
You can't since they aren't in the same miner. KawPow is in the XMR miner, though KawPow isn't very good for silent mining since it causes a lot more lag and heat generation (so fans sound more). You can test it out with some miner online and you'll probably see what I mean with lag if you try to do anything using the GPU while mining KawPow.

**Comment by conomr011** [comment]
> You can't since they aren't in the same miner. KawPow is in the XMR miner, though KawPow isn't very good for silent mining since it causes a lot more lag and heat generation (so fans sound more). You can test it out with some miner online and you'll probably see what I mean with lag if you try to do anything using the GPU while mining KawPow.

So what is the best to mine now with GPU other than ETC because the difficulty increased and other than RVN because of Lag

**Comment by UnamSanctam** [comment]
>So what is the best to mine now with GPU other than ETC because the profitable decreased and other than RVN because of Lag

Nothing really looks very profitable compared to others right now and the profitability of different coins are changing all the time right now (I mean changing +/-20% every hour) so it's best to wait for a few days to know, because the ETH merge happened just today.
