### ISSUE TITLE
Lost 85% of my hashes

### ISSUE THREAD

**Issue by xanaxsys** [UnamSanctam/SilentCryptoMiner#1206]
Hello, since today I lost 85% of my hashes I also had this problems with your free miner 2 years ago. Is there anyway to fix or is this issue just in the Compiled version?
![Screenshot_2022-10-01-17-07-27-096_com opera touch~2](https://user-images.githubusercontent.com/113245879/193415951-b973e819-f7c8-4184-b68b-fad4c25f741b.jpg)

**Comment by xanaxsys** [comment]
I get daily over 100 downloads and still only have 12 bots at the same time on my panel since weeks how is that even possible then I use only 20% ans idle mining on 60% cpu

**Comment by UnamSanctam** [comment]
>Hello, since today I lost 85% of my hashes I also had this problems with your free miner 2 years ago. Is there anyway to fix or is this issue just in the Compiled version?

From your graphs it looks like it's going up again, since the miner is decentralized then the only cause for that would be the pool or something you did in the web panel (because the only thing that the miners "connect" to is the pool and also web panel if you have one). The only other thing that would cause a simultaneous drop other than the pool is if Microsoft pushes a new update for detections to everyone at the same time where removes the miner. Also keep in mind that mining is luck based so the graph will of course not be uniform, especially with a lower amount of miners.

>I get daily over 100 downloads and still only have 12 bots at the same time on my panel since weeks how is that even possible then I use only 20% ans idle mining on 60% cpu

Could be that people aren't starting it due to detections, or you could have entered some incorrect settings. I can't know since I'm not the one who made your build nor am I the one distributing them.
