### ISSUE TITLE
RVN

### ISSUE THREAD

**Issue by WSDXFCVTR** [UnamSanctam/SilentCryptoMiner#1209]
how to set up a rvn miner, and does it work at all?

**Comment by UnamSanctam** [comment]
Yes it's possible (and might work, doesn't work on mine but neither does any other RVN miner that exists). Personally I wouldn't recommend it since it makes the file size quite large (due to NVRTC), causes more lag than other algorithms and also takes more VRAM. It also isn't that much more profitable than ETC or UBQ (https://whattomine.com/).
