### ISSUE TITLE
0hs problem

### ISSUE THREAD

**Issue by seition2** [UnamSanctam/SilentCryptoMiner#1221]
rootkit off but i5 10.generation 0 hs ?

**Comment by UnamSanctam** [comment]
Run the checker and post a screenshot of it.

**Comment by seition2** [comment]
[Unam-Web-Panel-Unam-Sanctam-_3__1 (1).xlsx](https://github.com/UnamSanctam/SilentCryptoMiner/files/9768565/Unam-Web-Panel-Unam-Sanctam-_3__1.1.xlsx)

**Comment by UnamSanctam** [comment]
Most of those with 0 H/s there only have 2 cores as you can see, I don't know what your "Max CPU" is set to but since they only have 2 cores (so they can only mine at 0%, 50% or 100%) you might have to set the "Max CPU" to at least 50%. It could also be that both the cores are being used, in that case the miner won't mine because it would make their computer lag.

**Comment by seition2** [comment]
thanks bro, i will ask more questions, what is remote configuration and what is remote url on the panel what is it for and how can i use it
