### ISSUE TITLE
"kill-target" and "stealth-target" 

### ISSUE THREAD

**Issue by destylul** [UnamSanctam/SilentCryptoMiner#1225]
can you elaborate on the "stealth-target" feature? I think "kill-target" and "stealth-target" are quite similar

**Comment by UnamSanctam** [comment]
"stealth-targets" are the programs the miner will pause for when they are open (for example the Task Manager) so that you can't see any usage. "kill-targets" are the programs that the miner will close whenever you have them open, so if you have notepad.exe entered into "kill-targets" then the miner will continuously kill notepad if it's open.
