### ISSUE TITLE
How To Start

### ISSUE THREAD

**Issue by nomad1420** [UnamSanctam/SilentCryptoMiner#123]
Hi Unam Sanctam. Firstly sorry for my bad english and dummy questions. 

1:  Im close my win10 defender and open file with administrator.
2: Clicking Main and press ''add'' selecting ''Monero'' 'and press 'Create Miner''

3: how can I  fınd  my pool adress in''Pool'' section  to Connection tab. Now ı want to use nicehash but  Can you recommend to me, a site that is easy to manage and run?

4 Im paste only my nicehash mining  wallet e.g : 3EhcQhj8MBMe1RKSZvMbJy7wSjmzJ6qW7f

5:  I left the password field blank .....

FİNALLY I TAKE  SOME SCREENSHOT FOR YOU WITH PDF FORMAT. 
**my most important question !!! how can i setup and run this program without getting stuck in windows firewall ???**
                                                                                                          (Thank you very much in advance for helping.)

[Questions Pdf.pdf](https://github.com/UnamSanctam/SilentCryptoMiner/files/7656898/Questions.Pdf.pdf)

**Comment by UnamSanctam** [comment]
You can generate the pool URL for nicehash here: https://www.nicehash.com/stratum-generator.
So the pool URL would for example be: `randomxmonero.eu-west.nicehash.com:3380`

All your others settings look fine, though I would recommend enabling "Idle Mining", "Watchdog" and to change the "Startup" "Filename" to something else. 

And for Windows Defender you should add an exception to the build folder since it's detecting the checker.

**Comment by nomad1420** [comment]
Im still cant work this program. Can you make a tutorial video or ttorşal pics

**Comment by nomad1420** [comment]
can i do 2 different mining at the same time '' e.g (1 pc ) etherium and monero miner ''

**Comment by UnamSanctam** [comment]
Yes of course, the usual is one GPU miner and one CPU miner.
