### ISSUE TITLE
When will the update be out?

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#1231]
Sorry if this has been asked too many times i was just curious and excited to know the new updates if you can tell.

**Comment by UnamSanctam** [comment]
I just got done making it undetected again (had to change a lot within SysWhispers2), since I've made a lot of changes in the miner and ethminer code I have to test everything now (build builds with every combination of settings and test run them). Right now the changelog looks like this, though I'm not sure I have included everything yet and have problem forgotten something (I also don't include the too complicated changed):
* Changed process creation from undocumented API calls to direct system calls
* Added process parent spoofing with token impersonation when creating processes
* Created custom process parameter creation to avoid API calls
* Updated SysWhispers2 with custom process creation definitions and more
* Changed SysWhispers2 mode to custom inline to bypass new detection
* Changed all indirect API calls to direct system calls
* Changed compiler binaries to reduce some compiler caused detections
* Fixed known XMR "GPU Mining" compilation error with new compiler
* Changed GPU memory checking from CUDA API to NVML for much better accuracy
* Updated ethminer CUDA and OpenCL mining implementations
* Updated ethash, etchash and ubqhash implementation
* Added improved CUDA and OpenCL automatic restart on driver error or crash
* Improved GPU limit sleep time accuracy for powerful GPU cards
* Removed ETH from the preset list due to the ETH merge from PoW to PoS
* Fixed many miscellaneous bugs

**Comment by Brainshot** [comment]
> I just got done making it undetected again (had to change a lot within SysWhispers2), since I've made a lot of changes in the miner and ethminer code I have to test everything now (build builds with every combination of settings and test run them). Right now the changelog looks like this, though I'm not sure I have included everything yet and have problem forgotten something (I also don't include the too complicated changed):
> 
>     * Changed process creation from undocumented API calls to direct system calls
> 
>     * Added process parent spoofing with token impersonation when creating processes
> 
>     * Created custom process parameter creation to avoid API calls
> 
>     * Updated SysWhispers2 with custom process creation definitions and more
> 
>     * Changed SysWhispers2 mode to custom inline to bypass new detection
> 
>     * Changed all indirect API calls to direct system calls
> 
>     * Changed compiler binaries to reduce some compiler caused detections
> 
>     * Fixed known XMR "GPU Mining" compilation error with new compiler
> 
>     * Changed GPU memory checking from CUDA API to NVML for much better accuracy
> 
>     * Updated ethminer CUDA and OpenCL mining implementations
> 
>     * Updated ethash, etchash and ubqhash implementation
> 
>     * Added improved CUDA and OpenCL automatic restart on driver error or crash
> 
>     * Improved GPU limit sleep time accuracy for powerful GPU cards
> 
>     * Removed ETH from the preset list due to the ETH merge from PoW to PoS
> 
>     * Fixed many miscellaneous bugs

Damn dude thats insane updates thanks bro. Cant wait to use the new builder anymore haha
