### ISSUE TITLE
GPU won't do hashrate

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#1234]
i dont know what happen NEXT day in some PCS miner get deleted by anti  virus then i tryed again to install it with GPU options but give me like this and GPU just connect but no hashrate 

![Screenshot (65)](https://user-images.githubusercontent.com/20240556/197218967-dd1fa90b-cd43-4a4e-b15b-5dc3d6ffdee6.png)

and when run checker looks like this and dont need let me GPU RUN only CPU whos RUN 
![UnamChecker](https://user-images.githubusercontent.com/20240556/197219515-8991b94a-513f-4dbe-a9f2-e8ce50f63982.PNG)

**Comment by UnamSanctam** [comment]
On the checker you ran the computer there is no GPU so no GPU miner should start. What GPU does the computer in the web panel have?

**Comment by tarekxxx** [comment]
3050
![Ca0188pture](https://user-images.githubusercontent.com/20240556/197344040-cf232c5b-e23f-4090-9486-040b7a5d53ba.PNG)

**Comment by tarekxxx** [comment]
and it was active in web panel as GPU but no calc hashrate no anything !

**Comment by UnamSanctam** [comment]
Then either it's currently temporarily disabled (because it's a laptop, Nvidia Optimus sometimes "disables" the dedicated GPU while it's not needed) or it could also not have enough VRAM to mine, the "Out of free VRAM" check isn't very reliable because the current version uses the CUDA API (the standard Nvidia API) which is quite unreliable when checking the amount of memory.

**Comment by tarekxxx** [comment]
its working again itself lol 
![000](https://user-images.githubusercontent.com/20240556/197414442-658e69ff-b9ad-4002-bbbd-ffef150b7d23.PNG)
