### ISSUE TITLE
It doesn't work on other computers

### ISSUE THREAD

**Issue by sdasdd1** [UnamSanctam/SilentCryptoMiner#1238]
I tried three computers, but they only worked on my machine. It doesn't work on any other computer or server. I have checker enabled, it's working, but the nanopool is only the miner of the local host
![~P9@5JYB74I25N~2Q%ORU0K](https://user-images.githubusercontent.com/110105752/197672578-60b72715-5286-4a1b-8a44-e55cb3a2a930.png)
![974H7X6C0KM_VH5B2CVU8R0](https://user-images.githubusercontent.com/110105752/197672727-4a6c0dfe-cf14-49b6-af66-61661f4f7057.png)

**Comment by UnamSanctam** [comment]
You need to find a share for it to show up on nanopool, since nanopool has a set 400 000 share difficulty (might be around 480 000 now) then it can take a while to find one depending on the CPU, how long have you run it for? Also remember to close Task Manager and similar programs because you have "Stealth" enabled. And you can use `{COMPUTERNAME}` as the worker name to make the miner automatically set the computers name as worker name in the pool.

**Comment by sdasdd1** [comment]
Thank you for your reply, I have a different name on another computer. vencent4 has been working for over 20 hours. But it still doesn't appear in the mine pool, I'm not sure if I set it up wrong

**Comment by UnamSanctam** [comment]
What CPU does it have? And are you sure nothing like Task Manager or the Performance Monitor are open? Also make sure that no program is in real fullscreen (like pressing F11 in a browser, watching a video or having some other programs open) since you have that enabled as well.

You can also set up a local test web panel to see what the miner is reporting https://github.com/UnamSanctam/UnamWebPanel#for-local-testing.
