### ISSUE TITLE
how much can you make with this a month

### ISSUE THREAD

**Issue by RDisOP** [UnamSanctam/SilentCryptoMiner#1252]
not really a issue but a question 
how much can we make a month if we were to mine on for eg 3 pc with i3 and 2 with i5 on 60% mining

**Comment by UnamSanctam** [comment]
Hard to say, but CPUs aren't too profitable per computer (due to the huge amount of competition), it also depends on the exact CPU models (some i3's and i5' are better than some i7's, it depends on the exact model). But with 5 computers only CPU mining you wouldn't get very much, but CPU mining can be done on nearly any computer and is hard (though depends on settings) to detect which is why it can be very profitable if you have a lot of computers.

**Comment by D3C0D31** [comment]
Depending on how much infects you have. So you can't do math without some numbers..
You can make like 4-4000 a month XD
