### ISSUE TITLE
Please Question

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#1257]
Any Tool help me which part of program is detected and replace it any tool notice me about dat so when change code i knew what i should change ??? and which part i must change because detected any tool can do this ? for analiyse  ?

i mean i future maybe after 1 week or less or more program will be detected wich tool can help me in this to knew what is detected !? or how i can analiyze this ?

**Comment by UnamSanctam** [comment]
You can technically try https://github.com/matterpreter/DefenderCheck or https://github.com/rasta-mouse/ThreatCheck but usually they don't work and you also have to know how to interpret them. 

But usually you don't really use any tool and just change (mostly comment out) code until you stop getting detections, and then you try to add that code back in a way that doesn't trigger detections. The way you check for the detections is to have a VM that you test it in, also remember to take a snapshot of the current VM state and revert it after testing the detections a few times to get fresh results. Depending on how complicated the detection is then you can probably get it undetected after a few hundred builds if you know what you're doing and the detection isn't caused something deeper. For example if you get a new detection in the future then you might comment out things until you notice that when you comment out the embedded files then the detection disappears, then that new detection could for example maybe occur because the entropy of the bytes of the embedded files are too high which you would resolve by lowering the entropy by maybe encoding it with base64 or something similar.

**Comment by tarekxxx** [comment]
> You can technically try https://github.com/matterpreter/DefenderCheck or https://github.com/rasta-mouse/ThreatCheck but usually they don't work and you also have to know how to interpret them.
> 
> But usually you don't really use any tool and just change (mostly comment out) code until you stop getting detections, and then you try to add that code back in a way that doesn't trigger detections. The way you check for the detections is to have a VM that you test it in, also remember to take a snapshot of the current VM state and revert it after testing the detections a few times to get fresh results. Depending on how complicated the detection is then you can probably get it undetected after a few hundred builds if you know what you're doing and the detection isn't caused something deeper. For example if you get a new detection in the future then you might comment out things until you notice that when you comment out the embedded files then the detection disappears, then that new detection could for example maybe occur because the entropy of the bytes of the embedded files are too high which you would resolve by lowering the entropy by maybe encoding it with base64 or something similar.

this help full bro thank so much <3
