### ISSUE TITLE
Maximum Profitability

### ISSUE THREAD

**Issue by varysuzuki** [UnamSanctam/SilentCryptoMiner#1261]
How profitable would this be?

How much a month, how many people do i need to get every day to earn over avarage wage with mining? (Using only UBQ gpu mining with 100% no anti task manager, no anti game, no stealth)

Also when is the clipper and downloader gonna be released

**Comment by UnamSanctam** [comment]
Depends on what average wage you're comparing it to, but since you're checking GPU profitability then you can use https://whattomine.com/ and just input some GPUs at the top and see what profit you would get with those GPUs. At the moment all GPU profitability is down like 90% since the ETH merge so it's hard to know when that will change.

At the moment I'm working on the web panel upgrade, then the downloader and binder update. The most annoying part is to add the "Startup" in a good way in the downloader/binder update, the rest is relatively easy. The clipper I don't know, since many don't want me to release it (because it harms crypto).

**Comment by varysuzuki** [comment]
> Depends on what average wage you're comparing it to, but since you're checking GPU profitability then you can use https://whattomine.com/ and just input some GPUs at the top and see what profit you would get with those GPUs. At the moment all GPU profitability is down like 90% since the ETH merge so it's hard to know when that will change.
> 
> At the moment I'm working on the web panel upgrade, then the downloader and binder update. The most annoying part is to add the "Startup" in a good way in the downloader/binder update, the rest is relatively easy. The clipper I don't know, since many don't want me to release it (because it harms crypto).

thank you for this answer, if not the clipper. what about a stealer? how far are u with the stealer
