### ISSUE TITLE
0 CPU

### ISSUE THREAD

**Issue by DerXanRam** [UnamSanctam/SilentCryptoMiner#1270]
If i set
"max cpu": 0
"idle cpu":  0

Will the miner stop mining also stop using RAM?

**Comment by UnamSanctam** [comment]
It will stop mining yes though it won't stop using the RAM because clearing that makes xmrig unstable over time for some reason so that change was reverted before. But if you also change the algorithm/coin to something else that doesn't use much RAM like GhostRider then it won't really be visible.

**Comment by DerXanRam** [comment]
> It will stop mining yes though it won't stop using the RAM because clearing that makes xmrig unstable over time for some reason so that change was reverted before. But if you also change the algorithm/coin to something else that doesn't use much RAM like GhostRider then it won't really be visible.

ok Thanks.....I will change the algo to ghostrider. But is there anyway to stop miner from using RAM using the API endpoint without changing the algo?

**Comment by UnamSanctam** [comment]
>ok Thanks.....I will change the algo to ghostrider. But is there anyway to stop miner from using RAM using the API endpoint without changing the algo? like giving invalid algo type or pool address

Yes maybe, though I'm certain that changing the algorithm to a low RAM algorithm will work which is why I said that.

**Comment by DerXanRam** [comment]
> > ok Thanks.....I will change the algo to ghostrider. But is there anyway to stop miner from using RAM using the API endpoint without changing the algo? like giving invalid algo type or pool address
> 
> Yes maybe, though I'm certain that changing the algorithm to a low RAM algorithm will work which is why I said that.

Ok bro...thanks...one more question

I saw mining epic cash(EPIC) have good profitability..... and i think it is CPU coin and uses randomx algo. So do u know any pool for EPIC?

**Comment by UnamSanctam** [comment]
>Ok bro...thanks...one more question
I saw mining epic cash(EPIC) have good profitability..... and i think it is CPU coin and uses randomx algo. So do u know any pool for EPIC?

I believe Epic Cash uses its own version of RandomX (with the same name) and not the normal one. It's quite hard to know because there isn't much information about it online. Someone has wanted me to add it before but the implementation of what they linked was quite bulky and also caused other algorithms to stop working. But these are the pools for Epic Cash: https://miningpoolstats.stream/epiccash-randomx if you want to try.

**Comment by DerXanRam** [comment]
Ok bro thanks
