### ISSUE TITLE
do i need a panel?

### ISSUE THREAD

**Issue by ofthehk** [UnamSanctam/SilentCryptoMiner#1288]
im sure you dont need a panel like unam, is there a way i can track down the computers without having to host a panel?

**Comment by UnamSanctam** [comment]
Yes you don't need one but that's the only way you can "control" the computers, you can use the "Remote Configuration" if you only want to change the settings. And you can also use `{COMPUTERNAME}` as the worker name if you want to track them on the pool through their computer names. But that's about it, because to track them they would need to communicate with you in some way.

**Comment by ofthehk** [comment]
@UnamSanctam am i alright without using the panel?

**Comment by UnamSanctam** [comment]
Yes it's entirely optional.

**Comment by ofthehk** [comment]
am unfamiliar with this stuff, do i need to take certain steps to claim the money or is it a automated system?

**Comment by UnamSanctam** [comment]
Depends on your pool, but pools almost always have a minimum payout threshold that you need to reach before a payout, when you've mined enough to reach that then they'll send it to you automatically. On many pools you can also lower the threshold from it's default amount.
