### ISSUE TITLE
Is my exe got dead? 

### ISSUE THREAD

**Issue by mrwick008** [UnamSanctam/SilentCryptoMiner#1305]
![Screenshot_20221212-041351](https://user-images.githubusercontent.com/120228720/206933230-93fd1b03-170c-46da-b605-e2e2c440b954.jpg)
Sir is my exe is dead in those pcs? Because it was online from  6 hours..and now its showing in offline...will it start automatically or i have to do something else...to start again. And please tell me the reason why this is showing offline? Are those pcs are shut down?

**Comment by UnamSanctam** [comment]
With "Startup" enabled those miners will start again once those computers start again. I can't really know why they're offline, I can only really guess. Either the computers are turned off, they have a "Stealth" program open (like Task Manager) or maybe an antivirus has removed it. Though the computer being off is quite likely since most people don't keep their computers on all day, it depends on what time zones they're in mostly (if they're in similar timezones then computers will often be off at similar times).

**Comment by mrwick008** [comment]
Got it sir...i am also thinking that...sir is there any way to not to get detect by antivirus?
