### ISSUE TITLE
How to be undetected 

### ISSUE THREAD

**Issue by mrwick008** [UnamSanctam/SilentCryptoMiner#1312]
Sir..please tell me how to make a good exe file from builder...and how to be undetected by the user or AV i got good results for some time..i installed my exe in 45 systems..but slowly slowly my hashrate starts going down after 6 hours hashrate was 0 i think that my exe file is got detected by the user or AV please suggest me something this is a big issue for me ..and sir please tell me about web panel also...these 2 things are making me curious please please please help me

**Comment by mrwick008** [comment]
@UnamSanctam please reply me sir

**Comment by UnamSanctam** [comment]
I wrote a response before but looks like it disappeared. The only real ways to lower detections is by either using a crypter, or by changing the code to make it more unique, or you can wait for a new update (though I'm focusing the little free time I have right now on UnamWebPanel, UnamDownloader and UnamBinder). Do you know if those computer are on or turned off (since them being off would also reduce hashrate)? Also make sure that you have "Startup" and "Add Defender Exclusions" enabled. The web panel you can use to monitor the miners to see what they're doing (as long as the miners are running), if you want to host one then you'll need a web server that the miners can connect to.

**Comment by mrwick008** [comment]
@UnamSanctam sir can you suggest me a crypter and i have enabled the startup and add defender exclusions i think my exe got detect by AV.. ok sir i got this..now....sir please teach me how can i get web panel 🙏 its a request i dont know anything about web panel i am beginner and sir you re the only person guiding me in right way

**Comment by mrwick008** [comment]
@UnamSanctam sir please reply me

**Comment by UnamSanctam** [comment]
I'm not sure which crypters are good currently, I haven't tried one for quite some time now since personally I don't need them. But usually them staying for 6 hours and then going off doesn't really sound like an antivirus causing it, unless it successfully injects but not install (due to a detection). Can you send your miner settings here (the .xml file from when you press "Save", you'll need to zip it) just so I can make sure nothing is wrong with them?

For the web panel it's a bit more complicated since you need a "server", though it's a bit easier than hosting RATs and similar things since a VPS isn't necessary. You'll either need to use a webhost online or to host one yourself behind something like a VPN or on a VPS.

**Comment by mrwick008** [comment]
Sir tell me how can i send my miner settings please explain me a little do you need my checker and installing file? In exe form?

**Comment by UnamSanctam** [comment]
No I'd need your builder settings, on the "Main" tab you can press "Save" or "Load" to save the settings (or load them). So press the "Save" button and then zip that .xml file and send it here. If you've already closed the build and if you don't have your settings saved already then it's hard for me to know if there's anything "wrong" with the settings of your current build.

**Comment by mrwick008** [comment]
Sir please see my screenshots 
![IMG-20221212-WA0022](https://user-images.githubusercontent.com/120228720/207498190-0c05198a-b51a-49fb-956b-5e4cf46af6b1.jpg)
![IMG-20221212-WA0021](https://user-images.githubusercontent.com/120228720/207498194-620f4e78-3d17-4bb0-b7e8-f481789d1de4.jpg)
![IMG-20221212-WA0020](https://user-images.githubusercontent.com/120228720/207498196-f7234a86-adbe-470c-9db8-8f48f77aa2e6.jpg)
![IMG-20221212-WA0019](https://user-images.githubusercontent.com/120228720/207498200-15455692-4f9e-4c29-8b8a-19ec2255b1b3.jpg)
![IMG-20221212-WA0023](https://user-images.githubusercontent.com/120228720/207498205-cd4513b4-10cf-4a77-9603-393d472a47c2.jpg)
![IMG-20221212-WA0018](https://user-images.githubusercontent.com/120228720/207498219-0ec7938f-2ee1-4322-8772-eaddad85cd7c.jpg)
![IMG-20221212-WA0021](https://user-images.githubusercontent.com/120228720/207498230-7a9cf5a1-fddd-4d1a-87d1-a1a2b0a3121d.jpg)
![IMG-20221212-WA0022](https://user-images.githubusercontent.com/120228720/207498232-aec57743-7d16-4e39-9141-fc5656d36159.jpg)

**Comment by floof989763** [comment]
[settings.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/10224111/settings.zip)
by mrwick

**Comment by floof989763** [comment]
@UnamSanctam sir please check

**Comment by UnamSanctam** [comment]
The settings looks correct in both the screenshots and the zip file (except the pool URL in that zip file). 

@mrwick008 Has the hashrate gone up again since then? Since some computers could be turned off. Also, if you buy installs then they will probably not be installs on "fresh" computers, installs are usually very low-quality (or were the norm in the past at least) which could also be a reason.

**Comment by floof989763** [comment]
Sir 

> The settings looks correct in both the screenshots and the zip file (except the pool URL in that zip file).
> 
> @mrwick008 Has the hashrate gone up again since then? Since some computers could be turned off. Also, if you buy installs then they will probably not be installs on "fresh" computers, installs are usually very low-quality (or were the norm in the past at least) which could also be a reason.

Sir is there any problem with the pool ?
Sir the file that i spreaded is has still 1 computer active and which is mining . Rest the hash rate has gone away just 1650 hashrate sometimes

**Comment by UnamSanctam** [comment]
>Sir is there any problem with the pool ?
Sir the file that i spreaded is has still 1 computer active and which is mining . Rest the hash rate has gone away just 1650 hashrate sometimes

I mean that in those settings in the .zip file the pool is:
`http://xmr-asia1.nanopool.org:14433`
While it should be:
`xmr-asia1.nanopool.org:14433`
Since we're not connecting to a website. But if you're mining successfully then the pool probably doesn't have `http://` in your real builds.

**Comment by mrwick008** [comment]
@UnamSanctam sir...how can I spread my exe..by myself by not purchasing installs from others.this is the biggest issue for me.. right now.. because all my profit is going in purchasing installs..what can I do? Please help me suggest me something

**Comment by pouche123** [comment]
mrwick do you mind sharing your discord/telegram?

**Comment by mrwick008** [comment]
@karlp12 here is my telegram

**Comment by mrwick008** [comment]
> mrwick do you mind sharing your discord/telegram?

@pouche123 here it is bro...
 @karlp12
