### ISSUE TITLE
where in source code i can find Idle mining?

### ISSUE THREAD

**Issue by iinQ1337** [UnamSanctam/SilentCryptoMiner#1338]

**Comment by UnamSanctam** [comment]
Depends on what you mean, if you mean the options then they're in the builder. If you mean the C++ code for it in the modified xmrig and ethminer then they're not on GitHub at the moment. But I can explain how I do it, since I need to check the idle time of every user and not just the current user I have to make my own implementation instead of what Microsoft offers. So what I do is get the `ReadOperationCount` of all users from `csrss.exe` using WMI, then every 30 seconds I check if the total operation count has increased or not, if it hasn't then all users are idle. Then if the total idle time has exceeded the "Idle Wait" then it activates idle mining. To prevent any potential overflow of adding the `ReadOperationCount` of all users together I only use the last 4 numbers of `ReadOperationCount` and compare those.

**Comment by iinQ1337** [comment]
did you modify the xmrig project source code for your project? And is the miner backed by child processes?

**Comment by UnamSanctam** [comment]
Yes, both xmrig and ethminer are modified, they have to be to implement all the features, new algorithms and updates. Not sure but you mean by `"backed by child processes"`, but there is a watchdog that makes sure the miners are running if that's what you mean. If you mean a child process that "activates" the idle and such like some projects do then no since I directly modify it. The xmrig and ethminer forks aren't on GitHub since I wouldn't have time to maintain the repositories, but of course there's also other reasons, though most of them are due to ethminer.

**Comment by iinQ1337** [comment]
"**but there is a watchdog that makes sure the miners are running**" so, there are two miner processes?  so there are two miner processes? 1st is xmrig process 2nd is "process support" which checks if 1st process is running or not. i'm right?

**Comment by UnamSanctam** [comment]
Yes essentially, if you mine something like XMR then it will spawn an xmrig process, if you mine something like ETC then it will spawn an ethminer process, if you have both added then it will spawn both. And then if you have "Watchdog" enabled in the "Startup" tab then another process will run that checks if the miner is in the correct place and/or running or not. If the .exe is gone then it will place it back and reinstall the miner, if the miners aren't running then it will start the .exe again to reinject the miners. The wiki entry for it is here: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#watchdog, and the code for the watchdog is here: https://github.com/UnamSanctam/SilentCryptoMiner/blob/master/SilentCryptoMiner/Resources/Code/watchdog.cpp

**Comment by iinQ1337** [comment]
i got it. thank u for your answers

**Comment by UnamSanctam** [comment]
Alright, no problem.
