### ISSUE TITLE
Decrypt Commandline

### ISSUE THREAD

**Issue by Chainski** [UnamSanctam/SilentCryptoMiner#1341]
Hello Unam,

**Not an issue just a query, you can close it when you reply**

Can the commandline process be decrypted and get the wallet details, pool info etc. I just want to know how strong is the encryption

Example
```
C:\Windows\System32\svchost.exe illcaqsdrufiqvxo 6E3sjfZq2rJQaxvLPmX[REDACTED]qdy4DBfa6KA==
```

**Comment by UnamSanctam** [comment]
It's encrypted with AES, it's possible to decrypt it if you know the decryption key (like the Checker does it https://github.com/UnamSanctam/SilentCryptoMiner/blob/1df8bae3c9b7f68cdf7b2602414d9884b7f5ca42/SilentCryptoMiner/Resources/Code/Checker.cs#L90), otherwise it's pretty difficult. But it doesn't really matter since the pool traffic can be sniffed anyways.
