### ISSUE TITLE
Add window defender exclusion

### ISSUE THREAD

**Issue by floof989763** [UnamSanctam/SilentCryptoMiner#1347]
Sir i wanted to ask that if i have turned this option on in the options of your tool silent crypto muner builder . Then will the window defender have no effect on the virus?

**Comment by UnamSanctam** [comment]
Yes, as long as the exclusions aren't removed and Microsoft does not change anything then it won't detect the miner. But of course it can only add the exclusions after the miner has been started so it can still detect the miner before it has been started.

**Comment by floof989763** [comment]
And sir why are some wokers that arr active show 0 hasrate

**Comment by UnamSanctam** [comment]
Usually not enough resources to mine, if it's an ETC miner then it could be due to something else on the computer using 100% GPU.

**Comment by floof989763** [comment]
no no its a monero miner

**Comment by UnamSanctam** [comment]
Then most likely there aren't enough idle cores (for example if it's a 2 core CPU) or there might not be enough free RAM. You can try mining another coin/algorithm like any coin that uses any CryptoNight or GhostRider algorithm, if you get a hashrate then it's most likely not due to not enough RAM for RandomX.

**Comment by floof989763** [comment]
ok ok sir
