### ISSUE TITLE
miner detection issue ??

### ISSUE THREAD

**Issue by anesd2** [UnamSanctam/SilentCryptoMiner#1359]
window defender detected the miner while compiling the miner. what's your take on this ?

**Comment by UnamSanctam** [comment]
Exclude the build folder, the builder and the tools aren't made to be undetected of course. And even then it's been some time since the last update so it will be detected, as is the same with every other program. It usually gets detected 1-2 weeks after release, it's usually the same if you buy some private miner as well. You'd need a crypter if you want it undetected, like with all other programs.

**Comment by floof989763** [comment]
> window defender detected the miner while compiling the miner. what's your take on this ?

i can make your file completely fud

**Comment by kabuchi391** [comment]
? Is it free or not
