### ISSUE TITLE
Hello Unam

### ISSUE THREAD

**Issue by gurice** [UnamSanctam/SilentCryptoMiner#1368]
Hello Unam,

My friend we use your panel and you are a really great programmer. That's why I want to thank you first. The panel works very well for the CPU, but we want to add GPU mining to the same machines with remote config? So, can we have CPU mining machines do GPU mining at the same time? If possible, can you share both the CPU and GPU example configs? Also we want to reduce GPU usage in this config (max-gpu ?). VRAM doesn't matter, it can stay fixed, but downgrading the GPU processor usage is our top priority. And finally, why does RAVEN not work with kawpow? Thank you from now. I'm on a job right now, if I make a profit, be sure I want to donate to you.

**Comment by UnamSanctam** [comment]
>My friend we use your panel and you are a really great programmer. That's why I want to thank you first. The panel works very well for the CPU, but we want to add GPU mining to the same machines with remote config?

If you did not compile the miner with any GPU options enabled then your miner binaries don't contain any GPU miner or GPU libraries, so you can't enable it through the "Remote Configuration" since the code for it isn't there.

> So, can we have CPU mining machines do GPU mining at the same time?

You can mine with the CPU and GPU at the same time as long as you compiled the miner with both CPU and GPU mining.

>If possible, can you share both the CPU and GPU example configs? Also we want to reduce GPU usage in this config (max-gpu ?). VRAM doesn't matter, it can stay fixed, but downgrading the GPU processor usage is our top priority.

For ethash, etchash and uqbhash GPU mining you can use the "max-gpu" option (https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#remote-configuration), for the other algorithms (xmrig GPU mining) then you can't directly reduce the usage though for CUDA there are some options (https://xmrig.com/docs/miner/command-line-options#cuda-backend) that you can enter into "Advanced Parameters".

>And finally, why does RAVEN not work with kawpow?

It has something to do with xmrigs implementation I would guess, I can't mine RVN with any miner at all (I've tested all that I've been able to find) on either my main computer or my older laptop so I can't really test it or try to fix it since it happens for all of them. Either way KawPow isn't very good for silent mining since it causes a lot more heat and lag for the user.
