### ISSUE TITLE
Blue Screen

### ISSUE THREAD

**Issue by Squatch55** [UnamSanctam/SilentCryptoMiner#1387]
My victims keep getting bleu screen when i add GPU mining with ETC

**Comment by UnamSanctam** [comment]
Are you using "Critical Processes"?

**Comment by Squatch55** [comment]
Yes

**Comment by UnamSanctam** [comment]
Could be that the GPU miner crashes which causes the BSoD (because it's not supposed to close), are their GPU drivers and everything updated if you know?

**Comment by Squatch55** [comment]
Yeah, its latest driver for their GPU

**Comment by Squatch55** [comment]
I disabled the BSoD and it worked. But now its not mining. Like there is active miners.
![image](https://user-images.githubusercontent.com/79423107/213463972-cd0ffc81-4f4c-4985-8704-b86e3f6c0032.png)

**Comment by UnamSanctam** [comment]
>Yeah, its latest driver for their GPU

What GPU do they have? And does it happen for multiple people? Since the GPU miner shouldn't close unless something causes it to crash, usually unrecoverable incorrect/broken CUDA or OpenCL drivers/installations. Or if its a laptop then something like Nvidia optimus could be causing issues.

>I disabled the BSoD and it worked. But now its not mining. Like there is active miners.

Yes disabling it would work, is the GPU miner running if you run the checker? Since it sounds like it's not able to run. And you also need to find a share first for it to appear in the pool of course.

**Comment by Squatch55** [comment]
> What GPU do they have?

I gave it to my friend to try. I think his GPU was R7 370(AMD)

> Or if its a laptop then something like Nvidia optimus could be causing issues.

No its not

> is the GPU miner running if you run the checker?

I don't know what you mean by that. But it says: Compatible GPU found: True

> And you also need to find a share first for it to appear in the pool of course.

I have no idea how to do that. Can you explain? Im using monero.hashvault.pro for CPU and etc.ethermine.org for GPU

**Comment by shainodev** [comment]
this is happening to one of my clients too

**Comment by shainodev** [comment]
and they said that it happens when they turn off their pc

**Comment by UnamSanctam** [comment]
>I don't know what you mean by that. But it says: Compatible GPU found: True

In the checker it will show one line for each miner that's running, they will contain the pool and everything so they will be  easy to identify. But you can ask him to start this normal version of the miner: [Test5.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/10465567/Test5.zip) it will show a console that mines just like normal and you'll be able to see what it says.

>I have no idea how to do that. Can you explain? Im using monero.hashvault.pro for CPU and etc.ethermine.org for GPU

When you mine to a pool you will first have to find a share before it appears in the pool: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining. Though that's of course as long as the miner is actually running.

>and they said that it happens when they turn off their pc

It could happen if the computer forcibly kills the miner since it's a critical process, but that shouldn't really happen because Windows also ends a lot of other critical processes.
