### ISSUE TITLE
Overclock

### ISSUE THREAD

**Issue by madani2003** [UnamSanctam/SilentCryptoMiner#139]
Hi Unam, 
I got a question, is there a way to overclock the GPU automatically when i launch the exe?

**Comment by UnamSanctam** [comment]
Not really but not that you'd want that anyway, every GPU has different optimal (though fiercely debated) settings and they differ wildly so an automatic overclock (or underclock which you can also do) won't really be a good idea, especially since I'm only one person and only have one GPU to test on.

**Comment by madani2003** [comment]
Yeah, i get what you mean by that, but wouldn't we be able to maximize our mining output by overclocking the GPU? 
I think it would be great if you could add the option to overclock the GPU later on in your updates, and i also saw that NB-Miner recently added the option to overclock the GPU in their most recent update (v40.0(2021-11-23))
https://github.com/NebuTech/NBMiner

![image](https://user-images.githubusercontent.com/95303657/145977524-cc5e2e12-0940-4bff-9a15-6082cff59179.png)

**Comment by UnamSanctam** [comment]
Yes but that's not automatic, you will have to specify each setting for each GPU, the values for each GPUs differ greatly.
