### ISSUE TITLE
Auto update on webpanel

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1394]
I was thinking of a way to do it since you said that it needs the miner-uninstaller. But wouldnt it be possible to just put the path of the miner in the commandline of ethminer.exe and just make the ethminer replace that on update? then open it and close itself and ofcourse more stuff for good measure like adding startup or something or dropping the new file in temp and waiting 10 secs and checking if it exists (to see if antiviruses delete it) and then if it does exist then it deletes the temp file and does the update process

**Comment by UnamSanctam** [comment]
Would only really work well if the settings for both the builds are the same (and that the two versions don't work too differently), since if they are different then you could have two different miners installed or some option still enabled from the old one. Another problem would be if they have "Critical Processes" enabled, since then if you have two miners running then the one that received the update call first (unless I were to only send it to one in the web panel itself) would have to first remove the critical process state from both the miners and then it would have to kill both as well so I'd have to build some things into the miners.

**Comment by shainodev** [comment]
> Would only really work well if the settings for both the builds are the same (and that the two versions don't work too differently), since if they are different then you could have two different miners installed or some option still enabled from the old one. Another problem would be if they have "Critical Processes" enabled, since then if you have two miners running then the one that received the update call first (unless I were to only send it to one in the web panel itself) would have to first remove the critical process state from both the miners and then it would have to kill both as well so I'd have to build some things into the miners.

Oh true, But could you atleast add an botkiller feature?

**Comment by shainodev** [comment]
Would it be bad or detected to do netstat -a -n, and get all the IP's and PID's and then search from the IP's if its any known mining ip and if it is then it closes the app. And then it gets all the running apps and uses virustotal api to scan them.

**Comment by shainodev** [comment]
Also is there a way that the ethminer could have a start delay? since one of my victims opened my program and then immediately noticed the lag

**Comment by shainodev** [comment]
Also what does the ethminer.exe do when the person HAS a gpu but it isnt good enough to mine the coin specified?

**Comment by UnamSanctam** [comment]
>Oh true, But could you atleast add an botkiller feature?

Not at the moment since I have to do a lot of testing for it but I can add it to my list.

>Would it be bad or detected to do netstat -a -n, and get all the IP's and PID's and then search from the IP's if its any known mining ip and if it is then it closes the app. And then it gets all the running apps and uses virustotal api to scan them.

You could do that with the IPs though making a list of all mining pool IPs wouldn't be a very fun experience. I would not really recommend the VirusTotal API scan of all running programs though since it would be very unwieldy.

>Also is there a way that the ethminer could have a start delay? since one of my victims opened my program and then immediately noticed the lag

Maybe, not sure where that would fit in though, maybe the "Advanced Parameters. The initial lag is usually from the DAG generation if they have a low-end GPU.

>Also what does the ethminer.exe do when the person HAS a gpu but it isnt good enough to mine the coin specified?

It will just wait until they have enough VRAM (which is never in that case), so it will just wait in the background.

**Comment by shainodev** [comment]
> Not at the moment since I have to do a lot of testing for it but I can add it to my list.

Please do.

> You could do that with the IPs though making a list of all mining pool IPs wouldn't be a very fun experience.

The problem i already realized with it was that i could not do anything with it anyways since its injected (i can only terminate but not delete anything nor remove any startup) so that seems kindof useless now.

> Maybe, not sure where that would fit in though, maybe the "Advanced Parameters. The initial lag is usually from the DAG generation if they have a low-end GPU.

But they had a high-end GPU, CPU and i use 50% gpu and 30% cpu, how could i prevent this?

> It will just wait until they have enough VRAM (which is never in that case), so it will just wait in the background.

Oh.

**Comment by shainodev** [comment]
tbh i cant find the issue where i talked about uninstalling Avast or Malwarebytes silently. but since i have so many issues open ill talk here. I tried to do the uninstalling. And installed malwarebytes free trial on my pc and it didnt detect anything at all. My strings arent even obfuscated at all or anything and malwarebytes didnt do anything

**Comment by shainodev** [comment]
Also do you know what does this mean:

XMR Miner:
- Utilizing XMRig
- Stealth mining. Miner will be paused whenever target is active and resumed when idle.
- CPU: Hashing speed of up to 2000 H/s on a modern strong i7 processor.
- GPU: Utilizes XMRig-CUDA whenever possible for even higher hash speed rate.
- Advanced options include; select threads, algorithm, donation value, process priority and more.
- 64-bit option for faster mining [Recommended].
- Live statistics in a managed table of all mining bots with total hash rate.
- Individual log view.

More specifically "- 64-bit option for faster mining [Recommended]."

**Comment by UnamSanctam** [comment]
>tbh i cant find the issue where i talked about uninstalling Avast or Malwarebytes silently. but since i have so many issues open ill talk here. I tried to do the uninstalling. And installed malwarebytes free trial on my pc and it didnt detect anything at all. My strings arent even obfuscated at all or anything and malwarebytes didnt do anything, is that normal? or is malwarebytes really that bad

Yes I believe they don't check that, don't know if it's any different in a real premium subscription or not though.

>More specifically "- 64-bit option for faster mining [Recommended]."

Not sure what silent miner you're getting that from but they might be offering both 32-bit and 64-bit builds, where 64-bit is faster for mining.

**Comment by shainodev** [comment]
> Yes I believe they don't check that, don't know if it's any different in a real premium subscription or not though.

Should i remove it then?

> Not sure what silent miner you're getting that from but they might be offering both 32-bit and 64-bit builds, where 64-bit is faster for mining.

I got it from bitrat, how could possibly the bit of the app change the speed?

**Comment by UnamSanctam** [comment]
>Should i remove it then?

Sure I don't think there's a downside.

>I got it from bitrat, how could possibly the bit of the app change the speed?

Because 64-bit can handle more data at once, so if a program needs to handle larger amounts of data then 64-bit can be faster, and it also has more registers. I haven't tested xmrig build for 32-bit in a long time though. There's a ton of differences between the architectures and the subject of performance between them is quite complicated and can also be quite controversial.

**Comment by shainodev** [comment]
Idk if I have asked this before. but,

Would it be better to use blueloader or just a downloader on startup to hold bots?

And if i do should i use a seperate vps for blueloader and pureminer? 

And thinking logically and detection wise, your miner would be as good as pureminer if i would use blueloader and your miner on the autotask right?

**Comment by shainodev** [comment]
also will it be more detected to use the Common thing on rats. for example Quasar-Common or for example asyncrat's MessagePack?

**Comment by shainodev** [comment]
and will a regex make my app more detected
