### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mljamels** [UnamSanctam/SilentCryptoMiner#1396]
i am new to this and i appreciate your effort, I am trying to infect the low-med pc I successfully infected 5 pc's by using discord i convinced ppl to use the cheker &  it was mining 
after i try it on my laptop (Intel(R) Celeron(R) 2957U (it has 2 cores) & 4gb ram ) the same think happen it was working but not showing on the pool
so i changed the miner from max 20 to max 50 and i leave ideal on 60 , in the second miner it works , but if i manage to infect mid or high end pc that will be noticeable what should i do
(i use 2miners pool by the way) i read few issues and I found out that share difficulty play role in this so can you suggest any pool that will be good for me 
thank you for you effort

**Comment by UnamSanctam** [comment]
Yes that's unfortunately the problem with low-end CPUs since they have so few cores. But if the miner is using CPU and it's not appearing on the pool then as you said it could be because your hashrate is very low compared to the pool share difficulty so finding a share takes a very long time. So you could try MoneroOcean in that case, in which you could also try mining some other cryptocurrency that requires less resources such as RTM or some other supported coin (MoneroOcean automatically exchanges to Monero).
