### ISSUE TITLE
figuring using xmrig proxy with build

### ISSUE THREAD

**Issue by harshitrajj** [UnamSanctam/SilentCryptoMiner#1400]
can you help me in setting up the xmrig-proxy with the miner build like how to link those sry i am newbie to this

**Comment by floof989763** [comment]
> can you help me in setting up the xmrig-proxy with the miner build like how to link those sry i am newbie to this
message me on telegram https://t.me/Samtg123.

**Comment by UnamSanctam** [comment]
Either you would have to get a VPS or a VPN with port forwarding, but both options usually costs money (since they're a service). Alternatively since you're using the web panel then you could try changing the mining pool from the "Configurations" until you find one that isn't blocked by your internet.

**Comment by xi-pinmping** [comment]
As someone with a VPS already Im also interested in this.
