### ISSUE TITLE
XMrig Proxy

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1402]
Good afternoon Unam. I mine XMR on a pool Moneroocean. I unite the workers with XMrig Proxy. As long as there are not many workers, everything works fine. When I switch more workers I get an error like in the screenshot.
![1](https://user-images.githubusercontent.com/36513967/214879232-7fd81170-0c12-4dfe-bac5-f04147dfd22d.jpg)
You can see in the screenshot below that when I reduced the number of workers, everything became normal. What could be the problem?

**Comment by UnamSanctam** [comment]
Firstly, are you using some other mode other than 'nicehash'? Since you have 108 upstreams with 373 miners (max 626) which is a low ratio of 1:3 (or 1:6 for the maximum amount). I would also recommend updating the proxy to 6.18.0. Other than that you could also try increasing the port number (since it corresponds with share difficulty). The reason for the message is usually that you're submitting too many shares.

**Comment by masterjek** [comment]
> Firstly, are you using some other mode other than 'nicehash'?
Here are my config settings.
![2](https://user-images.githubusercontent.com/36513967/214884828-3fb2bb37-149e-41cd-8483-3922ab186f63.jpg)
If I did something wrong, please tell me how it should be.



> Other than that you could also try increasing the port number (since it corresponds with share difficulty). The reason for the message is usually that you're submitting too many shares.

Is the port gulf.moneroocean.stream:20128 - It's like a port just for the maximum difficulty of mining. Or I'm wrong?

**Comment by UnamSanctam** [comment]
It's the port for the first difficulty used before any of the variable difficulty starts happening. But the most important thing is probably to update your xmrig-proxy. Hopefully it would somehow solve your upstream ratio since it's is terrible. You have a ratio of 1:3 while the maximum is 1:255.

**Comment by masterjek** [comment]
I just updated XMrig Proxy. Now it looks like this.
![3](https://user-images.githubusercontent.com/36513967/214887991-50356524-bcbd-4c0f-ba3a-a5430b5e6429.jpg)
I wasn't interested before. How do I understand the meaning upstreams - should be as small as possible. I understand correctly?

**Comment by UnamSanctam** [comment]
Each upstream is one connection to the pool, so if you have 100 upstreams then that means you have 100 connections to the pool (the pool sees 100 miners). Right now when you only have 2 upstreams then you only have 2 connections so the pool only sees 2 miners. When you had a ratio of 1:3 before then you had one pool connection for each 3 miners that were connected to the proxy. So yes there should preferably be as little upstreams as possible, since then the pool sees less miners.

**Comment by masterjek** [comment]
Final question meaning upstreams - Lowered by settings config.json. Or is this value configured in the XMrig Proxy and I can't set it up.

**Comment by UnamSanctam** [comment]
It can go to a maximum of 256 miners per upstream (due to how the NiceHash subjobs splitting works) so it will try to do that as best as it can unless there are any bugs or if it is unable to do so.

**Comment by masterjek** [comment]
Thanks for the help.
