### ISSUE TITLE
Malwarebytes

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1428]
![image](https://user-images.githubusercontent.com/77803435/217858462-d9dac2e1-b2ad-4fc7-98cd-54a801f65bb2.png)
how do i bypass this? do i use some not well known pool to mine? but wont that be more untrusted for someantiviruses or be less stable

**Comment by UnamSanctam** [comment]
Yes either that or set up your own xmrig-proxy, though that wouldn't work for ETC of course.

**Comment by shainodev** [comment]
> Yes either that or set up your own xmrig-proxy, though that wouldn't work for ETC of course.

or maybe should i do that and make the miner uninstall malwarebytes every launch?

**Comment by UnamSanctam** [comment]
You could try that yes.

**Comment by shainodev** [comment]
does it cost alot to make a xmrig-proxy? and is it worth it

**Comment by shainodev** [comment]
and what not popular mining pools do you suggest if you know any?

**Comment by UnamSanctam** [comment]
You just need somewhere to host it usually a VPS or on your own computer behind a VPN (that support port forwarding). You can find mining pools here: https://miningpoolstats.stream/monero, not sure which ones they have blocked.

**Comment by shainodev** [comment]
> You just need somewhere to host it usually a VPS or on your own computer behind a VPN (that support port forwarding). 

if i do it on my computer behind a VPN wouldnt i get caught? and also i would have to keep my pc open 24/7?

> You can find mining pools here: https://miningpoolstats.stream/monero, not sure which ones they have blocked.

moneroocean.stream?

**Comment by shainodev** [comment]
should i also use monerooceans xmrig proxy since it has algo switching option inside the proxy?

**Comment by shainodev** [comment]
do you have a suggested arguments for proxy?

**Comment by shainodev** [comment]
also i cant help but notice that when opening the miner on any.run (i viewed the public submissions and found your miner) it creates like alot and when i say alot i mean alooooot of processes (with the disable windows updates, startup, etc). wouldnt it be better to do all these by code not by shellexecute? and should i use like URLDownloadtofileA on my downloader? or would it make it detected

**Comment by UnamSanctam** [comment]
>if i do it on my computer behind a VPN wouldnt i get caught? and also i would have to keep my pc open 24/7?

You would use a no-log VPN so unless they're lying then no. And yes it would always have to be running.

>moneroocean.stream?

You can test it, I don't know what malwarebytes have on their blacklist.

>should i also use monerooceans xmrig proxy since it has algo switching option inside the proxy?

Doesn't matter since you're not doing algo-switching anyways.

>do you have a suggested arguments for proxy?

There isn't really much to change.

>also i cant help but notice that when opening the miner on any.run (i viewed the public submissions and found your miner) it creates like alot and when i say alot i mean alooooot of processes (with the disable windows updates, startup, etc). wouldnt it be better to do all these by code not by shellexecute?

You can't do most of them by code which is why it uses commands, and it doesn't do it using ShellExecute (obviously) it uses NtCreateUserProcess. Doing it by code can also be more detected during runtime.

>and should i use like URLDownloadtofileA on my downloader? or would it make it detected

You can try though I believe it has limitations.

**Comment by shainodev** [comment]
And do you know how i could use just a proxy to mine not a xmrig proxy or anything?

**Comment by UnamSanctam** [comment]
>i have to have monerooceans xmrig to do that?

Yes but it's not the best for silent mining, it's a bit better now but there are still downsides and limitations.

>Thats more undetected?

In some cases yes since Windows API calls can 

>yeah but not doing it by code is reallly like LOUD if you know what i mean.

Sure but you can't do many of them programmatically, but doing some of them programmatically instead of using the command line (such as the power configuration, service stopping and registry changes) increased my test programs detections from 5/71 to 53/71. I have been trying to get around it but the Windows API calls for them make antiviruses really mad.

>limitations as in detections?

That and it can have problems on older Windows versions since it uses the built-in Internet Explorer I believe.

>Also is there any way i can use your syswhispers whatever thing just inside my program without having to use your builder to build the whole app? and would it be detected to do so?

Yes you can, and technically it would be less detected than using normal API calls since you're using system calls.

>And do you know how i could use just a proxy to mine not a xmrig proxy or anything?

In xmrig there's a command `--proxy=HOST:PORT` that you can add into "Advanced Parameters".

**Comment by shainodev** [comment]
> Sure but you can't do many of them programmatically, but doing some of them programmatically instead of using the command line (such as the power configuration, service stopping and registry changes) increased my test programs detections from 5/71 to 53/71. I have been trying to get around it but the Windows API calls for them make antiviruses really mad.

but what should i do then? theres adding a antiVM that works but when i want the people to for example: when the app doesnt work i want them to record using processhacker2 and seeing if it opens werfault.exe when it closes or not, then i want them to not notice the powershell code opening or something (same case for the conhost.exe being so blatant) i know theres a rootkit but with that comes stability problems and detection problems. 

Is there not any way to like modify the memory of ethminer.exe to put in arguments that way not be in the commandline? Or maybe is there a way to spoof the parent process to something legit?

> Yes you can, and technically it would be less detected than using normal API calls since you're using system calls.

so i should use your syswhispers to replace the shellexecute and that will be better?

> In xmrig there's a command `--proxy=HOST:PORT` that you can add into "Advanced Parameters".

but none for eth? and how do i create a proxy with a vps for example

Also I'm thinking of maybe checking the antiviruses and if Malwarebytes or Windows Defender is ONLY there then i will download the miner and do the malicious stuff and then of course i said malwarebytes cause i can uninstall it and then the website blocker will prevent them from downloading anything else. or is this idea bad?

**Comment by UnamSanctam** [comment]
>but what should i do then? theres adding a antiVM that works but when i want the people to for example: when the app doesnt work i want them to record using processhacker2 and seeing if it opens werfault.exe when it closes or not, then i want them to not notice the powershell code opening or something (same case for the conhost.exe being so blatant) i know theres a rootkit but with that comes stability problems and detection problems.

You can try changing it so that it does it all programmatically and see how it goes.

>Is there not any way to like modify the memory of ethminer.exe to put in arguments that way not be in the commandline? Or maybe is there a way to spoof the parent process to something legit?

Not really unless you were to do it using environmental variables or something, but the parent process is already spoofed to 'explorer.exe' if you're using my injection.

>so i should use your syswhispers to replace the shellexecute and that will be better?

Sure but you'd still have to code the process creation yourself, unless you use some pre existing code like the one I made in my miner.

>but none for eth? and how do i create a proxy with a vps for example

No there's none built into ethminer, for the VPS you'd have to just make it into a proxy server, but at that point it would probably be easier to just run xmrig-proxy.

>Also I'm thinking of maybe checking the antiviruses and if Malwarebytes or Windows Defender is ONLY there then i will download the miner and do the malicious stuff and then of course i said malwarebytes cause i can uninstall it and then the website blocker will prevent them from downloading anything else. or is this idea bad?

It's not a bad idea really no.

**Comment by shainodev** [comment]
> Not really unless you were to do it using environmental variables or something

Is it a bad idea to do?

> but the parent process is already spoofed to 'explorer.exe' if you're using my injection.

Yeah but thats still reaalllyyy loud since i dont think explorer is gonna be opening conhost or something like that, why not wininit.exe?

> No there's none built into ethminer, for the VPS you'd have to just make it into a proxy server, but at that point it would probably be easier to just run xmrig-proxy.

what do i do for the ethminer then do i really have nothing at all?

> It's not a bad idea really no.

would it be detected to programatically call WMI to check antiviruses?

**Comment by shainodev** [comment]
Also, why cant you use MSBuild or something to make the miner instead of gcc

**Comment by UnamSanctam** [comment]
>Is it a bad idea to do?

Not really, it's just that writing environmental variables and then reading that inside the miner isn't the most optimal.

>Yeah but thats still reaalllyyy loud since i dont think explorer is gonna be opening conhost or something like that, why not wininit.exe?

Explorer usually has things opened, everything you open from the explorer has explorer.exe as its parent process. On my main computer explorer.exe has 30 child processes, including 2 conhosts. And wininit.exe requires Admin/System permissions.

>what do i do for the ethminer then do i really have nothing at all?

Yes there isn't much really, but I have been testing other solutions such as environmental variables since I plan to change it in the next version.

>would it be detected to programatically call WMI to check antiviruses?

Everything is detected to some degree, when trying to avoid antivirus detections you just have to build it and see if it works for you or not.

>Also, why cant you use MSBuild or something to make the miner instead of gcc

That was the first thing I tried it in. But because every user would need to install the Visual Studio Build Tools, even if the non-IDE version is used then they still have to go through the install even if it's run silently. It also breaks for some people since it's made my Microsoft, which means everything is bloated and broken (I have to manually modify some registry files to make it work in one of my VMs). It is available through a nuget package but I don't really want to bundle it. And even then building it using MSBuild isn't very easy either. I have been experimenting with using it but MSBuild really isn't meant for portable builds.

**Comment by shainodev** [comment]
> Everything is detected to some degree, when trying to avoid antivirus detections you just have to build it and see if it works for you or not.

Well i got 

> That was the first thing I tried it in. But because every user would need to install the Visual Studio Build Tools, even if the non-IDE version is used then they still have to go through the install even if it's run silently. It also breaks for some people since it's made my Microsoft, which means everything is bloated and broken (I have to manually modify some registry files to make it work in one of my VMs). It is available through a nuget package but I don't really want to bundle it. And even then building it using MSBuild isn't very easy either. I have been experimenting with using it but MSBuild really isn't meant for portable builds.

But it does avoid a lot of detections i think

**Comment by wnetMC** [comment]
I have a repo for making any file fud

**Comment by shainodev** [comment]
Also i wanted to ask if i should remove the website blocker, since ive noticed people wanting to download malwarebytes and then they cant cause the website doesnt connect so they either ask their friend for malwarebytes setup or they reset their pc, what should i do?

**Comment by shainodev** [comment]
> I have a repo for making any file fud

Which repo?

**Comment by UnamSanctam** [comment]
>But it does avoid a lot of detections i think

Possibly, though I just tested it with the new (in development) UnamDownloader version (that isn't undetected yet) and it gets detected by Windows Defender when built with MSBuild as well. Both gcc and msbuild give 2/71 detections for it.

**Comment by wnetMC** [comment]
> > I have a repo for making any file fud
> 
> Which repo?

https://github.com/wnetMC/Windows-Defender-Bypass
