### ISSUE TITLE
help

### ISSUE THREAD

**Issue by haunted199** [UnamSanctam/SilentCryptoMiner#143]
friend, please explain to me if I have enabled shellcode then should I activate wathdog? and also my panel does not work, but mining is in progress

**Comment by UnamSanctam** [comment]
Doesn't matter, the shellcode and watchdog are independent of each other and enabling or disabling one won't affect the other. Make sure that the web panel URL is correct (only use https if you have a certificate otherwise use http), also make sure that your PHP version is 7.4 or above and lastly make sure that all your files have the correct permissions.
