### ISSUE TITLE
Miner have bug with XMR?

### ISSUE THREAD

**Issue by 0xZikoo** [UnamSanctam/SilentCryptoMiner#144]
Hello, why do I have big drops?

![image](https://user-images.githubusercontent.com/96027824/146234076-23829b49-466c-4def-a523-bd21d86291d3.png)

**Comment by UnamSanctam** [comment]
That's how mining works, it will only go up when you submit a share, since nanopool has a share difficulty of 400 000 it will submit shares less frequently. Check point 3 on this page: https://help.nanopool.org/article/62-faq#6.-hashrate

This FAQ is also partly relevant in terms of pool calculations: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-the-hashrate-shown-on-the-pool-different-from-what-i-expect-or-from-what-is-shown-in-the-web-panel

**Comment by 0xZikoo** [comment]
Okay thanks i see now, last question why i have 0H/s 
![image](https://user-images.githubusercontent.com/96027824/146239109-60ec456a-b24f-4ea2-b576-a94a22505ae5.png)
Maybe I don't have enough GB on my GPU to load the etc?

**Comment by 0xZikoo** [comment]
I have 
![image](https://user-images.githubusercontent.com/96027824/146239292-84fdde2d-9446-483f-b4d8-ee3099dd6611.png)

**Comment by UnamSanctam** [comment]
Yes most likely, ETC takes between 2.8-3GB of VRAM and Windows (10%-20%) and other programs will also take some so 3GB won't be enough.

**Comment by 0xZikoo** [comment]
That's what I thought. Thank you for your quick response.

**Comment by UnamSanctam** [comment]
Yes I'm aware, seems to be some bug with datatables (or maybe how I fetch it), it used to work but I must have accidentally changed something.

**Comment by 0xZikoo** [comment]
I'll try to fix it if I can, I'll get it for you

**Comment by UnamSanctam** [comment]
Search and sorting has been fixed in the new version.
