### ISSUE TITLE
Injection into explorer.exe

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1440]
Good afternoon Unam. Tell me, a lot of changes need to be made to the code in order to return the injection to explorer.exe in version 3.1.0?

**Comment by UnamSanctam** [comment]
Since explorer.exe isn't in System32 then you'd need to change the injection paths since all other injection options are inside System32. So what would need to be done is to either a) Add explorer.exe into the injection selection and change all paths to point directly towards the Windows folder (would break all other options) or b) Add explorer.exe into the injection selection and change the code to change between the Windows folder and System32 depending on whether it's injecting into explorer.exe or any of the other options. If you're only ever planning to inject into explorer.exe then the first option would work.

**Comment by masterjek** [comment]
And in new versions you will not return the injection to explorer.exe?

**Comment by UnamSanctam** [comment]
Maybe, the problem was the Windows Defender was detecting the injection into explorer.exe but not any other programs. So if that stops happening then maybe.

**Comment by UnamSanctam** [comment]
Hmm, it was the opposite for me on Windows 10 and 11. Though I only tested on 7 different computers/VMs (3 computers, 4 VMs) so the sample size isn't that big. That was back in 07/09/2022 though so it might be different now, I'd have to redo the tests.

**Comment by masterjek** [comment]
I tested with the following antiviruses: OS: Windows 10 Version 21H2
1. Avast
2. Avira
3. Kasperskyi Internet Security
4. Max Secure
5. Nod 32 Internet Security
6. Windows Defenred
7. Zillya Internet Security
So these antiviruses allowed injection into explorer.exe

**Comment by UnamSanctam** [comment]
Alright, then it is different now, I only tested Windows Defender and Avast last time and both of them blocked explorer.exe then, Windows Defender blocked it with the DefenseEvasion detection while Avast used the normal generic detection name they use. So I'll add explorer.exe into the development versions options and add it into my testing list for version 3.2.0.

**Comment by masterjek** [comment]
It will be great if in version 3.2.0 there is an injection into explorer.exe
Avast now miners from version 3.1.0 does not delete the miner file itself, but deletes the fake application where it is embedded, and the miner file itself remains on the computer. I even emailed you about this.
