### ISSUE TITLE
schtasks /create

### ISSUE THREAD

**Issue by svox07** [UnamSanctam/SilentCryptoMiner#1445]
hello Unam can you drop schtasks /create with your settings to run it on command line cmd.exe

**Comment by svox07** [comment]
I need a command to be able to execute his command line

**Comment by UnamSanctam** [comment]
The full line is here:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/1df8bae3c9b7f68cdf7b2602414d9884b7f5ca42/SilentCryptoMiner/Classes/Codedom.cs#L395
It only uses the schtasks command on Windows 7, because the command does not support all different settings, such as the option to run on battery power.

**Comment by svox07** [comment]
it turns out there will be one option left is to import the settings xml file

**Comment by UnamSanctam** [comment]
Yes but then you'd have to write an XML file to the disk.
