### ISSUE TITLE
hosting your exe

### ISSUE THREAD

**Issue by floof989763** [UnamSanctam/SilentCryptoMiner#1458]
hello sir!
its not an issue i will close it as soon as i get my answer. sir i use your miner... and it is working perfectly. but people in the market need direct download link for the exe. like a link which when clicked on it should start  downloading your exe through the browser.
can you please guide me sir??

**Comment by UnamSanctam** [comment]
The easiest way is to use Discord (create a new account, share the file somewhere, such as a private server or between two accounts and then copy the link) but your file could get removed. Otherwise you can use something like BitBucket but setting it up can be difficult, then there are also guides online for getting direct downloading links from Dropbox or Google Drive.

**Comment by UnamSanctam** [comment]
Yes there aren't really any permanent direct download sites, it's more like which one will keep it the longest before removing it.

**Comment by floof989763** [comment]
sir people provide link to thier exe's such as
https://klh.ajn322bb.com/files/pe/pb1101.exe
and the file directly downloads
please guide me to do the same sir
