### ISSUE TITLE
Hello Unam (kawpow)

### ISSUE THREAD

**Issue by tallops** [UnamSanctam/SilentCryptoMiner#1459]
Kawpow rvn mining shows 0h/s. Can you help?

Thank you.

**Comment by tallops** [comment]
Build running > 6052mb usage

**Comment by tallops** [comment]
Web panel https://imgur.com/U3DaoEU

**Comment by UnamSanctam** [comment]
If you stop the miner does the VRAM usage decrease? Just to know whether it could generate the DAG or not since there's no "Out of free VRAM" status for KawPow since it uses xmrig.

**Comment by tallops** [comment]
> 

yes i stopped it and it dropped 2100mb.

**Comment by UnamSanctam** [comment]
Hmm alright, can you try with the normal xmrig and see if you get any hashrate there? KawPow doesn't work for me with any miner (I've probably tested all miners that exist) so I can't really test it on my side.

**Comment by UnamSanctam** [comment]
You also need https://github.com/xmrig/xmrig-cuda if you don't already have it.

**Comment by tallops** [comment]
Thank you i install plugin after run > https://imgur.com/Or0Z29b

**Comment by UnamSanctam** [comment]
Hmm, I can't really find anything about the error. Frankly I would recommend mining something else to be honest, getting errors with KawPow seems to be quite common. The biggest problems with KawPow for silent mining are really: 1) A much larger file size since it requires bundling of NVRTC, 2) Requiring quite a lot of VRAM (https://minerstat.com/dag-size-calculator) and 3) Potentially causing quite some lag and extra heat (fan sound) for the user since KawPow is more focused on core GPU usage than other algorithms.

**Comment by installs-provider** [comment]
hello!
I sell high quality installs for miner at high cpu and gpu configurations. ping me on telegram- https://t.me/karlp12  if someone needs.
