### ISSUE TITLE
How do I change the remote configuration URL?

### ISSUE THREAD

**Issue by slezerr** [UnamSanctam/SilentCryptoMiner#1462]
Is there a setting I can put in my remote config files that can change them (I want to host my config files on a new domain)

**Comment by UnamSanctam** [comment]
You can with `"remote-config": "Remote Configuration URL",` but that will only be until the next miner restart since it's not persistent (saved anywhere) for both simplicity, stealth and security reasons (for example so that no miner could potentially be permanently stolen if someone were to gain access to your "Remote Configuration" or web panel).

**Comment by slezerr** [comment]
Okay, is there a more permanent way to do this? Or could I simply keep the line that redirects the miners to the new domain?

**Comment by UnamSanctam** [comment]
There's no permanent way except building a new miner with those settings (the initial miner settings are always the one from the builder), but yes you can keep that line in there and it will always redirect the miner to the new domain when it first starts up.

**Comment by slezerr** [comment]
Alright thanks for the fast reply as always, much love.
