### ISSUE TITLE
im kind of new to coding

### ISSUE THREAD

**Issue by A3ima** [UnamSanctam/SilentCryptoMiner#1469]
i wanted to integrate this into a python app i want to make, but idk how to make the python script im coding to choose options in ur app and compile it, can u give me an idea on how i can do it?

**Comment by UnamSanctam** [comment]
Depends on what you're trying to do, are you trying to code a builder for it in Python or the actual miner itself (the injector, installer, etc)? Though both of them would require quite advanced knowledge and experience in programming.

**Comment by A3ima** [comment]
a builder

**Comment by A3ima** [comment]
can you guide me?

**Comment by UnamSanctam** [comment]
It really depends on what you're actually trying to make, are you trying to recreate my whole builder and miner inside Python or are you just making a wrapper for it in Python?

If you're just making a wrapper then the easiest thing would be to make your Python script generate a configuration XML file that the miner can use, an example of it is here: https://github.com/UnamSanctam/SilentCryptoMiner/files/9377744/ExampleSettings_Lite.zip. Then you would modify my miner builder a bit so that when your Python script starts my builder then it reads that XML file and build the miner to a location and then closes.

If you're looking to recreate it then it's a very complicated thing but if that's what you want to do to learn then that's fine, are you going to use my program to choose all the settings or are you going to make your own builder? If that's so then you should first decide on a GUI library for Python that you're going to use and then you'll have to recreate each GUI element from my builder inside that. If you want to make the actual miner injector/installer itself then that's going to be a lot more difficult, but you would do the same thing then, you would look at the miners code here https://github.com/UnamSanctam/SilentCryptoMiner/tree/master/SilentCryptoMiner/Resources/Code (miner.cpp and then the files inside Files.zip that it uses) and then recreate it as best you can in Python.

**Comment by A3ima** [comment]
thanks for the help
