### ISSUE TITLE
Suggestion and Question 

### ISSUE THREAD

**Issue by Torpedo0x** [UnamSanctam/SilentCryptoMiner#1480]

**Comment by Torpedo0x** [comment]
> The miner is made in C++, the assembly loading is only for .NET assemblies and not native binaries.
so how can i load it , i'm using Reflection.Assembly]::Load($decrypted.ToArray()).EntryPoint.Invoke($null, @())
to all .net executables and it works fine but with your miner it's not
could you please provide me with the right method?

**Comment by UnamSanctam** [comment]
Because the miner is not a .NET executable, it's made in C++ so it's a native executable. If you want to load it into memory then you should inject it (like all crypters do).

**Comment by Torpedo0x** [comment]
Great, I've been trying my x64 RunPE Library and I'm invoking the methods from the Library to inject the miner bytes to a native process, but still not working with your miner, It's working with other native executables thou. IDK where the problem is but i tried a lot .
If you have any suggestions for an open source RunPE worked with your miner before so I can develop it, I will be thankful.

**Comment by Torpedo0x** [comment]
> If you're able to inject other native programs then it should work with the miner as long as you don't have "Startup" enabled, since the miner won't be able to install itself (because it's injected in another process, it can't know where the original file is and thus can't install), so you'll have to handle the installation yourself just like how crypters do it.
OFC I'm doing the installation but not from the builder, I was wondering if the Miner executed on a device and another miner executed after it  what is gonna happen?
suggest me an Runpe worked with your miner before?

**Comment by UnamSanctam** [comment]
If you start the miner twice the the second one will just close. Any 64-bit RunPE should work, I have never seen any not work.

**Comment by UnamSanctam** [comment]
>Yeah even if they have different settings?
About the RunPe , i will give it another try ..thanks ^^

No if they have different settings then they can't find each other since they're hidden, in that case it will start two of them because they don't know that another miner is running. But you can technically set the minerIDs to be the same on every build instead of being randomized in which case they will always be able to find them.  Though if you overwrite the installed miner with a new miner then on the next restart only the new miner will start because the other one will have been overwritten.

**Comment by Torpedo0x** [comment]
Finally it works, and i encrypted it , thanks

**Comment by UnamSanctam** [comment]
Alright great.
