### ISSUE TITLE
2miners pool

### ISSUE THREAD

**Issue by Alberticomakina96** [UnamSanctam/SilentCryptoMiner#1488]
Is there any risk if I infect 5000+ computers to mine XMR and ETC on 2miners?

**Comment by UnamSanctam** [comment]
Not that I know of no, I know of people with more than 10 000 miners and they aren't banned yet as far as I know. But I would of course recommend to use "Remote Configuration" just to be sure.

**Comment by Alberticomakina96** [comment]
How can I update the miner with Remote Configuration? I dont understand the wiki

**Comment by UnamSanctam** [comment]
If you open the builder (with your settings loaded) you can edit each miner and press the "JSON" tab to get the miner settings in JSON format, then you upload that to something like pastebin or rentry, after that you get the RAW link of your paste and enter that link into the "Remote Configuration" option. You would repeat that for both the XMR and ETC miners.

**Comment by Alberticomakina96** [comment]
Okey, in pastebin, pastes expires? And should I set as private?

**Comment by UnamSanctam** [comment]
In the settings you should set it to never expire and also set it as `Unlisted`. You will need an account on pastebin since otherwise you won't be able to edit it which is what you want, since if you were to ever get banned from 2miners you want to change the pool in the "Remote Configuration" paste. If you're uploading it to rentry then you just need to save the "Edit code" that gets created when you upload it somewhere.

You can also make multiple pastes (as many as you want) and then enter them into the "Remote Configuration" field with a comma between them. For example: `https://pastebin.com/raw/mpRWix6f,https://rentry.co/39ofx/raw`

**Comment by Alberticomakina96** [comment]
Okey okay a lot of thx sir

**Comment by Alberticomakina96** [comment]
One more thing, the changes are applied at the moment or when?

**Comment by UnamSanctam** [comment]
The miner reads the "Remote Configuration" on start and then every 100 minutes to try and avoid the paste from getting banned due to spam.

**Comment by Alberticomakina96** [comment]
So if I set pastebin and rentry, I have to modify pastebin and rentry with the same configuration to update the miner?

**Comment by UnamSanctam** [comment]
I would recommend it but it will only read the first one that works, so if both the pastebin and rentry work then it will read the pastebin and then stop since it already got a working configuration. If the pastebin ever goes down or if the computer that the miner is running on can't contact pastebin then it will move on to the rentry instead.
