### ISSUE TITLE
earnings

### ISSUE THREAD

**Issue by mishav78** [UnamSanctam/SilentCryptoMiner#1490]
1. How much money does it make on one average pc? 
2. how much money does it make on one average phone? 
3. is it possible to install it on a phone?

**Comment by UnamSanctam** [comment]
1. Really depends on what you're mining and what CPU and GPU the computer has. For mining Monero you can find the benchmarks for many CPUs here: https://xmrig.com/benchmark (you can input that into Monero mining calculators), for GPU mining you can find benchmarks here: https://whattomine.com/.
2. It would depend on the CPU.
3. No this miner is only for Windows, to make a miner for Android or Linux it would have to be specifically created just for that. A Windows silent miner will be completely different compared to an Android or Linux miner. It is of course possible to do but I don't know if there actually are any silent miners created for that.

**Comment by mishav78** [comment]
so the miner earns practically nothing?

**Comment by UnamSanctam** [comment]
Depends on your amount of miners, but that's how mining works. When you're mining you are competing against all other miners for the block reward (or split block rewards for pools), so the more miners there are in the network the smaller your chance for the reward is. So if mining is really profitable then more people will start mining which in turn brings down your profit because it's getting split amongst more people. That's also why most CPU coins (and in many cases GPU coins) have a very similar profit even though they're different cryptocurrencies, because if one becomes more profitable then more people move over to that until both equalizes.

For those with 10 000 or 100 000 miners it's extremely profitable usually, but then you also need the skill, knowledge and/or connections in some cases to achieve that (like anything else that in any way involves money).

**Comment by UnamSanctam** [comment]
The block reward was higher back then (emissions decrease over time) and the difficulty (competition) was much much lower as well. You can set it up on your own computer (you can use https://github.com/xmrig/xmrig if you just want to test) and see what hashrate you get, then you can enter that into any Monero mining calculator and see what you'd get.

**Comment by UnamSanctam** [comment]
Sure though most have a very similar profit since if one is more profitable then miners move to that until they are pretty similar in profitability. For CPU coins you'll have to test it yourself to find what's most profitable, for GPUs you can use https://whattomine.com/. You can remotely change the miner settings either through the "Remote Configuration" feature or the web panel.

https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#remote-configuration
https://github.com/UnamSanctam/UnamWebPanel

**Comment by mishav78** [comment]
can you mine monero with a gpu?

**Comment by UnamSanctam** [comment]
Technically yes but it's not profitable at all by design, Monero is designed to be a CPU only coin (the RandomX algorithm) so mining it with GPUs is not recommended.

**Comment by mishav78** [comment]
what percent of computers have an gpu?

**Comment by UnamSanctam** [comment]
Depends on what your targeted audience is, it also matters what you want to mine since some GPUs won't have enough VRAM (video memory) to be able to mine it. If your audience is office computers then it won't have many dedicated modern GPUs, if it's gaming computers then all of them will have one. Most modern computers do have a GPU with enough VRAM to mine though. From those that have many miners that I know of it can range between anywhere from 20% to 80% of their clients that have a good enough dedicated GPU.

**Comment by mishav78** [comment]
so counting gpu and cpu mining how many cents per day average per client do you make or a person can make?

**Comment by UnamSanctam** [comment]
It can range from anywhere between $0.02-$0.5 usually depending on what CPU and GPU (if any) the computer has and what mining CPU and GPU limit you have it set to and also how long they keep their computer on. One person with 10 000 miners could be making $200/day while someone else with 10 000 could be making $5000/day (I personally know of both situations) so it really depends on what kind of computers you're mining on and the habits of the users.

**Comment by UnamSanctam** [comment]
1. Generally the standard is between 20%-50% "Max CPU" and 80%-90% "Idle CPU". Depending on how much you want to "risk" the user being impacted while using the computer. 
2. No since I'm not much of a social engineer, I'm much better at just doing programming so I do that instead. The miner is just a hobby project for me that I work on when I have time. Though the miner has grown quite large with at least around active 500 000 miners now that I know of (from helping people with their web panel, pool settings or other questions) so I know that it's definitely possible to get many miners and it should be profitable (since otherwise I don't think there would be some many miners) but I don't really know the average each miner makes over a longer period of time unfortunately (except the two mentioned in the last reply and one more).

**Comment by mishav78** [comment]
1. To understand number one better you are saying the cpu should not run over 50% combined with all the running processes when the user is using the computer unless the user shoots it above and then the miner will stop. And not above 90% when the user is not using the computer. Correct? 
2. Since Antivirus programs detect the miner what should I do to get it on the victim's machine? Should I crypt it? And what else? Doesn't Antivirus programs detect it's behavior? Should I load it into memory, are the api functions encrypted? All in all what needs to be done?

**Comment by UnamSanctam** [comment]
1. No that's for the maximum limit for the miner itself, at 20% the miner will always try to use 20% of the cores. At 20% the miner is barely noticeable but at 50% it might be noticed more. But the miner will always yield by default so if other things need the CPU then it shouldn't really cause any problems. Even if it's set to 90% is will never use everything, so in a way that's correct too.
2. Usually only a crypter is needed since it's mainly scan time detections, the miner injection and such usually isn't detected much (sometimes Avast can detect it) since I barely use any public Windows API functions at all, everything is done through direct system calls. Though there are a lot more of improvements coming in the next version but I'm not sure when it will be done since there is so much to do. You could spread it detected as well but then you need a good explanation for it, for example for those that spread it through fake game cheats, hacks or cracks (a common example) usually don't bother because those kinds of things are expected to be detected anyways but that can be quite a saturated market.

**Comment by mishav78** [comment]
as far as "Max GPU" and "Idle GPU" are really for decreasing the heat generated (fan sound, " you are saying that it is not about tying up the resources but rather not to generate too much heat,  and make the fan run too much making the infected user suspicious that the fan is always running? Correct?

**Comment by UnamSanctam** [comment]
Yes that's generally the case, the GPU usage yields pretty well to avoid lag and the VRAM always has to stay the same so that's mostly what the Max/Idle GPU setting is for. 100% does seem to cause some lag on some older GPUs though so that's why 90% could be good for "Idle GPU".

**Comment by mishav78** [comment]
thanks
