### ISSUE TITLE
GPU Coins? ETHPOW?

### ISSUE THREAD

**Issue by arblad1990** [UnamSanctam/SilentCryptoMiner#1493]
Hey, currently I'm mining both XMR + ETC and I was wondering if there are any more profitable coins for GPU that are supported in the miner? 
I was looking into KAWPOW for ravencoin but I've read that this would replace the XMR miner rather than the ETC miner is that correct? I've tried replacing my ETC miners in the panel with RVN but doesn't seem like that works anyway.

Another thing I was wondering is, would it be possible to mine ETH POW? And is this worth it and more profitable than ETC?

**Comment by UnamSanctam** [comment]
Yes since KawPow requires NVRTC to run I haven't included in the ETC miner, because it's a separate 20MB DLL(s) that needs to be dropped on the disk. And since KawPow isn't very good for silent mining due to it's high core usage I personally don't think it's worth the tradeoff. The XMR miner does have that though (which is partly why the filesize gets so big if you enable XMR "GPU Mining") so RVN can only be mined using that.

Yes you can mine ETHW just fine and is about the exact same in terms of profitability, though it requires quite much more VRAM (since it's just a simple fork of ETH) so it can be mined on less GPUs than ETC. UQB is more profitable and requires very little VRAM but it can be difficult to sell anonymously since you need some blockchain knowledge.

**Comment by UnamSanctam** [comment]
I have directly added KawPow into the dedicated GPU miner now (the ETH/ETC/UBQ miner) so you can now mine that if that's in your interest.
