### ISSUE TITLE
a few question for a beginer (not very important so dont respond if you dont have time)

### ISSUE THREAD

**Issue by p0ubelle** [UnamSanctam/SilentCryptoMiner#1496]
Hey, 
I just want to know if you have good wallet to use for ETC or other crypto. I use MetaMask but if you have better option tell me thanks.
I also wanted to know what is Pool option. Can i use this to check how many computer have installed the miner. If it cant do you have simple solution to that? 

Thanks if someone respond, have a nice day

**Comment by raphael260** [comment]
and can i use etc.2miners.com to check miner maybe?

**Comment by UnamSanctam** [comment]
There are many different ones, but MetaMask works fine. For Monero there's the Monero GUI Wallet and then there are also other wallets such as Exodus, ZelCore and similar ones but they're usually not very good at privacy (neither is MetaMask obviously). The pool is the mining pool that your miners will mine to, you can technically use the pool to see how many miners that are mining but they will only appear when they find a share so it might not be too accurate. But if you want to use the pool to monitor the miners (rather than the web panel since it requires a webhost or server) then you can use `{COMPUTERNAME}` as the worker name so that each miner appears as its own worker. 2miners works perfectly fine for that.

**Comment by raphael260** [comment]
Thanks for your time it was clear, have a nice day/evening

**Comment by UnamSanctam** [comment]
You too, good luck with your mining.

**Comment by UnamSanctam** [comment]
You enter your ETC wallet address at the top of the page (the search bar) to get to your page and the workers will appear there.

**Comment by raphael260** [comment]
Oh ok thanks you have a nice day/evening :)
