### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Demon4u** [UnamSanctam/SilentCryptoMiner#1501]
Good day. When to wait for the new version?

**Comment by UnamSanctam** [comment]
Good question, right now I'm trying to make SysWhispers undetected since that's the only thing left that seems to cause a detection, everything else I've made undetected. I am also trying to implement some more algorithms but of course that take a huge amount of time so that might be for a future version instead. So the only thing left really is to make SysWhispers undetected.

**Comment by Demon4u** [comment]
Thank you for the answer, we are looking forward to the update.

**Comment by DogusCzk** [comment]
> Good question, right now I'm trying to make SysWhispers undetected since that's the only thing left that seems to cause a detection, everything else I've made undetected. I am also trying to implement some more algorithms but of course that take a huge amount of time so that might be for a future version instead. So the only thing left really is to make SysWhispers undetected.

will you also update the unamdownloader ?

**Comment by UnamSanctam** [comment]
>will you also update the unamdownloader ?

Yes but the new one also uses SysWhispers so I'll finish it after the miner.

**Comment by UnamSanctam** [comment]
Also posting it here, the new update has been released now.
