### ISSUE TITLE
!!! Fast update !!!

### ISSUE THREAD

**Issue by alix1011** [UnamSanctam/SilentCryptoMiner#1504]
Hi unam, I think it's time to do the new update (2023)and add algorithms, especially new currencies like KAS (KHeavyHash).

**Comment by UnamSanctam** [comment]
I can release the update but SysWhispers (what's used to avoid having to call Windows APIs directly) is detected at the moment so the miner would be detected, though that's the only thing left probably. If you want me to add a new algorithm then that's going to take a month or two probably.

**Comment by alix1011** [comment]
Well, until you give the main update, publish a sub-update to update the algorithms.

**Comment by UnamSanctam** [comment]
Don't you mean the opposite since finishing the main update will be much faster compared to adding new algorithms? If you want to some of the work yourself to speed it up then you can attempt coding a new algorithm into https://github.com/ethereum-mining/ethminer and send it here.

**Comment by DogusCzk** [comment]
Hey, what's the status of the update, when will it be released, sorry for asking over and over again, I've been waiting for a rebuild for a long time hahahha
@UnamSanctam

**Comment by UnamSanctam** [comment]
I have been testing builds all day for a few days now (after work was over) to make sure that every single combination of options work as they should, and I also just finished the signature cloning feature as well which was one requested feature. And I also finished a few other things such as making the rootkit work directly with the miner (instead of using the rootkit installer) so that the new AMSI detections (which were making the rootkit unable to run) won't ever happen and it also makes the rootkit more reliable. I also just finished the changes to the uninstaller so that the "Disable Windows Update" option effects can now be reverted when running the uninstaller. I am planning to finish the miner for release either today or tomorrow, this is the current changelog for all the changes:

- Changed miner settings from being passed through the command line to instead be passed directly through the PEB
- Changed XMR miner to clear RAM during "Stealth" when possible
- Changed PEB calls to be more obfuscated due to new detections
- Changed miner to read the current executable path for installation directly from the PEB instead of a Windows API call
- Changed miner and watchdog to read the environmental variables directly from the PEB
- Included rootkit directly inside the miner instead of using the rootkit installer to avoid the new AMSI detections and for more flexibility
- Changed rootkit to now run outside of the "Startup" installation flow to allow for it to run when "Startup" is disabled
- Moved "Install Rootkit" out from "Advanced Options" and renamed it to "Use Rootkit (Hide Miner)" since the rootkit should now be stable
- Updated compiler command options to reduce detections
- Added system call registry access functions to allow registry manipulation without using the Windows API or CMD
- Changed GPU checking to directly read the registry instead of using a WMI command with a file buffer
- Added signature cloning option to clone the digital certificate of another program into the miner
- Moved administrator checks from powershell directly into the C++ code
- Added Task Scheduler "Startup" entry checking into the Watchdog
- Merged obfuscate.h library and obfuscatew.h library into a custom-made unified version called obfuscateu.h
- Added a custom-made SysWhispersU direct system call generator and removed the previous SysWhispers2
- Modified SysWhispersU and obfuscateu.h to use different encryptions in order to avoid XOR detections
- Added simple obfuscation to well-known SysWhispers constants and offsets to avoid static detections
- Fixed SysWhispers Python compatibility on some Windows 7 versions
- Readded explorer.exe as injection option
- Made explorer.exe the default injection option again
- Updated uninstaller to instead find the watchdog and miner processes by enumerating system mutex handles to find the owner process
- Added "Disable Windows Update" rollback into the uninstaller to allow the uninstaller to fix Windows Update during uninstallation
- Updated checker to instead check if the mutex is active to ascertain whether the miner and watchdog is running or not
- Merged many C++ files together to be able to store them unzipped in the project in order to make all code changes directly visible in commits
- Optimized and shortened many functions such as the previously verbose process creation function
- Increased delete pending injection temporary file name length to further decrease collision chance
- Fixed possible parent spoofing failure if required buffer size changes between system calls
- Change installation to call reg.exe and schtasks.exe directly when possible instead of through cmd.exe
- Updated both miners
- Added Portuguese (Brazil) translation (MatheusOliveira-dev)

**Comment by UnamSanctam** [comment]
The new update has now been released on the releases page https://github.com/UnamSanctam/SilentCryptoMiner/releases. And it has a very large amount of changes so please report any bugs if you find any. I've tried to eliminate every bug that I've been able to find but since all computers can be very different then it's possible that all bugs might not be able to happen on my computer/VM.

**Comment by DogusCzk** [comment]
tysm
