### ISSUE TITLE
Xmrig

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1509]
Good evening Unam. In the new version of the miner Xmrig Not compressed with UPX?

**Comment by UnamSanctam** [comment]
No I chose not to since a lot of people wanted the original last time, I was planning on adding an option for it (where it compresses it during compilation) but chose not to since it sometimes didn't always work (since it hard to write and read the miners to the disk during compilation). If anyone does want it UPX compressed then they can do that on the xmrig or ethminer and then compiled the builder and that will work without issues.

**Comment by masterjek** [comment]
Thanks for the answer. I just need an uncompressed one. Just clarified for myself. Since compression adds virus detections.

**Comment by UnamSanctam** [comment]
Alright great, yeah that was also one reason I didn't do that even though it would save space. Good luck with your mining.
