### ISSUE TITLE
nice update Signature

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#1510]
what i can use signature correctly and what this for ? can get more info about this one ?

**Comment by UnamSanctam** [comment]
The feature allows you to clone the digital certificate of another program, for example you could clone the Google Chrome certificate and use that. The certificate will be invalid of course because it's not on the original file but some programs and antiviruses still gives the file more legitimacy due to the signature (digital certificate). If you open the properties of a file with a signature then there should be a tab called something like "Digital Signatures" where you can see it. For example, here is the Lite example settings with a Google signature cloned into it: [ExampleSettings_Lite_Sig.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/11130911/ExampleSettings_Lite_Sig.zip), if you build a miner with that then it will have that signature.

**Comment by tarekxxx** [comment]
> The feature allows you to clone the digital certificate of another program, for example you could clone the Google Chrome certificate and use that. The certificate will be invalid of course because it's not on the original file but some programs and antiviruses still gives the file more legitimacy due to the signature (digital certificate). If you open the properties of a file with a signature then there should be a tab called something like "Digital Signatures" where you can see it. For example, here is the Lite example settings with a Google signature cloned into it: [ExampleSettings_Lite_Sig.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/11130911/ExampleSettings_Lite_Sig.zip), if you build a miner with that then it will have that signature.

WOW BRO this Madness <3 love your work bro
