### ISSUE TITLE
I think my miner is not working

### ISSUE THREAD

**Issue by DogusCzk** [UnamSanctam/SilentCryptoMiner#1518]
2 days after the update i didn't see anyone mining on my panel but i saw them open also i am sharing a screenshot of an error someone just got after restarting their computer. Updater.exe is my miner's startup name
![image](https://user-images.githubusercontent.com/123574822/229612170-3bfbef44-b27e-4aa7-b1f5-c6fef42c0682.png)
and here it says The code execution cannot proceed because ffmpeg.dll was not found. Reinstalling the program may fix this problem

**Comment by DogusCzk** [comment]
maybe this is a user-generated error, i saw it working myself. Maybe this is a user-generated error, i saw it working myself. but no one came to the webpanel although I am sure that 5 6 people opened it

**Comment by UnamSanctam** [comment]
Are you binding it together with anything or using some kind of crypter? Since the miner doesn't use ffmpeg.dll (obviously). And if you're only mining ETC and nothing else then you can try the hotfixed current version https://github.com/UnamSanctam/SilentCryptoMiner/releases.

>maybe this is a user-generated error, i saw it working myself. Maybe this is a user-generated error, i saw it working myself. but no one came to the webpanel although I am sure that 5 6 people opened it

Yes I would assume so.
