### ISSUE TITLE
problem compiling

### ISSUE THREAD

**Issue by vavilovalila** [UnamSanctam/SilentCryptoMiner#1523]
![image](https://user-images.githubusercontent.com/102316713/230224067-41ec81fc-f0d9-4992-9f31-e3b46046bf03.png)

I use settings from 3.1.0. In this version they do not work, in the previous problem there is no.

**Comment by UnamSanctam** [comment]
Add an antivirus exclusion to the builder folder if you haven't already and also try starting the builder as administrator.

**Comment by vavilovalila** [comment]
> Add an antivirus exclusion to the build folder if you haven't already and also try starting the builder as administrator.

Defender off. Run as administrator. Not work.

**Comment by UnamSanctam** [comment]
Make sure that the operating system is 64-bit. Do you have another computer or Virtual Machine you can build it on? You're getting that error either because something can't run, something can't write or there's a problem with your drive/Windows.

**Comment by vavilovalila** [comment]
Rebooted the system, it helped. There is another question. In the previous version, the build weighed 4 mb. In this build with the same settings - 10 mb. Why?(

**Comment by UnamSanctam** [comment]
>Rebooted the system, it helped. There is another question. In the previous version, the build weighed 4 mb. In this build with the same settings - 10 mb. Why?(

Because xmrig and ethminer aren't UPX compressed in this version, UPX compression has both its pros and cons, and I didn't decide to use UPX compression in this version in order to lower the runtime detections in some antiviruses that almost always automatically mark UPX compression as malicious. If you want to compress them then you can download the project and then UPX compress xmrig and ethminer inside the Resources folder and then compile the builder.
