### ISSUE TITLE
Telegram message

### ISSUE THREAD

**Issue by IkSandr** [UnamSanctam/SilentCryptoMiner#1524]
Are you planning to add a function for messages in Telegram? Create control via telegram bot. Or so that such data as: ip, cpu, gpu, country after starting the miner come to a private channel. If not, can you suggest how to implement it?

**Comment by UnamSanctam** [comment]
Personally I'm not planning for that, but if you want to do that then you'll firstly need to get the CPU and GPU names, you could do that using a similar function to how I check the GPU (to see whether it's Nvidia or AMD). Then after that to get the IP and Country you will have to find some website to do that (because the computer has no idea about its own IP and Country), so you will have to contact that website (probably using a Powershell command since you do not want to include a http(s) library) and then after it returns the IP and country you would have to save that down probably into a file (you would do the saving part inside the powershell command, you could avoid files by using pipes instead but that's quite compilcated). Then you would read that file to get the IP and Country, after that you would need to construct a string containing all the data you want, such as CPU, GPU, IP and Country and then you would need to send that to a Telegram webhook, probably again using Powershell to contact it. So that would probably be how you'd implement it, though doing so requires quite extensive C++ and Windows knowledge and experience.

**Comment by FU3X** [comment]
instead send a pgp encrypted message to a room on xmpp. telegram sucks
