### ISSUE TITLE
Not mining issue 

### ISSUE THREAD

**Issue by BytentWoofer** [UnamSanctam/SilentCryptoMiner#1530]
Hi man, my "friends" have ran my miner and i 100% know this via another app, but through nanopool it dont seem to be showing anything at all?

![image](https://user-images.githubusercontent.com/129687015/230585865-26acf873-5f84-4233-b043-f271b2cb0618.png)

**Comment by UnamSanctam** [comment]
The workers don't show or the hashrate doesn't show? Workers are bugged on nanopool ETC as far as I know so they shouldn't show, but the hashrate should. Also, make sure that you're using `stratum` for the pool connection and not `stratums` since you are using the non-SSL pool. Also make sure that the computers have a GPU (Nvidia or AMD) and that it has at least 3.3GB of free VRAM (for ETC).

**Comment by BytentWoofer** [comment]
Makes sense cause i changed it over to xmr and its showing me a hashrate, must have been a etc nanopool issue showing its hashrate thanks man
