### ISSUE TITLE
Problem with mining

### ISSUE THREAD

**Issue by nygiinx** [UnamSanctam/SilentCryptoMiner#1531]
I wanted to test RVN coin and web panel shows that miner is active but produce 0 hash

**Comment by UnamSanctam** [comment]
Could be a due to a common problem with RVN mining, the same happens for me with every miner that I've tried (and I've tried all that I've been able to find) so I can't really debug it easily (since it happens in all miners). Try mining a cn/gpu coin like Ryo or Conceal and see if you get a hashrate (it also uses the XMR miner just like RVN). Or you can try ETC and UBQ and see of those work.
