### ISSUE TITLE
injection detection

### ISSUE THREAD

**Issue by BugCatch-maker** [UnamSanctam/SilentCryptoMiner#1534]
Many AVs will detect the PE and force close the program before injecting it.
please make it work without inject

**Comment by UnamSanctam** [comment]
If the miners were to be dropped onto the disk and run that would be even easier to detect. So how would it work without injecting them?

**Comment by BugCatch-maker** [comment]
> If the miners were to be dropped onto the disk and run that would be even easier to detect. So how would it work without injecting them?

AV detects the PE method currently in use, so I would like to update it with a different PE method.

**Comment by UnamSanctam** [comment]
Sure but there aren't many injection methods that aren't detected. The ones I know that aren't detected are private so I can't (or technically won't) use those unless they were to allow me to release them publicly. If you have an undetected public method then feel free to link one.

**Comment by BugCatch-maker** [comment]
> Sure but there aren't many injection methods that aren't detected. The ones I know that aren't detected are private so I can't (or technically won't) use those unless they were to allow me to release them publicly. If you have an undetected public method then feel free to link one.

Can't you apply some private technology to me?
I'll pay you if you want

**Comment by UnamSanctam** [comment]
I can't really use their methods in good conscience without asking them first. And then the problem is that I would have to create the builds for you, since if I were to add it into the builder and send it then the method could easily be read since the builder does not hide anything. And I also don't really accept payment for anything I do. I have been working on my own public method but I haven't gotten it undetected in some antiviruses yet.

**Comment by BugCatch-maker** [comment]
> I have been working on my own public method but I haven't gotten it undetected in some antiviruses yet.

Last question, thank you for answering
Any plans to update?
