### ISSUE TITLE
nothing show in 2miners

### ISSUE THREAD

**Issue by p0ubelle** [UnamSanctam/SilentCryptoMiner#1535]
Hey, 
So i build the .exe to test it and everything work fine. The miner appear in the checker but no in 2miners.
The pool in the lite example is etc.2miners.com:11010 but on the website its etc.2miners.com:1010.
i tested them both but in the 2 case it dont show up my miners in the website

**Comment by UnamSanctam** [comment]
Port 11010 is for SSL and port 1010 is for normal stratum (non-SSL). Make sure that your GPU has enough free VRAM to mine ETC (3.3GB at the moment), you can check if it's using GPU with something like MSI Afterburner. And then also make sure to mine until you find at least one share since otherwise the pool won't show anything https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining.

**Comment by raphael260** [comment]
Thanks you very much I should have read better. Have a nice day

**Comment by UnamSanctam** [comment]
SSL (port 11010 with `stratums (SSL)` selected in the miner) is generally better since it uses an encrypted connection.

**Comment by raphael260** [comment]
thanks!
