### ISSUE TITLE
Can we use any .json file for options.

### ISSUE THREAD

**Issue by PH03N1X1000** [UnamSanctam/SilentCryptoMiner#1553]
Can we use any .json file for the miner the same json file we use for xmrig binary as some of the commands of priority and yield as well as donation seems viable to me and i get huge help from modifying some features in the json file.
Can i use a json file for the same with the miner created by your software tbh not very imp but it seems usefull to me.
Thanks.

**Comment by PH03N1X1000** [comment]
As well as what is the donation level set to in the xmrig used by the silent miner. (By default with xmrig binary its 1%)
Do you take any of donation through mining done by us (thats not an issue though its very nice to have this software for free) 
Thanks

**Comment by UnamSanctam** [comment]
>Can we use any .json file for the miner the same json file we use for xmrig binary as some of the commands of priority and yield as well as donation seems viable to me and i get huge help from modifying some features in the json file.
Can i use a json file for the same with the miner created by your software tbh not very imp but it seems usefull to me.
Thanks.

Technically yes, though you can directly input the command line options (https://xmrig.com/docs/miner/command-line-options) into the "Advanced Parameters" field instead of using the JSON.

>As well as what is the donation level set to in the xmrig used by the silent miner. (By default with xmrig binary its 1%)
Do you take any of donation through mining done by us (thats not an issue though its very nice to have this software for free)
Thanks

Way back the donation level used to be 1% like the normal xmrig (this was a long time ago during SilentXMRMiner era, so before SilentCryptoMiner was released) but my domain that was used for the proxy and a few other things was taken down, and since then the donation level should be at 0% by default. You can also set the donation percentage manually through the "Advanced Parameters" option by adding `--donate-level=N`

**Comment by PH03N1X1000** [comment]
Can i use command line options from the web server as i cannot modify each of the miner again? Should i use add configuration option (during creation of the miner i enabled advanced paramenters and kept it empty)

**Comment by UnamSanctam** [comment]
Not from the web panel or "Remote Configuration" since the options get set during the start of the miner, I can technically try and implement a custom solution for changing them but it's quite a complex thing and there hasn't been much justification yet for allocating the required time to implement (and test) it.

**Comment by PH03N1X1000** [comment]
ok no problem thanks
