### ISSUE TITLE
Watchdog without startup

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1555]
It's really annoying that the watchdog requires startup, but I know its cause u cant read and write the file back after. But what about when the miner opens, it reads itself, then passes it to the watchdogs commandline (or peb like the miner does now with the mining commandline) and then when miner gets closed it injects it instead of dropping somewhere?

**Comment by UnamSanctam** [comment]
It's theoretically possible but what would be the point with that? Since that wouldn't work with crypters if that's what you're going to use it for.

**Comment by betabuilds01** [comment]
> It's theoretically possible but what would be the point with that? Since that wouldn't work with crypters if that's what you're going to use it for.

![10323655](https://user-images.githubusercontent.com/129922370/233751434-a9b830f8-c88e-43e1-a579-d7d631c5960a.png)

I'll be the first to test  a  few builds that uses that same technique as I use a reflective dll method that doesn't drop the miner to disk. I'm anticipating a pre-release that has the watchdog enabled without the startup. Interesting to see how that would work.

**Comment by UnamSanctam** [comment]
>I'll be the first to test a few builds that uses that same technique as I use a reflective dll method that doesn't drop the miner to disk. I'm anticipating a pre-release that has the watchdog enabled without the startup. Interesting to see how that would work.

Well the proposed Watchdog solution wouldn't really work then in your situation if you don't drop it to disk, since in this theoretical situation the watchdog would need the miner exe to be able to start it if the injected miners aren't running (the Watchdog without Startup would basically only check for that since it's not installed).

Because here is how the Watchdog would work without Startup:

- Miner (injector) starts
- Miner (injector) injects Watchdog with a command line path to the current miner (injector) location
- Watchdog gets the current miner (injector) location from the command line and reads the file into memory
- When the Watchdog detects that the injected miners (the actual miners doing the mining) aren't running it either injects the miner file it read into some program or drops it to disk and starts it

So if the miner is never present on the disk for you then the Watchdog will never be able to read the file into its memory. I can't really think of any other ways to do it, any other solution seems to involve some kind of "chicken or egg" problem.

**Comment by shainodev** [comment]
> It's theoretically possible but what would be the point with that? Since that wouldn't work with crypters if that's what you're going to use it for.

The point is for people who use another thing to drop it like a downloader that already has startup or a botnet, without startup will be less noisy or less detected.

**Comment by shainodev** [comment]
> Well the proposed Watchdog solution wouldn't really work then in your situation if you don't drop it to disk, since in this theoretical situation the watchdog would need the miner exe to be able to start it if the injected miners aren't running (the Watchdog without Startup would basically only check for that since it's not installed).
> 
> Because here is how the Watchdog would work without Startup:
> 
> * Miner (injector) starts
> * Miner (injector) injects Watchdog with a command line path to the current miner (injector) location
> * Watchdog gets the current miner (injector) location from the command line and reads the file into memory
> * When the Watchdog detects that the injected miners (the actual miners doing the mining) aren't running it either injects the miner file it read into some program or drops it to disk and starts it
> 
> So if the miner is never present on the disk for you then the Watchdog will never be able to read the file into its memory. I can't really think of any other ways to do it, any other solution seems to involve some kind of "chicken or egg" problem.

Then you could make the watchdog and miner both have the resource "ethminer" and "xmrig" miner. And you will pass the ethminer commandline and xmrig commandline to the watchdog instead and make the watchdog inject the miners directly

**Comment by UnamSanctam** [comment]
>Then you could make the watchdog and miner both have the resource "ethminer" and "xmrig" miner. And you will pass the ethminer commandline and xmrig commandline to the watchdog instead and make the watchdog inject the miners directly

There's a few problems with that, biggest one of course would be that it would double the filesize of the miner since both the miner and watchdog would need to contain the miners. Another problem would be that the entire miner would basically have to be maintained inside the watchdog as well (with some parts in a common file), and only for those who aren't going to use it without Startup. Another small problem would be that since we wouldn't be injecting the original miner injector then it won't run all the code for the options inside the miner if the person needs that. So while it is possible, majorily the first issue of the doubled filesize make that a really undesirable solution.

**Comment by betabuilds01** [comment]
> > Then you could make the watchdog and miner both have the resource "ethminer" and "xmrig" miner. And you will pass the ethminer commandline and xmrig commandline to the watchdog instead and make the watchdog inject the miners directly
> 
> There's a few problems with that, biggest one of course would be that it would double the filesize of the miner since both the miner and watchdog would need to contain the miners. Another problem would be that the entire miner would basically have to be maintained inside the watchdog as well (with some parts in a common file), and only for those who aren't going to use it without Startup. Another small problem would be that since we wouldn't be injecting the original miner injector then it won't run all the code for the options inside the miner if the person needs that. So while it is possible, majorily the first issue of the doubled filesize make that a really undesirable solution.

That's a really undesirable solution for sure but the only thing that's protecting the miner process from being killed is the BSOD option since it was implemented in v2.6.0 of the unified miner. The watchdog was always a problem for me since my crypts are handmade and enabling the watchdog in the miner triggers werfault which crashes the watchdog process (probably the watchdog couldn't locate my file on disk) which is why the watchdog without startup is considerably effective in my situation. Some issues and other unprecedented problems may arise due to this but being challenged in life is inevitable but being defeated is optional.
