### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1557]
Good evening Unam. Some workers in the control panel show an error, but at the same time they show the speed of mining. I'm attaching a screenshot.
![1](https://user-images.githubusercontent.com/36513967/234086968-2bad4cb7-3101-44ba-b8d9-b14cada07069.jpg)

**Comment by UnamSanctam** [comment]
Maybe it got disconnected from the pool? Though I think the hashrate should go down then, though it's hard to test all situations (since only way to test it is really to try and simulate it). How long do they show "Error"? If it's only occasionally then the pool could be disconnecting them sometimes, which could also explain the hashrate. NiceHash is well-known for being quite bad so it's hard to tell.

**Comment by masterjek** [comment]
How long do they show "Error"? - 22 Minutes
Then I'll try to just switch to another pool and see how it connects.
