### ISSUE TITLE
Ucompiler and other

### ISSUE THREAD

**Issue by mastroaliberti3333** [UnamSanctam/SilentCryptoMiner#1558]
hello first of all I wanted to thank you for the continuous updating of the miner and the time you dedicate to answering the questions, I wanted to ask you a series of things
 1) when I build the exe file with the builder, the ucompiler folder is also created, does the folder also have to be sent to the miner computer?
2) to make it undetectable and spread it could I use a dropper and maybe associate a vbs file with the exe?
3) I'm considering buying some way to make AV invisible and spread it if I write you on discord, telegram or wickr could you give me some contacts or maybe provide them to me yourself.
i know some code obfuscation technique but i wouldn't know how to apply it to your program.
thanks in advance.

**Comment by UnamSanctam** [comment]
Sorry, looks like my response never got posted.

1. No the UCompilers folder is only there for the compilation and isn't necessary to run the miner, it doesn't get automatically removed since writing the files on each build would be unnecessary.
2. If you make the dropper add Windows Defender exclusions before dropping the files then that would make it undetected by Windows Defender.
3. Unfortunately I've been banned from the platforms I had, the only contact method I have left is email (unams@protonmail.com) though sometimes I can miss it (accidentally mark it as read) since I receive a ton of emails every day.
