### ISSUE TITLE
2miners

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1563]
Good afternoon Unam. I switched xmrig proxy to pool 2miners. I am attaching a screenshot of the work below, tell me it's normal that there are a lot of rejected decisions.
![1](https://user-images.githubusercontent.com/36513967/234595930-fba25f5b-3cff-457a-961f-9bca764f7e0c.jpg)

**Comment by UnamSanctam** [comment]
That's usually just stale shares, usually happens if either you submit a share after a block has already been found (if either the miner that's connected to your xmrig-proxy has a high ping or if the xmrig-proxy has a high ping to the pool, or potentially if you CPU is maxing out sometimes) or if the pool is being slow. In this case it might be a high (enough) ping causing the stale shares.

**Comment by masterjek** [comment]
Thanks for the explanation.
