### ISSUE TITLE
Code Remote Configuration

### ISSUE THREAD

**Issue by anbu-squad** [UnamSanctam/SilentCryptoMiner#1568]
Unam Hello

Help please find a code section
responsible for reading remote configuration (pastebin)

**Comment by GitHubUser5672** [comment]
You need a site which will display the text in raw format. Github does that, and you can get the configuration by copying the JSON when creating a miner

**Comment by UnamSanctam** [comment]
The "Remote Configuration" reading is done inside the miners themselves (xmrig and ethminer), though my versions aren't open source yet since I don't have the time to maintain them (I haven't even gotten the time to update the UnamDownloader and UnamBinder yet). Though I can post the code where I do the "Remote Configuration" retrieval when I have time if you want that.

**Comment by anbu-squad** [comment]
It would be very useful for me to see the code on the example

I wrote with the help of a chatGPT Loader, reading the contents of pastebin, however, I periodically have an error 403
