### ISSUE TITLE
i fucked up...

### ISSUE THREAD

**Issue by karolszkotak** [UnamSanctam/SilentCryptoMiner#1577]
i hard resettet my phone (with xmr wallet) now i have new addy, can i change addy for mining from web panel in anyway?

**Comment by UnamSanctam** [comment]
Yes you can change the configuration for any miners in the web panel using the "Configurations" tab, if you create a miner in the builder then you can get the settings pre-made as JSON inside the "JSON" tab, or you can write it manually https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration.

You should also make sure to save down the seed whenever you create a wallet so that you can restore it if lost.
