### ISSUE TITLE
Help with webpanel and remote control :v

### ISSUE THREAD

**Issue by pepe123456789-cmyk** [UnamSanctam/SilentCryptoMiner#1587]
Hi unam first of all thank you for not charging for something that's easily a $300+ tool; thank you :)
I love the latest version and I especially love the amount of persistence this thing has lol; but I have a problem, I want to use the web panel and the remote control feature so I could remotely control and monitor my bots after they been ran on loader. Only problem is that I have a condition called noobness that's why I went with pureminer since it was much easier on my little brain but your miner has WAY better persistence and it's free so I want to learn how to set up both Remote control and Web panel; I noted there wasn't any guide on how to actually set these up, there's a WIKI on the miner itself but no guide on how to setup web panel and remote control so would you mind explaining it to me step by step, Do I need any kind of DNS, cpanel, or anything like that? Could you explain it as if I was 5 years old if you don't mind; I would really appreciate it mr unam :) 

Thank you in advance:)

**Comment by pepe123456789-cmyk** [comment]
What would I put on the Remote control tab, my DNS?
What would I put on the web panel thing?
I actually have no clue pls help, thanks :)

**Comment by UnamSanctam** [comment]
You can find a wiki entry on the "Remote Configuration" feature on these pages which goes more in-depth in terms of the actual format of it:
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#remote-configuration

Basically, you just need to upload the JSON text (either write it manually by looking at the wiki or the miner has a "JSON" tab in it when you're creating one which writes one automatically) to any site that allows you to upload text. The most common sites being pastebin and rentry, after you upload the JSON text to pastebin, rentry or anywhere else that allows it you should copy the RAW link of your paste (the RAW link can be found on the pages, the RAW link contains only the JSON and nothing else which is why you need to enter that into the miner) and then paste that into the "Remote Configuration". The miner will contact the URL you enter when starting and then also every 100 minutes after that, if it finds a valid JSON text then it will retrieve that and apply any of the settings found. Meaning that as long as you can edit your paste you can also edit the miner settings post-build in case you ever need or want to change anything. You can also add multiple different paste URLs into the "Remote Configuration" field (separate them with a comma) in case any of them stop working or is taken down, the miner will use the first one of them that works, so when one stops working it will try the next one of your added URLs until it finds one that works.

For the web panel it's a bit more complicated since you need to host it somewhere. You can either host it on any webhost online or you can host it on a VPS or any computer by installing a webserver (don't host it on your own IP though). As long as they support PHP and SQLite (built into PHP) it should work, you just have to make sure that they won't take it down. Many webhosts don't like hosting those sort of things which is why many can take it down after some time, and that is also why for many using a VPS (or any kind of computer they can have access to that has port forwarding) is more popular. You can find the web panel here: https://github.com/UnamSanctam/UnamWebPanel. To set up the web panel you just need to download the files from the GitHub "Releases" and upload them to a webhost or copy them into a webserver and then change the password inside `config.php`. After that it should be working, if not then also make sure that the webserver is using PHP 8 and that the database is readable (permissions on the `db` folder and `unamwebpanel.db` should be set to writable). Then you can paste the URL of the endpoint of your site (either using a domain or just an IP) into the "API Endpoint URL" (also supports multiple by separating them with comma like the "Remote Configuration" does) and the miner will contact the site on first start and also every 1 minute after that. On the web panel you will be able to monitor the status of your miners and also change their configurations like how the "Remote Configuration" does it.

If you use both the "Remote Configuration" and web panel then you will have the most control over your miners.

**Comment by calworld** [comment]
que dice el perro pepe
