### ISSUE TITLE
etc miner is offline

### ISSUE THREAD

**Issue by Fructose3481** [UnamSanctam/SilentCryptoMiner#1588]
![firefox_uuXPHJ6lme](https://user-images.githubusercontent.com/132773671/236685629-63acf3a6-976e-461e-bc7b-e93fe054a841.png)

**Comment by UnamSanctam** [comment]
Most likely the GPU is disabled or the drivers might have something wrong. Since it's offline then that usually means that there's something wrong with the GPU, if there wasn't any problem then the watchdog would just start the ETC miner again, so because it hasn't that would be the most likely explanation. If you check the XMR miner then does it report any GPU and also how long is the runtime?
