### ISSUE TITLE
Virus scan

### ISSUE THREAD

**Issue by emuChitE** [UnamSanctam/SilentCryptoMiner#16]
Hi, where would you advise to check the miner? Many people do not advise to use virustotal , although it shows the most correct data, for example antiscan.me and kleenscan Kaspersky does not detect the virus but in reality Kaspersky sees a trojan in the miner

**Comment by UnamSanctam** [comment]
There aren't really any I can recommend that works well, only real "perfect" solution is to have your own VMs that check the files. Usually the reason that antiscan and kleenscan do not show all the detections is because they have "Cloud Detections" disabled because if that is enabled then it will be shared with Microsoft or whatever company runs each specific antivirus. You can never get around that since "Cloud Detections" are done directly on their servers, so to see if "Cloud Detections" detect any program you have to send the file to the antivirus company.

**Comment by emuChitE** [comment]
It still bothers me that from the new version the miner began to detect the Kaspersky anti-virus, namely the Trojan "VHO:Trojan.Win32.Inject.gen". As I understand it is a virus embedded in system files. Is there any way to hide this trojan?

**Comment by UnamSanctam** [comment]
It has been detecting that for maybe a month now, which is normal since that's exactly what it does. If you recode the shellcode loader using some other injection method like maybe transacted hollowing (though that only works on Windows Visa and above) then that might disappear, or you can buy a crypter.

**Comment by emuChitE** [comment]
Do you mean to crypt the compiled miner?

**Comment by UnamSanctam** [comment]
Yes, any that supports 64-bit files should work. If the crypter uses injection to avoid detection then you might need to use that crypters "Startup" settings instead of the miners "Startup" settings, most crypters with injection has that since they usually break the crypted programs own "Startup" because the crypted program can't read where it is (to know if it should install or not) because it's injected and wasn't ran from its original executable.

**Comment by emuChitE** [comment]
Do you recommend limecrypter from NYAN-x-CAT for crypto payload files(Watchdog and uncompiled miner)?

**Comment by UnamSanctam** [comment]
No the last update for that was 2 years ago, a crypter stub usually lasts for one week to one month. So after one week to one month you usually need to get an updated crypter and recrypt your program.

**Comment by emuChitE** [comment]
Have you heard of "alien crypter" and is it suitable for a miner?

**Comment by UnamSanctam** [comment]
Haven't heard of it and I don't know if it's suitable. You would have to see if it supports 64-bit programs.
