### ISSUE TITLE
NiceHash And XmrigProxy

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#160]
Good evening. Please tell me I'm trying to set up mining through XmrigProxy. I manage to run your miner on another machine and he drops the balls on the main machine, but when sending them to Nicehash here's a mistake - "Invalid nonce; is miner not compatible with NiceHash?" It turns out that this quiet miner will not be able to work with - XmrigProxy?

**Comment by UnamSanctam** [comment]
Did you enable "Nicehash Mining"?

**Comment by masterjek** [comment]
Yes

**Comment by UnamSanctam** [comment]
Oh right, are you connecting with the proxy to NiceHash? In that case don't forget to enable NiceHash in the proxy as well. It's also possible that you might not be able to connect to NiceHash with xmrig-proxy since technically you are double-splitting the jobs. First NiceHash splits up the jobs and sends them to the proxy (that's how NiceHash works), then the proxy splits up the jobs to the miners so it's possible that xmrig-proxy might not work with NiceHash though I'm not sure.

**Comment by masterjek** [comment]
Yes I am trying to connect NiceHash through XmrigProxy. This is necessary so that all decisions come from one ip. And the pool didn't see botnets. Sorry to bother you. I found information that XmrigProxy Do not support nicehash.
