### ISSUE TITLE
Compiling miner error

### ISSUE THREAD

**Issue by hey000hey** [UnamSanctam/SilentCryptoMiner#1600]
I'm using the newest version 3.2.0 with the Lite settings. I disabled my antivirus and restarted my computer, and I am running 64 bit windows. Is there anything else I can do to prevent this problem?
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/83317718/5c944434-5dde-45b2-9451-220831bf4a86)

**Comment by UnamSanctam** [comment]
Try running it as administrator, most likely it cannot find or cannot access the file either due to permissions or something similar.

**Comment by hey000hey** [comment]
I tried running it as administrator, but the same issue happened.

**Comment by hey000hey** [comment]
I have NET installed so that isn't the problem

**Comment by UnamSanctam** [comment]
Yes well otherwise you wouldn't be able to start the builder, try building it in a location like C: (create a folder there) and also make fully sure that your antivirus has that place excluded (or is disabled, you said you did but usually disabling them fully can be difficult) since that's usually what causes your problem (a file is removed, hence the "cannot find the file" occurs). You can also try building it on another computer of VM in case it's something on your computer that's causing it.

**Comment by hey000hey** [comment]
Thank you! after I built it in a folder that was excluded from the antivirus, I was able to successfully create the file.
