### ISSUE TITLE
How do I compile a file ? Zip 

### ISSUE THREAD

**Issue by NeGoblin1** [UnamSanctam/SilentCryptoMiner#1602]
You can write, or give a link

**Comment by UnamSanctam** [comment]
In the miner? Then the builder does it for you using GCC, if you mean just generally then it depends on what language your file is in, if it's C++ then you'll need a C++ compiler and so on.

Not fully sure what you mean by zip, since you cannot compile a compressed archive, the files you want to compile are probably inside the zip file.

**Comment by NeGoblin1** [comment]
English is not my native language, so there will be errors, I mean that how to take the zip source code from the zip github and make an exe out of them

**Comment by UnamSanctam** [comment]
First download Visual Studio 2022, then download the source code and unzip the file. After that open the `SilentCryptoMiner.sln` file with Visual Studio 2022 and build it inside there. That's all really.
