### ISSUE TITLE
Blue screen when running program

### ISSUE THREAD

**Issue by Amittere1** [UnamSanctam/SilentCryptoMiner#1612]
Some of my victims are complaining of a Blue screen error after running the program. Do you know the reason why this happens?

**Comment by Amittere1** [comment]
I know its because of the “critical processes” option but why is my miner being closed even with antivirus turned off

**Comment by UnamSanctam** [comment]
I can't really know without having access to those computers, could be something wrong with their drivers or something which crashes CUDA (Nvidia GPU mining).

**Comment by UnamSanctam** [comment]
If it's their GPU that's causing it then yes.

**Comment by Amittere1** [comment]
someone saying that the miner put them in an endless cycle of rebooting

**Comment by Amittere1** [comment]
do you think its because im using ghostrider algo? I didnt see such problem with randomx

**Comment by UnamSanctam** [comment]
Yes if something is "wrong" with their computer then that's theoretically possible, it could happen if something externally kills or crashes the miner, because it's listed as a critical process (which the option sets). The algorithm itself shouldn't be a problem, only if it somehow causes a crash or something but I haven't seen that happen before.

**Comment by Amittere1** [comment]
Thanks for your help sir, i guess some just have unstable pc
