### ISSUE TITLE
XMR mining CPU or GPU

### ISSUE THREAD

**Issue by extensionov** [UnamSanctam/SilentCryptoMiner#1619]
hello people , im wondering if its a good idea to create 2 separate XMR miners , one for CPU and other for GPU
or should I just create same miner but with GPU and CPU togheter ?

**Comment by UnamSanctam** [comment]
Usually two separate ones, like how it's done in the example settings: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings. That's usually the most profitable since to make a CPU coin work they must limit GPU mining profitability and for a GPU coin then a CPU could never really compete with a GPU.

**Comment by extensionov** [comment]
> Usually two separate ones, like how it's done in the example settings: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings. That's usually the most profitable since to make a CPU coin work they must limit GPU mining profitability and for a GPU coin then a CPU could never really compete with a GPU.

I just want to mine XMR , so I should create 2 miner (one cpu and 1 GPU )
Is this correct

**Comment by UnamSanctam** [comment]
If you want to mine XMR then you only need a CPU miner, since XMR is designed to be bad at mining with the GPU (CPU coins have to do this because a CPU can never really compete normally with a GPU on an even playing field).

**Comment by extensionov** [comment]
ok thank you very much
last question, most of my etc miners are PAUSED on stealth for days now.
should I turn it off ?

**Comment by UnamSanctam** [comment]
What program is causing the "Stealth"? If it's not essential then you could remove that program from the "Stealth Targets".

**Comment by extensionov** [comment]
(Stealth - LeagueClientUx.exe)
task manager
worldof tanks 
etc

**Comment by extensionov** [comment]
Stealth - Pauses the miner and clears the GPU memory and RAM while any of the programs in the "Stealth Targets" option are open

But its been clearing for days, should I just remove the stealth or its a bad idea

**Comment by UnamSanctam** [comment]
Yes you can remove things like LeagueClientUx.exe from the "Stealth Targets" then, since that's just the League client that many have open in the background at all times. Things like the Task Manager might not be the best to remove though, since then the miner would be easier to "find",  though technically they'd just see the usage but they would still be able to see it.

>But its been clearing for days, should I just remove the stealth or its a bad idea

Yes well if they have one of the "Stealth Targets" open all the time then it would be paused all the time.

**Comment by extensionov** [comment]
ok thank you very much for your help.
Is there a by pass for that as well (Not enough free VRAM)
I get that a lot for etc mining

**Comment by UnamSanctam** [comment]
Mining a coin that requires less VRAM, or getting a GPU with more VRAM. The amount of required VRAM is always a certain dynamic value (on purpose) https://minerstat.com/dag-size-calculator.
