### ISSUE TITLE
Mining limitations ?

### ISSUE THREAD

**Issue by etoweb** [UnamSanctam/SilentCryptoMiner#1636]
![IMG_2555](https://github.com/UnamSanctam/SilentCryptoMiner/assets/132036873/14f28c31-700e-424b-aac7-caa7bc99ce43)
Hello, is that normal I have some worker blocked to 4.77h/s on etc mining ? 

Thanks for your work.

**Comment by etoweb** [comment]
Maybe because I have probably 50% of my worker with 1650gtx and I block GPU usage to 50% when not idle ??

**Comment by UnamSanctam** [comment]
That's just because of how pools calculate hashrate, they calculate it by taking the amount of shares submitted over an interval and calculating an approximate hashrate. For example, in their statistics one share might be worth 4.77 MH/s, so if a miner submits one share during the interval (let's say 10 minutes) then it would show a hashrate of 4.77 MH/s.

https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-the-hashrate-shown-on-the-pool-different-from-what-i-expect-or-from-what-is-shown-in-the-web-panel

**Comment by etoweb** [comment]
I see thanks 👍🏼
