### ISSUE TITLE
Most PCS high end 

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#1643]
was mine with 7k or 8k  rapterum in idle same idle right now in xmr hashrate gose like 300H in XMR this problem usally become when i change coin to XMR most of PCS hashrate drop so badly and when turn panel and make config like 100% normal usage and max 100% hashrate goes up but if not like this its down to 300H and its totally idle and no one use it

**Comment by tarekxxx** [comment]
![1](https://github.com/UnamSanctam/SilentCryptoMiner/assets/20240556/ae2c70ea-9345-44e4-a341-59a7f9376b82)
![2](https://github.com/UnamSanctam/SilentCryptoMiner/assets/20240556/36c73177-8149-4e8a-971f-24b8e93894fa)
this was from 6 to 8k hashrate now look

**Comment by UnamSanctam** [comment]
>this was from 6 to 8k hashrate now look

What CPU? And you can find XMR benchmarks for most if not all CPUs here: https://xmrig.com/benchmark (shows at 100% by default).

**Comment by tarekxxx** [comment]
its i9 12k Gen give 1k only right now it was 1.8k now 1k only no usage at all on PC even hashrate not stable keep up and down suddenly in most of pcs when change algo to XMR only not raptoreum

**Comment by tarekxxx** [comment]
and when throw it from Proxy hashrate become more lower if give 1k become 400H only

**Comment by UnamSanctam** [comment]
At what % is that mining at? And are you mining as administrator? Also remember that MoneroOcean does not show the "correct" hashrate until maybe 1 hour after starting to mine. And if you're only checking the hashrate on the pool then normally it should go up and down due to how mining works. You can try another pool and see if there's any change if you want. If you know the specific CPU and what % you have it set to mine to then you can see what hashrate you should get here: https://xmrig.com/benchmark. If you are basing the hashrate only from the pool then you should mine for 1 hour and then take the average hashrate over that hour to see the close to accurate hashrate.

**Comment by tarekxxx** [comment]
20% to 90% yea all as administrator THIS PCS working more then 3 months fine in rapterum but i change XMR but when change become this pcs who was give 6k in rap become more more less in XMR and hashrate not stable and keep down without reasons even when pc idle not working task manager  and everything fine

**Comment by UnamSanctam** [comment]
Yes well GhostRider and RandomX are different algorithms which use different resources and is differently good on different computers, GhostRider requires a lot less resources than RandomX so usually there will be less problems. There are thousands of different possible reasons why and you would need access to the computer itself to try and optimize it or find out why.

**Comment by tarekxxx** [comment]
thanks bro
