### ISSUE TITLE
the miners dont work

### ISSUE THREAD

**Issue by horpanel** [UnamSanctam/SilentCryptoMiner#1650]
I see these at the webpanel

all the miners just go offline instantly

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/135713681/6c1ca3b1-4823-4312-b24a-7759ae03b534)
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/135713681/58d19964-71dd-4036-a8e9-b950c5723ec8)

**Comment by horpanel** [comment]
so do i have to obfuscate the .exe? if so how?

**Comment by UnamSanctam** [comment]
Possibly, you would most easily do it with a crypter. You can check if that's the problem by running the miner inside a VM or on a computer and see if it appears on the web panel and if it goes offline or not.

**Comment by UnamSanctam** [comment]
I'm not sure which ones are actually good at the moment.

**Comment by horpanel** [comment]
because i cant find any

**Comment by UnamSanctam** [comment]
There are many on forums, but nearly all of them will be paid ones of course since they require active development to keep them undetected. There are a few on GitHub that can reduce some detections, I would try running it on a VM or computer and see if it gets detected for you. Since the miner seem to be removed after they went online (so it successfully injected) then most likely it's getting removed by a more advanced antivirus like Avast or something (compared to Windows Defender which usually isn't very good at detecting injections)
