### ISSUE TITLE
Advice on file encryption

### ISSUE THREAD

**Issue by Driadasasa** [UnamSanctam/SilentCryptoMiner#1659]
Greetings, can you please tell me which of these will be able to help me crypt the file and are you still sitting in a telegram?
https://dropmefiles.com/h5J5d

**Comment by UnamSanctam** [comment]
Sorry for the late response, I would suggest testing it with "Self" first since sometimes that means that the in-built miner "Startup" can work (compared to when it's injected into another program since you would need to use the crypters "Startup" instead). I cannot access my Telegram, I believe my number and everything is banned/blocked.

**Comment by Driadasasa** [comment]
> Sorry for the late response, I would suggest testing it with "Self" first since sometimes that means that the in-built miner "Startup" can work (compared to when it's injected into another program since you would need to use the crypters "Startup" instead). I cannot access my Telegram, I believe my number and everything is banned/blocked.

https://dropmefiles.com/TiOtI
Pass: Sz21YoTi5WI7Kn3
Startup crypt

https://dropmefiles.com/
kStmO3cDPG3CJ1s
Startup miner

Please check

**Comment by UnamSanctam** [comment]
One of the files is missing it's usable link, but I also need to miners checker really to see if it's actually mining or not.

**Comment by Driadasasa** [comment]
> One of the files is missing it's usable link, but I also need to miners checker really to see if it's actually mining or not.

Do these files work?

**Comment by UnamSanctam** [comment]
Well I'd need the checker to really know, and the "Startup miner" link is incorrect.
