### ISSUE TITLE
Domain And WebPanel

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1666]
Good afternoon Unam. Hosting providers are increasingly blocking domains hosting a web panel. Tell me if you configure the endpoint through localhost then, as I understand it, no one can block access to the web panel for me?

**Comment by UnamSanctam** [comment]
What do you mean through localhost? You mean hosting it yourself and using something ngrok?

**Comment by masterjek** [comment]
I mean, use the endpoint without buying a domain, but instead of a domain, use the ip address of my computer. And so that the web panel would continue to work through XAMPP

**Comment by UnamSanctam** [comment]
Yes you can do that, though of course you would be exposing your IP. The reason for using a domain is to be able to change the IP address since sometimes your computer, your VPS or your host can change the IP address and then you'll lose it (though you can still change it using "Remote Configuration"). That has happened a few times and you can find a few issues on here about it.

**Comment by UnamSanctam** [comment]
Alright that sounds good, just send it to unams@protonmail.com.

**Comment by masterjek** [comment]
I just emailed you.
