### ISSUE TITLE
Compiling error with cc1plus.exe

### ISSUE THREAD

**Issue by LuisXuexe** [UnamSanctam/SilentCryptoMiner#1680]
I have almost no experience with code, but something tells me nothing about the compiler should be using that much memory.
![cc1plus error](https://github.com/UnamSanctam/SilentCryptoMiner/assets/137979436/ed52bec8-6cf5-4358-9d97-7bfefa9f0862)

Maybe this has something to do with running the compiler on a VM? Or a setting I used? I couldn't find anyone else with the issue on the page. Help would be appreciated, even if it's something stupid-simple.

**Comment by UnamSanctam** [comment]
It's because you're trying to compile the miner with XMR "GPU Mining" enabled, that needs to embed 50MB of CUDA libraries for KawPow to be minable (to be able to compile the KawPow kernel during runtime). To embed such large files you need a lot of RAM (or virtual RAM) for the compiler. What you can do is increase your Windows page file size (your RAM on your disk) to be able to compile it. Or you can choose something else to GPU mine, such as ETC, UBQ or any Ethash coin.

In the next version I am remaking 90% of the ETH/ETC/UBQ miner and including KawPow (and a few other algorithms) directly into that miner instead (no need for the large CUDA library), I have gotten it working but there is still a ton of work and testing I still have to do.

**Comment by LuisXuexe** [comment]
Increasing the page size did the trick, thanks!
