### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by opteh** [UnamSanctam/SilentCryptoMiner#1681]
When compiling in SilentCryptoMiner v3.2.0 the following errors occur:

![screen1](https://github.com/UnamSanctam/SilentCryptoMiner/assets/138050167/0c4cf078-2de7-4076-b6cb-b93ef391840c)
![screen2](https://github.com/UnamSanctam/SilentCryptoMiner/assets/138050167/886a18fb-e90d-4d8d-bebe-7240f50421ed)

Running as administrator, windows 10, defender turned off.

**Comment by UnamSanctam** [comment]
Remove any non-numbers from the version fields in the "Assembly" tab.

**Comment by opteh** [comment]
There are no numbers there, if that's what you mean:
![screen](https://github.com/UnamSanctam/SilentCryptoMiner/assets/138050167/dc8bb6a0-d009-4fb7-b017-ffaadf957b2b)

**Comment by UnamSanctam** [comment]
Hmm, well it gives that error so at least one of the fields does have something else in it (maybe a new line), you can enable it, press "Randomize" and then disable it again. And also add an exclusion to the miner build folder in Windows Defender since even if it's disabled then it can still remove and block things.

**Comment by UnamSanctam** [comment]
That is quite a difficult error but usually it's because the resource compiler (windres) cannot find the code compiler (GCC). Are you sure that you're running it as administrator and that you have added an exclusion into Windows Defender? Also try removing the `UCompilers` folder and build it again in case something removed any files from the compilers.
