### ISSUE TITLE
Can you make miner proxy through tor

### ISSUE THREAD

**Issue by qmada** [UnamSanctam/SilentCryptoMiner#1683]
Pools ban you if they see a lot of different workers, not sure what it is but I know that there is a way to proxy miner though tor network so all workers will be combined and pool will only see 1 worker with all the hashrate

**Comment by UnamSanctam** [comment]
Do you mean xmrig-proxy? That can turn every 255 miner connections into only 1 pool connection. If you use a normal proxy (or Tor in this instance) then the worker amount would be the same except they would all come from the same IP. Though routing through Tor is quite difficult since the Tor proxy will need to be installed on the computer.

**Comment by ARMANDTAKER** [comment]
Hi i have onion pool and onion xmrig proxy, where to add the sock5 line
