### ISSUE TITLE
please unam 

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#1685]
can i include this 
https://github.com/MoneroOcean/xmrig/releases/tag/v6.19.3-mo1
in silent miner because they mining in ZEPH but most of miner not working or working on seems switching and mining alot of algo please check this out and i hope you can include this or to put this as options because there more profit i think right now

**Comment by UnamSanctam** [comment]
That version does not include ZEPH I believe, that's only in the 6.19.4-dev as far as I'm aware. But are you talking about algo-switching? The biggest problem with that is that it can cause lag on some computers (due to the different algorithms, though it's less common now after Dero was removed), and it also takes a while to perform all the benchmarking during startup (which also makes "Stealth" and such able to make the benchmarking give incorrect results). And the algo-switching will also only work on some pools (like MoneroOcean) so I'm not fully sure how I should include it in order to be dynamic. But currently I'm still working on the full GPU miner rewrite (the ETH/ETC/UBQ miner) which right now is around like 95% done I think, so far I've gotten KawPow, ProgPow and ProgPowZ to work by only using OpenCL for both Nvidia and AMD (so that I don't have to use the 20MB CUDA NVRTC library).

**Comment by tarekxxx** [comment]
it will be more profit if you can do it bro really with XMR give in EPYC 7742 2.8$ per day but something like ZEPH coin can give like 9 - 10$ per day  keep going man you awesome

**Comment by tarekxxx** [comment]
this maybe help 
https://github.com/MoneroOcean/xmrig/releases/tag/v6.19.2-mo1

**Comment by UnamSanctam** [comment]
ZEPH support is inside the next unreleased version 6.19.4 (dev) https://github.com/xmrig/xmrig/commits/dev, I can add that into the next version after I'm done with my current GPU miner rewrite.

**Comment by tarekxxx** [comment]
Awesome !
