### ISSUE TITLE
Port Forward

### ISSUE THREAD

**Issue by mastergamer111** [UnamSanctam/SilentCryptoMiner#1687]
Do I need to port forward the client to be able to mine on ports: 80, 443, and 3333?

**Comment by UnamSanctam** [comment]
Well you don't need to port forward anything on 99% of networks to be able to mine. Or do you mean for something like xmrig-proxy?

**Comment by mastergamer111** [comment]
no i was just talking about being able to mine. Also, another question, could you add a features for RVN mining as it is much more profitable?

**Comment by UnamSanctam** [comment]
Well you can already mine RVN but since it's in the XMR miner (xmrig) it's not the best. Right now I'm rewriting the whole GPU miner for that, I'll quote it below:

>currently I'm still working on the full GPU miner rewrite (the ETH/ETC/UBQ miner) which right now is around like 95% done I think, so far I've gotten KawPow, ProgPow and ProgPowZ to work by only using OpenCL for both Nvidia and AMD (so that I don't have to use the 20MB CUDA NVRTC library).

And here is also an issue about the next version: https://github.com/UnamSanctam/SilentCryptoMiner/issues/1670

Though RVN isn't necessarily much more profitable due to its higher VRAM requirement and higher core usage.

**Comment by mastergamer111** [comment]
thanks for the update
