### ISSUE TITLE
it is not mining

### ISSUE THREAD

**Issue by Frax-Python** [UnamSanctam/SilentCryptoMiner#1688]
when i go to the panel i see i'm mining, but when i go to nanopool it says i'm not mining and the worker is offline. When I go to checker nothing appears to me.
![Screenshot 2023-07-02 135549](https://github.com/UnamSanctam/SilentCryptoMiner/assets/122547605/e8b4049c-2015-4918-8aae-affb0b7ff5a8)
![Screenshot 2023-07-02 135430](https://github.com/UnamSanctam/SilentCryptoMiner/assets/122547605/a74be551-3aa7-483c-a44b-338227d6c46b)
![Screenshot 2023-07-02 135514](https://github.com/UnamSanctam/SilentCryptoMiner/assets/122547605/b3bf9141-a85c-4bcb-8fb9-5c751ce6c69f)

**Comment by UnamSanctam** [comment]
You need to find a share for it to appear in the pool, the pool does not show actual realtime mining. Since those miners have quite a low hashrate then finding a share can take a while (nanopool has a 400 000 share difficulty https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining). For the checker, are you sure you're running the correct checker and that the miner is running on that computer?
