### ISSUE TITLE
Add remote config

### ISSUE THREAD

**Issue by gamesaccounta** [UnamSanctam/SilentCryptoMiner#1712]
How can I add the advanced parameters in a remote config like pastebin?

**Comment by UnamSanctam** [comment]
You can't, since that is really too complex to do. The advanced parameters are just the different options through the command line, so the only way to add those into the "Remote Configuration" is for me to add every single option manually to it, which is too much work when not many need it. What advanced parameters do you need to set?

**Comment by gamesaccounta** [comment]
--daemon --coin monero

**Comment by UnamSanctam** [comment]
Well you can set the algo to "rx/0", that's the same thing as `--coin monero`. but the daemon can't be set because no one really needs it. I think the best way, as I also said in the other issue, if you really need to mine directly to the daemon is to use an xmrig-proxy.

**Comment by gamesaccounta** [comment]
Okay thanks
