### ISSUE TITLE
XMRig Proxy

### ISSUE THREAD

**Issue by gamesaccounta** [UnamSanctam/SilentCryptoMiner#1714]
Hello Unam, how can I setup to solo mine in my node with XMRig Proxy with a VPN?

**Comment by UnamSanctam** [comment]
You can find xmrig-proxy here: https://github.com/xmrig/xmrig-proxy/releases, you will then need to change the pool connection  inside the xmrig-proxy settings to your node and then you will also need to change the xmrig-proxy bóund ports (the ports that the miners connect to). After that inside the miner builder you simply point it towards your VPN IP and the port you set. Please also make sure that you're able to port forward that port in your VPN, since otherwise miners cannot contact your xmrig-proxy (or your node that you were trying before).

Though I would never recommend solo mining Monero unless you are planning on getting thousands of miners. Solo mining isn't really any more profitable than pool mining either, so it's only really done to support the Monero network.

**Comment by gamesaccounta** [comment]
So in the monero node i set rpc-bind-ip 0.0.0.0 and rpc-bind-port XXXXX with a opened port in the vpn? And in xmrig proxy setting I set the pool to my vpn public ip and the opened port, i set my wallet and marked daemon true?

**Comment by UnamSanctam** [comment]
Is the node on the same machine as the xmrig-proxy? Then making the node public isn't necessary so that doesn't really matter, you can ignore those rpc options. In the xmrig-proxy you should set the mode to `simple` (or possible `extra_nonce`) and then set the pool to 127.0.0.1 (if it's on the same machine) and the daemon port you set or the default one if you don't set one.

And are you going to be having thousands of miners with your setup?

**Comment by gamesaccounta** [comment]
Okay thanks, Im just testing solo mining
