### ISSUE TITLE
edit the injection method

### ISSUE THREAD

**Issue by anbu-squad** [UnamSanctam/SilentCryptoMiner#1718]
In which file do you need to edit the injection method?

As far as I understand, you need to make some sections of the code unique

Purely in theory, if you come up with your private injection method, then it will be better possible to generally profit?

I want to study my own given moment

**Comment by anbu-squad** [comment]
New Miners - Today
36
New Miners - 3 Days
97
New Miners - 7 Days
209
New Miners - 30 Days
1025



Total
1025
Active
59
Active (Idle)
57
Starting
1
Paused
33
Not enough free VRAM
7
Error
0
**Offline
868**

And by and large, about 1000 workshops per day online should bring a good hashrate

I have permanently constantly about 100 online

So I want to understand the problem for myself

**Comment by tarekxxx** [comment]
how get this amount of bots ?

**Comment by kh3zyyy** [comment]
please acknowledge us on how you have achieved these kind of results

**Comment by anbu-squad** [comment]
I had to spend a decent amount of time
And then 80% flies off offline

I can advise, send a miner build in free swimming and look for devices without antivirus

**Comment by MASHMEEPMASH** [comment]
> 

free swimming?

**Comment by anbu-squad** [comment]
That is, the result from the miner comes after some time

**Comment by possessed-client** [comment]
> That is, the result from the miner comes after some time

Hey, anbu-squad, in a different issue you wrote that with VMProtect you got low detection results on the miner executable itself when using mutation. I also tried, but ESET (offline, with 3+ month old databases) always statically detects it as PUP Win64 Coinminer. What version of VMProtect did you use and did your builds manage to bypass ESET? Is there anything more that needs to be done? Oh, and if you are able to get the miner runtime&scantime FUD with protectors, then you should be able to run it directly without injection just by using the argument generated by SCM with which it normally would run the injected process.

**Comment by anbu-squad** [comment]
I don’t remember specific results in individual antiviruses, there were only a few detectives at the time of static scan, perhaps after use the situation has changed, it will be necessary to check

I used the latest hacking public version 3.8.1

In general, to achieve results, it is necessary to develop a private fork
We have with you, for this you have:
Developer + community + AI
As long as there is such an opportunity, you need to learn how the hidden miner works

I have so far created a builder in which the executable files of miners and rootkita lie next to the folder
Resource protection ===> Build assembly ===> Build protection

The strategy consists in creating constantly new iterations

True, what to do next, and what to change, I do not know yet personally

**Comment by possessed-client** [comment]
> I don’t remember specific results in individual antiviruses, there were only a few detectives at the time of static scan, perhaps after use the situation has changed, it will be necessary to check
> 
> I used the latest hacking public version 3.8.1
> 
> In general, to achieve results, it is necessary to develop a private fork We have with you, for this you have: Developer + community + AI As long as there is such an opportunity, you need to learn how the hidden miner works
> 
> I have so far created a builder in which the executable files of miners and rootkita lie next to the folder Resource protection ===> Build assembly ===> Build protection
> 
> The strategy consists in creating constantly new iterations
> 
> True, what to do next, and what to change, I do not know yet personally

I too have a personal mod which involves obfuscating and slightly modifying the old .net SCM version injection dlls and the whole net build + wrappers around SCM build for static FUD - I'm not even modifying the xmrig miner file at all currently (and also there's the generation side which obfuscates and generates many builds automatically), which allows me to bypass at least some AVs during injection, like Malwarebytes, Avast/AVG(though it will constantly make the sandbox popup on every run and will kill the miner on memory scan after a while), I think also WD(I think it passed injection, but currently I'm having static cloud ML detects on the whole build, so can't get to run) and a bunch of less popular ones too.
But about your system, if you're getting severely bottlenecked by injection, you could just protect the xmrig executable resource (assuming you can get it reasonably FUD), then not build the whole SCM file and just write and FUD your own dropper(technically should be much easier than injection FUDing) for persistence setting and xmrig installation, and either have the dropper run the xmrig with the SCM's arg every time, or set persistence directly to dropped xmrig file including the arg in the task or whatever other way. And for longevity this should also involve an update mechanism after successful installation, so it gets and reinstalls newly generated builds periodically before a detect. 

(well, the ideal way would be to also rewrite the xmrig mod completely with the basic necessary features and then obfuscate the source+protect during generation, because who knows what UnamSanctam has included in his closed source xmrig mod, though he says nothing and that donation is low - still who knows and who can be trusted, especially in this field of endeavour)

**Comment by ssttell** [comment]
How can I see the results? like how many miners you get

**Comment by anbu-squad** [comment]
somewhere, maybe 20% percent remains online
the remaining 80% go offline

I met a user here who had 500 active connections

personally, I have about 100 supported

**Comment by nobody1m** [comment]
yo, do you know how i could add a webhook notification when miner starts and stops? with a few details like mac address and hostname.
