### ISSUE TITLE
what crypter

### ISSUE THREAD

**Issue by jankisjonas** [UnamSanctam/SilentCryptoMiner#1724]
hi, what crypter would u recommend would work the best with unam miner? also i have purecrypter, what settings i should put on unamcrypter so its the most compatible with purecrypter, should i crypt the watchdog seperatly when building the miner? and with what settings?

**Comment by UnamSanctam** [comment]
I am not sure which crypters work best, as long as you disable "Startup" in the miner and then enable "Startup" in the crypter then it should theoretically work. Because the crypter will most likely inject the miner into some other program, if so then the miner would not be able to install itself (because it does not know where it is) so that's why you should use the crypters "Startup" instead (and is also partly why it exists). And you should not really have to crypt the watchdog separately.

If you send me a screenshot of your crypter settings then I could see if there are any specific options you should use.

**Comment by jankisjonas** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/140894178/7f834062-ef26-4834-9936-80feda483496)

**Comment by jankisjonas** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/140894178/f10acc77-ae9c-4434-a8db-de7fffda50d4)

**Comment by UnamSanctam** [comment]
Alright, I would probably recommend enabling these settings on those two pages then:

**Payload Behavour:**

- "Execution Delay" - same kind of option as the "Start Delay" inside the miner, would recommend maybe 15 seconds.
- "Exclusion Windows Defender" - enable this and maybe also "Add Defender Exclusions" option inside the miner builder since I don't know what folders the crypter excludes.
- "Anti Virtual Machines And Debug"
- "Change Timestamp"

**Various Options**
- "Installation (Startup)" - enable this and disable the "Startup" inside the miner, since the crypter injects the miner into another program then the crypter has to handle the installation.

Then you can also set an icon and such if you need it.

**Comment by UnamSanctam** [comment]
Yes, it will only use them if it finds a valid configuration.

**Comment by Tamshi27** [comment]
Hey, what crypter you use? any free one you would recommend?

**Comment by opget** [comment]
> purecrypter

where you bought the pure crypter?

**Comment by googlemA1** [comment]
> > purecrypter
> 
> where you bought the pure crypter?

purecrypter is shit, there is something much better

give me your telegram
