### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by F1reOS** [UnamSanctam/SilentCryptoMiner#1729]
during startup, the miner works, after it turns off and that's it.
![msi](https://github.com/UnamSanctam/SilentCryptoMiner/assets/69204113/363fadb8-7922-4cf1-a613-6d1a4d10992e)
![console](https://github.com/UnamSanctam/SilentCryptoMiner/assets/69204113/fb7e4b69-9ca4-4813-a548-f76d94905326)

**Comment by F1reOS** [comment]
Also at one point he started working again. But worked for 30 seconds and turned off

**Comment by UnamSanctam** [comment]
I wouldn't recommend KawPow, since it's using xmrig and it's not very good at GPU mining. In the next version that's in development I have directly implemented KawPow into the ethminer instead but right now the almost finished next version has suddenly stopped working (only KawPow) so at the moment I'm trying to make it work again.

**Comment by F1reOS** [comment]
> I wouldn't recommend KawPow, since it's using xmrig and it's not very good at GPU mining. In the next version that's in development I have directly implemented KawPow into the ethminer instead but right now the almost finished next version has suddenly stopped working (only KawPow) so at the moment I'm trying to make it work again.

Then which algorithm to choose and which pool?

**Comment by UnamSanctam** [comment]
At the moment probably Etchash or Ubqhash, for the pool any would work. Usually 2miners or nanopool is used nowadays since they don't ban very often.

**Comment by F1reOS** [comment]
Thank you!
