### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1743]
Good afternoon Unam. Can we expect an update soon?

**Comment by UnamSanctam** [comment]
Right now I'm trying to fix the KawPow/FiroPow OpenCL kernels, the Ethash, Etchash. Ubqhash, ProgPow and ProgPowZ work just fine but the KawPow/FiroPow kernels are returning an invalid mixhash. I even bought an AMD GPU to try and debug it (since I only had an Nvidia card) but I've not been able to find the issue yet, Though I have greatly optimized the kernels for AMD GPUs so far at least.

**Comment by masterjek** [comment]
Does the Monero miner work normally in the new version?

**Comment by UnamSanctam** [comment]
Sure everything works except the KawPow and FiroPow kernels I believe, though I haven't fully tested everything for production yet since I'm stuck on the kernels at the moment.
