### ISSUE TITLE
ETH/ETC combination?

### ISSUE THREAD

**Issue by ForsenZ** [UnamSanctam/SilentCryptoMiner#180]
If I add 2 miners - ETH&ETC will the second one work only if GPU ram < 4GB?

**Comment by UnamSanctam** [comment]
No it will run both since the miner can't know if your mining ETH or some other ethash coin, and even then it has no idea how much VRAM is required for the coins until the pool tells it. You can do this through the web panel, first build the miner with for example ETC, then in the web panel see if any has a GPU with enough VRAM and then apply an ETH configuration to that miner.
