### ISSUE TITLE
less than 10%

### ISSUE THREAD

**Issue by PhilippTemkin** [UnamSanctam/SilentCryptoMiner#1802]
How to set the CPU usage value for constant mining and mining in idle mode to less than 10? That is, I want no more than 3% of the processor to be used during constant operation, and 5% when idle. But how to achieve this?

**Comment by UnamSanctam** [comment]
You can't really do so unless the computer has a lot of cores. The limiting of the maximum CPU usage is done by limiting how many CPU cores it is mining on, so if a CPU has 8 cores and you want to mine at 20% then the miner would limit itself to only use 8*0.2=1.6≈2 cores which means 2/8=0,25=25% of the CPU will be used. For a maximum of 3% to be used then you would need a CPU that has at least 100/3≈33 cores, the majority of CPUs don't have that many cores which is why using only 3% would be difficult. So, the lowest amount of cores you can use is 1, for a 4 core CPU the minimum would be 25%, for an 8 core CPU the minimum would be 12,5% and for a 16 core CPU the minimum would be 6,25%.
