### ISSUE TITLE
Anti VirusTotal

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1804]
Good evening Unam. I found this topic - [https://github.com/6nz/virustotal-vm-blacklist](url) As I understand it, this is blocking virtual machines VirusTotal. Since I don’t understand programming, I don’t know how it works, but I want to ask, is it possible to implement a similar function in a miner?

**Comment by UnamSanctam** [comment]
That's a collection of different identifiers for VirusTotal machines that they use, so you could technically implement something using those lists (though it will only find those that are in the list that is implemented of course). For example the repository has a list of CPU serial numbers that some VirusTotal machines use, to implement that into the miner one would get the CPU serial number of the machine and then compare it to that list. The biggest potential "problems" are these: 1) The lists might only be for some of the VirusTotal machines 2) Some of those checks could also be triggered for normal computers that aren't VirusTotal machines 3) The checks themselves could also increase detections. Those are the main reasons why I haven't implemented something like that into the miner yet. And if I did implement that myself then I wouldn't want to use someone else's list either, mainly because I don't know the accuracy of the lists, meaning that I would have to create my own bot that tries to automatically get the VirusTotal machine identifiers (which I have not had time for).
