### ISSUE TITLE
For no reason

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#1822]
For No Reason The Miner Become 0 Hashrate iam sure last week was calc like 7K but same PC now calc 0 hashrate with so wired no anivirus and i can ping to website i mine with which is wired to me where problem should be ?
and i do checker everything running on settings

**Comment by UnamSanctam** [comment]
With miner version 3.3.1? Have you checked your "Remote Configuration" or web panel configuration that nothing is wrong there? And can you post a screenshot of the checker?

**Comment by tarekxxx** [comment]
yea with lastest version check configuration working with another pcs normal same remote config webpanel when i change from proxy to normal connection do same keep 0 hashrate even i change the pool to another change pool but 0 hashrate same it happen with alot 
![Screenshot (177)](https://github.com/UnamSanctam/SilentCryptoMiner/assets/20240556/5f9c80cb-103c-4b94-9dab-7481c11d486a)

**Comment by UnamSanctam** [comment]
And there's enough free resources on that computer? Such as CPU and RAM. Since you're not mining on normal computers then please check the amount of free RAM and also the server settings (since you're mining on servers). In version 3.3.1 if the miner is at 0 Hashrate for at least 2 minutes while it shouldn't be then it will try to recreate the CPU threads to make it mine again, but since it has gone longer than that then it usually means that there isn't enough resources or some other issue like pool connection (but in your case I assume that's not the problem).

>But If i Change to Rapterum it should work with less hashrate with not profit at all !

Does it work with Raptoreum? If it works with Raptoreum (GhostRider) then most likely the computer does not have enough resources to mine Monero (RandomX) at the moment.
