### ISSUE TITLE
XMR mining on gpu doesn't work

### ISSUE THREAD

**Issue by essie98927** [UnamSanctam/SilentCryptoMiner#1846]
Hi unam,

The gpu mining feature with the XMR miner doesn't work...

Did some tests:

CPU only = working
CPU + GPU = only the CPU is mining
GPU only = error cannot connect to the pool

I tested with nanopool and moneroocean as pool, stratum and SSL, and also used your panel to confirm if it was mining. Always the same results.

Any clue what's happening?

**Comment by UnamSanctam** [comment]
Seems like it might be because the NVRTC library (like 20MB) was removed when I removed KawPow algorithm from the XMR miner (because KawPow is now in the GPU miner instead). On my test computer it works but doesn't seem to work for everyone. Though, what are you trying to mine using the GPU in the XMR miner? Since that's usually not very profitable.

**Comment by essie98927** [comment]
I just wanted to mine XMR on gpu...

Will you re add the library or make anything to fix the issue?

**Comment by UnamSanctam** [comment]
Well yes it will be fixed in the next version, though you shouldn't mine XMR on the GPU. Since XMR is designed to be a CPU only cryptocurrency then mining it on the GPU is not really profitable at all and uses a lot of GPU resources.

**Comment by essie98927** [comment]
Yeah yeah you're totally right it's near useless I was just trying lol.

Thanks for the futur fix and as usual for your quick answers!
