### ISSUE TITLE
Is he stealing our clients?

### ISSUE THREAD

**Issue by Sh4r3cat** [UnamSanctam/SilentCryptoMiner#185]
Hey guys do you think unam is steal our mining bots ? Because my friend dropped on 1 day 5 GHS

**Comment by UnamSanctam** [comment]
You can just easily verify it if you use a RAT. You'd see if the miner is running or not and if it appears in the pool.

**Comment by Sh4r3cat** [comment]
![IMG-20211227-WA0000](https://user-images.githubusercontent.com/43313587/147471290-2d83f29f-c5de-47bb-aa79-8de5ebc5b797.jpg)
But so much looses can't be real

**Comment by UnamSanctam** [comment]
I would try changing the pool, or new detections/updates could have been added to Windows Defender. That I don't steal workers (and I never have, nor can I) can be verified if your friend has RAT (or access) to any of the computers since they'd see if the miner is running or not and can see if it appears on the pool (if they use computer names as worker names).

I can't know the reason for your drop in hashrate since I don't have any control over what you do, what settings you use or anything else.

**Comment by masterjek** [comment]
UnamSanctam Doesn't steal clients. A week ago, my speed also dropped by half. And all because many antiviruses, after updating the databases, began to detect the introduction of the miner into the system. I personally checked it took the miner encrypted it. After encryption, the antivirus shows that the file is clean, but as soon as the antivirus is launched, when the miner is introduced, it deletes it. Your file may be clean with a static scan. But there are also detections that are dynamic when the file is run. Now, when the miner is launched, it is destroyed by avast and avg antivirus. Nod and Kaspersky do not detect the file at startup. I did not check the rest of the antiviruses. All that remains is to wait for the miner to update.

**Comment by AspectKraken** [comment]
masterjek what encryption do u use?

**Comment by masterjek** [comment]
AspectKraken I cannot say which encryptor, as it is private and custom-made.
