### ISSUE TITLE
Redacted

### ISSUE THREAD

**Issue by sa6ta6ni6c** [UnamSanctam/SilentCryptoMiner#1888]
Redacted

**Comment by UnamSanctam** [comment]
>Sharing all logs, written in Rust, windef + many av bypass. Write tg below.

I was thinking of making a version for Rust before though creating some kind of portable compiler for it (since the builder would need one) seems kind of impossible from when I tried.

>About CryptoMiner it lacks evasion stuff @UnamSanctam

Which evasion stuff specifically? I generally don't add any risky bypasses or private ones that I know of (since those belong to the ones who "invented" them). But if you know of any that aren't risky (by risky I mean that there's any chance that the miner would stop working if it's ever fixed) or are public methods then feel free to share. When I develop the miner probably 95%+ of the time goes into the xmrig and ethminer development since that's by far the most complicated (especially the 3.3.0 update which was probably the most difficult thing I've done so far). Due to that then I usually don't have much time to develop on the installer/injector without having to massively delay the update (and I'm also normally pretty burned out from all the testing at that point), though right now for the upcoming update I've only been working on different ways to get around detections and improving parts of the code.

**Comment by sa6ta6ni6c** [comment]
> >Sharing all logs, written in Rust, windef + many av bypass. Write tg below.
> 
> 
> 
> I was thinking of making a version for Rust before though creating some kind of portable compiler for it (since the builder would need one) seems kind of impossible from when I tried.
> 
> 
> 
> >About CryptoMiner it lacks evasion stuff @UnamSanctam
> 
> 
> 
> Which evasion stuff specifically? I generally don't add any risky bypasses or private ones that I know of (since those belong to the ones who "invented" them). But if you know of any that aren't risky (by risky I mean that there's any chance that the miner would stop working if it's ever fixed) or are public methods then feel free to share. When I develop the miner probably 95%+ of the time goes into the xmrig and ethminer development since that's by far the most complicated (especially the 3.3.0 update which was probably the most difficult thing I've done so far). Due to that then I usually don't have much time to develop on the installer/injector without having to massively delay the update (and I'm also normally pretty burned out from all the testing at that point), though right now for the upcoming update I've only been working on different ways to get around detections and improving parts of the code.

Unam, I already have a silent monero miner in Rust. I really appreciate your work, but there is no point in reducing detection as it's up to people using the miner. You could focus on features instead. 

**Anyways, I want ppl to know I still need someone to spread my stealer 1/72 detection on Virustotal, Insane anti-vm + collection of data. 
Also have my own dropper, any exe, all downloads thru Microsoft servers. Sharing all logs. Mail me or write here ur telegram/we can also do Signal.**

My mail:

unlucky_me@tutanota.com

**Comment by emmalaporte93** [comment]
@sa6ta6ni6c  plz check ur mail

**Comment by Aciid-Nuk3r** [comment]
Why are people using virus total?? 🙄 use kleenscan in the future, I’ve yet to wrap my head around the thought process, virus total distributes the file you uploaded to the AV community to review…

**Comment by sa6ta6ni6c** [comment]
> Why are people using virus total?? 🙄 use kleenscan in the future, I’ve yet to wrap my head around the thought process, virus total distributes the file you uploaded to the AV community to review…

Hello.

It's dropper with anti vm, bypasses all virustotal av/vm sandboxes. So I don't care about it being uploaded on vt.

Regards
