### ISSUE TITLE
can you change xmr wallet after installing the miner?

### ISSUE THREAD

**Issue by FrazeDev** [UnamSanctam/SilentCryptoMiner#1892]
can you change xmr wallet after installing the miner?

**Comment by UnamSanctam** [comment]
If you have a "Remote Configuration" or web panel then yes you can do it through that.
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration

**Comment by FrazeDev** [comment]
Thanks for quick response, is there any eta when will you make the miner fud ?

**Comment by FrazeDev** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/72148172/e97bb216-2197-4cdf-af08-3030a97d434d)
i need to add the config here and press Save correct?

**Comment by FrazeDev** [comment]
so i changed it there replace it but still the wallet doesn't change for some reason 
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/72148172/eeac332b-453a-45a1-b851-c1b17b5131cb)

**Comment by FrazeDev** [comment]
what changed is the hasrate dropeed by a lot

**Comment by UnamSanctam** [comment]
>i need to add the config here and press Save correct?

Yes that's correct.

>Thanks for quick response, is there any eta when will you make the miner fud ?

Not sure, right now I'm trying to make the embedded files undetected but everything else in my development version is currently undetected so only that should be left, though the miner will never be FUD (fully undetected) of course since it's a public open source project but it should be undetected for most, or at least Windows Defender.

>so i changed it there replace it but still the wallet doesn't change for some reason

Is the configuration correct for the "xmrig1" configuration?

**Comment by FrazeDev** [comment]
yep its the xmrig1 so it changed after few minutes but the hasrate is the problem now btw the auto refresh on web panel doesn't work

**Comment by UnamSanctam** [comment]
>yep its the xmrig1 so it changed after few minutes but the hasrate is the problem now btw the auto refresh on web panel doesn't work

Since the connection was just established then the hashrate it shows might not be the full amount, since it showed the hashrate just after it switched over. And auto-refresh should work, it refreshes every 15 seconds.

**Comment by FrazeDev** [comment]
> > yep its the xmrig1 so it changed after few minutes but the hasrate is the problem now btw the auto refresh on web panel doesn't work
> 
> Since the connection was just established then the hashrate that you see on the web apenl might not be the current hashrate in the, since it got the hashrate just after it switched over. So after a minute or two you should see the accurate hashrate. And auto-refresh should work, it refreshes every 15 seconds.

okay, and w this one everything was okay but now its only 1.5kh/s it was 800h/s earlier and everytime now after reinstalling it it doesnt go above 4 and its running with admin

**Comment by UnamSanctam** [comment]
And you didn't change the "max-cpu" or "idle-cpu" in the"xmrig1" configuration?

**Comment by FrazeDev** [comment]
and 3 miners are running but in 2miners its shows that its only 1 so idk if its the web bugging or the 2miners 
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/72148172/2aa90b91-5568-4592-9294-01a0ecbfccf3)


> And you didn't change the "max-cpu" or "idle-cpu" in the"xmrig1" configuration?

change it to it was 30 changed it to 40 and now its even less then before

**Comment by FrazeDev** [comment]
wait now my brain is not braining 1 sec

**Comment by FrazeDev** [comment]
kh/s is higher right ?

**Comment by UnamSanctam** [comment]
Yes that's right, 3.5 KH/s is 3500 H/s, the K means Kilo (1000).

**Comment by FrazeDev** [comment]
what about the thing w the 2miners where its says only working 1 but its actually 3
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/72148172/9d1c213c-c84c-4f6f-a218-32a319fd5764)


> Yes that's right, 3.5 KH/s is 3500 H/s, the K means Kilo (1000).

**Comment by UnamSanctam** [comment]
They show workers and not miners, so since all your miners have the same worker name (no worker name) then it will group all the miners under the same worker. If you want a separate worker for each miner then you can set the worker name to something like `{COMPUTERNAME}` (the miner will replace that with the computers name). You can add a worker name by adding a dot (.) after your wallet address and then entering the worker name, like so: XMRWallet.WorkerName

**Comment by FrazeDev** [comment]
aa okay understood and last question if i installed the miners only to mine xmr w cpu/gpu can i add another currency to mine for only gpu ?

**Comment by UnamSanctam** [comment]
No since the code for that isn't inside your file, the builder only includes the code that you're using. And each miner is also injected independently and will show up as its own entry as well (to make things easier to manage). I would recommend an XMR (or ZEPH, they are the same algorithm) miner mining on the CPU and then maybe mining KawPow or ProgPowZ on the GPU. You can see what GPU coins are the most profitable here: https://whattomine.com/.

**Comment by FrazeDev** [comment]
what wallet do you suggest for KawPow cus i only got monero so

**Comment by UnamSanctam** [comment]
Depends on what KawPow cryptocurrency you will mine, but for most GPU coins you can use things like MetaMask, Exodus, ZelCore and things like that.

**Comment by FrazeDev** [comment]
thank you for your help

**Comment by UnamSanctam** [comment]
No problem, good luck with your mining.

**Comment by FrazeDev** [comment]
> 

can u send zelcore wallet cus i can't find it

**Comment by UnamSanctam** [comment]
It's here: https://zelcore.io/, ZelCore is a bit more "budget" (as in appearance and sometimes a bit more buggy) than many other wallets but I use it since I like how the portfolio looks.
