### ISSUE TITLE
How to know if you're banned from the pool? -Having some weird issue.

### ISSUE THREAD

**Issue by sn00rlax** [UnamSanctam/SilentCryptoMiner#1913]
Hi,

So as title says, does the pool bans your crypto wallet address, or stop the address from receiving hashrate?
Or they ban workers' IP addresses?

What raised suspicious for me is that from today 2miners' stats "Estimated daily profit" decreased by double for me for XMR mining, but the hashrate is same as any other previous days.
Also the price of XMR hasn't significantly changed in these days as well.

After switching the pool to "supportxmr" the estimated profit returned back to same how it looked on 2miners dashboard past days.

Do you have any idea what caused this? Or it's some glitch with 2miners? 
Anyone else having same issue with mining XMR today with 2miners?

**Comment by sn00rlax** [comment]
Update: After asking same questions in 2miners' Telegram group they say earnings decreased bcz more miners came and also because of ASICs for mining Monero being launched. 

Anyone having same issues like me today? Just want to hear someones opinion about this or is there anyone else with a same problem.

**Comment by UnamSanctam** [comment]
If you were to get banned then your hashrate would decrease, since they would ban your wallet address so that when trying to mine 2miners would stop the connection with an error message. But yes earnings will decrease if the total hashrate increases (though there hasn't been much difference lately https://2miners.com/xmr-network-hashrate), because you are competing with more people for the block rewards (the block rewards of course always stays the same). It's also possible that there was some issue with their statistics, mainly because the estimated daily profit is calculated from your average hashrate over the last hour.
