### ISSUE TITLE
emoved XMR "CPU Mining" option due to it having no reason to exist now that the "GPU Mining" option is gone

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#1928]
Brother are you Removed XMR CPU Mining in new update ?

**Comment by UnamSanctam** [comment]
Yes because it always mines using the CPU now, so there's no reason for the option to exist. The reason it existed before was if you only wanted "GPU Mining" enabled and no CPU mining but since the xmrig GPU mining has so many flaws I chose to remove it and thus the "CPU Mining" option isn't necessary anymore.

**Comment by DARK-DEVIL-66** [comment]
i can't untasdand please expline me ?

my fav minig is xmr cpu based minig so everyone has no gpu

**Comment by DARK-DEVIL-66** [comment]
any cpu based mining option have in new update ?

**Comment by UnamSanctam** [comment]
XMR now is CPU-only in the new version, previously you could choose between XMR CPU mining and GPU mining (or both) but now in the new update you can only mine XMR with the CPU. So if you only want to mine XMR with the CPU then there's no difference compared to the old version.

**Comment by DARK-DEVIL-66** [comment]
can i mine xmr and etc at the same time in new update ?

**Comment by DARK-DEVIL-66** [comment]
XMR & ETC

**Comment by UnamSanctam** [comment]
Yes.

**Comment by DARK-DEVIL-66** [comment]
Thank's Bro
