### ISSUE TITLE
WD detection alerts "coin miner" even though exclusions are added with installation

### ISSUE THREAD

**Issue by sn00rlax** [UnamSanctam/SilentCryptoMiner#1935]
Hi,

About your latest version. WD alerts about coin miner inside conhost.exe process even though all exclusions are added by miner.
(re-checked)

Screenshot: 
![Screenshot_threatblockedcoinminer](https://github.com/UnamSanctam/SilentCryptoMiner/assets/126919137/8ad7a465-67cf-4dbb-a9f4-9b3b812a9fe6)

BTW would it be possible to return back choice for users of selecting user profile path of installation rather then Program Data (run as system)? 

I think Windows is more strict with detections when programs are running as system. Also could you add a path for user profile path back  into exclusions list please?

**Comment by UnamSanctam** [comment]
>About your latest version. WD alerts about coin miner inside conhost.exe process even though all exclusions are added by miner.
(re-checked)

Hmm, I don't get that detection (or any detection at all in the new version) on any of my VMs so that's a bit hard to replicate. You can try changing it to explorer.exe maybe. I get more detections from using explorer.exe (though never the detection you're getting) but maybe you won't.

>BTW would it be possible to return back choice for users of selecting user profile path of installation rather then Program Data (run as system)?

Not when it's running as a service like it does now, the main problem with not installing it as System is that it won't run for all users. So for example, if someones main Windows account is User1 and they aren't an administrator, then when they install the miner (as an administrator) it will install under the administrator account and not the User1 account. So the miner will never start on startup because it's not installed under User1. The problem with using the Task Scheduler is that it's quite detectable since you have to either write the plaintext Task .xml file to the disk or run a long powershell command (that risks an AMSI detection).

>I think Windows is more strict with detections when programs are running as system. Also could you add a path for user profile path back into exclusions list please?

I haven't experienced any more detections but I can't be sure. And the user profile path is still in the exclusions command just like always.
https://github.com/UnamSanctam/SilentCryptoMiner/blob/c61e842d5ec04e2493a83f54f096ba2f3b95687d/SilentCryptoMiner/Classes/Codedom.cs#L262

**Comment by sn00rlax** [comment]
> > About your latest version. WD alerts about coin miner inside conhost.exe process even though all exclusions are added by miner.
> > (re-checked)
> 
> Hmm, I don't get that detection (or any detection at all in the new version) on any of my VMs so that's a bit hard to replicate. You can try changing it to explorer.exe maybe. I get more detections from using explorer.exe (though never the detection you're getting) but maybe you won't.
> 
> > BTW would it be possible to return back choice for users of selecting user profile path of installation rather then Program Data (run as system)?
> 
> Not when it's running as a service like it does now, the main problem with not installing it as System is that it won't run for all users. So for example, if someones main Windows account is User1 and they aren't an administrator, then when they install the miner (as an administrator) it will install under the administrator account and not the User1 account. So the miner will never start on startup because it's not installed under User1. The problem with using the Task Scheduler is that it's quite detectable since you have to either write the plaintext Task .xml file to the disk or run a long powershell command (that risks an AMSI detection).
> 
> > I think Windows is more strict with detections when programs are running as system. Also could you add a path for user profile path back into exclusions list please?
> 
> I haven't experienced any more detections but I can't be sure. And the user profile path is still in the exclusions command just like always.
> 
> https://github.com/UnamSanctam/SilentCryptoMiner/blob/c61e842d5ec04e2493a83f54f096ba2f3b95687d/SilentCryptoMiner/Classes/Codedom.cs#L262

Hi,

I see...

After I changed injection to explorer.exe now there is no detection alert anymore.

BTW user profile path is not adding itself to exclusions list for me.
Screenshot:

![Screenshot_2-exclusions](https://github.com/UnamSanctam/SilentCryptoMiner/assets/126919137/39b8848c-9e75-4b4d-b5b4-9624a2b6e61f)

And last question, if I inject both ETH and XMR miners to explorer.exe will it cause any interruptions to each other? Or only one should be injected to explorer.exe? 

Thanks!

**Comment by UnamSanctam** [comment]
>After I changed injection to explorer.exe now there is no detection alert anymore.

Hmm alright weird, for me it was the opposite, but keep it as explorer.exe if it is better for you. Now I'm not sure whether I should revert the default back to explorer.exe or not. For me conhost.exe is working better but since you're getting memory detections from conhost.exe (which is a more serious detection than what I was getting) then explorer.exe might be better, I guess it depends on how it is on most computers (which sadly we can't really know). 

>BTW user profile path is not adding itself to exclusions list for me.

`C:\WINDOWS\system32\config\systemprofile` is the user profile of System, things like UserProfile are relative to whatever is running the program (though it should have added your user profile whenever you first ran the miner). Which is the same thing as what I said before regarding administrator accounts and such, for example if you had "Run as System" disabled in the previous versions but ran it as administrator then it still excluded the administrator user profile folder and not necessarily the user that's logged in who started the miner (because they can be two separate account).

>And last question, if I inject both ETH and XMR miners to explorer.exe will it cause any interruptions to each other? Or only one should be injected to explorer.exe?

No that's totally fine, you can inject both into that without issue.

**Comment by sn00rlax** [comment]
Thanks for your fast and detailed replies. I'll leave this thread opened for a while, maybe we'll see if any other users are having similar detections from these injections then we will be more sure is it better to keep it under explorer or conhost injection.

Best regards!
