### ISSUE TITLE
this maybe dumb but plz add it

### ISSUE THREAD

**Issue by furjac** [UnamSanctam/SilentCryptoMiner#1943]
see i tried to write a code like  using it u can delete any folder and file even if it is running like the iobit unlocker it unlocks and delete anything so what if we deleted the antivirus using this if windows security it will add exclusion and if anything other than windows security delete it through this method and run a code if any antivirus is going to be installed delete it i know its dumb tho

and leave the above thing its not the actual question my actual question is 
i work in a company where all the systems are connected through a domain to a server the server is windows server edition 2008
and how to spread the miner to all computers i know the domain user and password and how to do it like is there any way to spread it like that if a new system is connecting to that server this new system should be affected

**Comment by UnamSanctam** [comment]
>see i tried to write a code like using it u can delete any folder and file even if it is running like the iobit unlocker it unlocks and delete anything so what if we deleted the antivirus using this if windows security it will add exclusion and if anything other than windows security delete it through this method and run a code if any antivirus is going to be installed delete it i know its dumb tho

Sadly doing that to an installed antivirus is not really possible, since not even the administrator user has enough permissions to be able to kill and/or remove the files or registry keys associated with antiviruses. The only way to do so is through exploits but they tend to be fixed pretty quickly. Though some antiviruses can be uninstalled through special methods, but quite a lot of things needs to be done for that. Though it is technically possible to kill the installers for new antiviruses if they are distinct programs, which is what some do by adding the installed .exe name into the "Kill Targets" part of the miner.

>and leave the above thing its not the actual question my actual question is
i work in a company where all the systems are connected through a domain to a server the server is windows server edition 2008
and how to spread the miner to all computers i know the domain user and password and how to do it like is there any way to spread it like that if a new system is connecting to that server this new system should be affected

It really depends on how the entire network is set up, either you can use things like services, scheduled tasks or PsExec https://learn.microsoft.com/sv-se/sysinternals/downloads/psexec, but doing this across a domain can get pretty complicated. There might be special scripts available to automatically do it though I don't know about any specific ones.

**Comment by furjac** [comment]
thank u so much for the info
