### ISSUE TITLE
how to mine in single miner without get banned

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#1944]
Hi Dear

i have 04 miner but inthe futrue 1000miner i know low hashrate miners are banned by some pools so can i have any chaces to merge all miners into single miner (rigid 0)

**Comment by UnamSanctam** [comment]
Only if you host your own xmrig-proxy on some computer/server and proxy all your miners through that. Other than that it's not really possible due to how the internet works. Even if they have the same worker name (rig ID) they are still separate miners, so the only way to "merge" all the miners would be to have some sort of middleman, usually an xmrig-proxy.

**Comment by DARK-DEVIL-66** [comment]
ok welldone

whats happen i not specifying rigid(miner name) i think 2miners.com dashboard showing rigid 0 for all merged miners

**Comment by DARK-DEVIL-66** [comment]
what is that how is it work xmrig-proxy.

**Comment by DARK-DEVIL-66** [comment]
2miners.com will banned for me lot of miners i have ?

**Comment by UnamSanctam** [comment]
>whats happen i not specifying rigid(miner name) i think 2miners.com dashboard showing rigid 0 for all merged miners

If you don't specify a worker name then pools will just show all miners under the default worker name. Worker names are really just used for statistics, they usually don't have anything to do with whether you get banned or not.

>what is that how is it work xmrig-proxy.

xmrig-proxy can use the NiceHash protocol (not the pool, the protocol) for all the connected miners, this means that it can split each job from the pool into 256 sub-jobs. Because of this then xmrig-proxy can use a single pool connection (upstream) for 256 miners, so 1000 miners would just use 4 pool connections (pool would see 4 miners).

>2miners.com will banned for me lot of miners i have ?

Probably not, one person has said so before in an issue but no "proof" has ever been sent so we don't know whether it actually happens or not. I know som people that have tens of thousands of miners that have been using 2miners for years now without getting banned. So most likely you won't get banned.

**Comment by DARK-DEVIL-66** [comment]
any possible way for findout our web penal in internet Using Quiris i mean
intitle:UnamSanctam

**Comment by UnamSanctam** [comment]
It shouldn't, the web panel has a robots.txt that tells search engines not to index any of the pages:
https://github.com/UnamSanctam/UnamWebPanel/blob/master/UnamWebPanel/robots.txt

**Comment by DARK-DEVIL-66** [comment]
what is defult web penal password

**Comment by UnamSanctam** [comment]
`UnamSanctam`
https://github.com/UnamSanctam/UnamWebPanel/blob/b8b30b7b0412fa2f817fb80df9b561291eddb186/UnamWebPanel/config.php#L6

**Comment by DARK-DEVIL-66** [comment]
i forgetit web penal password and i don't have acess to server now can i break the password ?

**Comment by UnamSanctam** [comment]
No, the web panel has built-in brute force protections, it will block your IP for 15 after 5 wrong password attempts.

**Comment by DARK-DEVIL-66** [comment]
u mean no way to break the password or reset

**Comment by UnamSanctam** [comment]
Correct, not without access to the config.php file on the server.

**Comment by DARK-DEVIL-66** [comment]
not without access to the config.php file on the server. what u mean

**Comment by UnamSanctam** [comment]
Only way to check the password or change it is if you have access to the config.php file so that you can read or change it.
