### ISSUE TITLE
make donation for particuler wallet address

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#2030]
hey bro

i want to know about how to use advanced parameter and what can i use this filed 
and i want to make donation for particuler xmr address
so pls expline me ?

**Comment by UnamSanctam** [comment]
You can add command line options for the miner which will be included, for example https://xmrig.com/docs/miner/command-line-options. By donation do you mean that some percentage of what you mine should go to some other wallet address? Then the only way to do that is to modify the xmrig.exe code to do that, or alternatively to use a pool which supports doing that (like MoneroOcean). Or alternatively to add the donation percentage/wallet address into the xmrig-proxy.exe code to make the proxy do that.

**Comment by DARK-DEVIL-66** [comment]
i don't like to build or other miner compire to your silent miner is best
but we don't have a option in web penal figerout howmany shares are submited by miner and how many shares are rejected by pool it's the solution for all errors like (0hashrate and miner how long take to  submiting share to pool,somebody say stealing my hashrate blabla --> actually i know you don't do that)

any way your work are wonderfull nobody can make like this repo!

**Comment by DARK-DEVIL-66** [comment]
i want to know something somebody say "plase install windows 7/10 to my laptop" so can i have chance to make our miner pre installed in iso file 


i mean incoude our miner into windows iso file   (like system app-pre installed)


or

we can restore exiting backup One Computer(miner installed pc) to Another with Different Hardware
if you know wich software do that work by done ?

**Comment by DARK-DEVIL-66** [comment]
Why i switched prevously 2miner config to zergpool config but it"s auto switching to defult 2miner wallet addres pool detiles and etc but still remain config switching feild zergpool config ?

**Comment by UnamSanctam** [comment]
>i don't like to build or other miner compire to your silent miner is best
but we don't have a option in web penal figerout howmany shares are submited by miner and how many shares are rejected by pool it's the solution for all errors like (0hashrate and miner how long take to submiting share to pool,somebody say stealing my hashrate blabla --> actually i know you don't do that)
any way your work are wonderfull nobody can make like this repo!

Thank you, I can technically add shares (only valid/invalid) and difficulty, I chose not to add those since I have been trying to reduce the amount of data being sent as much as possible. But I might add them.

>i want to know something somebody say "plase install windows 7/10 to my laptop" so can i have chance to make our miner pre installed in iso file
i mean incoude our miner into windows iso file (like system app-pre installed)

You will have to edit the ISO or installation to to that, it can be quite complicated.

>we can restore exiting backup One Computer(miner installed pc) to Another with Different Hardware
if you know wich software do that work by done ?

I'm not sure what you mean, do you mean cloning a harddrive?

>Why i switched prevously 2miner config to zergpool config but it"s auto switching to defult 2miner wallet addres pool detiles and etc but still remain config switching feild zergpool config ?

xmrig will go to the next pool configuration if the current pool configuration stops working to ensure that the miner isn't doing nothing, the specific zergpool server could have stopped working (for the user) for a moment or something.

>after few miniute i push the miner for little bit of time &
now i switched to zergpool config it"s worked fine
why this happen bro ?

It probably couldn't connect or something happened so it moved to the backup pool configuration, this is default xmrig behavior so that the miner doesn't just stop. It should retry the default (zergpool) configuration after a while.

**Comment by DARK-DEVIL-66** [comment]
yes bro the pariculer miner never appeared in zergpool dashbord after long time but it's appeared to 2miner i will try the 2miner....
