### ISSUE TITLE
I've been trying this all day,"But it still cannot start automatically.

### ISSUE THREAD

**Issue by chenguanxiwjr** [UnamSanctam/SilentCryptoMiner#2068]
I've been trying this all day, and neither with my settings nor with the exe generated from your example XML does it automatically start. 
![04c6bb80aa7ebdd8dce201f5b65cf47](https://github.com/UnamSanctam/SilentCryptoMiner/assets/131135720/c9731626-673a-41a0-a5fc-ba380e648054)
Also, the exe you previously provided to someone else doesn't automatically start on my computer either.
![03ef111b1cf503b0592390e5b317b74](https://github.com/UnamSanctam/SilentCryptoMiner/assets/131135720/12685c33-57ea-4248-95ff-684cb4cbefd8)
 If I double-click the generated files, they run fine, but they don't start automatically. I couldn't find the expected content in the registry or the specified path.
![d098bc1c30864d64bdab856e43546ad](https://github.com/UnamSanctam/SilentCryptoMiner/assets/131135720/484c1732-95bb-4b83-bd31-2d5334475d07)
![5dac22aaf49fad3622b35041a0502da](https://github.com/UnamSanctam/SilentCryptoMiner/assets/131135720/0711c55a-f2b2-42c1-873a-21a3044d94f2)
![3497cc8af7d312852309602f3a53141](https://github.com/UnamSanctam/SilentCryptoMiner/assets/131135720/a19d5ca3-8784-4da6-8365-0fafc2d1687c)
 Initially, I thought it might be because the Chrome folder already exists, but even after changing the generation path, the corresponding files are still not generated. My operating system is Windows 10 Professional, version 22H2. I've tried creating it on both my virtual machine and my VPS, but it still doesn't start automatically
My VPS version is Windows Server 2016 Standard Edition

**Comment by UnamSanctam** [comment]
Hmm, there should be a folder inside %ProgramData% (not Program Files anymore) called "pidzzubohya" where your file is (your "Startup" tab). And a Windows Service with the name "OMOUPQKG". What happens if you place the miner file on the C: drive and run it there? Though your MinerTest.exe does not seem to be from the 3.4.0 builder.

**Comment by chenguanxiwjr** [comment]
They seem to be nonexistent... I've generated it more than once and modified the generated path and name, but they don't seem to have been added to Windows services or folders.
![e021bc98c464a89c7ad453124429bcd](https://github.com/UnamSanctam/SilentCryptoMiner/assets/131135720/0880ae5f-a13d-4ed9-9827-7bd04c6b9f32)
![4478e66cc93f43cc23801a9854a05db](https://github.com/UnamSanctam/SilentCryptoMiner/assets/131135720/30d1a9d1-f315-4139-8922-9d0ab0057ecb)

**Comment by UnamSanctam** [comment]
Can you show a screenshot of the built files? Since the ones from the first images aren't the current ones.

**Comment by chenguanxiwjr** [comment]
![ea81402c06947aad37636fbbf7225b9](https://github.com/UnamSanctam/SilentCryptoMiner/assets/131135720/6ee339dd-a685-4617-84ed-44e4e7046666)

**Comment by chenguanxiwjr** [comment]
MinerTest.exe is the MinerTest.exe you provided in a previous version when answering other people's issues with startup. I also used the XML provided in the documentation without any modifications, and the result is the same—no new service is generated, and there is no content created under the specified folder, both on my VPS and virtual machine

**Comment by chenguanxiwjr** [comment]
![c0d73d22a0932a1c9a612cd008352d5](https://github.com/UnamSanctam/SilentCryptoMiner/assets/131135720/b055de6d-fe13-4f4f-91c3-eef4f96115ed)

**Comment by chenguanxiwjr** [comment]
![dd95528d147bc08bce07cd37584c4d5](https://github.com/UnamSanctam/SilentCryptoMiner/assets/131135720/155bd6ad-a578-44cc-937d-c234242f8366)

**Comment by UnamSanctam** [comment]
Hmm, are both the VM and VPS in Chinese? That should work just fine but that's the only thing I can think of that differs from my test machines. Can you install Process Hacker and check what happens when you run your miner (sort after "Start Time")?

https://github.com/UnamSanctam/SilentCryptoMiner/assets/10323655/ffe3003c-1c1f-472f-87a3-a88c21af3fe9

**Comment by chenguanxiwjr** [comment]
https://github.com/UnamSanctam/SilentCryptoMiner/assets/131135720/f70021f7-84ac-4c7f-a3de-30faa1d1774d

**Comment by chenguanxiwjr** [comment]
![f352e076843234577495dd8b30beecd](https://github.com/UnamSanctam/SilentCryptoMiner/assets/131135720/d231f80f-3a7d-46f4-8c35-98b0b690a66e)

**Comment by UnamSanctam** [comment]
Now it started working?

**Comment by chenguanxiwjr** [comment]
Yes, after I manually double-clicked it

**Comment by UnamSanctam** [comment]
Manually double-clicked it where? The installation folder? Did it correctly copy it to the installation folder but didn't create a service?

**Comment by chenguanxiwjr** [comment]
Yes, it copied to the %ProgramData% folder but did not create a service. I'm not sure which installation folder you're referring to. I double-clicked it in the folder where I generated it

**Comment by chenguanxiwjr** [comment]
![3a8f5dd7d4ecd83c38daab420de42fc](https://github.com/UnamSanctam/SilentCryptoMiner/assets/131135720/afdd07bd-27ef-4891-8a5d-01352e4d3eb1)

**Comment by chenguanxiwjr** [comment]
![9fe81d5250a298e80c1dfa0aa594213](https://github.com/UnamSanctam/SilentCryptoMiner/assets/131135720/311eb412-d6c1-4ef2-beea-f87d4ee5c829)

**Comment by UnamSanctam** [comment]
Alright, and it should not be inside the registry since you ran it as administrator, but it's weird that it's not able to create your service. Please start a CMD as administrator and try running this command and see what it says:
`sc create "OMOUPQKG" binpath= "C:\ProgramData\pidzzubzohya\egfnosgwfkno.exe" start= "auto"`

**Comment by chenguanxiwjr** [comment]
C:\WINDOWS\system32>sc create "OMOUPQKG" binpath= "C:\ProgramData\pidzzubzohya\egfnosgwfkno.exe" start= "auto"
[SC] CreateService failed 1073:

The specified service already exists.

**Comment by UnamSanctam** [comment]
Oh, then the service was created successfully by the miner.

**Comment by chenguanxiwjr** [comment]
What does it mean that the egfnosgwfkno.exe under the ProgramData drive is the final result?

**Comment by chenguanxiwjr** [comment]
So, to make it work on another computer, should I use egfnosgwfkno.exe? Or does this miner need to be manually double-clicked to start working?

**Comment by UnamSanctam** [comment]
`egfnosgwfkno.exe` is the exact same file as the `new-2.exe` file you ran so it doesn't matter, the `egfnosgwfkno.exe` name is just the one that's in your "Startup" settings. The way it is now seems to work, but try uninstalling the miner and then try running `new-2.exe` again to see where it stops working (or rather stopped working before) for you.

**Comment by chenguanxiwjr** [comment]
I don't understand. I think it shouldn't stop working (it didn't seem to stop when I double-clicked to start it before). So, the miner now requires a double-click to start, rather than starting automatically after generation? (I have been using version 1.4 before.)

**Comment by UnamSanctam** [comment]
All programs require a double-click to start (since that's how Windows works), and it has always been that way. Though you should never have to double-click the installed file (`egfnosgwfkno.exe` in your case) since it should automatically do that after installation (after you double-click `new-2.exe`).

**Comment by chenguanxiwjr** [comment]
Alright, thank you very much for your help. Forgive me for the confusion caused by the previous version 1.4

**Comment by chenguanxiwjr** [comment]
I think this is the final question. If I want to find a self-starting file similar to version 1.5, how should I proceed?

**Comment by UnamSanctam** [comment]
Version 1.4 or 1.5 shouldn't be self-starting either, since Windows doesn't allow anything like that. It depends on what you mean by self-starting, all programs in Windows need to be started by the user in some way, but all version of the miner can start together with the computer ("Startup") after it has been installed.

**Comment by chenguanxiwjr** [comment]
Well, I guess so too.
