### ISSUE TITLE
Endpoint

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#2082]
Hello Unam. Recently, some antiviruses began to block miner access to the web panel. A message appears that the IP address is blocked. But I also have a remote configuration and the miner switches to it and works successfully. But why does the antivirus continue to show a message that the IP address is blocked at intervals of less than a minute? After all, when a miner is connected via a remote configuration and is working, does it still very often try to connect to the web panel?

**Comment by UnamSanctam** [comment]
The miner reports to the web panel every minute, which is how you can get the latest statistics of it. Unless you have disabled the web panel then it will still try to connect, since both the web panel and "Remote Configuration" can be used simultaneously. If you set the `"api-endpoint"` to `""` in the "Remote Configuration" then you can disable the web panel calls.

**Comment by masterjek** [comment]
If I disable the web panel via remote configuration, will it disconnect from all miners or only from those that are blocked by the antivirus?

**Comment by masterjek** [comment]
I want to clarify through the remote configuration I turn off the endpoint, it will work like this:
1. All miners will be disconnected from the web panel?
2. Will only those miners whose antivirus blocks access to the web panel be turned off?
Which option is correct?

**Comment by masterjek** [comment]
I did it like this - I’m throwing off a piece:
"kill-targets": ""
"api-endpoint": ""
I saved everything, but still once a minute I receive a warning from the antivirus that the IP address is blocked.

**Comment by UnamSanctam** [comment]
Setting the "api-endpoint" to "" should work once it contacts the "Remote Configuration" the next time, or you could set the "api-endpoint" option to some fake address.

**Comment by masterjek** [comment]
Yes it worked, I just didn't know that the miners had to restart. I just thought everything would work differently - those miners whose antivirus blocks access to the panel will switch to a remote configuration, and those who do not block access will remain in the web panel.
But now absolutely all of my miners have disconnected from the web panel. And now even when I go to the web panel, I get an endpoint error.

**Comment by UnamSanctam** [comment]
The miner does not know that the web panel access has been blocked, so it will continue trying to connect as long as it's told to (as long as it has a web panel URL set). Since you set "api-endpoint" to "" then all miners who use the "Remote Configuration" (all miners who have it set) will disconnect, since the miners use both the "Remote Configuration" and web panel at the same time, it's just that the web panel configuration takes priority.

**Comment by masterjek** [comment]
Thanks for the detailed explanation.
