### ISSUE TITLE
Hey unam when i crypt the miner

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#209]
Should i enable the obfuscator option (from the silent miner) and then crypt the miner ?

the crypter also has obfuscation

**Comment by Brainshot** [comment]
Also is the watchdog the one causing detections should i crypt that too?

**Comment by MR81726** [comment]
hes at work

**Comment by UnamSanctam** [comment]
Answer is a bit late but you can enable the "Pause for Obfuscation" if you wish to obfuscate internal parts in the miner, so if you are only planning on using a crypter then I would recommend crypting both the watchdog loader and the miner loader (not the payloads since they are C# .NET and not native).

**Comment by bloodhunt214** [comment]
How do you reach the watchdog loader and the miner load to encrypt it if i may ask @UnamSanctam , and thanks for the contribution bro

**Comment by UnamSanctam** [comment]
> How do you reach the watchdog loader and the miner load to encrypt also what settings should you turn off(can you use the bypass WD?) when encrypting it if i may ask @UnamSanctam ,thanks for the contribution bro

You can reach those files by enabling "Pause for Obfuscation", you can use "Bypass Windows Defender" just fine, no option really needs to be turned off.
