### ISSUE TITLE
What source code file(s) needs to edit to return back AppData installation?

### ISSUE THREAD

**Issue by sn00rlax** [UnamSanctam/SilentCryptoMiner#2094]
Hello sir,

I have the miner' previous version of source code too, where it was possible to make the miner to install inside User AppData folder, but I'm a total newbie when it comes to coding. So I decided to play with this a bit and hopefully learn some coding from it.

I want to replace the source code for miner installation from the old version to the current one.
Which files inside source code do I need to edit for this? There are so many of them and I don't know what to start with.

Also, what program(s) I need to open and edit them? Such as Visual Studio I guess. Which one for C++? 

I have some feeling that previous version was performing a bit better for me. Because now when it runs as system, the miner do not always start after PC restart/power up. Sometimes it starts, sometimes it doesn't. I was testing it many times on wmvare and can't figure out what exactly is causing that. That's why I would like to test AppData installation with a new improved current version.

Thanks & kind regards!

**Comment by UnamSanctam** [comment]
>I want to replace the source code for miner installation from the old version to the current one.
Which files inside source code do I need to edit for this? There are so many of them and I don't know what to start with.
Also, what program(s) I need to open and edit them? Such as Visual Studio I guess. Which one for C++?

You can use Visual Studio to edit everything in the project. Both C# and C++, though since the C++ files are only embedded then you won't get the full IDE experience when editing them. You will need to install .NET 4.5 to compile it which can be tricky (thanks Microsoft) but there are many guides online.

>I have some feeling that previous version was performing a bit better for me. Because now when it runs as system, the miner do not always start after PC restart/power up. Sometimes it starts, sometimes it doesn't. I was testing it many times on wmvare and can't figure out what exactly is causing that. That's why I would like to test AppData installation with a new improved current version.

You can already install it to AppData if you don't run it as administrator, just like how it's been before. Or do you mean that you want it to install using the Task Scheduler instead of as a Service? In that case you'll need to copy over quite a bit, since you'll need to include the template files to extract and such (to avoid having to use powershell since it can cause AMSI detections). You can see all the changes that were made in the commit: https://github.com/UnamSanctam/SilentCryptoMiner/commit/c61e842d5ec04e2493a83f54f096ba2f3b95687d.
The important parts are the DefStartup parts and also the installation checking that the watchdog does.

**Comment by sn00rlax** [comment]
Hi,

Thank you for your answer! 

The thing is, if we don't run it as administrator, then adding to WD exclusions won't work, same as disabling WindowsUpdate and blocking websites right? And if we run it as admin with the current version, then it goes to ProgramData and running as system.

So, with the current version, it's not possible to install it as administrator, but run it as a Service (Task Scheduler) correct? 
I will have to replace this code from the old version? 

Also one more thing I've noticed with running as system is that inside the WebPanel, "Active Window" tab shows "Running as System". Before we could see what window they have opened at the moment. With analyzing this information we can improve Stealth Targets for the miners because we can track what games are they playing so we can add them to Stealth Targets. With running as system we cannot see this.

**Comment by UnamSanctam** [comment]
>The thing is, if we don't run it as administrator, then adding to WD exclusions won't work, same as disabling WindowsUpdate and blocking websites right? And if we run it as admin with the current version, then it goes to ProgramData and running as system.

Yes that's correct, in the previous versions it has installed into ProgramFiles with the Task Scheduler. Then now it changed into ProgramData with a Service since that was much more undetected.

>So, with the current version, it's not possible to install it as administrator, but run it as a Service (Task Scheduler) correct?
I will have to replace this code from the old version?

Yes that is correct.

>Also one more thing I've noticed with running as system is that inside the WebPanel, "Active Window" tab shows "Running as System". Before we could see what window they have opened at the moment. With analyzing this information we can improve Stealth Targets for the miners because we can track what games are they playing so we can add them to Stealth Targets. With running as system we cannot see this.

Yes because the System user does not have any open windows, and cannot see what windows the other users have open. But that was the same in the old versions, since you should always have had "Run as System" enabled anyways. Without running it as System then the miner cannot run on all users, you can make it run on **only** the administrator user which will make it show the "Active Window" but it also means that the miner will not run if any other users than the administrator logs in.

**Comment by sn00rlax** [comment]
Thanks a lot for the explanation!
