### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by GkyEla** [UnamSanctam/SilentCryptoMiner#2117]
Hey unam thanks for amazing work, is there any new version coming soon with more effective source code for windows defender also avira. Thanks

**Comment by Alcinzal** [comment]
I am not sure if Unam is working on a new version, and I am also not completely sure what you mean by "effective source code for windows defender also avira", but if you mean that you want the miner to stay undetected from Windows Defender and Avira, then you will have to use a crypter. Since this is public code, it will always end up getting detected by most antiviruses, no matter how many times Unam updates it.

**Comment by GkyEla** [comment]
iknow ihave crypter i just wanted to know that new features coming or not like new algos and integrated simple obfuscater
