### ISSUE TITLE
Code question

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#2125]
Hello Unam. Please tell me. Is it possible in the code to change the priority of which configuration the miner accesses? The configuration from the builder comes first, and then all the rest. If I use version 3.2.0.
If the miner successfully connected to the configuration specified in the builder, then why does it continue to connect to the web panel, and if it does not, then with the remote configuration.

**Comment by UnamSanctam** [comment]
No there's no way to change that in the code, but I don't really think doing it that way would be desirable. Since doing that would mean that you can **never** change the pool configuration no matter what you enter in the web panel or "Remote Configuration" as long as the builder pool still works (which will probably be a very long time).
