### ISSUE TITLE
Question / Request

### ISSUE THREAD

**Issue by Forsy** [UnamSanctam/SilentCryptoMiner#2145]
Hello!

Is there any way to obtain the actual shellcode that is injected? Ethier by modifying the programa bit or some feature I did not find. It would be usfull for times where you wanna make a custom implementation of it in order to bypass secutity measures.

Many thanks!

**Comment by UnamSanctam** [comment]
Depends on what you mean, do you mean the xmrig.exe and ethminer.exe? If so then sadly no I do not have public repositories for them yet, for the large part due to me not having enough free time to maintain two more repositories. If you mean the rootkit then you can find the one used here: https://github.com/bytecode77/r77-rootkit.

**Comment by Forsy** [comment]
Yeah i ment the xmrig.exe, I guess i can try twaking things up and see if i can get it no worries. Thanks!
