### ISSUE TITLE
Trying to become a doveloper

### ISSUE THREAD

**Issue by A3ima** [UnamSanctam/SilentCryptoMiner#215]
Hi UnamSanctam, as i have seen your projects and played around with them it encouraged me to create my own applications like this.

i was wondering if i can i have a understanding of why u used C#,C and visual basic .NET and if u could have used another language to make this application. and what is OOP when i got on forums it shows up when someone is comparing the different types of C's

and what's the difference between C,C# and C++ and what is .NET/Core and what is visual basic .NET? and I heard a language called react, is it a substitute?, is it better than all the types of C's.

and if i were to learn how to make applications like this which language/s would u recommend?

and which Udemy/courses do u recommend?

note that I'm ready to spend 4 to 7hrs a day to learn how to code so don't hold back on any information that could be useful to me.

thanks UnamSanctam!

**Comment by UnamSanctam** [comment]
Hello,

Just a caution, I will try to simplify a lot of the things I write here to try and make it easier to understand so everything might not strictly be correct.

Firstly, OOP is object-oriented programming which you can read about more here: https://en.wikipedia.org/wiki/Object-oriented_programming, but generally most commonly used programming languages are OOP languages. C isn't an OOP language (though you can technically still write OOP code with structs and such) while C++ and others are.

C# (or VB) is used for the builder since it greatly reduces the work required to create the GUI and allows fast development due to it's simplicity because of the .NET framework features, though of course it has the downside of requiring .NET framework to work but the majority of computers have it. It's the same reason why it's used for the miner installer, injector and watchdog, it's a lot easier to work in and has a lot of built in features, it also allows people to modify the code for their own usages (such as adding a Discord webhook) really easily. Another big reason that I don't use C++ for the miner installer, injector and watchdog is that there aren't really any small portable C++ compilers that I could use in the builder for compilation, so either I'm stuck with using C (the TinyCC compiler) or using C#, if I could use C++ I would personally rather use it instead of C# for the miner parts.

The miner itself (and nearly all other miners) is made in C/C++ since it's a lot faster than high-level languages like C# that are ultimately  run using a JIT compiler. C/C++ is a programming language that (usually) gets compiled into machine code and directly "run" when running the executable that gets "created" while C# is a programming language that gets built into a managed assembly (in an intermediate language) that when run gets interpreted by the .NET VMs JIT-compiled which compiles it into machine code. So the C# code requires an intermediate step (.NET) to run so it's not always good to use. Visual Basic is technically just another .NET language like C#, it's more like a simpler version of C# and isn't used very often anymore.

React isn't a programming language but a JavaScript (programming language) library used for front-end web development, JavaScript isn't really in any way comparable to C/C++/C# since they usually serve completely different purposes.

For software GUI I personally prefer C# WinForms (though Microsoft wants everyone to move to WPF) but there are tons of different GUI libraries for all types of programming languages. But for actual functional software programming I always prefer C or C++.

Personally I haven't really used any courses or anything except maybe watching YouTube tutorials many many years ago, I mostly learn by just taking something and starting to work on it, either a new project or by modifying a already exciting project I can find to suit whatever I want to create. But everyone prefers different things so it's best to find your own niche or what you think is the most fun. I have always been programming just because it's fun though so a lot of my thoughts might be biased towards that viewpoint compared to something that might program for another reason. I would then talking from experience recommend watching something like a YouTube tutorial video series about programming something that you personally enjoy. For example some kind of program, some kind of game modding, maybe mobile apps if you like that, maybe websites though you would not really use any software languages for that.

My favorite languages are by far PHP, C, C++, C# and Java (nostalgia) and those are what I spend most of my free time (and work) programming in and thus that is what I recommend, but everyone likes different things so your tasted might be wildly different from mine.

**Comment by A3ima** [comment]
so u recommend that i take courses on c# and use its WinForms and learn how to code in c++ to? do u think that WPF is better I have used WPF but very little so I don't have much understanding of it

**Comment by UnamSanctam** [comment]
For something like this, a miner or something close to it then C++ would be required for the actual software yes, then you can make the GUI for the builder or whatever else you'd need in anything that supports GUIs but personally I prefer C# using WinForms, I don't really like working with WPF. But WPF is what Microsoft likes a lot more and thus has more "features" like more customization (though that's not always a positive) but it also has a lot more restrictions on what you can really do on a deeper level.

**Comment by A3ima** [comment]
i have taken a like towards python and am doing courses on them but i know that c++ is more capable of creating apps like this miner as python is not used to create apps like these, though i have heard of some libraries u can add to make guis like tkinter but tkinter is not meant for design as when i try to make good looking apps with it they just end up looking bad

**Comment by A3ima** [comment]
just pirated a $200 c++ course but cant find any c# course :/
