### ISSUE TITLE
GPU Miners not appearing on pool

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#2183]
I use the pool https://moneroocean.stream/

I have set a different worker name for the GPU miner than CPU miner 

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/77803435/4464b2d2-e460-4f1b-bf9f-4f3cca720703)

they are mining, but it doesnt appear on the pool at all it has been mining for a few days already and i just opted to use the webpanel to see what's going on

Can you please help

**Comment by UnamSanctam** [comment]
The miner doesn't appear or the worker doesn't appear? And do they have static worker names (not something like {COMPUTERNAME})?

**Comment by shainodev** [comment]
> The miner doesn't appear or the worker doesn't appear? And do they have static worker names (not something like {COMPUTERNAME})?

The worker doesn't appear, they have static worker names

**Comment by UnamSanctam** [comment]
Is it a valid worker name? And are any workers being shown?

**Comment by shainodev** [comment]
The CPU ones are mining and the CPU worker names are being shown, just not the GPU ones, maybe its too little of a hashrate?

**Comment by UnamSanctam** [comment]
Hmm, the hashrate should be enough. I actually don't know what the difficulty MoneroOcean sets for KawPow miners (it depends on the port but I don't know how it converts to KawPow), so it's possible that that is the issue. You can try a lower port for the GPU miner and see if it appears in the pool.

**Comment by UnamSanctam** [comment]
Here are all their different ports, I don't know how their difficulties scale to KawPow (since it's in megahashes).

- 80 (SSL 443): 100 diff (1-5 h/s)
- 10001 (SSL 20001): 1000 diff (5-50 h/s)
- 10002 (SSL 20002): 2000 diff (50-100 h/s)
- 10004 (SSL 20004): 4000 diff (100-150 h/s)
- 10008 (SSL 20008): 8000 diff (150-300 h/s)
- 10016 (SSL 20016): 16000 diff (300-500 h/s)
- 10032 (SSL 20032): 32000 diff (500-1000 h/s)
- 10064 (SSL 20064): 64000 diff (1000-2000 h/s)
- 10128 (SSL 20128): 128000 diff (2000-4000 h/s)
- 10256 (SSL 20256): 256000 diff (4000-8000 h/s)
- 10512 (SSL 20512): 512000 diff (8000-20000 h/s)
- 11024 (SSL 21024): 1024000 diff (20000-40000 h/s)
- 12048 (SSL 22048): 2048000 diff (40000-80000 h/s)
- 14096 (SSL 24096): 4096000 diff (80000-160000 h/s)
- 18192 (SSL 28192): 8192000 diff (160000+ h/s)

**Comment by shainodev** [comment]
what do u recommend me to put

**Comment by UnamSanctam** [comment]
You can try with a low port just to see if it appears in the pool.

**Comment by shainodev** [comment]
still doesnt work

**Comment by UnamSanctam** [comment]
And you're using something like port 10001 or 20001?

**Comment by shainodev** [comment]
yes

**Comment by UnamSanctam** [comment]
It could possibly be that MoneroOcean is sending some weird job structure to you, I know it has happened with MoneroOcean before.

**Comment by shainodev** [comment]
how could i fix this tho?

**Comment by UnamSanctam** [comment]
If that's the cause then best would be to mine on another pool, either it's temporary or I need to change something in the job handling. The same thing happened a few months ago when they added or changed some part of what they wanted when sending completed shares to the pool.

**Comment by shainodev** [comment]
Is there another pool which sends to XMR but mines something else?

**Comment by UnamSanctam** [comment]
Zergpool, not sure about others.

**Comment by shainodev** [comment]
does it ban?

**Comment by UnamSanctam** [comment]
I don't know actually, I haven't gotten any reports of it but I don't know of many who mine there.
