### ISSUE TITLE
Miner not starting (no sign of live)

### ISSUE THREAD

**Issue by schieferzahn** [UnamSanctam/SilentCryptoMiner#2278]
When i use the example settings or any other settings (i already tried everything) the miner wont start.

All av is off and when i start it nothing happens, it doesnt even ask for administrator (even though i have enabled it)
When i run the checker it also finds nothing.

 when i try search for something in /programmfiles/google/chrome it says directory not found.

pls help i already tried everything but nothing works...

**Comment by UnamSanctam** [comment]
On some computers there's a bug with powershell whenever there's a space in the filename, if you do have a space then try removing it then try again.

**Comment by schieferzahn** [comment]
finally it works thank you so much. it was because of the name. why is that?
but  for some reason the cpu usage is only around 40% even though i have idle mining turned off

**Comment by UnamSanctam** [comment]
On some computers the current "Run as Administrator" powershell command doesn't work due to a bug when there's a space (it doesn't escape correctly). What do you have "Max CPU" set to? That's how much it will use. It's also possible that only 40% of your CPU cores are available though that's not usually the case. And if you're using the example settings with "Stealth" still enabled then the miner will pause (to hide) when any program in the "Stealth Targets" are open, which includes the Task Manager and a few others by default.

**Comment by schieferzahn** [comment]
I have stealth and idle mining completely turned off and nothing else except task manager is running

**Comment by UnamSanctam** [comment]
And what's Max CPU set to? If you check using the checker.

**Comment by UnamSanctam** [comment]
Yes, then yours is set to use 20% CPU, though if you have less cores then it will use more since it will use 20% of the cores (rounded up). For example if the CPU has 4 cores then the minimum possible usage is 25%, for a CPU with 2 cores the minimum possible would be 50% (1 core).

**Comment by schieferzahn** [comment]
but how do i change that i had idle mining disabled

**Comment by UnamSanctam** [comment]
Which is why it's not idle mining, the amount of CPU to use when not idle mining is what "Max CPU" does.

**Comment by UnamSanctam** [comment]
Yes if you set "Max CPU" to 100% then it will try to use as many cores as it can, though it will still yield to other programs to not cause any lag (that can be disabled though usually not very good to do).

**Comment by schieferzahn** [comment]
and about the rootkit what do you mean by it can break some stuff on computers?

**Comment by UnamSanctam** [comment]
It's a rootkit, so it will inject into multiple Windows processes and try to modify their behaviour. Since it does that then there's a chance that weird things can happen or possible even crashes (though that's not common). Any amount of different things could happen, though mostly background things.

**Comment by schieferzahn** [comment]
And turning off windows defender is nececarry right? because no matter what i do it keeps getting detected.

**Comment by UnamSanctam** [comment]
Yes that's preferable, normally exclusions will stop the detections though updates can always change something.

**Comment by schieferzahn** [comment]
its almost impossible to turn off defender without admin...

**Comment by UnamSanctam** [comment]
Yes of course, otherwise that would be a huge security flaw. Though you can use UAC bypasses.

**Comment by schieferzahn** [comment]
i will try my best do you want to know if i succed?

**Comment by UnamSanctam** [comment]
Sure if you're willing to.
