### ISSUE TITLE
RandomX performance 

### ISSUE THREAD

**Issue by IgorAlaf** [UnamSanctam/SilentCryptoMiner#2282]
Hi,I have question.how is the performance percentage determined if randomX always uses 2 gb of RAM,or am I wrong?Let’s say if I set 25% of the miner’s power,then it will simple use not 4 processes but one?I have processor with 4 cores.Sorry for my English,I haven’t dug into the code yet,but if I don’t get answer ,I ‘ll have to read it.thanks

**Comment by UnamSanctam** [comment]
Yes, the percentage is the amount of CPU cores to use, so at 25% it would use 1 out of your 4 cores. As you said RandomX requires 2GB of RAM to be able to mine, which can't be decreased due to how the algorithm is designed (it's made that way to stop GPUs and ASICs from mining it efficiently, since it's designed as a CPU coin).

**Comment by IgorAlaf** [comment]
Thanks,but this is easily detected, no?, when 2 GB of memory is taken from a person? Does this greatly affect the performance of the entire hardware? If we say >= 10gb ram

**Comment by UnamSanctam** [comment]
Only if they have a low amount of RAM, and RAM allocation never affects performance as long as your RAM is not maxed at 100%. And when you have "Stealth" enabled in the miner then when any program inside the "Stealth Targets" is open, such as the Task Manager then the miner will pause and no RAM (or CPU) will be used while it's paused.

**Comment by IgorAlaf** [comment]
I get it,bro,thanks
