### ISSUE TITLE
miners fallback strategy

### ISSUE THREAD

**Issue by emmalaporte93** [UnamSanctam/SilentCryptoMiner#2309]
Hi Unam, firstly, thanks for making this great project open source, we all appreciate it :) 

I wanna know how exactly scm dealing with multiple mining configs; was trying to find answer in wiki and other issues but failed

Say, I have mixed set of workers with both old and new GPUs. I want to add RVN as 1st coin for GPU, then smth like XNA or other coin with smaller DAG size to be able to use weaker GPUs, also few different pools for each coin in case if specific pool is n/a because of WAF

Can scm  handle this requirements? Will it detect weaker GPU and switch from 1st RVN worker to 2nd and so on?
Thanks!

**Comment by UnamSanctam** [comment]
Essentially the miner can store three different configurations in its memory, one from the builder settings, one from the "Remote Configuration" and one from the web panel configuration. The miner does not move on to the next configuration in the case of not enough VRAM to mine (since that might not be what someone wants) though it does move on to the next configuration if the pool does not work.

Changing the configuration if the free VRAM isn't enough would likely be done through the UnamWebPanel, for which one could code a specific configuration it should try if the miner has the "Not enough free VRAM" status. Though that does mean that you'd need to host a web panel that the miners connect to.

**Comment by emmalaporte93** [comment]
Ok got it, I will consider having panel :)
