### ISSUE TITLE
Question for Xmrig Proxy 

### ISSUE THREAD

**Issue by Untorest** [UnamSanctam/SilentCryptoMiner#2367]
This pictures are from #1682 about setting up Xmrig Proxy in VPS
![Screenshot_2024-04-30_045307](https://github.com/UnamSanctam/SilentCryptoMiner/assets/157064340/8da27387-511f-4771-b39c-b178ae625922)
![Screenshot_2024-04-30_045325](https://github.com/UnamSanctam/SilentCryptoMiner/assets/157064340/f73b1c48-c51c-4153-9916-15967c724349)
According to this guide, should change config of xmrig proxy, host it in VPS and input "IP address of my VPS server:port" in the "pool" instead of something like xmr.2miners.com:12222

The question is, Then what if the VPS become dead while hosting xmrig proxy, how will it affect on the miners? Because they will lose the pool address because the VPS is dead. 

In that situation, if I get new VPS, host xmrig proxy in the new one and edit the config of pool address to "New VPS IP address:port"in the "Web Panel",
Would the miners I connected when i was hosting the old VPS keep working well with the new Pool address(New VPS IP:Port)? Or would they become disconnected forever becuz they once lost pool address for a while?

**Comment by UnamSanctam** [comment]
If your VPS dies then the miners won't be able to connect to that of course, so they will default back to their builder configuration. But if you do change either the "Remote Configuration" or web panel configuration to the new VPS then they will connect to that instead. As long as you don't lose both your "Remote Configuration" and web panel you can always change the configuration of the miner. It's usually recommended to set a normal pool configuration in the builder so that there's always a final backup "real" pool connection, and then set your xmrig-proxy pool connection in the "Remote Configuration" and/or web panel. Since if you do this then even if your "Remote Configuration", web panel and VPS gets taken down then the miner will still mine to your normal pool configuration that your entered when building it.
