### ISSUE TITLE
Compiler Folder and Main Build

### ISSUE THREAD

**Issue by UpChurchDirt** [UnamSanctam/SilentCryptoMiner#2372]
Why is there a UCompilers folder in finished build output?

Do I only bind the main miner build?

After this is resolved if I decide to crypt should I crypt the build or crypt file post bind?

#                         -Dirte

p.s. I tried executing the miner in a VM and nothing happened at all.

p.p.s. I tried to see if folder was needed to execute but when ran in UniExtract it stated the file type was unknown and might not be an Inoo executable. I've tried reading the code but have no background in C so it was past my ability by miles.... Any thoughts? I'm gonna try a debugger and a few other things while waiting for response but not sure how lucky I'll be on my own.

Sorry so short and  unfriendly sounding. I had a well written detailed post typed out and github wiped it when posting photo and didn't have copy history turned on. 

Anyways, I appreciate you taking the time to read regardless and that much more if you decide to respond.

![Test](https://github.com/UnamSanctam/SilentCryptoMiner/assets/168809483/101fdca2-1dd8-4045-af93-f100fd9cf0bf)

**Comment by Alcinzal** [comment]
Hey, I am not totally sure what UCompilers is, but I assume it is a folder where the builder will place temporary files and compilers to create the finished 3 executable files. Here is an explanation of the 3 executable files:

* Test.exe: This is the main miner, this is the one you would want to crypt and spread. 
* Test-checker.exe: This is simply a program you can use to see if the miner is running and what the current settings are. 
* Test-uninstaller.exe: This will stop the miner process and will revert any changes that Test.exe has made, except for a few things, like if "disable sleep" is enabled, uninstaller will be unable to revert it back to normal, since it doesn't know your sleep original settings.

What type of VM did you try running it in? I have successfully ran my miner inside a QEMU/KVM, everything worked fine for me. And no that UCompilers folder is not needed for the Test.exe file. Nothing is needed for the exe file to work except for a Windows 64-bit system.

**Comment by UnamSanctam** [comment]
The UCompiler contains the C++ compiler and a few other programs needed to compile the miner, and yes only the main miner build (Test.exe) needs to be cypted, whether to crypt it before binding or not it's usually the best to crypt it both before binding it and after (since your binder might not be undetected). @Alcinzal also explained what the files do in a good way. After running Test.exe inside your VM try running the checker and see if a miner is listed inside it.

**Comment by UpChurchDirt** [comment]
Awesome. Thanks thanks for the replies.
