### ISSUE TITLE
#136 

### ISSUE THREAD

**Issue by HIDDEN-MINER** [UnamSanctam/SilentCryptoMiner#244]

**Comment by HIDDEN-MINER** [comment]
please throw off the source code of Etherium + etc (the miner itself)

**Comment by HIDDEN-MINER** [comment]
не могу найти просто исходники, а темы 136 нету

**Comment by HIDDEN-MINER** [comment]
ethminer 0.21 Please

**Comment by Nobellium1** [comment]
Also please respond to "Custom order"

**Comment by UnamSanctam** [comment]
@HIDDEN-MINER I also wrote it in your other issue but I've already linked what I've said before about it (UnamSanctam/SilentETHMiner#136), currently I don't have time with more repositories since I'm already behind on the updates I want to do for the 4 actives ones I have right now.

> Also please respond to "Custom order"

Yeah I responded.

**Comment by HIDDEN-MINER** [comment]
☹

**Comment by CarloPonxi** [comment]
He is a man working tirelessly on a project that has marked history, that makes him a genius like Einstein... for free (some time ago I asked a developer who charges 10% of your hash speed if it was possible to make an ETH miner, and he told me that it was not possible Unam made it possible). Everything he has shown has been free, many times I told him not to share his source code because there are those who are going to use it to get rich, right now there are those who sell versions of this miner at 100 USD for each license, that's not right, don't you think? I hope you don't share the code, because I'm sure friend, you're going to get a lot of money out of it, and that's not right.

A simple user does not need the source code of the miner brother.

**Comment by HIDDEN-MINER** [comment]
bro is not for sale to me - I want to try to add a lot of points on bypassing the blocking of video cards and not only

**Comment by CarloPonxi** [comment]
Work with him then, don't ask for source code of his intellectual property. My thoughts, sorry to interrupt

**Comment by CarloPonxi** [comment]
By the way... Merry Christmas and Happy New Year Unam. You know I don't like to comment here, but I have no other way to say thanks and give you my appreciation.

Thanks for your hard work!
