### ISSUE TITLE
The best settings for a .net encryption

### ISSUE THREAD

**Issue by dingodingo2** [UnamSanctam/SilentCryptoMiner#260]
So I heard that I needed to disable Shellcode. But is there anything else ? I cant get it to work once encrypted. Thanks :)

**Comment by UnamSanctam** [comment]
Disabling "Shellcode Loader" is all you need for it to be .NET, if your obfuscator isn't working then turn off resource encryption in your obfuscator if there is one since the miner already has the resources encrypted.

**Comment by dingodingo2** [comment]
Okay it worked! And last question is there a way to change the miner name? Like giving him a random name? If you have a solution 💯

**Comment by UnamSanctam** [comment]
Depends on what you mean, miner name meaning the .exe filename or miner name meaning the worker name on the pool?

**Comment by dingodingo2** [comment]
Yeah sorry I mean the worker name.

**Comment by UnamSanctam** [comment]
Yes there are three different implemented ones you can use, 1) `{COMPUTERNAME}` which will use the computers name as the worker name, is usually the most reliable. 2) `{USERNAME}` which will use the username, is usually less unique than computer names. 3) {RANDOM} which will randomize the worker name on each run, due to it randomizing on every run it's the most unique but will not be persistent so monitoring can be more difficult.

**Comment by dingodingo2** [comment]
Thanks man :)

**Comment by Gopnitsa** [comment]
> Thanks man :)

Hİ how you make encryption to the miner can you explain to me ? İ really need help.  my discord adress : Gopnitsa # 01 16
