### ISSUE TITLE
All miners are offline

### ISSUE THREAD

**Issue by freeze2222** [UnamSanctam/SilentCryptoMiner#320]
Web panel says that all my 28 miners are offline and were online only one time when were installed. It seems that autorun doesnt working because I ran miner on my pc and all was ok but now it say that I am offline. So strange. I dont think that 28 people didnt use their pc for one week :/

There are no AV on my pc.

Help pls :(

**Comment by UnamSanctam** [comment]
You'd have to send your settings here for me to check.

**Comment by gawad123** [comment]
I have a similar problem, the miner starts and works well, but after restarting the computer it stops working, I tested on several computers with different configurations and everything starts fine, and after restarting the computer does not start, I tried different combinations of settings which you have advised others who have had similar problems but does not work

(sorry for my english)

**Comment by UnamSanctam** [comment]
> I have a similar problem, the miner starts and works well, but after restarting the computer it stops working, I tested on several computers with different configurations and everything starts fine, and after restarting the computer does not start, I tried different combinations of settings which you have advised others who have had similar problems but does not work
> 
> (sorry for my english)

Can you try the Example Settings at the top of the wiki (https://github.com/UnamSanctam/SilentCryptoMiner/wiki) and see if that happens?

**Comment by gawad123** [comment]
> > У мене схожа проблема, майнер запускається і працює добре, але після перезавантаження комп'ютера перестає працювати, я тестував на кількох комп'ютерах з різними конфігураціями і все запускається нормально, а після перезавантаження комп не запускається, пробував різні комбінації налаштувань який ви порадили іншим, хто мав подібні проблеми, але не працює
> > (перепрошую за мою англійську)
> 
> Чи можете ви спробувати приклад налаштувань у верхній частині вікі ( https://github.com/UnamSanctam/SilentCryptoMiner/wiki ) і перевірити, чи станеться це?



> > I have a similar problem, the miner starts and works well, but after restarting the computer it stops working, I tested on several computers with different configurations and everything starts fine, and after restarting the computer does not start, I tried different combinations of settings which you have advised others who have had similar problems but does not work
> > (sorry for my english)
> 
> Can you try the Example Settings at the top of the wiki (https://github.com/UnamSanctam/SilentCryptoMiner/wiki) and see if that happens?
So I tried it too, the only thing that changed the first algorithm on Ghost Rider, maybe a problem in computers, I will now attach the configuration file that I made

**Comment by gawad123** [comment]
> > I have a similar problem, the miner starts and works well, but after restarting the computer it stops working, I tested on several computers with different configurations and everything starts fine, and after restarting the computer does not start, I tried different combinations of settings which you have advised others who have had similar problems but does not work
> > (sorry for my english)
> 
> Can you try the Example Settings at the top of the wiki (https://github.com/UnamSanctam/SilentCryptoMiner/wiki) and see if that happens?

So I tried it too, the only thing that changed the first algorithm on Ghost Rider, maybe a problem in computers, I will now attach the configuration file that I made

**Comment by gawad123** [comment]
just updated Windows on all laptops, started your configuration after starting everything worked rebooted the computer and everything stopped working, allivi all shut down
![Uploading IMG_20220122_173030.jpg…]()

**Comment by gawad123** [comment]
Surprisingly, the process does not add to the "Task Scheduler", that the miner itself works but does not restart for a while, then did a few days then stopped the configuration were different, all with administrator rights. And I do not know how to solve it since I just tried with your configurations and did not change anything, even the wallet, and I see this problem occurs regularly, and what is possible and the status in the web panel offline

**Comment by UnamSanctam** [comment]
Are you saying that the miner is not added into the "Task Scheduler" for you?

**Comment by gawad123** [comment]
> Are you saying that the miner is not added into the "Task Scheduler" for you?

it seems I understood but I do not know how to fix, I have 2 users 1 administrator, and the other does not run from "Task Scheduler", it is performed only if you log in to the administrator then it will work, and if you run on a normal user with administrator rights then in this case turning on the computer will not start

**Comment by gawad123** [comment]
this is if the miner is run from a user (who does not have administrator rights)

then after restarting the miner will not start, it will start only when the login is valid from the user (the administrator who gave permission to run the program)

can this be fixed? because in the manual settings in "Task Scheduler" you can select "Run for all users" or it is possible to fix it in the code

**Comment by UnamSanctam** [comment]
Yes unfortunately that's how Windows works, a programmatically added Task Scheduler task cannot run for all users. Though it can technically be done if the task is added to run under the "System" user, but this causes things like "Idle Mining" and other things to stop working (and isn't really fixable) due to how Windows works. Only other method to run something on startup for all users is to use the registry, but the registry cannot start programs as administrator (but requires administrator to be added to all users) so it wouldn't be possible to use the registry for programs that requires administrator privileges to run.

**Comment by Gopnitsa** [comment]
![111](https://user-images.githubusercontent.com/96687176/150680840-ae5c2885-856b-4da9-8df2-9bc7e547b141.jpg)

I have Same Error. some people run it with no issues at all. Do you know how they do

**Comment by UnamSanctam** [comment]
Check the "Last Connection" time of your miners to know when they last went online. To know how long they've on average been offline.

**Comment by FireHack7z** [comment]
Me top 700 miner offline
