### ISSUE TITLE
mining raptoreum

### ISSUE THREAD

**Issue by haunted199** [UnamSanctam/SilentCryptoMiner#323]
Hello. Is it more efficient to mine on a CPU or GPU?

**Comment by UnamSanctam** [comment]
Only mine it on a CPU, for GPU mine GPU coins like ETH/ETC (or others).

**Comment by Lanikai-B** [comment]
I've been unable to figure out how to mine it on Moneroocean. I figure I definitely want to mine it over monero considering how little profit monero gives compared to rapt.

`{
    "algo": "gr",
    "pool": "us-or.moneroocean.stream",
    "port": 10128,
    "wallet": "**_<my wallet>_**",
    "password": "",
    "nicehash": false,
    "ssltls": "false",
    "max-cpu": 40,
    "idle-wait": 1,
    "idle-cpu": 90,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,GPU-Z.exe,Autoruns.exe,adwcleaner.exe,CCleaner64.exe,Malwarebytes.exe,MSIAfterburner.exe,GTA5.exe,ModernWarfare.exe,Warframe.x64.exe,RainbowSix.exe,TslGame.exe,FortniteClient-Win64-Shipping.exe,r5apex.exe,VALORANT.exe,PortalWars-Win64-Shipping.exe,left4dead2.exe,DeadByDaylight-Win64-Shipping.exe,RocketLeague.exe,Overwatch.exe,vrserver.exe,nvcplui.exe,vrmonitor.exe",
    "kill-targets": ""
}`

According to their FaQ that should work, do you have any ideas? Or an alternative pool to use for rapt? Thanks.

**Comment by UnamSanctam** [comment]
For MoneroOcean you should enter the algorithm into the "password" field as well after the workername, so enter `workername~ghostrider` into the "password" field. Their pool does also have some issues sometimes when "algo" isn't "rx/0" so change it to that (`"algo": "rx/0",`), it won't matter since it'll read the algorithm in the "password" field instead.

**Comment by Lanikai-B** [comment]
![image](https://user-images.githubusercontent.com/95944334/151893350-50ddbb87-413d-455a-9ba9-e9365272555b.png)

Here's what the checker resulted in. I left it to run overnight, but the pool reported receiving no shares. I assumed "workername~" was to be replaced so I tried the variable, potentially that messed it up?

**Comment by UnamSanctam** [comment]
Use algo "rx/0" (RandomX), the MoneroOcean pool seems to not work if you use the "gr" (GhostRider) algorithm directly for some reason.

**Comment by Lanikai-B** [comment]
Ahhh I kept trying to change it in the json output text but that obviously didn't stick, but I didn't think to change the algo as a whole when setting up the miner module. I'll give that a shot.

**Comment by Lanikai-B** [comment]
> Use algo "rx/0" (RandomX), the MoneroOcean pool seems to not work if you use the "gr" (GhostRider) algorithm directly for some reason.

Seems to have worked, though considering I read Rapt is far more profitable than Monero, I'm not sure it's.. working? It's difficult to tell because they seem to just convert whatever you mine to a monero balance. 

Potentially should I use a different pool that more "officially" supports it? Any advice appreciated, thanks again Unam

**Comment by UnamSanctam** [comment]
Yes it calculates the GhostRider hashrate into the RandomX (Monero) equivalent because you can mine multiple different algorithms at once (and MoneroOncean always pays you in XMR) but you can see the original hashrate if you change it from "Pay" hashrate to "Raw" hashrate. If you want Raptoreum instead of Monero then you'll need to use a real Raptoreum pool yes but the direct profit will still be the same, what can differ is if you hold whatever coin (XMR/RTM) then that coin can rise or fall in price.
