### ISSUE TITLE
How work setting in WebPanel

### ISSUE THREAD

**Issue by kokoulin** [UnamSanctam/SilentCryptoMiner#327]
How often is data retrieved from the API?
I see that no matter what config I set for the miner, the miner works with the config set during the build.

The miner works, I see its hashrate in the panel, but when I change the settings, I see the settings in checker.exe that I set during the build

FYI in the builder in the json field after setting there is no ```wallet``` field

**Comment by UnamSanctam** [comment]
It connects to the API every minute, if it's not changing the data shown in the web panel (pool/wallet) then some of your settings are wrong so it's using the backup settings instead (what your entered in the builder).

 The checker.exe shows the command line arguments, meaning they will never change no matter what (since that's how they work), they are only the settings that the miner is started with, they then get changed inside the program itself.

I hotfixed the `wallet` field maybe a week ago or earlier so if you redownload the latest builder then it should be there.
