### ISSUE TITLE
How strong is the raptoreum mining usage?

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#339]
for CPU is it same as Monero mining? for example the lagging and all that

**Comment by Brainshot** [comment]
at 50% will users experience bad lag? even on a good pc

**Comment by UnamSanctam** [comment]
Well CPU usage usually doesn't lag much, I can run the Monero miner at 100% (only uses idle cores anyways so it only uses maybe 50%) without noticing anything. Though on VMs things can lag since they're usually only allocated 1 or 2 cores, but any normal user won't have 1 or 2 cores. But Raptoreum usually doesn't really use any RAM like Monero which means it's a bit more hidden.
