### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by marbletissue** [UnamSanctam/SilentCryptoMiner#34]
Firstly, awesome build dude. Really good job with this and all your tools.
Questions:
- If a deployment tool is used to install the miner on several devices, does the idle detection look for mouse/keyboard activity of the admin account used to install it, or the active logged on user?
- Secondly, does the miner rely on an active logged on user, or does it run as a service regardless of a user logged in or not?
Thanks!

**Comment by UnamSanctam** [comment]
In Windows you can only do idle detection through the active session (the user that starts it), that's the limitation of the Windows API, so it will and can only look at the logged in users idle activity.

It relies on the actively logged in user for that same reason, if it ran as a service (runs as System) then it would only be able to check the idle status of the System user, which is why I doesn't. Of course I would want it to do that but I have not been able to create any good idle detection outside of the Windows API (to allow detections from all sessions) since you need to inject something like a DLL into every program and check the idle activity that way.

**Comment by marbletissue** [comment]
I see, is this what you are referring to when you say Windows API? (https://docs.microsoft.com/en-us/windows/win32/taskschd/task-idle-conditions)
I wonder if there is a tool available which offers complete system idle detection which you can integrate with this program.

**Comment by UnamSanctam** [comment]
No, https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getlastinputinfo is used and is the only way to do it that I'm aware of. Windows does not want you to detect system wide idle so they do not have any built-in API calls to do so.

**Comment by UnamSanctam** [comment]
They have done it that way for security reason and any way to bypass it would be to find some "exploit" to do so. They added that security improvement back in Windows Visa.

**Comment by marbletissue** [comment]
I see.. Task Scheduler has a trigger for Is Idle. I wonder what they use for that, and if it can be applied system wide.. But i guess if you add the exe to task scheduler to run on idle, would it work without a user logged in.. maybe do some testing and see what happens.

**Comment by UnamSanctam** [comment]
That isn't really an option since then the program would only run when idle, since that's what the Task Scheduler does (starts programs and similar things).

**Comment by UnamSanctam** [comment]
It's a very error prone method of doing it, I would personally never want to do it that way since we have no idea when or how it will stop working. Would also mean that the watchdog couldn't really exist.
