### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by alexfiltov** [UnamSanctam/SilentCryptoMiner#351]
Watchdog says miner is running, but it's not
![изображение_2022-02-01_184418](https://user-images.githubusercontent.com/98814391/152011744-35fe65b2-47af-4796-8164-c5d7351c6be3.png)

here's my example
[myminer.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7980308/myminer.zip)

**Comment by UnamSanctam** [comment]
Yes it's running, why do think it doesn't? If it's because of the GPU usage then it's because you're using the Task Manager, the Task Manager can't display CUDA usage (unless you change it a bit) so I would recommend using something like MSI Afterburner or some similar program to check the GPU usage.

**Comment by alexfiltov** [comment]
oddly🤔 yesterday task manager showed gpu usage, but today didn't. Yeah, miner works, but my hasrate is unstable 
![image](https://user-images.githubusercontent.com/98814391/152021632-69ea42d7-fe60-4107-8c65-efb6ddd242bd.png)

**Comment by UnamSanctam** [comment]
That's how pools work, they only show graph activity when you submit shares, so to view your hashrate you calculate (or check) the average hashrates over longer periods of time.

**Comment by alexfiltov** [comment]
ok, thanks
