### ISSUE TITLE
Xmrig parameters

### ISSUE THREAD

**Issue by jacktrue1337** [UnamSanctam/SilentCryptoMiner#364]
hi guys, tell me the command for xmrig for smart load, I can't find it (I'm talking about -tt and something similar

**Comment by UnamSanctam** [comment]
Smart load? You can find the default command line parameters here: https://xmrig.com/docs/miner/command-line-options

**Comment by jacktrue1337** [comment]
so I can't find them there) please help

**Comment by jacktrue1337** [comment]
maximum cpu, idle cpu, cpu waiting

**Comment by UnamSanctam** [comment]
Oh, it's `--cpu-max-threads-hint` (Max CPU), `--cinit-idle-cpu` (Idle CPU) and `--cinit-idle-wait` (Idle Wait).

**Comment by jacktrue1337** [comment]
So, but I didn't find the cinit command in support

**Comment by UnamSanctam** [comment]
Yes of course it's not from the original XMRig, but you can find the commands used inside the builder code.

**Comment by jacktrue1337** [comment]
can you help and find such commands in the original xmrig?1

**Comment by UnamSanctam** [comment]
There aren't any.

**Comment by jacktrue1337** [comment]
and where can I find such an unofficial xmrig?

**Comment by UnamSanctam** [comment]
I haven't released it because I don't have time to maintain and support it, since I already maintain and support the miner, web panel, binder and downloader on GitHub, HF, Telegram and Hugin (though the binder and downloader don't require much support). So I already spend all the time I have on work and supporting my projects, only way to support more ones at the moment would be the quite my job which I obviously can't. I don't release anything that I don't intend to maintain and give support for into the foreseeable future. If I did gain more time I would release more of the projects I have.

**Comment by jacktrue1337** [comment]
give me your telegram, there is a commercial offer

**Comment by UnamSanctam** [comment]
My Telegram is @UnamSanctam but currently I'm not at the computer that has the Telegram running on it so I can't read it immediately.
