### ISSUE TITLE
Mining through tor (onion) and running with system privileges

### ISSUE THREAD

**Issue by mickhaorex** [UnamSanctam/SilentCryptoMiner#369]
The xmrig program has the ability to mine through a socks proxy and, accordingly, through a tor.
Is it possible to implement a built-in tor in this miner, without an external tor-bundle program?
It would also be nice to add the ability to autostart from the system directory (%windir%; %windir%\system32) and autorun as a service.

And what do these settings mean?
![Screen](https://user-images.githubusercontent.com/99164289/152738347-7d295eba-edd1-4c4e-8c74-ab3aad2d66a7.jpg)

**Comment by UnamSanctam** [comment]
You can just add the `--proxy` command (https://xmrig.com/docs/miner/command-line-options) into the "Advanced Parameters" to connect to a SOCKS5 proxy. But there aren't really many advantages of mining through Tor. 

The ability to install into System32 wasn't carried over into this miner from the older miners because it doesn't work on all computers, so I would have to create a dynamic solution for that which also poses some problems especially with library paths (which is why it hasn't been re-added yet either).

And it depends on what you mean by service but installing it as an actual service can pose some problems depending on the computer (have to create it using the Service API and abide by any setting thereof) and wouldn't really make much sense. If what you mean "by service" is to run it as the "System" account then that also has problems, mainly that things like the Windows API idle detection wouldn't work since it's session based, so for some idle detection to work for the "System" user (meaning it checks all users) then I'd probably have to create some DLL that hooks into all programs and checks for mouse and keyboard access (but that also has issues as you can see if you search for that online). But running it as the "System" account is what I'm currently trying to make work.

You can get explanations for those settings on the wiki: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#options

**Comment by paolosezart** [comment]
Thank you for the detailed answer. 
By service, I meant working under the "system" account, that is, starting the miner when the computer starts, and not when the user logs in. This is true on server computers (there are usually very powerful computers there) where no user has logged in for months. And also on the terminal server, where there are a lot of users and it is easier to start the service than to do autorun for each user. 
As for reducing the load when the user/users are active, then in this case you can disable this feature. Leave only the stop of the miner when starting the task manager and similar programs.

**Comment by Roronoa-Z0RO** [comment]
interested

**Comment by hidden-69** [comment]
Any progress on running as system? Was planning on starting the miner with a scheduled task as local system from some directory excluded by WDefender

**Comment by hidden-69** [comment]
Why not use the Idle Time from Sessions info? cmd> quser

**Comment by hidden-69** [comment]
cool, any info on a eta?

**Comment by UnamSanctam** [comment]
I'm aiming for today.

**Comment by hidden-69** [comment]
Awesome!

What would the behavior be if the miner starts as system on computer startup, and then starts also when the user logs on?

**Comment by UnamSanctam** [comment]
Well since it would need to run as administrator in both instances they would see each other and the newest instance would close down (like how it is normally).

**Comment by hidden-69** [comment]
Sp if one would run as System and the other as local user without admin rights it would probably run double

**Comment by UnamSanctam** [comment]
Yes but it's the same right now as well, if one runs as Administrator and one as user the same happens. But if you compile it with "Run as Administrator" they have to run it as that.

**Comment by hidden-69** [comment]
Would be cool if the miner without admin would still detect the admin miner somehow, based on procesname and CPU usage for eg.

I prefer to run without admin and set startup etc from Powershell, but it runs as admin when started as system ofcource.

**Comment by UnamSanctam** [comment]
Well a non-admin user can't see the process information of the admin process, which is why it can't find it.

**Comment by hidden-69** [comment]
a admin user running non-elevated can tho, I'm pretty sure a normal user can see default information as well. It just won't have rights to inject into system processes or check in them

**Comment by UnamSanctam** [comment]
It can't (always) see the command line arguments and some other information which it needs to detect it.
