### ISSUE TITLE
One small question 

### ISSUE THREAD

**Issue by balvskimovies** [UnamSanctam/SilentCryptoMiner#374]
If the builder get detected by all anti viruses. Will the exe file be detected ?
Or how to run the builder 
Thanks..

**Comment by UnamSanctam** [comment]
Well the builder isn't meant to avoid antiviruses and has everything unencrypted/unobfuscated in it so the builder itself will almost always be detected which is why you should probably add an exclusion of the builder folder to your antivirus. The final miner build that you will generate from the builder will most likely be detected since this is a public and open source project, meaning it will get detected quite soon after each release but you can use crypter and/or obfuscators to reduce detections (as with any other program).

**Comment by kenzoppaate** [comment]
What crypt service can u advice?

**Comment by Gopnitsa** [comment]
> What crypt service can u advice?

Yes me too looking for, which crypter and how to apply ?
