### ISSUE TITLE
Will you improve stealth features?

### ISSUE THREAD

**Issue by SuperSnake802** [UnamSanctam/SilentCryptoMiner#377]
I got some good features for Unam's miner. 

* If bot is playing games or watching netflix, it can stop mining to prevent any lag for stealth purposes.
* If bot opened task manager, It can stop mining for stealth purposes.
* If bot is not idle, It can stop mining for stealth purposes.
* All these options can turn ON or OFF by you anytime.

Note, I sent some donation to you in XMR!

**Comment by UnamSanctam** [comment]
Well you can already to all those in the current version, for point 1) you can already add games into the "Stealth Targets" (Netflix wouldn't really be necessary) and for point 2) Task Manager is already a part of "Stealth Targets" by default so if you have "Stealth" enabled then it will already pause when you have "Task Manager" open. You can already also do point 3) by enabling "Idle Mining" and setting the Max CPU/GPU to 0% and the the Idle CPU/GPU to something else, then it will only mine when the computer is idle. Point 4) can also be done by using the "Remote Configuration" feature or by using the web panel.

>Note, I sent some donation to you in XMR!

Thank you very much, I appreciate it.

**Comment by SuperSnake802** [comment]
> lr

Thank you so much!

**Comment by ragnarok223** [comment]
1. my windows defender constantly detected the miner and remove it a few seconds after the miner builder build it ( please note I do not lunch it on my pc )
2. system 32 can't install it 
3. I have a question if the victim Successfully install the trojan and activate windows defender will it get detected by it or not

**Comment by ragnarok223** [comment]
please contact me as soon as possible cause I am willing to provide you with 2% of my income in any form you like

**Comment by UnamSanctam** [comment]
> 1. my windows defender constantly detected the miner and remove it a few seconds after the miner builder build it ( please note I do not lunch it on my pc )
> 2. system 32 can't install it
> 3. I have a question if the victim Successfully install the trojan and activate windows defender will it get detected by it or not

1) Yes it's a public open source project so it will get detected quite quickly after release, usually a crypter or obfuscator is used to reduce detections (https://github.com/UnamSanctam/SilentCryptoMiner/wiki#how-can-i-decrease-detections).
2) Do you mean that it doesn't work on 32-bit systems or that it can't install to the System32 folder? For the first instance, it's a 64-bit miner so it currently only runs on 64-bit. For the second instance, System32 was temporarily removed since System32 is protected on some computer so some backup solution has to exist first to make it stable.
3) It shouldn't if you have "Bypass Windows Defender" enabled since then it will add exclusions into Windows Defender.
