### ISSUE TITLE
can i change fees develeper ?

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#432]
can i change fees develeper in json in webpage or in pastebin 

any options i can put while system infected with miner remote ?

**Comment by UnamSanctam** [comment]
For the XMR miner it's 1% (or maybe 0%, don't remember if I changed the default or not) and for the ETH miner there is no developer fee. So there's not much to change, unless you want to somehow increase them.

**Comment by tarekxxx** [comment]
how change this remotly by pastebin ?? or json webpage unam web panel ?

**Comment by UnamSanctam** [comment]
What are you trying to do? Increase them? Since there's no fee for the ETH miner and either a 1% or 0% fee for the XMR miner. There's no option to remotely change it, though you can change it in the builder (only the XMR miner since it's the only one with a built-in fee) by adding `--donate-level=1` (for 1%) into the "Advanced Parameters".

**Comment by tarekxxx** [comment]
okay thanks sir
