### ISSUE TITLE
{COMPUTERNAME} for Remote configuration

### ISSUE THREAD

**Issue by Sikeriz** [UnamSanctam/SilentCryptoMiner#433]
https://sikhub.com/api/mygate.php?id={COMPUTERNAME}
no replace for this variable on miner side.

how can i use this for remote configuration? its not working to replace before request.
can i have exact code to replace in source code? i have visual studio 

and for old version eth miner, i had donated this project before :) sorry for your time
thanks for your making this good project

**Comment by UnamSanctam** [comment]
What exactly are you trying to do here? If you place {COMPUTERNAME} somewhere inside the "Remote Configuration" then it will replace it with the computer name. For example:
```
{
	"algo": "rx/0",
	"pool": "xmr-eu2.nanopool.org",
	"port": 14433,
	"wallet": "8BbApiMBHsPVKkLEP4rVbST6CnSb3LW2gXygngCi5MGiBuwAFh6bFEzT3UTufiCehFK7fNvAjs5Tv6BKYa6w8hwaSjnsg2N.{COMPUTERNAME}",
	"ssltls": true
}
```
Will make it mine with the computer name as the worker name.

**Comment by UnamSanctam** [comment]
It doesn't replace the computer name in the URL (obviously), for that it's better to use the API endpoint since the miner already sends the computer name in the API call. Since the web panel https://github.com/UnamSanctam/UnamWebPanel is already in PHP it should be easy enough for you to change to do what you want or copy over relevant parts to your project, especially since I have already added basic client separated configurations in the web panel.

**Comment by Sikeriz** [comment]
Thanks much then, thanks for fast answer.
