### ISSUE TITLE
wondering whats the best way to make money nowadays

### ISSUE THREAD

**Issue by yagger328** [UnamSanctam/SilentCryptoMiner#473]
is mining still the best way with it down and all? what should i do to make money good with malware, do you know?

**Comment by UnamSanctam** [comment]
Well it's the "easiest" method of it, since all other methods of malware usually requires some form of finding information and stealing (or selling botnets and such though that's more difficult). Mining is still profitable though of course and will probably always be in some form, if you don't need the money instantly then you can always just hold what you mine as well.

**Comment by zahin45** [comment]
disguise the miner as roblox hacks, and nitro gens, and put direct links to it using mega, and put a bunch of keywords at the desc of ur vids so it will show up when people search for it

**Comment by Smurfboi007** [comment]
Well, I have been using this for something like a year now, it is still very much profitable and if you stay consistent it will pay off.

Though you gotta be smart with the money you make. Start day trading COIN/USDTPERP pairs, same there, if you stay consistent it will pay off. I started day trading in October, paper traded for two months before using the money I mined up, been pulling in a 30% monthly return. 

Using 2% position size with 50x leverage, only trading price action*
