### ISSUE TITLE
Feature Suggestion: Worm

### ISSUE THREAD

**Issue by LolloDev5123** [UnamSanctam/SilentCryptoMiner#482]
Spread through internet ports, emails, files?

Second Suggestion: Prioritize the best miner instead of using all of them at once

**Comment by UnamSanctam** [comment]
Well it would be better to use some external worm instead since that would be quite a huge codebase and wouldn't be very optimal.

What miner is best is subjective so there's no real way for the miner itself to know which is best. Normally it's optimal to have a CPU miner and GPU miner mining at the same time, then which algorithm or coin is most profitable depends on the ever-changing market.

**Comment by LolloDev5123** [comment]
Can the best algorithm out of all the miners be chosen? I want to add as many miners as possible but it just mines all of them at once, maybe it could mine both cpu and gpu at once but only most profitable?
