### ISSUE TITLE
Suggestions for next update: 

### ISSUE THREAD

**Issue by FireHack7z** [UnamSanctam/SilentCryptoMiner#484]
- Encrypted pastbin
- Dynamic dll loading for runtime
- self morphing and function name randomiser 

[IMPORTANT]
 Update system :
    If currver < lastversion 
    Download new file and replace it from    original
(On pastbin : 
 last_ver :  123,
- last_file : DIRECTLINKBIN or false,

Download/ exec (using runpe for bypass)
On pastbin:

file_r : DIRECTLINKBIN,
 DIRECTBIN or false,

**Comment by UnamSanctam** [comment]
>Encrypted pastbin

There wouldn't be much point in having an encrypted pastebin really, unless you want it to avoid detection by pastebin themselves? Since for the miners you can just sniff the miner traffic to the pool and such, there isn't much to hide.

>Dynamic dll loading for runtime

What do you want dynamically loaded? Since the miner itself and such already are, do you want some option that builds the miner to a DLL?

>self morphing and function name randomiser

Functions are already randomized (and have always been) and all strings are already obfuscated as well.
https://github.com/UnamSanctam/SilentCryptoMiner/blob/e7d01c6c5ba7e9fd88e9cbcadd25c64c02773939/SilentCryptoMiner/Classes/Codedom.cs#L602
Though things can always be improved of course, though it wouldn't make too much of a difference unless there's some radical change.

>Update system

This would have to be a separate pastebin using something like XML (instead of JSON since C# or .NET doesn't natively support that) since this would have to be loaded inside the C# program and not inside the miners like the normal pastebins ("Remote Configuration"). The biggest problem with this is that I would have to save what the current version is somewhere on the disk so that it can compare it, and even then it's quite risky since people will mess it up and accidentally replace their current miner with a broken file (quite a common thing).

That would be a feature for quite advanced users only, so technically anyone that needs it could probably code it into the code themselves since it's not that difficult to do (because you don't have to care about user experience and human error then).
