### ISSUE TITLE
Any free hosting service that supports the Web Panel?

### ISSUE THREAD

**Issue by LolloDev5123** [UnamSanctam/SilentCryptoMiner#499]
Is there any service that supports the UnamWebPanel and PHP and a way to install it easily?

**Comment by UnamSanctam** [comment]
Hmm, well most services like 000webhost and such usually have traffic limits on free accounts to stop people from using them too much without paying. And most other services also do that (since they technically lose money if you don't pay) so it's hard to say, I haven't seen one without traffic limits yet and I'm not sure there are any. Though if you have a VPS (or VPN with port forwarding) then you can of course host it using that as well.

**Comment by FireHack7z** [comment]
Buy a 1$ vps, install LAMP and All it's good
