### ISSUE TITLE
Understanding Shellcode loader more

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#5]
whats the difference with and without?

does shellcode loader have any downs?

**Comment by UnamSanctam** [comment]
Without the shellcode loader it is just the normal C# miner that existed before. With the shellcode loader enabled it will create native C files that load the C# files into memory, this can decrease detections and makes it harder to kill (since it's injected into normal processes). The downside might be that it complicates things a bit.

**Comment by Brainshot** [comment]
> 
> 
> Without the shellcode loader it is just the normal C# miner that existed before. With the shellcode loader enabled it will create native C files that load the C# files into memory, this can decrease detections and makes it harder to kill (since it's injected into normal processes). The downside might be that it complicates things a bit.

What do you mean complicates?

The shellcode creates a bunch of folders and stuff can i just delete them and keep using the Exe? just like i have been doing

I guess the shellcode lowers detections

**Comment by UnamSanctam** [comment]
I mean that it complicated the flow a bit since it needs to to shellcode injection and such but I haven't really had any problems with it so far. 

You can remove the folders it creates without issue, it doesn't remove them automatically since they are around 10MB I think and extracting them and removing them on each build would be unnecessary.

And yes the shellcode loaders do reduce the detections by quite a lot, you can build one with it enabled and one disabled and you would most likely see the difference.
