### ISSUE TITLE
Will next update be uploaded soon?

### ISSUE THREAD

**Issue by DogusCyk** [UnamSanctam/SilentCryptoMiner#513]
Hi Unam, will next update be published soon? Thank you. Sorry for asking again

**Comment by UnamSanctam** [comment]
Yes I'm trying to reproduce the bug you sent before so that I can fix it, I haven't been able to make the bug happen to me yet. I also have to test the miner on all Windows versions with all kinds of different settings first as well, especially since I have changed it to run as System now (when installed as administrator).

**Comment by DogusCyk** [comment]
thank you for everything

**Comment by exaless** [comment]
Doğuş bu programla ilgili güzel bir fikrim var istersen anlatabilirim.

**Comment by DogusCyk** [comment]
> Doğuş bu programla ilgili güzel bir fikrim var birlikte çalışmak istersen anlatabilirim.

dc sal

**Comment by exaless** [comment]
AL3S#5262

**Comment by unknownreq10** [comment]
Grubda yer var mı ? :D

**Comment by DogusCyk** [comment]
> Grubda yer var mı ? :D
ekle Doğuş#4896

**Comment by exaless** [comment]
ekle knk AL3S#5262
