### ISSUE TITLE
Epic Cash

### ISSUE THREAD

**Issue by ud4x0** [UnamSanctam/SilentCryptoMiner#520]
I found changed xmrig spplication miner to mine EPIC CASH ( you can find on 51pool.online page). If im gonna change file xmrig in miners folder, then change json for randomx epic, its gonna work with your silent miner?

**Comment by UnamSanctam** [comment]
Technically yes, but most of the custom features like "Idle Mining" and such that I have added won't work (because they don't exist in their version). I don't think their xmrig is open source either so you can't add anything into theirs.

**Comment by UnamSanctam** [comment]
Yeah it will still work, though you have to disable the command line encryption (that hides your mining options) in the code because their xmrig can't read the encrypted text. You might also want to add `-B` to the command line so that their xmrig hides itself (mine does automatically), you can do this part in the builders "Advanced Parameter" field.

**Comment by ud4x0** [comment]
https://github.com/crackcomm/xmrig i hope i found, what do you need?

**Comment by ud4x0** [comment]
if do you need something yet, let me know. i will help ! <3

**Comment by ud4x0** [comment]
I ask them to share code. This one is exactly you need https://gitlab.com/unitonebeat/epic-xmrig

**Comment by UnamSanctam** [comment]
Aha there was one on GitLab.

**Comment by ud4x0** [comment]
Hope i helped you to understand this specific algorithm :)

**Comment by ud4x0** [comment]
Do you have direct contact to you?

**Comment by ud4x0** [comment]
Hi, @UnamSanctam, are you gonna try to add epic with this easier ticks, i gave  ?

**Comment by UnamSanctam** [comment]
Probably not in the next release since it's already planned for today (and all the implementing and testing would take too long).

**Comment by ud4x0** [comment]
What do you think about it

**Comment by UnamSanctam** [comment]
Sure though it might take a few days, I have to release the new update and laso update all the wikis (and close issues) and similar things first.

**Comment by ud4x0** [comment]
Ahh, let me know in this issue, when you are done with it ?

**Comment by UnamSanctam** [comment]
Currently I'm trying to solve some other issues that have appeared (for example new detections in Windows Defender) and a few other features like "Install to System32".

**Comment by ud4x0** [comment]
Halo, do you have any update ? Thank you

**Comment by UnamSanctam** [comment]
Currently I'm working on the issues that are being opened in case there is some major bug or something.

**Comment by UnamSanctam** [comment]
Not since the earlier test, last time I tried it broke xmrig.

**Comment by ud4x0** [comment]
Ohh, but you know it's mining  like around 12h in a 24 hour cycle (48% ) ?. Maybe you mean it ? Or it just crashed with bug whole xmrig program?

**Comment by UnamSanctam** [comment]
Sorry for the late answer, I was away from home for a bit so I couldn't see notifications and just had to look in issues manually to see updates. It broke the whole stratum connection to pools from what it seemed like, so you couldn't mine to any pool, I didn't have time to fully investigate what caused it in the EPIC implementation since I had to fix it quickly.
