### ISSUE TITLE
Fake Application?

### ISSUE THREAD

**Issue by KindaDumb4** [UnamSanctam/SilentCryptoMiner#524]
Is there anyway for this to be hidden?
For example:
The SilentCryptoMiner is cloned as "Google Chrome" but when you launch the .exe It will first run the Crypto Miner but then run the real Google Chrome so the user has no idea what happend.

also how are you gaining anything from this?

**Comment by UnamSanctam** [comment]
You can use a binder to do that (in that case launch Google Chrome through CMD) or directly change the code in the miner to do that, though they would have to have Google Chrome installed for that to work of course.

Programming is what I do for fun so that's why I work on the miner. I work as a programmer (in real life) as well but there I can't choose my own projects or what I want to do, so this GitHub is where I release my hobby projects that I make for fun..
