### ISSUE TITLE
No System dir install in new version? 

### ISSUE THREAD

**Issue by 1mavricks1** [UnamSanctam/SilentCryptoMiner#527]
Hi, just checked your new update. There is no system dir to select, does it done it auto? 
Also I have second version, will panel be updated also now? 
Thank you.

**Comment by UnamSanctam** [comment]
Currently there's no System32 directory install since I need to figure out some kind of backup (what I had in mind before didn't work) because a lot of people can't install into System32. I technically released a web panel update but it's just for translations, there aren't any known bugs with the web panel itself that I'm aware of.

**Comment by 1mavricks1** [comment]
Do I need to enable rootkit for all users install to work? Rootkit still does not work on any of my PCs, I got nslookup.exe crash all the time..

**Comment by 1mavricks1** [comment]
Can I change rootkit install to use explorer.exe for example? It craches also when I just use nslookup.exe as cover

**Comment by UnamSanctam** [comment]
No it doesn't require "Install Rootkit" for it to install to all users. 

Hmm, weird that nslookup.exe crashes, I've never experienced that in any install before so it's hard to test. It can't be done with explorer.exe (or any other program that you actually need) since it will hide the program completely and make it unusable, I also need to recompile it if it needs to hide another program. But I can look into changing which program it should be for version 2.2.1, I just don't know which ones work and which ones don't since all work for me.

**Comment by 1mavricks1** [comment]
Ok thank you, I don't know why but nslookup.exe makes problems with any combination of settings

**Comment by 1mavricks1** [comment]
On my builds

**Comment by UnamSanctam** [comment]
Yeah I'm guessing it's something with your Windows, I'll see if there are any viable alternatives to nslookup.exe (a program that all Windows versions has and isn't usually needed) that I can use.
