### ISSUE TITLE
Hello Which crypter on HF you advice to use? and settings?

### ISSUE THREAD

**Issue by Sikeriz** [UnamSanctam/SilentCryptoMiner#560]
Hello Which crypter on HF you advice to use? and settings?

**Comment by UnamSanctam** [comment]
Not sure, it's been quite a few years since I bought one and it's not like people share what crypter they use the get it undetected since then more people will use that crypter and thus risk theirs getting detected faster. For settings you can start by using the example settings https://github.com/UnamSanctam/SilentCryptoMiner/wiki#what-are-the-recommended-settings if that's what you mean.
