### ISSUE TITLE
suggestion    add a file pumper

### ISSUE THREAD

**Issue by Azzerzz** [UnamSanctam/SilentCryptoMiner#567]
it would be cool if you could add the ability to increase the file size, doing this would reduce the chances of miner being flagged as malware because it wont be able to be scanned with things like virustotal or kleenskan if the file size is too large, although can be detected by on system avs it would help

**Comment by UnamSanctam** [comment]
Biggest problems would be that it would be easier to detect by the user (since the file would be very large) and it could take quite some time to install (copy to final location) depending on how big you make it. But if someone really wants to increase the file size then there are also thousands of file pumpers out there (since they are quite simple).

I might add it someday but It's not really something I'm planning to add at the moment.

**Comment by Azzerzz** [comment]
> Biggest problems would be that it would be easier to detect by the user (since the file would be very large) and it could take quite some time to install (copy to final location) depending on how big you make it. But if someone really wants to increase the file size then there are also thousands of file pumpers out there (since they are quite simple).
> 
> I might add it someday but It's not really something I'm planning to add at the moment.

it would be good for fake apps such as a infected cracked game, or program
