### ISSUE TITLE
client proxy settings

### ISSUE THREAD

**Issue by hidden-69** [UnamSanctam/SilentCryptoMiner#571]
How are proxy settings handled? In corporate environments internet is mostly blocked and only allowed trough a proxy server, does it use the configured IE proxy settings?

**Comment by UnamSanctam** [comment]
No probably not, it should probably only use the proxy settings if they were system-wide which IE proxy settings aren't. The miner doesn't send HTTP traffic, mining is done using the stratum protocol

**Comment by hidden-69** [comment]
IE Proxy settings are global for the entire OS, a feature like this would be great as open internet is often blocked on corporate firewalls.

The stratum protocol should be allowed on most proxy servers, protocol is not a issue as more then http is allowed (http, https, smtp, ftp, ftps, etc, ssh, telnet).

**Comment by UnamSanctam** [comment]
Not on earlier Windows versions, but the proxy server settings in Windows 10 and 8 are usually global yes (though it depends). If it's those then it might apply to the miner connections as well yes. The reason I mentioned what protocol it is due to it meaning that it's not using the IE libraries/API which means that on Windows 7/XP the proxy settings probably don't apply.

**Comment by hidden-69** [comment]
No IE/System proxy settings were always global, even in XP (https://superuser.com/questions/434686/where-can-i-find-system-proxy-settings). But in applications you can often define if you want to use system settings, no proxy, or define a proxy in the app itself.

The client must implicit use system settings it doesn't automatically make use of the system/IE settings. I don't know this is build in SCM or not?

**Comment by UnamSanctam** [comment]
Yes it not being automatic for all traffic like a VPN is what I meant by system-wide or global. You can find the base miners here: https://github.com/xmrig/xmrig and https://github.com/ethereum-mining/ethminer. I haven't tested whether they abide by the IE settings or not but most other miners don't from what I remember (I know the NiceHash miner didn't because I had to help someone with that) which is why I think xmrig and ethminer might not either. But you can manually enter a SOCKS5 proxy in xmrig.

**Comment by UnamSanctam** [comment]
Yeah exactly which is why I said it that way in the first reply (in more layman's terms of it not being "system-wide" like a VPN). You can check the code for those miners to see if it's possible if you want to. I can't check for a while since I'm at a client setting up their new network. You can also set up a test environment with a proxy and see if the miners connect through the proxy or not if you have the time.
