### ISSUE TITLE
Hashrate Loss

### ISSUE THREAD

**Issue by kinggskral** [UnamSanctam/SilentCryptoMiner#572]
It's not an issue in the app. I am sorry to post there but I want to listen other persons ideas. Me and some of the guys here lost some of our hashrate. I assume that we lost our hashrate because of a Windows Update. Has anyone thought any precaution against the updates? I guess no one would want to lose their hashrate again. And another question for you : Most of the hashrate loses I saw was from ethermine, has anyone not using ethermine had a loss? Maybe its because of an Ethermine update or something.

**Comment by UnamSanctam** [comment]
Well it seems like there was an update that updated Windows Defender (from what I've been told), and when Microsoft does that they usually resets/reinstalls the entire Defender so any settings are often lost (exclusions included). Since this will happen no matter really what you do to Windows Defender (even if you completely destroy it like removing files) due to them reinstalling it the only real solution would be to disable Windows Updates. In the next version (which almost complete) there will be an option to disable Windows Updates which hopefully could reduce that happening in the future, only problem with disabling Windows Updates is of course that someone will notice that something is wrong if they ever want to use Windows Update but the trade-off could be worth it.

On another note, Ethermine does block quite a few countries now and is continuing to expand their blocked IPs from what I've been told, mainly by Russians (since Russia is now banned from Ethermine). So theoretically that could also reduce your hashrate if you're using Ethermine. The countries that they currently block should be Russia, Belarus, Afghanistan, Bahamas, Barbados, Botswana, Cambodia, Ethiopia, Ghana, Iran, Iraq, Jamaica, Mauritius, Mongolia, Myanmar, Nicaragua, North Korea, Pakistan, Panama, Syria, Trinidadand Tobago, Uganda, Vanuatu, Yemen and Zimbabwe.

**Comment by golxd** [comment]
i have nanopool and i also lost 50% h/s. I don't think it's the pool.

**Comment by Zeevsq1** [comment]
2miners also dropped Hashrate
