### ISSUE TITLE
Microsoft Defender SmartScreen

### ISSUE THREAD

**Issue by Zeevsq1** [UnamSanctam/SilentCryptoMiner#575]
how to bypass Microsoft Defender SmartScreen warning on startup?
![Annotation 2022-04-09 090524](https://user-images.githubusercontent.com/101643042/162558991-0b8f233e-0cf9-40b3-b4ea-474dab87a1a6.png)

**Comment by UnamSanctam** [comment]
Do you mean that it appears when you start the miner or on startup of the computer? If the former then you can't really bypass it, it's not a detection or anything, it just says that it can't recognize the program (since you haven't paid for a certificate).

**Comment by Zeevsq1** [comment]
1, I tried to install (copy) the certificate from another file, but it did not help

**Comment by UnamSanctam** [comment]
Yes because that won't be a valid certificate, it does work sometimes with some tools but usually not. Windows SmartScreen appears for all programs which hasn't paid for a certificate for their program (or if they detect some "bad" signature). Only way to bypass it reliably would maybe some sort of DLL side loading.
