### ISSUE TITLE
Which watchdog is better?

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#581]
the one run in memory or the one dropped

**Comment by UnamSanctam** [comment]
I'd say running it in the memory.

**Comment by Brainshot** [comment]
> I'd say running it in the memory.

Could you explain why?

**Comment by UnamSanctam** [comment]
Because then it won't have to be dropped to the disk, meaning that there's no file to ever get detected.

Here's the only difference (with "Shellcode Loader" enabled):
Run in memory:
Miner Start -> Inject Watchdog Loader -> Inject Watchdog Payload.
Run as file:
Miner Start -> Drop Watchdog -> Start Watchdog Loader -> Inject Watchdog Payload.

When it runs only in the memory the Watchdog will always use "Shellcode Loader" (since it has to).
