### ISSUE TITLE
Hello. Regarding "Kill Targets"

### ISSUE THREAD

**Issue by bvi32** [UnamSanctam/SilentCryptoMiner#582]
I found the list here in the discussions:
`afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe ,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe`

I would like to know your opinion, nothing bad will happen to the computer if it is used? Can you supplement it somehow?
I also noticed that "Kill Tragets" is found in all miners, and is not listed separately as "Block Websites", why is this exactly the case?

There is also a list of sites, I want you to take a look at it too and add to it if possible.

`avast.com,www.avast.com,totalav.com,www.totalav.com,scanguard.com,www.scanguard.com,totaladblock.com,www.totaladblock.com,pcprotect.com,www.pcprotect.com,mcafee.com,www.mcafee.com,bitdefender.com,www.bitdefender.com,us.norton.com,www.us.norton.com,avg.com,www.avg.com,malwarebytes.com,www.malwarebytes.com,pandasecurity.com,www.pandasecurity.com,surfshark.com,www.surfshark.com,avira.com,www.avira.com,norton.com,www.norton.com,eset.com,www.eset.com,microsoft.com,www.microsoft.com,Zillya.com,www.Zillya.com,kaspersky.com,www.kaspersky.com,usa.kaspersky.com,www.usa.kaspersky.com,dpbolvw.net,www.dpbolvw.net,sophos.com,www.sophos.com,home.sophos.com,www.home.sophos.com`

I think that these lists can be useful to anyone who reads this thread.

**Comment by bvi32** [comment]
Ещё вопрос. Если в "Remote Configuration" две ссылки какая из них будет использоваться первой например в таком случае
https://pastebin.com/raw/123,https://rentry.co/raw/123 ?

**Comment by bvi32** [comment]
One more question. If there are two links in the "Remote Configuration", which one will be used first, for example in this case
https://pastebin.com/raw/123,https://rentry.co/raw/123 ?

**Comment by UnamSanctam** [comment]
Killing those shouldn't have any real negative effects from what I can see, I don't really know any other good programs to kill other than those in the discussion of the top of my head. 

The reason that "Kill Targets" and "Block Websites" are separate is because the website blocking happens during the miner injector start since it only needs to run once while the "Process Killer" happens in a loop inside the actual injected miners together with the "Stealth" check. The miner injector (that blocks the websites) exits after it has injected the miners.

Those sites look good but you should probably remove microsoft.com from the list from what I can remember, Windows Defender goes crazy if you add that since it's a part of their blacklist. I haven't really put together any myself since I've been busy with coding. I'm planning on opening a "Block Websites" discussion as well.

>One more question. If there are two links in the "Remote Configuration", which one will be used first, for example in this case
https://pastebin.com/raw/123,https://rentry.co/raw/123 ?

In that case the first pastebin will be used first, and then if the miner cannot find a configuration there it moves on to the next one which in this case it the rentry one.

**Comment by bvi32** [comment]
Thanks for the detailed answer.

I noticed that when forming a miner in the JSON section, "kill-tragets" remains empty, so should it be?

**Comment by UnamSanctam** [comment]
That means that it will disable it (because you have "Process Killer" disabled in the builder), if you want it to use the builder settings for the "Kill Targets" then you can remove that line in the JSON.

**Comment by bvi32** [comment]
> because you have "Process Killer" disabled in the builder

Strangely, I have entered the entire list in the builder, which I described at the beginning of the topic. Why are "stealth-targets" passed without exception?

**Comment by UnamSanctam** [comment]
Because you have "Stealth" enabled but not "Process Killer".

**Comment by bvi32** [comment]
I'm sorry, I found this function only on the fourth inspection, it turned out funny xd
