### ISSUE TITLE
About the no sleep option

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#586]
Lets say someone has a laptop and his sleep mode is disabled by miner, if he closes the laptop that would automatically put it to sleep so my question is if he closes it will it still put it to sleep? or will the laptop be on even when its closed.

**Comment by UnamSanctam** [comment]
Yes that would still put it to sleep, otherwise the user would notice that something is wrong immediately. I only change the timed sleep (after X amount of minutes it goes to sleep) since that is usually the only thing you would want to disable. If someone wants any other thing to be disabled then they can always edit the command as well.
