### ISSUE TITLE
What does it mean?

### ISSUE THREAD

**Issue by Driadasa** [UnamSanctam/SilentCryptoMiner#588]
Added advanced option to not overwrite old installed miners if desired

My miner won't overwrite other people's?
Or other people's miners will not be able to overwrite my miner?

**Comment by Zeevsq1** [comment]
wiki
Will stop the miner from being installed if there's already a file present in the location of the "Startup" tabs "Save Path" with the same "File Name".
if there is already a file with the same name

**Comment by Driadasa** [comment]
> 

My miner or a competitor?

**Comment by Driadasa** [comment]
> Вики остановит установку майнера, если в расположении вкладок "Startup" уже присутствует файл "Save Path" с тем же "Именем файла".если уже есть файл с таким же именем

My miner or a competitor?

**Comment by Driadasa** [comment]
If after installing my miner, others cannot install their miner, then cool, if not, then garbage function

**Comment by UnamSanctam** [comment]
> My miner or a competitor?

> If after installing my miner, others cannot install their miner, then cool, if not, then garbage function

It will not install the miner if there's already a file installed in your chosen location, it's a feature that was requested and that's why it's there. It's in the "Advanced Options" menu because it's an advanced option and not everyone needs it or possibly understands its function. But the option is beneficial for some people that have many multiple builds and want to avoid them overwriting each other, so for some people it's not a garbage option.

**Comment by Driadasa** [comment]
> > Мой майнер или конкурент?
> 
> > Если после установки моего майнера другие не могут установить свой майнер, то круто, если нет, то функция мусора
> 
> Он не установит майнер, если в выбранном вами месте уже установлен файл, это функция, которая была запрошена, и именно поэтому она там. Это в меню "Дополнительные параметры", потому что это расширенный вариант, и не все нуждаются в нем или, возможно, понимают его функцию. Но этот вариант полезен для некоторых людей, которые имеют много нескольких сборок и хотят избежать их перезаписи друг друга, поэтому для некоторых людей это не вариант мусора.

In fact, no one needs it. Make sure that they cannot overwrite the existing miner)

**Comment by UnamSanctam** [comment]
>In fact, no one needs it

Well of course some need it, that's why they ask for it. And it does make sense if you have quite a large operation with multiple builds with different settings. Instead of having to create a custom miner on each update with that feature implemented I chose to just add it as an option.

>Make sure that they cannot overwrite the existing miner

Well no one can really overwrite your miner if you set your own "File Name" and "Entry Name" in the "Startup" tab.

**Comment by Driadasa** [comment]
> Ну, никто не может перезаписать ваш майнер, если вы установите свое собственное "Имя файла" и "Имя записи" на вкладке "Запуск".

The file when unpacking for everyone is called "System"

**Comment by UnamSanctam** [comment]
If you change the "File Name" and "Entry Name" in the "Startup" tab then your miner won't be overwritten unless someone else has the exact same "File Name" and "Entry Name".
