### ISSUE TITLE
RunPE.dll

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#589]
Good afternoon. Tell me what option the file is responsible for - RunPE.dll. This file contains virus detections. And will these detections affect the installation and launch of the miner.

**Comment by UnamSanctam** [comment]
It is just the RunPE code (that inject the miner) that was in the miner before but moved into a DLL instead, moving it into a DLL is the biggest reason for the detection decrease in the C# code.

It used to be right here: https://github.com/UnamSanctam/SilentCryptoMiner/blob/9a477cdb74df390dedba58135fb8fe93326d45f2/SilentCryptoMiner/Resources/Code/Program.cs#L506

**Comment by masterjek** [comment]
I can just return the code to the line again and this file will not be needed right?

**Comment by UnamSanctam** [comment]
Yes but your detections will also go up a lot.

**Comment by masterjek** [comment]
So on the file itself - RunPE There are also antivirus detections. As I understand it, they also affect the implementation of the miner.

**Comment by UnamSanctam** [comment]
No, the RunPE file is encrypted before it's decrypted inside the miner itself, so it doesn't add any detections to file during scan time but instead only possible detections during runtime. Before Assembly.Load (that loads the DLL) used to trigger some detections which is why it was moved into the code instead of a DLL (how it always was before) but now it's better to use a DLL again instead of directly in the code.

Let me explain it like this:

RunPE inside code directly:
Scan time detections + Runtime detections.

RunPE inside DLL:
Possible Runtime detections.

**Comment by masterjek** [comment]
I understand if I encrypt xmrig. Can RunPE run encrypted miner?

**Comment by UnamSanctam** [comment]
XMRig and all other files are already encrypted inside the miner.

**Comment by masterjek** [comment]
Thanks for the help.

**Comment by masterjek** [comment]
Tell me more please. I can file - RunPE encrypt against antivirus detections?

**Comment by UnamSanctam** [comment]
All files get encrypted when they're built into the miner (AES_Encryptor function)
https://github.com/UnamSanctam/SilentCryptoMiner/blob/d10c7d9f40995caa3cddc38ad7c0b6548af36862/SilentCryptoMiner/Classes/Codedom.cs#L70
RunPE.dll doesn't give any file scan detections at all since it's not readable by antiviruses.

**Comment by masterjek** [comment]
![1](https://user-images.githubusercontent.com/36513967/162617692-527d4485-4086-4e70-91f2-12021c4af351.jpg)

There are 3 antivirus detections. But I'm scanning a file from a project. I take it you shouldn't pay any attention to them? I'm just trying to encrypt a file - RunPE.dll To remove these 3 detections - But after encryption, the file stops working.

**Comment by UnamSanctam** [comment]
Yes those won't affect the miner detections (except maybe some runtime detections) and definitely won't affect the file scan detections (the only detections that matter for Windows Defender when "Add Defender Exclusions" are enabled), but even then there would be more detections if they were directly in the code like before (though that was not always the case previously). You can technically obfuscate RunPE.dll but you'll probably never be able to reduce those detections because all of them are due to the Windows API functions that are used for injection which are unavoidable unless you try some sort of system calls instead (though they have their own issues as well).

**Comment by masterjek** [comment]
Thanks for the answer.
