### ISSUE TITLE
Sign Out?

### ISSUE THREAD

**Issue by WaveyyBeFresh** [UnamSanctam/SilentCryptoMiner#598]
Will the Miner continue to mine if the user is signed out, or if a different user is signed in? Or does it only mine when the user who ran the file is signed in, or does it mine as long as the computer is turned on.

**Comment by UnamSanctam** [comment]
In the newer versions (since 2.2.0) if you have "Run as System" enabled (it's enabled by default) then it will run as the System user. This means that it will run even if all users are signed out, it will mine as long as the computer is on but someone does have to originally log in after a restart for the miner to start (but then they can log out and it will still be running).

**Comment by WaveyyBeFresh** [comment]
The pre-compiled one you have in GitHub is a newer version, correct?

**Comment by UnamSanctam** [comment]
Yes exactly.

**Comment by WaveyyBeFresh** [comment]
Alright, so all I have to do is build the miner and double click the file and it starts mining, and it should automatically start? And once I log out it will keep mining as long as the computer is on. Lastly it should just show up in my pool right? Sorry for all the questions, just want to get it all answered at once.

**Comment by UnamSanctam** [comment]
Yes exactly, if you start the file then it will do that. But remember that in the builder you need "Startup" enabled and you also need to run it as administrator (since otherwise it can only run on a user) for that to happen. It will also first need to restart once to start running as System (all users). And yes it should appear in the pool after you find at least one share (https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining).

**Comment by WaveyyBeFresh** [comment]
So I need to restart the computer after running the miner? Do I have to sign back in after that?

**Comment by UnamSanctam** [comment]
You don't need to restart it technically, the miner will still start running even if you don't restart after installation, but it will start running as System if you do restart, but you can maybe also just log out and in again for it to start as System. As long as anyone logs in to the computer the miner will start if it isn't already running.

**Comment by WaveyyBeFresh** [comment]
Im mining on 3070 ti's and its been 10 minutes and still no share has been mined. Are you sure it should work fine? Heres my configuration,
{
    "url": "stratum://`0xc5D3EF29fBa594630755580bff3f2527f2BfCD3C`@eth-us-east1.nanopool.org:9999",
    "algo": "ethash",
    "max-gpu": 70,
    "idle-wait": 3,
    "idle-gpu": 100,
    "stealth-targets": "Taskmgr.exe",
    "kill-targets": ""
}

**Comment by UnamSanctam** [comment]
Yes those settings work, can you open something like MSI Afterburner and check the GPU usage graph?

**Comment by WaveyyBeFresh** [comment]
<img width="675" alt="Capture" src="https://user-images.githubusercontent.com/94556647/162825027-8eecefef-2eb3-45dc-9d5f-ca96f46cd5ff.PNG">

**Comment by WaveyyBeFresh** [comment]
It will randomly spike, but sits around 3-4%

**Comment by UnamSanctam** [comment]
Do you have Task Manager open?

**Comment by WaveyyBeFresh** [comment]
No I do not

**Comment by WaveyyBeFresh** [comment]
Should I turn off stealth and see what happens?

**Comment by UnamSanctam** [comment]
Yes sure, only other thing I can think of is maybe your graphics drivers, but an RTX 3070 shouldn't really run on old drivers.

**Comment by WaveyyBeFresh** [comment]
I dont really know. Same thing with the new one.

**Comment by UnamSanctam** [comment]
Can you try extracting this and run any of the .bat files? It's a normal ethminer (though a bit old) [Test5.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/8467554/Test5.zip) just to see if that works.
