### ISSUE TITLE
bots don't work

### ISSUE THREAD

**Issue by faqu1** [UnamSanctam/SilentCryptoMiner#605]
I got about 20 installs on this panel, and about 70 on the other. in the previous panel, before its ban, a maximum of 5 bots worked, and here there are only 2 active ones

![image](https://user-images.githubusercontent.com/95179319/162959725-0bbc48b7-a007-4289-b975-50dfc8fcef12.png)
![image](https://user-images.githubusercontent.com/95179319/162959766-23fa2dc6-6259-4fdd-adb0-9a78fbe658c4.png)
 - hashrate from 100 installs.

**Comment by UnamSanctam** [comment]
They are all offline, or what are you asking?

**Comment by faqu1** [comment]
It can't be that out of 70 computers, only 5 are constantly online. Or is it default?

**Comment by UnamSanctam** [comment]
It depends on who is using the computer, there are people who use the computer for 2 hours a day and there are people who use it for 20 hours a day. Then there's also the chance that they've been removed, you can check the "Last Connection" time to see if it's recent, in that case most likely the computer is just turned off.

The only two real viable possibilities I can think of are either 1) computer is off or something similar, or 2) miners has been removed by something.

I also wouldn't recommend hashpool since they ban anyone that has over 100 miners (you have to use xmrig-proxy if you do have over 100).

**Comment by faqu1** [comment]
which pool ton ban after 100+ users?

**Comment by UnamSanctam** [comment]
Ah sorry, Hashvault does that, and also some others like MineXMR.
