### ISSUE TITLE
Question about ETH Miner 

### ISSUE THREAD

**Issue by 1mavricks1** [UnamSanctam/SilentCryptoMiner#611]
Hi, I want to ask about Eth miner, when it is set to 50% in Active state, does users pc lagg and can it be detected by user ? I got one report form my "slave" that his pc started lagging like crazy, my settings for eth miner are 50% active 100% idle and reptoreum 50% active, 100% idle, do you have any recomendation to make it more stealth? TY.

**Comment by UnamSanctam** [comment]
No the GPU usage usually doesn't cause any lag at all, what can usually cause lag is the VRAM that is being used if the person has a GPU with just enough VRAM to mine (for example a 4GB GPU mining ETC which is 3GB) but you cannot decrease that without mining some other cryptocurrency (since it's the coins DAG size).

**Comment by 1mavricks1** [comment]
Ah, thank you
