### ISSUE TITLE
feature request - stealth on full screen

### ISSUE THREAD

**Issue by hidden-69** [UnamSanctam/SilentCryptoMiner#642]
A option to go into stealth when user uses a full screen app like movie or playing a game would be great and would avoid lag.

**Comment by UnamSanctam** [comment]
Well games aren't really played on fullscreen anymore (at least the majority of people don't), so at most it would only really trigger with movies.

**Comment by hidden-69** [comment]
They're not?! Well I haven't gamed for years...

How about stealth detection if opengl/directx is used by another application?

**Comment by UnamSanctam** [comment]
> They're not?! Well I haven't gamed for years...

Haha yeah, you probably know about it but now "Borderless Windowed" is the standard which is just a simulated fullscreen (maximized windowed mode with the borders removed) so it usually registers just like any other maximized window.

> How about stealth detection if opengl/directx is used by another application?

It's technically possible since we can get the foreground window and and check if there's some DirectX DLL loaded. Though it wouldn't work very well for OpenGL since a ton of normal programs (or rather feels like every program now a days) use that and detecting OpenGL usage accurately is a real pain if not near impossible (at least in my experience). Checking for DirectX is therefore quite a lot easier but the problem is that a lot of programs use that too, for example if I just check my computer right now I can see that Windows Explorer, Notepad++, Visual Studio, NoMachine, Discord and many more currently have DirectX loaded. So it would cause a lot of false positives.

**Comment by hidden-69** [comment]
hehe allright, didn't know. I'll keep updating my game.exe list then.
