### ISSUE TITLE
Configuration Json

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#65]
Hey unam is it possible to switch from XMR to ETC for example?

Lets say if i create a XMR build with silent crypto miner, but in the webpanel wanna switch to ETC mining, is it possible? if so what json code do i need

**Comment by UnamSanctam** [comment]
No, since they are different miners and the "Remote Configuration" is retrieved inside the miners themselves.

**Comment by JABirchall** [comment]
What if it could dynamically load the miners from the panel if you have the panel setup?

So if you have panel URL set, don't embed the miners I the resources export them for uploading to the panel. then when the bot lauches and gets config from panel it can download the relevant miner. 
And ofcourse if you don't have a panel setup keep the miners embeded.

**Comment by UnamSanctam** [comment]
Won't really work since the injector never connects to either the web panel or the "Remote Configuration", and even if it did then it wouldn't know which configuration to get because each individual miner you add is different. Also the command line string that you compile it with is different for the two miners so those wouldn't work as well.
