### ISSUE TITLE
0 Hashrate

### ISSUE THREAD

**Issue by kinggskral** [UnamSanctam/SilentCryptoMiner#656]
Most of my Active workers get 0 Hashrate. Even with Radeon RX 5500 XT gpu drivers or nvidias 2000, 3000 series. Is this  a bug in panel? Because right now according to the panel I have 36 online users and now I get 51 MH/S only on Ethermine. I know that it can take time to appear in Ethermine but its been around 40-50 for an hour now. I wonder why most of them dont work now?
Another question is what does "Stopped" mean?

**Comment by UnamSanctam** [comment]
"Stopped" means that they cannot connect to the pool and has thus stopped, and that's usually also some have 0 H/s.

**Comment by kinggskral** [comment]
Stopped ones are understandable but active showing ones are also 0. They have good gpus too. Should I maybe try changing pool?

**Comment by UnamSanctam** [comment]
Yes, if you're using ethermine then they could be potentially blocked depending on what country they're from since they have quite a few countries blocked now. Not sure if they actually block people from mining or how they actually enforce it but they could be doing that. You can try 2miners and see what happens.
