### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by steelstealer** [UnamSanctam/SilentCryptoMiner#66]
1. when a someone downloads the miner do they have to open it for the first time or the miner will itself run as soon as someone downloads it 

2. when we enable run as administrator does that mean it will automatically run as administrator or the victim has to give administrator privileges to the miner 

3. what coin do u think that can be worth mining through your silent miner both Gpu and Cpu and what % should I put the miner both for idle and normal conditions, need your opinion on this I am sure there are many people who has this query 

And thanks for this amazing miners of yours, you are doing a commendable job

**Comment by UnamSanctam** [comment]
1. They have to open/run it like any other program, no program can run itself directly when downloaded since that would be a huge security flaw.
2. They have to give administrator privileges, there is no UAC bypass in the miner since I have not found any reliable ones that work for all versions of Windows and won't break everything if ever fixed.
3. Usually smaller coins is more profitable to mine with the CPU but you have to know when to buy, when to hold and when to sell to mine them optimally. That's why I usually recommend mining XMR with the CPU (or mining a different algorithm to MoneroOcean, because MoneroOcean will automatically exchange what you mine and pay you in XMR) and ETH or ETC with the GPU, those are the most reliable to mine.
