### ISSUE TITLE
Old versions Xmrig

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#665]
Good evening. Tell me please. I can use in version 2.3.1 xmrig from version 2.0.0?

**Comment by UnamSanctam** [comment]
Sure, though then you should disable things such as "Run as System" (or disable "Idle Mining" since that's the main thing that won't work when running as System in the old versions). Though there aren't really any upsides of using an earlier xmrig version.

**Comment by masterjek** [comment]
There are no benefits in older versions. But with each update, it's getting harder to encrypt the miner xmrig.

**Comment by UnamSanctam** [comment]
That should probably be the case with older ones as well though, but are you crypting the xmrig to avoid runtime detections or something?

**Comment by masterjek** [comment]
I checked on the old version xmrig it encrypts perfectly. And here xmrig since version 2.3.1 - Remains detection from Avast Internet Security - Win64:CoinminerX-gen [Trj]. Yes I encrypt xmrig In order to exclude detection during its introduction into the system.

**Comment by UnamSanctam** [comment]
Alright, some xmrig updates probably adds/changes some detections then, xmrig is at version 6.17.0 now, not sure which version it was at the builder version 2.0.0 but it was probably at version 6.15.2 or 6.15.3. So you can check the xmrig changelog to see if there has been any critical problems since then.

**Comment by masterjek** [comment]
Thanks for the help.
