### ISSUE TITLE
How would I receive the crypto?

### ISSUE THREAD

**Issue by Virtualmachine39** [UnamSanctam/SilentCryptoMiner#674]
This is more like a question than a issue. I have 2 questions actually.

How do I receive the crypto? Is it automatic or do I manually have to transfer it to my wallet with the support of the web panel?

2nd question.

How do I create a website for the web panel? I was confused a little because I didn’t know how to create a website. If you can, please provide instructions on how to create a website, and how to access the "public_html"

**Comment by Zem0rt** [comment]
I will answer what I know.
First question - Via pool [website] (I use hashvault.pro). You must create a wallet to which your currency will be transferred. When the minimum payout is reached, it automatically transfers. On monero.hashvault.pro "0.001". Yes, it won't be too fast. 
2 question - (not everyone knows how to create websites) I use sprinthost.ru free hosting but I would like a different hosting because it is Russian (Enemy because of the invasion of my country) okay, but that all free hostings block on all sites because of a suspicious load. there are different hostings and different instructions. Unfortunately, I can't show you right now.

**Comment by UnamSanctam** [comment]
Yes as @Zem0rt said the pool will pay you automatically once you reach the minimum threshold that the pool has (on most you can change it as well). 

Websites are basically just servers that host web content that you connect to, so to get a website you can either host it yourself (on a VPS or something since you don't want to expose your IP) or you can use some online webhost that hosts it for you, any webhost that supports PHP should theoretically work, though some can have blockfilters and such.

**Comment by Virtualmachine39** [comment]
@UnamSanctam does the same also apply with ethernine.org? I’m currently using that website
