### ISSUE TITLE
Bind executable

### ISSUE THREAD

**Issue by LolloDev5123** [UnamSanctam/SilentCryptoMiner#677]
How do I make it so that I can open an .exe and it does what I want it do do, but along that it also starts up the hidden miner inside of the executable? So it's one .exe that also runs hidden miner but does what I want it do to

**Comment by LolloDev5123** [comment]
How do I stop/pause the miner from WebPanel?

**Comment by UnamSanctam** [comment]
You can set the "Max CPU" or "Max GPU" to 0 or add "explorer.exe" into the "stealth-targets" of the "Configuration" (you can create a new configuration that pauses the miner).

**Comment by LolloDev5123** [comment]
Suggestion: WebPanel could create configurations and have a GUI instead of pasting in the JSON

**Comment by UnamSanctam** [comment]
Well it's possible to create a GUI (that generates JSON) and I've considered it but right now I think the builder is enough (the "JSON" tab in it). Yes, the icon preview doesn't reload in the current version, I have to add it manually and haven't considered it important enough yet though I have added it in my development version (that I'm currently working on). I currently haven't added any languages (or an easy file to change it in) since I have to figure out some way to make the texts not overlap with other things, since some words might be longer is some languages which could cause text to go over the button next to it.
