### ISSUE TITLE
A couple of ideas

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#689]
Good afternoon Unam. There are a couple of ideas for the next update. I don't know much about programming so don't judge ideas too harshly as I don't know how hard it is to implement.
1. WebPanel - Make automatic removal of miners from the table that have not connected and worked for a month.
2.  Implement the addition of the miner to the exclusions of other antiviruses, not all, but those that are quite popular.

**Comment by UnamSanctam** [comment]
1. It's possible, though it would be better to just have a button that you can press for removing old miners, I can make a field where you choose the amount of days and then a button that removes any miners that have been offline for longer than that.
2. We can only add exclusions into Windows Defender since Microsoft allows us to and has made it easy to do so, unfortunately the majority of other antiviruses don't allow that and usually the only way to add exclusions is manually through the GUI.

**Comment by masterjek** [comment]
Thanks for the answer.
