### ISSUE TITLE
not a issue just fun idea

### ISSUE THREAD

**Issue by harry133712** [UnamSanctam/SilentCryptoMiner#696]
would love to hear your opionin on a feature for the webpanel where we can see where the miners are located l like some sort of world map with dots if that is possible 

let me know what u think about it

**Comment by UnamSanctam** [comment]
Well it's technically possible, what you do is that you usually have a database with every IP and their country downloaded from somewhere (I think GeoIP2 is the most common) which is then used with the miner database to place everyone on the map. I was going to place a flag next to each IP depending on what country they're from but there was some reason I didn't do that yet, there was some issue but I can't remember what it was. If I do finish that then placing them on a map is something I can consider since it does sound helpful (and fun).
