### ISSUE TITLE
Transfering ETC miner to mine Ravencoin (moneroocean)

### ISSUE THREAD

**Issue by Redkits02** [UnamSanctam/SilentCryptoMiner#698]
Since the price for ETC has dropped in price again, seems to be way more profitable mining RVN,
i've tried transferring using remote config, but i just can't manage to get it working.

xmr miners transfer to different algo's no problem, (password:workername~algo)
but since etc config is formatted differently, any idea how to set it up correctly?
are the etc/xmr configs at any point interchangeable? (as in, just swapping max-cpu to max-gpu and calling it a day)

**Comment by UnamSanctam** [comment]
The ETC miner and the XMR miner (where RVN is mined) are two different miners, so you can't use the same "Remote Configuration" to change between them. You can technically change an XMR miner to mine RVN but you'll need to have built the miner originally with "GPU Mining" enabled since otherwise the CUDA libraries won't exist in the miner.

**Comment by Redkits02** [comment]
so, is changing an etc miner to mine ravencoin on moneroocean possible?
and what would have to be done for that?
adding this line:
    "password": "worker~kawpow",
and changing the wallet to an xmr wallet?

**Comment by Redkits02** [comment]
oh wait... so ravencoin can only be mined with the xmr miner?

**Comment by UnamSanctam** [comment]
Yes, the ETC miner is an Ethash/Etchash algorithm miner only.

**Comment by Redkits02** [comment]
so, the only way to bypass etc price going so low, is to go eth mining and hope you have enough 5+gb gpu's for it to pay off then
i see, thanks unam.

**Comment by UnamSanctam** [comment]
Yes, though the reason the mining rewards for ETC is down is because we're now in Era 4 which means that the overall block rewards have been reduced from 3.2 ETC to 2.56 ETC. Though ETC isn't that far behind RVN, RVN is now 10-20% more profitable depending on the computer, though RVN is more intense so it's easier for the user to see lag.
