### ISSUE TITLE
Name miner in taskmgr

### ISSUE THREAD

**Issue by alix1011** [UnamSanctam/SilentCryptoMiner#709]
Hi my friend, why after running eth miner in taskmgr, the miner's name was written as (lolminer)?

**Comment by UnamSanctam** [comment]
It's not, are you sure you're running this miner?

**Comment by alix1011** [comment]
Yes, can they have run the miner with these specifications before and overwrite it after running my miner?

**Comment by UnamSanctam** [comment]
I'm not sure what you mean, and the miner will be shows in the Task Manager with the process you chose in the "Inject Into" selection, so by default it will show as explorer.exe in the Task Manager. The actual miner used is a modified version of ethminer (and not lolminer, since that's not even open source).
