### ISSUE TITLE
Administrator question

### ISSUE THREAD

**Issue by azuilol** [UnamSanctam/SilentCryptoMiner#710]
I’ve read the wiki and haven’t been able to figure this out. If you enable run as administrator but the user declines will the miner still mine just without Admin required items such as not allow defender exclusions or will it not work at all.

**Comment by UnamSanctam** [comment]
No it won't start then, the administrator privilege escalation is handled by Windows itself and not the miner, which you can see by the program having a little shield on its icon. While you can technically create a program that can continue running even when declined by doing the privilege escalation through the code after the program has been started it wouldn't make much sense since the administrator functions wouldn't work.

**Comment by LolloDev5123** [comment]
Would it be possible to add such a feature? Work without administrator privileges/features if they have been denied

**Comment by UnamSanctam** [comment]
Well, if you haven't obfuscated/crypted it well then Windows Defender will most likely detect it if it does that (since there will be no exclusions) so most people wouldn't really be able to use the feature. And I'm not sure what such an option would be called.

**Comment by azuilol** [comment]
Would you be able to either tell me or link me to a tutorial on how to obfuscate the files, when I build the exe and enable pause for obfuscation I don’t know how to do it. Cheers.

**Comment by UnamSanctam** [comment]
Well it fully depends on the obfuscator, but currently I think it's undetected from Windows Defender if you have "Shellcode Loader" disabled, you can try the example settings and see https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings (only "Full" adds Windows Defender exclusions).

**Comment by azuilol** [comment]
Is there a particular obfuscater that you would recommend?

**Comment by UnamSanctam** [comment]
[ConfuserEx 2](https://github.com/mkaring/ConfuserEx) is generally pretty good.

**Comment by azuilol** [comment]
Thanks. I see that it is recommend for C files to be crypted instead of obfuscated, can ConfuserEx 2 crypt too?

**Comment by UnamSanctam** [comment]
No it's an obfuscator so it can only obfuscate managed assemblies (for example C#), though if you disable "Shellcode Loader" then there will be no C files. For some, using "Shellcode Loader" and crypting (with some good crypter they have) is the best alternative, and for some disabling "Shellcode Loader" and only obfuscating it is the best alternative. It all depends on how good the crypter or obfuscator you have is.

**Comment by azuilol** [comment]
Is there a good crypter you would recommend. Sorry for so many questions.

**Comment by UnamSanctam** [comment]
There aren't really any "good" free ones, most free ones will be proof of concepts, experimental ones or very detected ones. This is because crypters are very different compared to obfuscators and those that will make things undetected will be private paid ones because the creator (usually) has to actively update/change their crypter. It's for this reason that "Shellcode Loader" is an optional setting, so that if you can't get a crypter then you can always disable it and go with obfuscators.

**Comment by azuilol** [comment]
I just downloaded the full preset from the GitHub and I see the pool used is 2miners.com, on the website is says for password input "x" but on the full preset available from GitHub the password is left blank? Do you know if it will work either way?

**Comment by UnamSanctam** [comment]
Yes it doesn't matter, the 'x' is just another meaning for blank, and some miners (like ethminer) just fills it in with 'x' automatically if you leave it emtpy. Pools usually say 'x' in the password field when it's unused so you could put anything there and it shouldn't matter.
