### ISSUE TITLE
Can i make it work on osx

### ISSUE THREAD

**Issue by SnakeKi11er** [UnamSanctam/SilentCryptoMiner#729]
I was looked thoroughly throught the whole internet and i can't find a single silent miner and i wanted to know if there can be any silent miner made for osx

**Comment by UnamSanctam** [comment]
While it could technically be possible, it would be quite difficult to make it work and it probably wouldn't work very well since OS X is so unfriendly for (real) developers, so I don't think anyone is going to really make one. Many of the features that exist could also never exist in OS X, it's too restrictive for them.

**Comment by SnakeKi11er** [comment]
1. is there any way just to hide the window in osx and maybe even add a shortcut key to pause the mining instantly?
2. can i make a an osx terminal miner to hide ? 
3. can it be installed in macos by just installing it directly like it does in windows

**Comment by UnamSanctam** [comment]
1. You can compile something like xmrig without a console, should work on OS X as well. https://xmrig.com/docs/miner/build/macos
2. Yes, the same as in 1.
3. No I believe you'll have to create a real macOS application that you'll then have to install like you do any other app on macOS, then that app will have to start the miner. Or you might be able to make a miner file runnable at startup with `launchd`.

**Comment by SnakeKi11er** [comment]
thanks bro for answering my queries and for quick replies u are very great and also one more question
1. i am just a begginer who knows nothings about coding and which language should i learn first for stuff like this thank you

**Comment by UnamSanctam** [comment]
All miners are usually in C++ but it's not an easy language, if you want to code things for macOS then they also have their own languages that really only they use called Swift and Objective-C though of course things coded in C, C++ and others like Python can run as well. You can also make things in C# but I think that requires .NET Core installed on macOS to run.

**Comment by SnakeKi11er** [comment]
is there anyway u can make this silent miner undetectable and it can just be installed by a double click in any sytem

**Comment by UnamSanctam** [comment]
> is there anyway u can make this silent miner undetectable 

You'll need obfuscator or crypters to make it undetectable, since the project is public and open source I can never make it undetectable by itself.

>and it can just be installed by a double click in any sytem like a backdoor software ? or can u tell me how to do so

It's not really possible to create an OS agnostic software when it needs to utilize a lot of different OS APIs and "exploits", you'd have to fully rewrite the code (and probably even make it in an entire different language) to make it work on macOS or Linux distros. If you're just wondering if you can run it on any Windows system then yes you can run this silent miner on any Windows computer (Windows 7 and up).

**Comment by SnakeKi11er** [comment]
no just for windows no os

**Comment by SnakeKi11er** [comment]
ok bro thanks finally for giving your time to me

**Comment by SnakeKi11er** [comment]
can i make the miner i was talking about earlier with swift and c++ only or does it need any other more language

**Comment by UnamSanctam** [comment]
First you'd have to compile miners themselves (you don't want to make your own base miner of course), something like like https://github.com/xmrig/xmrig/ (made in C++, to make any changes you have to know C++), then you'd probably have to make the installer, injector (if even possible) and everything else in Swift (to be able to use the APIs/SDK).
