### ISSUE TITLE
Detection issues

### ISSUE THREAD

**Issue by gitthisandthat** [UnamSanctam/SilentCryptoMiner#734]
hey unam,

i have some problems with the detection of the miner, i have a good obfuscation also without shellcode 2/26 build on antiscan and windows defender detects my miner as WATACAB!ML also tried it with a fully fud downloader and it detects the miner aswell with the same wataca dectetions is there a way to bypass this detection?

**Comment by gitthisandthat** [comment]
and thats without the downloader included

**Comment by UnamSanctam** [comment]
Yeah then I guess new detections have been added, do you get the same detections if you use the "Full" example setting https://github.com/UnamSanctam/SilentCryptoMiner/wiki#full (just built it, no changes)? It has been 10 days since release so it being detected would be logical. If you want to lose detections you'll probably have to find a better obfuscator, keep in mind that 2/26 detections doesn't actually mean much since it doesn't do all the checks that a normal computer does. For example, most scanners that don't distribute don't scan with "Cloud Protection" in Windows Defender (from what I believe) since that would share the file with Microsoft, so any detections from "Cloud Protection" won't be shown in those kinds of services.

**Comment by gitthisandthat** [comment]
with the full example i get without obfuscation sabsik.FL.A!ml and with obfu i get wataca also tried multiply obfuscators but they all give me the same detection

**Comment by UnamSanctam** [comment]
Then it seems like they've added new detections, either you can try and change the code, find an obfuscator that obfuscates enough to "bypass" that detection or you can wait for the next update whenever I get done with that.
