### ISSUE TITLE
Watchdog without Install

### ISSUE THREAD

**Issue by Sh4r3cat** [UnamSanctam/SilentCryptoMiner#744]
Hey, since i use the crypters startup is there a way to use the watchdog? and my other qestions is, can i "auto select" the best coin for 4gb and 6gb gpu over the panel?

**Comment by UnamSanctam** [comment]
> Hey, since i use the crypters startup is there a way to use the watchdog? and my other qestions is

No since the watchdog wouldn't know where the miner is (wouldn't know its install location), you'd have to build/remake the watchdog yourself with hardcoded install paths that match the crypters install path.

>can i "auto select" the best coin for 4gb and 6gb gpu over the panel?

Not really, since the miner works based of algorithms and not coins and even then it wouldn't automatically know which coin is the best (in terms of profitability), you can technically code a list of GPUs yourself in the panel where it would apply one configuration (6GB) and a different configuration if it's not in the list (4GB). Though some GPUs can have different amounts of VRAM even though they have the same name.

**Comment by Sh4r3cat** [comment]
Oh okay, thank you.
