### ISSUE TITLE
Request: bypass UAC

### ISSUE THREAD

**Issue by FireHack7z** [UnamSanctam/SilentCryptoMiner#751]
It's possible to add Bypass UAC for get Admin right without executing in admin

**Comment by UnamSanctam** [comment]
Well I won't really add one (that's public) since most don't work on all Windows versions (all between Windows 7 to Windows 11) and those that do don't always work very well. And if they ever get fixed the miner would potentially stop working. But if anyone ever wants to use one then they can implement whatever method they want from things like https://github.com/hfiref0x/UACME that fits their use case.

**Comment by FireHack7z** [comment]
Thank you man , I try add it into the miner
