### ISSUE TITLE
Stealth and ldle 

### ISSUE THREAD

**Issue by Ninja133** [UnamSanctam/SilentCryptoMiner#754]
i have questions 
if the is Pc idle - and have games.exe in stealth up running in the task manger 
is it going to mining ( active ) or not  ( Paused Stealth ) because of games.exe in stealth even if it idle ?

**Comment by UnamSanctam** [comment]
"Stealth" will always take priority, so it would be paused. Mainly since there are many possible problems if it's not done that way, especially since idle does not necessarily mean that they're not at the computer, it only means that they haven't interacted with the computer for the "Idle Wait" amount of time. Also if someone has GPU/CPU monitoring software open then you wouldn't want the miner to ignore "Stealth" due to going into idle (mining) mode, so that's why it always prioritizes "Stealth".
