### ISSUE TITLE
pool management, important topics to study.

### ISSUE THREAD

**Issue by darkdevil111** [UnamSanctam/SilentCryptoMiner#78]
hello first of all I wanted to thank you for working on such a functional program, constantly updating it and making it public, I do not speak English very well but I would have some questions to ask you: 1) do devices to be infected simply receive the exe contained in the pre-built build and then are monitored and controlled via the web panel? if yes what settings should I use 2) I would like to understand more to maneuver the bot in the best possible way is there anything in particular that you advise me to study? important topics or programming languages that can serve me to understand and make the program work in the best way. 3) if I use a pool I do not have special ram needs because the infected devices collaborate with each other, or must they still have minimum resources?
could I finally have your contact type discord so as to confront us directly?
thanks in advance

**Comment by UnamSanctam** [comment]
1) Yes they only have to start the .exe and it will start mining, it will use the builders settings and then you can monitor it in the web panel (or the configuration can be changed from the web panel as well). https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#api-endpoint-url
2) Reading the wiki would probably be the most informative, the miners is built (or at least attempted to be built) to be as easy to use as possible while still providing a good amount of customization.
3) Miners only ever connect to the pool (and web panel if you have one) and all of them need the minimum amount of resources, even if it was somehow possible to share resources it would be far to slow to give any significant hashrate at all. Hence why GPU mining always uses the VRAM and never substitutes it with something like normal RAM if there isn't enough VRAM because that would be really slow (so a low hashrate), so sharing resources with other systems over the internet wouldn't work.

I have a Discord you can contact me on: Unam Sanctam#3135
