### ISSUE TITLE
Ability to change from ethash to etchash with remote config?

### ISSUE THREAD

**Issue by Bartixxx32** [UnamSanctam/SilentCryptoMiner#788]
Hey, as in topic, just want to ask if its possible, or it need new build of the miner to do so?

**Comment by UnamSanctam** [comment]
Yes you can change between Ethash and Etchash through the "Remote Configuration", just change `"algo": "ethash",` to `"algo": "etchash",`

**Comment by Bartixxx32** [comment]
Oh thats good to know

**Comment by Bartixxx32** [comment]
Btw to not open new issue (agin) i want to ask if its possible using remote configuration, to update Remote management url to old miners?, i have old miner whih using old site with panel, but i want to tell "him" to use new panel instead, 

Will adding `"remote-config": "Remote Configuration URL",` to json do job? becouse i dont want to screw up somentig xD

**Comment by UnamSanctam** [comment]
Yes you can change the "Remote Configuration" and/or the "API Endpoint URL" using either:
```
"remote-config": "Remote Configuration URL",
"api-endpoint": "API Endpoint URL",
```
But keep in mind that it will only use that for the current session (since it's saved in memory it's not permanent), when the miner restarts it will use the old URL (that it was compiled with) until it gets told the new one from the JSON again.
