### ISSUE TITLE
Small idea

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#794]
Good afternoon Unam. I don't know if such a function can be implemented. What would the miner add himself to the firewall exceptions?

**Comment by UnamSanctam** [comment]
I don't think it works, since the miner is injected into a program (for example explorer.exe) it would have to add that program to the firewall, problem is that in my tests it doesn't actually seem to do anything when you do that (when adding the program that it was injected into to a firewall exception).
