### ISSUE TITLE
Is rootkit helping in anything than powerusers?

### ISSUE THREAD

**Issue by Bartixxx32** [UnamSanctam/SilentCryptoMiner#825]
Hey i have question about rootkit, i readed the docs and im understand that it only hide process with params, but it hide it for users or for antivirus too ( i mean makes harder for av to detect)? Becouse i wonder about using it, if it would not have adventage with detections. As my logic it can cause increased detections.

Btw its arleady stable? Becouse in last build it was experimental.

**Comment by UnamSanctam** [comment]
It is mostly for powerusers and users that are following some sort of guide to try and find something. It was added due to requests. The miner uses the r77-rootkit so it will be stable whenever that becomes stable (if ever), it has always been stable for me but other users report that they get problems.

**Comment by asxtin** [comment]
> It is mostly for powerusers and users that are following some sort of guide to try and find something. It was added due to requests. The miner uses the r77-rootkit so it will be stable whenever that becomes stable (if ever), it has always been stable for me but other users report that they get problems.

![image](https://user-images.githubusercontent.com/106918443/172112098-8238ab93-946f-44f2-b665-a2111798f109.png)
uhh... why??

**Comment by UnamSanctam** [comment]
>uhh... why??

Don't know, someone has reported via email that they might have problems (with normal RandomX) on one of their computers (out of 40) due to the Panthera (it's a variation of RandomX so it changes RandomX code) algorithm and from what he has sent it seems logical. I sent him a version without Panthera and it seems to work for him so I'll be removed Panthera in the next version. Your problem could be due to that, but since it might only happen on some CPU/computers it's hard to know (happened only on one of his 40 computers)
