### ISSUE TITLE
WD exclusion not working nor miner starting as the system starts 

### ISSUE THREAD

**Issue by minerfortyniner69** [UnamSanctam/SilentCryptoMiner#831]
https://user-images.githubusercontent.com/107041842/172380341-44541e9f-4425-4f0a-8c1f-df420503edaa.mp4
[miner xmr.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/8853251/miner.xmr.zip)

hello hello!
as seen the miner didn't exclude it self nor it start it self after restarting the pc

please if there is something im doing incorrectly please do tell me 

thanks for you time!

**Comment by UnamSanctam** [comment]
Well first of all I didn't see you actually start the miner in the video, second of all you should use the `minertest-checker.exe` that got generated with the miner to see if it's running. And even the exclusions are there, the `C:` and `C:\Users\miner` are the exclusions that gets added.

**Comment by minerfortyniner69** [comment]
hello hello! 
![image](https://user-images.githubusercontent.com/107041842/172529427-9b6f716b-2057-43a1-a715-f11fea687449.png)

![image](https://user-images.githubusercontent.com/107041842/172529456-95d6a538-f4c5-484c-b667-d7cc6b48f735.png)

from what i understood, the miner would start on its own when windows starts "start up" option 
but then again at "run as system" it also mentioned that will start with windows when any user logs on the next start up, hence why i restarted the pc in the video and at the end it was brief but i runned the checker it was saying watchdog not running nor the miner is running.
![image](https://user-images.githubusercontent.com/107041842/172530331-6fda635a-cc0e-4f28-be92-3a8a20188de9.png)

also what is the scenario  that the minner keep running but watchdog wont be run because at times WD would catch the watchdog even tho the memory option is on i thought the watchdog cant be caught or something along those lines 

regarding the WD exclusion i mistaken understood that those files are something WD excludes pre-usual (thought like its system files and such so wont be touched) thought it would exclude the actual files not like the entire drive and such (thus leading to my misconception) 

oh and lastly couple more questions.
1.even if a file is added as an exclusion to WD doesn't mean it wont be caught and deleted 
2.there is no way to have the program auto starts as soon as it get download (without admiration access)
3.Obfuscation method. you would need it if the program has no administration access right? 


thanks for your time yet again!

**Comment by UnamSanctam** [comment]
Yes of course, it will install itself and start with Windows automatically but you still need to start the program for it to install, you never double-clicked the miner in the video so it never installed it.

It excludes the entire drive since excluding just the miner would expose where the miner is and what added the exclusion.

1. If added to exclusions then files themselves will never be scanned and deleted.
2. No you can't make anything automatically start after download in Windows, it would be a huge security hole.
3. Yes if you're not going to use exclusions then you'll need obfuscation even more.

**Comment by minerfortyniner69** [comment]
hello hello yet again!
so as you can see i started the miner and was operating normally but after restarting the computer the miner didn't run again

https://user-images.githubusercontent.com/107041842/172611970-359cea33-8c93-4740-9579-dffeef28c0fe.mp4

another set of questions coming right up! 

1. i see i see well in my case the limerat issue some how causes the miner and everything related to it being deleted (not shown in this video) (ill report back after testing the bypass hotfix you sent out in another post) 

2. alrighty understood. tho is there a way to mask the program? like make it seem its a word file and once opened just an empty word file opens up but in actuality the miner has started running?  (something more complex  than the assembly since the assembly once clicked wont pop anything if no administrator setting were on)

3. so from what i read throughout the posts no reliable obfuscation exists as of now right? 

4. so let say the limerat issue gets taken care of. on the settings present so far in the miner turned on will be able to completely bypass WD?

5. even when the exclusion method on WD would return a notification saying no scanned threat but that some files weren't scanned due to exclusion . is there a way to not let that message pop? 

6. to bypass real anti-virus software you need obfuscation along with running as administrator right? 

7. without administrator permission the program wont be able to auto lunch when windows start after installing right? 

once again for taking your time to answer my question along with everyone elses questions too! 
 
                                                           (*^.^*)

**Comment by UnamSanctam** [comment]
1. Yes it looks like it's not injecting after restart due to the AMSI blocking the process hollowing and shellcode injection, if you use the new bypass version then it shouldn't happen.
2. There are two main methods of doing that (hiding it as a Word document), the first simplest method is to first use a file binder to combine a Word document and the miner together into one .exe, then you would use an extension spoofer on that file to spoof it into a .docx. The second harder method is to find a Word exploit program, there are programs that using Word exploits inserts your .exe into a real Word document that then when the word document gets opened it runs your .exe, but most of these kinds of programs usually cost money since many use private exploits. Both methods have their own pros and cons.
3. Many free obfuscators can reduce detections with different kinds of options, then there are also many paid obfuscators which can reduce detections by quite a lot.
4. Yes those settings would bypass Windows Defender, there is also the destructive "Disable Windows Update" option that completely disables Windows Update and as such prevents any Windows Defender updates from being installed as well. So with "Disable Windows Update" enabled it would prevent any future detections due to updates on computers it has been ran on. But as a caution, there isn't really any way to reverse the changes done by this setting.
5. Not really but that notification usually doesn't pop up for me at all so I'm not sure when it appears, you could potentially add the Windows Defender notification program into the "Kill Targets" and then the miner will kill it if it can, thus theoretically preventing it from appearing.
6. Yes, though most people use Windows Defender so people usually just focus on that.
7. Without administrator it will install it locally on the user it was ran/installed on, so the miner would then start whenever that user logs in.

**Comment by minerfortyniner69** [comment]
ah! yes welcome welcome sir sanctam ( ★^O^★ )
1.obfuscators  is a must if no administrator access was allowed right?. also how long do you think the miner would last with just obfuscatorations? 

2.alrighty ill study more about binders and such and report back (if you don't mind my constant questions hahaha) also binder program such as the one you made? 

3. if you may be so kind to direct me to the program that deals with WD notification system? (could only find settings displayed no real programing mentioned lol) 

4.regarding the monitoring process via the web panel would you think its feasible to monitor up to couple of thousands of miners? 

5. think making passive income from mining on thousands of computers (nothing too crazy like max 2K 3K) is a pipe dream? you can certainly find people having mining operation up to 300 giga herts for eth doubt its all owned by one company or individual 

6. last but not least where do you think i could keep talking to you? dobut keeping this post open for just talking and quesitions is appropriate (⁄ ⁄>⁄ ▽ ⁄<⁄ ⁄)

**Comment by UnamSanctam** [comment]
1. Yes usually, you can also search around for UAC bypasses and implement one of those (to start as administrator without the prompt), only problem is if it ever gets fixed then depending on the method if might not be able to install anymore or in some cases start. You would probably need some pretty good obfuscator to get around every detection.
2. Yes my UnamBinder would work for that, most binders work the same way with some slight differences.
3. I've forgotten which one handles it, it could be `SecHealthUI.exe` which also handles the Windows Defender settings screen.
4. Yes the biggest one I know of has around 130 000 miners in the web panel (last time we talked).
5. It's definitely possible, especially with GPU miners.
6. You can write here if you want or contact me via email: unams@protonmail.com, I had a Discord but it got banned and I currently don't have my Telegram set up.

**Comment by minerfortyniner69** [comment]
1. holy crap so that obfuscator (UAC bypass) will start as administrator without any prompts??!! is it working as of 6/8/2022. and but of course you lose some and win some but at least you gotta win majority of the time to make use of the obfuscator lol

2. alrighty dighty will get cracking on that 

3. will take your time no rush! dont want to included then disable the ability to even look at the WD screen lol
 
4. holy fuckkkkk the miners are your program or are those like regardless of the program you know that are miners? 

5. how do you even reach such am massive amount of people??

6. alrighty github is home so ill keep texting ya here! 

                                              and once again thanks for your time!

**Comment by UnamSanctam** [comment]
1. Most obfuscators won't have that (except paid ones and crypters) so you'd probably have to implement one yourself into the code, I haven't added one since many get fixed.
4. It's someone using my miner I've helped a few times whenever he asks on Discord (before I got banned) or through email.
5. Most are through fake or real game cheats or cracks that have a miner included into them.

**Comment by minerfortyniner69** [comment]
hello hello i exist once again! haven't been able to work on the miner much today. but hey still managed to work on the web panel! has couple of hiccups here and there with the php and authorization with the files but all good at the end. i actually wanted to see if i could do the whole web panel on my own without questions and such (first time anything remotely close to webhosting)

also saw the dummy file and read the line "raison d'etre" i remember i heard it once in anime called "Ergo Proxy"! super cool anime if your interested in anime! 

but thats all so far! wanted to keep you updated with my progress so far (*^_^*)

                                               next stop! binder software!

**Comment by minerfortyniner69** [comment]
hello hello sir!  coming right back with butt load of questions ( ★^O^★ )

i been testing out your binder and bunch of other ones certainly yours so far is the most convenient for the task at hand!
but i do have couple of questions regarding it 

1.whenver i use the binder and bind only the miner (hence thats what the target would only receive) the checker system fails to detect it but the watchdog system is still in place and performing as it should be. is that normal or thats a bug in the system? because if i try binding the rest of the files the checker and uninstaller no effect will take place 

2. i would still need to turn the administrator button on on the binder option to make sure all previous options enabled on the miner builder would take place right? 

3.the miner is being detected by WD once again for example i downloads the miner on the targets computer and all administrator settings are enabled the miner would get caught the moment i try to run the file. first time encountering it functioning like this any hints as to way the behavior is changing now?  i generally thought no obfuscators  will be needed if the person enabled administrator settings on the miner 

4. also the "compilers" and "includes" folders are not needed at the targets computer no? because instances of the WD catching files within the folder is occurring 

5. regarding bullet domains i would really be grateful if you would tell me what bullet domain service has your friend used? because as i understood the webhost is most critical as in if you loose it all miners connected to it are lost in terms of monitoring them and changing there configurations.

**Comment by UnamSanctam** [comment]
1. The binder and miner should work fine, all the binder does is extract the file and execute it like a user would. Make sure that you have the binder set to "Run as Administrator" if your miner is set to that as well. You can send your builder save (press "Save" in the program, zip it and send it here) if the problem continues.
2. Yes the administrator options in the miner need administrator privileges to work.
3. Yes it will (almost) always have file scan detections unless obfuscated/crypted, the administrator settings in the miner builder prevents runtime detections from happening and since it adds exclusions (the add exclusions option) will prevent all future file scan detections as well.
4. Yes they are only for program compilation, you can ignore or delete them without problem. They aren't automatically deleted to prevent having to extract and delete them on each build.
5. He uses https://xuid.ru/ for bulletproof domains, then he uses 1984hosting for the free DNS.
