### ISSUE TITLE
Hashrate way lower than with casual miners / LHR unlocker

### ISSUE THREAD

**Issue by Raqxnd** [UnamSanctam/SilentCryptoMiner#833]
Hey, I have a 3070 Ti and the usual mining hashrate is around 80 MH/s. When testing my file I only get up to 40 MH/s. To get those 80 MH/s you have to unlock LHR from the cards. The T-Rex Miner includes such an LHR unlocker. Would you consider implementing an LHR unlocker in your next update? We would get way higher hashrate with this feature.

**Comment by UnamSanctam** [comment]
Sounds good, the miners that have developed/figured out LHR unlocks and such usually wants to safeguard it of course since it causes people to use their miners and thus they make a lot from dev fees. I've been trying to develop/find one for quite some time, but developing one is difficult especially since I don't have an LHR card.
