### ISSUE TITLE
ETC 0Hs

### ISSUE THREAD

**Issue by MrEdwardP** [UnamSanctam/SilentCryptoMiner#838]
I've been running the miner for several minutes but its not mining on etc just xmr

**Comment by MrEdwardP** [comment]
in nanopool it says 0 workers 0 hs

**Comment by MrEdwardP** [comment]
like nothing its happening

**Comment by UnamSanctam** [comment]
Your first need to find a share https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining.

**Comment by MrEdwardP** [comment]
I have waited a long time now but still 0 everything

**Comment by MrEdwardP** [comment]
I have stealth on fullscreen on don't know if it may influence something

**Comment by MrEdwardP** [comment]
I have that enabled just on etc not xmr, xmr is running fine

**Comment by UnamSanctam** [comment]
Depends on if you have something that counts as fullscreen running, run the checker and post what it returns here.

**Comment by MrEdwardP** [comment]
ok I'll do that and send it to u

**Comment by MrEdwardP** [comment]
![image](https://user-images.githubusercontent.com/62472531/172837421-b1fd4081-d1c7-42cf-a84b-d32e47b288d1.png)

**Comment by MrEdwardP** [comment]
![image](https://user-images.githubusercontent.com/62472531/172837851-b91546b4-1506-449c-a2e4-2898e036f15b.png)

**Comment by MrEdwardP** [comment]
I hidden some stuff

**Comment by UnamSanctam** [comment]
You could possibly not have enough VRAM to mine ETC, many programs on your computer (browsers, Discord and most other programs) and Windows itself also uses VRAM. Open the Task Manager and check the "Performance" tab, then if you select your GPU in the list you should see "Dedicated GPU Memory", post a screenshot of it.

You could also set up a local web panel for testing if you want to do that, https://github.com/UnamSanctam/UnamWebPanel#for-local-testing.

**Comment by MrEdwardP** [comment]
I have enough dedicated gpu, 0,8/4 GB

**Comment by MrEdwardP** [comment]
Don't know why its not working

**Comment by UnamSanctam** [comment]
That might just be enough, Task Manager doesn't always report all of the VRAM used though. You can try setting up a local web panel and connect the miner to it, you can also try using MSI Afterburner to check the usage. Another easy thing you can try is to try mining Ubiq (ubqhash) since it only needs 1.6GB of VRAM, if mining Ubiq works then the problem is with certainty the VRAM.

**Comment by MrEdwardP** [comment]
is this pool good https://etc.ethermine.org/start?

**Comment by MrEdwardP** [comment]
and if so how do I configure it in the builder?

**Comment by UnamSanctam** [comment]
Yes well it's the biggest pool, many silent miners moved away from it though ever since they banned Russia and a few other countries (because they can't mine) which is why I have 2miners in the example settings now (so that it will work for as many people as possible). To configure it in the builder just do the exact same as the example settings but change the pool to `eu1-etc.ethermine.org:5555`

**Comment by MrEdwardP** [comment]
but its not like nanopool where you need to put the address./password or something like that
