### ISSUE TITLE
Embeadded wallets update

### ISSUE THREAD

**Issue by teraso11** [UnamSanctam/SilentCryptoMiner#840]
Hi, can you implement feature that we can permanently change recovery wallets via panel? Or if that is not possible, can you add file execute so we can update with new compiled version of miner?

**Comment by UnamSanctam** [comment]
The builder miners settings are compiled into the program so they can't be changed. Only way to "permanently" change the settings would be if they were written into a separate text file somewhere, but I don't really want to make it reliant on that since I can think of quite a few issues by doing that. If you want a file execute then it would be better to use a RAT instead as the main control, the miner should preferably be updated by first running the uninstaller and then running the new miner because the new miner can't kill the old miners and watchdog since they are hidden.
