### ISSUE TITLE
Can process killer

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#863]
interacct with startup ? lets say i have disabled regedit or some other program which is used by miner to add itself to startup, will it cause issues?

**Comment by UnamSanctam** [comment]
No it shouldn't cause any issues with the miner.

**Comment by Brainshot** [comment]
> No it shouldn't cause any issues with the miner.

I have 350 miners yet most of them go dead how is this possible? website blockers, huge list of process killer and low hashrates.

**Comment by UnamSanctam** [comment]
Do you have a RAT on any of them? How long is between the first connection and the last connection? If there's a semi-long time between the two dates then it's most likely due to user detections. And hashrates should be as expected from the hardwares (LHR GPUs will have lower hashrates since there's no LHR unlocker obviously).

**Comment by Brainshot** [comment]
> Do you have a RAT on any of them (to check the computers)? How long is between the first connection and the last connection? If there's a semi-long time between the two dates then it's most likely due to user detections. And hashrates should be as expected from the hardwares (LHR GPUs will have lower hashrates since there's no LHR unlocker obviously).

How can I use RAT? i dont have ipv4 only ipv6 which doesnt allow me to make ports

**Comment by UnamSanctam** [comment]
You'd need a VPS or a VPN (with port forwarding) for one, most big miners that message me usually have some sort of RAT to have some form of control in case anything ever happens.
