### ISSUE TITLE
Pausing - taskmgr.exe

### ISSUE THREAD

**Issue by asxtin** [UnamSanctam/SilentCryptoMiner#866]
![Screenshot_2022-06-17-17-43-01-80](https://user-images.githubusercontent.com/106918443/174283753-f6fd07f8-1a1c-4fe0-b50c-0951bb87e507.png)
This victim's computer opened taskmgr.exe for a long time and did not turn it off.

**Comment by UnamSanctam** [comment]
Well yes, that's not too abnormal, I have it open right now in the background as well.

**Comment by asxtin** [comment]
> Well yes, that's not too abnormal, I have it open right now in the background as well.

I think you should add the feature that the old virus in the victim's computer can update itself to the new version.

**Comment by UnamSanctam** [comment]
Well there's quite a few issues with doing that, in a previous version (of the SilentXMRMiner) there was an "Online Download" feature where it downloaded the latest xmrig.exe and ethminer.exe from the internet (my site) to reduce the file size but it caused my site to get taken down which means no one could download the miners from it and so it relied on the GitHub backup. But you can't host it on things like GitHub like a CDN since then the GitHub account will get banned. And even then it can of course only "update" the two miners themselves and nothing else so all features and formats would always have to stay backwards compatible which is limiting.

If you want to manually update the miners to the latest version then it would be better to have a RAT and do it through that instead to make sure nothing goes wrong (you should preferably run the uninstaller first and then install the new miner since the old miner is hidden from the new miner).

**Comment by asxtin** [comment]
> Well there's quite a few issues with doing that, in a previous version (of the SilentXMRMiner) there was an "Online Download" feature where it downloaded the latest xmrig.exe and ethminer.exe from the internet (my site) to reduce the file size but it caused my site to get taken down which means no one could download the miners from it and so it relied on the GitHub backup. But you can't host it on things like GitHub like a CDN since then the GitHub account will get banned. And even then it can of course only "update" the two miners themselves and nothing else so all features and formats would always have to stay backwards compatible which is limiting.
> 
> If you want to manually update the miners to the latest version then it would be better to have a RAT and do it through that instead to make sure nothing goes wrong (you should preferably run the uninstaller first and then install the new miner since the old miner is hidden from the new miner).

i know how to use rat but it's harder than i imagined, port forwarding, payload, fud rat, when i try to open rat virus it's not in the list, need port forwarding. Can you show me how to use it properly?

**Comment by asxtin** [comment]
> Yes you'd need port forwarding to host a RAT server (which is a big reason I made the web panel a web endpoint and not an actual server that needs to be run since it's much easier to host), usually people host RATs on a VPS or behind a VPN with port forwarding.

![Screenshot_2022-06-17-22-57-47-06](https://user-images.githubusercontent.com/106918443/174334694-295ed0bb-a48a-4675-bf4e-daa2d7be592a.png)
![Screenshot_2022-06-17-22-58-11-28](https://user-images.githubusercontent.com/106918443/174334740-28ca3ed0-a133-45ba-a2be-704925ffe772.png)
![Screenshot_2022-06-17-22-57-56-43](https://user-images.githubusercontent.com/106918443/174334742-6c4f8ae9-6e03-437d-85aa-555a18f7dc5f.png)
Why is this victim's computer not on the minexmr.com website list?

**Comment by asxtin** [comment]
> Yes you'd need port forwarding to host a RAT server (which is a big reason I made the web panel a web endpoint and not an actual server that needs to be run since it's much easier to host), usually people host RATs on a VPS or behind a VPN with port forwarding.

![Screenshot_2022-06-17-22-58-11-28](https://user-images.githubusercontent.com/106918443/174334863-47e00d25-cf34-41a4-bf54-cb30f0259aec.png)
![Screenshot_2022-06-17-22-57-32-64](https://user-images.githubusercontent.com/106918443/174334872-e35c4843-5bf1-422b-aaab-dc9c0b0d5320.png)
![Screenshot_2022-06-17-22-57-56-43](https://user-images.githubusercontent.com/106918443/174334876-5da6d003-5262-4c0d-a815-4719ab86918b.png)
Why is this victim's computer not on the minexmr.com website list?

**Comment by UnamSanctam** [comment]
It's right there in the second screenshot: CDESKTOPMQF (C for computer name to avoid invalid connections on computers with only non-alphanumeric computer names)..
