### ISSUE TITLE
online download

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentCryptoMiner#883]
you can throw off an example code for downloading miners from the Internet

**Comment by UnamSanctam** [comment]
Here: https://pastebin.com/jeGePMX1, I made a new one based of the old code.

**Comment by UnamSanctam** [comment]
It's because it first downloads a string from the link, if you only want to download the data directly then you don't need the DownloadString part and can use DownloadData directly, I did it that way since I first had a URL that led to a site that gave the final download link (so that it can be changed). And don't download directly from my GitHub when you do it in the "production" later since that's against the Terms of Service and might get me banned.

**Comment by Toxenskiy** [comment]
ok thanks

**Comment by Toxenskiy** [comment]
this code doesn't work

![image](https://user-images.githubusercontent.com/55586522/175232800-a68c56c4-8ea0-436a-8ff2-8e1c6a8721c0.png)

**Comment by UnamSanctam** [comment]
What about it doesn't work? You might have to enable SSL for the web client as well.

**Comment by Toxenskiy** [comment]
how can i do this?

**Comment by UnamSanctam** [comment]
You should try writing the downloaded bytes to a file to see what it got from the DownloadData call.

**Comment by Toxenskiy** [comment]
The code for downloading xmrig.zip works, maybe something goes wrong?

**Comment by UnamSanctam** [comment]
Then that code looks like it should work, does it work if you do it the normal way?

**Comment by Toxenskiy** [comment]
your assumption about "ssl" is correct
