### ISSUE TITLE
Learner

### ISSUE THREAD

**Issue by AspectKraken** [UnamSanctam/SilentCryptoMiner#9]
hi I'm new/newb to coding and I want to learn how to create applications like yours!
if u could recommend me some apps, courses, techniques or some coding secret's/websites,
and what programming languages is this coded in and etc.
I have grown fond of the kind of applications u create and am curious on how u create it.
if u could right back in GitHub or direct message me in Discord(Aspect#4853)
I would greatly appreciate it

**Comment by UnamSanctam** [comment]
Hey, I've been programming for a very long time so it was quite some time ago since I was first learning things but when I first started I learnt by just going straight into programming while watching YouTube videos about programming and similar things. It's also easier to learn when striving to create something about what you're passionate about.

For this program the miner itself is programmed in C++, the miner installer, injector and watchdog is programmed in C# and the shellcode loader is programmed in C.

**Comment by AspectKraken** [comment]
what's the difference C++,C# and C? they all sound similar 
and what apps did u use?

**Comment by UnamSanctam** [comment]
You can see the differences here: https://csharp-station.com/understanding-the-differences-between-c-c-and-c/ and here: https://www.upwork.com/resources/c-sharp-vs-c-plus-plus. But C++ is used for the miner itself (and is used by all other miners) due to its speed. I use C# for the installer/injector since it's easier to get things working quickly without using big external libraries (like in C++)  and it also allows people to modify it more easily if they want to add some feature. C is used for the shellcode loader since there aren't really any small portable C++ compilers that I can ship together with the miner so I have to use C.

When programming in the miner (C++) and miner installer/injector (C#) I use Visual Studio and when programming in C I use anything like notepad++ or just normal notepad, doesn't matter much for me.

**Comment by AspectKraken** [comment]
and i have one last question this process : MsMpEng.exe its the windows defenders process when im making 2 miners in through this miner should i put both kill process : MsMpEng.exe,

**Comment by UnamSanctam** [comment]
Yes I would do that, ensures that if some miner doesn't run or is closed for whatever reason then it will still try to kill MsMpEng.exe.
