### ISSUE TITLE
ravencoin for gpu

### ISSUE THREAD

**Issue by asxtin** [UnamSanctam/SilentCryptoMiner#909]
can you tell me how to configure raven coin in unam miner?

**Comment by UnamSanctam** [comment]
Create a new miner by clicking "Add", then select "Ravencoin" in the list, then enter a Ravencoin pool and wallet address, then on the "Mining" tab disable "CPU Mining" and enable "GPU Mining".

**Comment by asxtin** [comment]
> Create a new miner by clicking "Add", then select "Ravencoin" in the list, then enter a Ravencoin pool and wallet address, then on the "Mining" tab disable "CPU Mining" and enable "GPU Mining".

why i create it the exe file is more than 32,000 kb?

**Comment by UnamSanctam** [comment]
Because of xmrig CUDA libraries, otherwise you won't be able to mine on Nvidia cards.

**Comment by asxtin** [comment]
> Because of xmrig CUDA libraries, otherwise you won't be able to mine on Nvidia cards.

Can monero coin mine with gpu?

**Comment by UnamSanctam** [comment]
> Can monero coin mine with gpu?

Yes but it's not very profitable since Monero is designed to be mined with the CPU only.

**Comment by asxtin** [comment]
> 

So which cryptocurrency mines gpu for weak computers?🤔

**Comment by asxtin** [comment]
> > Can monero coin mine with gpu?
> 
> Yes but it's not very profitable since Monero is designed to be mined with the CPU only.

So which cryptocurrency mines gpu for weak computers?

**Comment by asxtin** [comment]
> > Can monero coin mine with gpu?
> 
> Yes but it's not very profitable since Monero is designed to be mined with the CPU only.

on my list there are more than 10 victim computers but all of them are showing not enough free vram which really makes me depressed

**Comment by UnamSanctam** [comment]
None really, profitability always depend on competition, so you're going to be competing against good GPUs. The lowest requirement GPU minable coin (with some "good" degree of profitability) is probably Ubiq (Ubqhash) since it only requires 1.6GB of VRAM.

**Comment by asxtin** [comment]
> None really, profitability always depend on competition, so you're going to be competing against good GPUs. The lowest requirement GPU minable coin (with some "good" degree of profitability) is probably Ubiq (Ubqhash) since it only requires 1.6GB of VRAM so you can try that.

Now I'm very confused and don't know where to start about this silent miner, I'm very annoyed when the list of victim computers shows 0H/s:/. Can you show me which cryptocurrency is suitable for newbies like me?🤔

**Comment by UnamSanctam** [comment]
It depends on that computers they have, lower requirement coins have lower profitability while higher requirement coins have higher profitability. For GPU coins the high-end is ETH, medium-end is ETC and low-end is UBQ, RVN is almost the same as ETC in terms of requirements.

ETH requires 4.9GB VRAM.
RVN requires 3.4GB VRAM.
ETC requires 3GB VRAM.
UBQ requires 1.6GB VRAM.

And the profitability is in the same order as well, so ETH has the most profit and UBQ has the least, but in the current market they aren't too different in terms of profitability https://whattomine.com/coins.

For CPU there are many, many different coins to mine, but the most common coin to mine is Monero, but some extremely low-end computers can't always mine it due to a lack of resources. So for those computers, then mining any CryptoNight coin or maybe some other variation of RandomX can be good since they have less memory requirements.

**Comment by asxtin** [comment]
> 

okay this time i will try and thank you for helping me bye👍
