### ISSUE TITLE
ethminer.exe

### ISSUE THREAD

**Issue by varysuzuki** [UnamSanctam/SilentCryptoMiner#936]
Hey, could i possibly get the source to the ethminer.exe?

**Comment by UnamSanctam** [comment]
Yes what @Werlrlivx posted is what it's based on, I haven't created a repository with the changes to it though, I've posted quite lengthy posts before about it but the main issue for me right now is time, currently I don't have time to maintain all the required repositories, if I wanted to post all sources I would have to create and maintain the following repositories:

- Custom ethash repository
- Custom OpenCL repository
- Custom ethminer repository
- Custom xmrig repository
- Custom xmrig-cuda repository
- unamlib  repository (my own library I use for xmrig and ethminer for common code)

Which I don't really have time to do, especially since they are very complicated compared to my current repositories.

**Comment by shainodev** [comment]
> Yes what @Werlrlivx posted is what it's based on, I haven't created a repository with the changes to it though, I've posted quite lengthy posts before about it but the main issue for me right now is time, currently I don't have time to maintain all the required repositories, if I wanted to post all sources I would have to create and maintain the following repositories:
> 
> * Custom ethash repository
> * Custom OpenCL repository
> * Custom ethminer repository
> * Custom xmrig repository
> * Custom xmrig-cuda repository
> * unamlib  repository (my own library I use for xmrig and ethminer for common code)
> * Custom r77-rootkit repository
> 
> Not including all the ethminer dependencies that you have to compile statically on your own unless maybe I would include the premade DLL's for those. The normal ethminer is compiled to require Visual C++ which of course not everyone has, so I changed everything to compile statically, tragically this also means that you have to compile all the dependencies (boost, CLI11, ethash, JsonCpp, OpenCL and OpenSSL from what I can remember) statically as well.
> 
> So maintaining all those repositories is something I really don't have time to do (since unfortunately I have a lot of work), especially since they are very complicated compared to my current repositories which are just user-friendly C# builders that I've made to be as easy to build and use possible.

i mean you dont have to create a repository u could just send the source and not provide help for it ig but its understandable if u cant do that.

**Comment by GjergjiFloychi** [comment]
> Yes what @Werlrlivx posted is what it's based on, I haven't created a repository with the changes to it though, I've posted quite lengthy posts before about it but the main issue for me right now is time, currently I don't have time to maintain all the required repositories, if I wanted to post all sources I would have to create and maintain the following repositories:
> 
>     * Custom ethash repository
> 
>     * Custom OpenCL repository
> 
>     * Custom ethminer repository
> 
>     * Custom xmrig repository
> 
>     * Custom xmrig-cuda repository
> 
>     * unamlib  repository (my own library I use for xmrig and ethminer for common code)
> 
>     * Custom r77-rootkit repository
> 
> 
> Not including all the ethminer dependencies that you have to compile statically on your own unless maybe I would include the premade DLL's for those. The normal ethminer is compiled to require Visual C++ which of course not everyone has, so I changed everything to compile statically, tragically this also means that you have to compile all the dependencies (boost, CLI11, ethash, JsonCpp, OpenCL and OpenSSL from what I can remember) statically as well.
> 
> So maintaining all those repositories is something I really don't have time to do (since unfortunately I have a lot of work), especially since they are very complicated compared to my current repositories which are just user-friendly C# builders that I've made to be as easy to build and use possible.

It would be perfectly acceptable to post a tarball of the code in the releases.

**Comment by UnamSanctam** [comment]
> i mean you dont have to create a repository u could just send the source and not provide help for it ig but its understandable if u cant do that.

> It would be perfectly acceptable to post a tarball of the code in the releases.

Sure but it would also create the same kinds of problems, I could provide boost, CLI11, JsonCpp and OpenSSL pre-compiled for ethminer which would make it easier to build but I would still need to provide the modified ethash, OpenCL, unamlib, ethminer, xmrig and xmrig-cuda projects for manual compilation to give the source for anyone to change things since all of them contain important files for anyone that wishes to change things so they can't really be pre-compiled. 

The normal ethminer uses hunter to automatically download and compile the dependency packages which makes things a lot easier but since things are modified in my version it does not use hunter but instead needs everything to be compiled and combined together manually. It will also take quite a bit of work from me to make everything dynamic for others to use since all paths and everything are hardcoded at the moment and uses several .bat files to move files to where they should go after compilation due to how my environment is set up.

The instructions to get the requirements (both Visual Studio 2019 and Visual Studio 2022, Cmake, Perl and CUDA Toolkit 11.2), instructions to compile everything and to combine it together would be quite long and difficult to follow so most people would probably need help with building it (I've helped others compile everything before and it usually takes a few hours if they're only semi-experienced), which over time would create quite a few (complicated to solve) issues here in this repository since they would not have their own repositories for it. Unless of course I would say that there's no support at all for those projects but that goes against my personal philosophy, I don't like to release something unless I'm fully prepared to help anyone that needs help with it. Unfortunately most people won't be as good with computers as you two are which makes the whole process a lot harder.

**Comment by varysuzuki** [comment]
oh, well unfortunate. oh and one more question while im already here i dont want to create another repository, is DLL hijacking a good idea? cause i tried dll hijacking winrar's thingy RarExt.dll in c:/program files/winrar (it loads the dll when u right click on a file) it works with a messagebox but stops working when i try stuff like IsAdmin or shellexecutea and when the person closes the right click context menu then the dll closes. and this isnt good for persistence/stability. and idk what i should do?

**Comment by UnamSanctam** [comment]
> oh, well unfortunate. oh and one more question while im already here i dont want to create another repository, is DLL hijacking a good idea? cause i tried dll hijacking winrar's thingy RarExt.dll in c:/program files/winrar (it loads the dll when u right click on a file) it works with a messagebox but stops working when i try stuff like IsAdmin or shellexecutea and when the person closes the right click context menu then the dll closes. and this isnt good for persistence/stability. and idk what i should do?

For what are you using DLL hijacking in this situation, are you trying to use it instead of "installing" something using the registry or Task Scheduler? In that case then using that isn't a bad idea since people right click on files relatively often, I would probably use the DLL hijacking to inject a program (RunPE) or run a program somewhere on the disk to make it "persistent", have you tried catching the error you get from attempting ShellExecuteA?

**Comment by varysuzuki** [comment]
> > oh, well unfortunate. oh and one more question while im already here i dont want to create another repository, is DLL hijacking a good idea? cause i tried dll hijacking winrar's thingy RarExt.dll in c:/program files/winrar (it loads the dll when u right click on a file) it works with a messagebox but stops working when i try stuff like IsAdmin or shellexecutea and when the person closes the right click context menu then the dll closes. and this isnt good for persistence/stability. and idk what i should do?
> 
> For what are you using DLL hijacking in this situation, are you trying to use it instead of "installing" something using the registry or Task Scheduler? In that case then using that isn't a bad idea since people right click on files relatively often, I would probably use the DLL hijacking to inject a program (RunPE) or run a program somewhere on the disk to make it "persistent", have you tried catching the error you get from attempting ShellExecuteA?

in my case it's a really bad idea to use rarext, im using it so i dont have to download or add anything to startup so i can just drop a dll and thats it, RarExt.dll when i restarted my pc and still used my malicious version of RarExt.dll then my explorer kept crashing (kinda the same way as when i used r77 rootkit and it injected into explorer) and didnt want to work unless i deleted it and that was when the rarext.dll did ShellExecuteA, i want to use cscapi.dll now in C:/Windows, since explorer uses it and it uses it only once on startup so, but i still dont know what to do using a runpe would get detected no?

**Comment by shainodev** [comment]
is it a good idea to create a c# rat instead of a c++ one? will it drastically change the detections since c#'s source is more easily accessible?

**Comment by UnamSanctam** [comment]
Sorry for the late responses, I missed the notifications for this thread.  

> in my case it's a really bad idea to use rarext, im using it so i dont have to download or add anything to startup so i can just drop a dll and thats it, RarExt.dll when i restarted my pc and still used my malicious version of RarExt.dll then my explorer kept crashing (kinda the same way as when i used r77 rootkit and it injected into explorer) and didnt want to work unless i deleted it and that was when the rarext.dll did ShellExecuteA, i want to use cscapi.dll now in C:/Windows, since explorer uses it and it uses it only once on startup so, but i still dont know what to do using a runpe would get detected no?

RunPE getting detected depends on the antivirus and what technique you use, make sure that the cscapi.dll will still return what it's supposed to it might be necessary for the system.

> is it a good idea to create a c# rat instead of a c++ one? will it drastically change the detections since c#'s source is more easily accessible?

It has both upsides and downsides, C# RATs usually have more base detections due to being managed assemblies but finding a good obfuscator is much easier than a crypter, though the detections might not go down as much. A C++ RAT with crypting can usually become FUD much easier but finding a good crypter and then making the crypter work with your RAT is a bit more difficult.

**Comment by shainodev** [comment]
> 

I was on hackforums and some guy said that your monero miner works well, but ethminer always dissapears after 15 minutes or something. do you have anything to say about it?

**Comment by UnamSanctam** [comment]
> I was on hackforums and some guy said that your monero miner works well, but ethminer always dissapears after 15 minutes or something. do you have anything to say about it?

That he's wrong as far as I know? You can see the runtime in the web panel. The longest test I've done with the ETH miner is 5 days and it worked for the full duration.
