### ISSUE TITLE
missfunction

### ISSUE THREAD

**Issue by aoki233** [UnamSanctam/SilentCryptoMiner#941]
my friend have an rtx 3060 but once he clicked on my miner nothing happened my checker tells that the miner isn't actif however when i click on the miner from my pc it's get activated i used you full example btw

**Comment by UnamSanctam** [comment]
Does it say that the watchdog is running on your friends PC?

**Comment by aoki233** [comment]
yes

**Comment by UnamSanctam** [comment]
Is the XMR miner running? I'm guessing that you didn't remove it from the list.

**Comment by aoki233** [comment]
no no i removed because once i cick on the etc miner the watch dog says it's runnig  when i uninsstall it the checker says the miner isn't active

**Comment by aoki233** [comment]
and when someone with another pc try to run it my watch dog deosn't say it's runnig

**Comment by UnamSanctam** [comment]
Add the XMR miner back, then you'll know if it's not running due to the miner of it's due to something like your friends GPU drivers or something similar. If the XMR miner is running but not the ETC miner then it's most likely something with their GPU causing it, or the miner being unable to connect to the pool (for example if the pool has blocked their IP).

If the miner has installed (and "Watchdog" is enabled) successfully then if you run the checker on that computer it should say that the watchdog is running.

**Comment by aoki233** [comment]
okay i will try that but u should know not only my friend there is another guy it true he have an integrated gpu but the watch saying it's not runnig maybe i should build a new miner of your latest update the 2.5?

**Comment by UnamSanctam** [comment]
Yes build one with the latest version, Windows Defender has gotten a few new things like better AMSI detections in newer updates which can block Assembly.Load calls if there's no AMSI bypass/patch.

**Comment by aoki233** [comment]
alright then i will let you know of the results

**Comment by aoki233** [comment]
hey so the first problem i found is the port adress in your example it's should be "etc.2miners.com:1010" while you are making "etc.2miners.com:11010" i told to fix the problem

**Comment by UnamSanctam** [comment]
No, etc.2miners.com:11010 is correct for SSL which it is set to (https://etc.2miners.com/help#servers-ssl).
