### ISSUE TITLE
Recommended collective Pool for all algos?

### ISSUE THREAD

**Issue by LokeYourLord** [UnamSanctam/SilentCryptoMiner#96]
Since ETH mining will soon stop once Ethereum upgrades to ETH 2.0, I am on my way to converting all existing systems to this new miner. However, I currently use Nanopool for ETH, which will, once ETH 2.0 is fully deployed, be completely useless. This software of yours can run ALL these algos you listed at the same time, so what I am curious about, is which collective pool I can use that can accept all of these at the same time (like NiceHash). Which one would you recommend, and how would you set it up @UnamSanctam ?

**Comment by UnamSanctam** [comment]
Well, there's two miners, one ethminer (ethash/etchash) and one XMRig (all the other ones) so with something like "Remote Configuration" you can only edit the miner used itself (since the "Remote Configuration" is read inside the injected miner). When ETH moves to 2.0 I would just switch the ethminers to another ethash or etchash coin. All the other algorithms other than ethash and etchash (with the exception of kawpow) are all not very profitable for GPU mining compared to ethash/etchash. There aren't really any pools that supports all algorithms (neither does NiceHash since it's not even technically a pool, all you fo is sell your hashrate to the highest bidder on NiceHash) but for ETC I usually recommend ethermine or ezil.

**Comment by LokeYourLord** [comment]
I mean will ethash still work on Nanopool even if ETH moves to 2.0?

**Comment by LokeYourLord** [comment]
Also, another question: If I install both the ETH & ETC Miner into the combined SilentCryptoMiner, will it automatically use the one that works best right now?

For example: Currently, ETHASH is most profitable, and needs 6GB VRAM at least. But if in the future, maybe it needs 8GB VRAM or more, and the systems I run it on only have 6GB or less. Will it then automatically stop the ETHASH miner and run ETCHASH instead? Sorry for asking, but this isn't explained anywhere in the wiki if it automatically changes to the most appropriate/best working one at any given time automatically, or exactly how this functions if you choose to include multiple miners (like the NiceHash Miner).

**Comment by UnamSanctam** [comment]
Ethash is just the algorithm, there are many coins that use ethash and not only ETH so it can't really know which one is best automatically since all coins have different DAG sizes and profitability. The most optimal is usually to build the miner with an ETC miner and then check their GPU with the web panel, then if they have a good enough GPU for ETH then you can apply an ETH configuration on them.

**Comment by LokeYourLord** [comment]
Hmm, but can I not also do the opposite and build a Miner with ETH and apply ETC config instead? Or just include both by default? Like, which one will run if I include both at the same time?

**Comment by UnamSanctam** [comment]
Sure but since ETC requires less it would be more efficient to use ETC by default and change it to ETH since then there is less work to do. If you include both then both will run, since they are independent.

**Comment by LokeYourLord** [comment]
Oh ok well that is stupid then if I include both as that would have the effect of basically not mining at all, as most cards can't handle both at the same time. Thank you for clarifying that (might wanna include it in your Wiki to avoid this question in the future).

**Comment by LokeYourLord** [comment]
Oh and one last question: On the old ETH Miner, you had to include (for Nanopool) the worker name + the email in the "Extra data" field. However, this changed, as now the data has to be included after "address.workername/email". The question is:
For the email, you had to use "%40" for the "@" in between "xxxx @ mail.com". Is that still the case, or can I use "@" now?

**Comment by LokeYourLord** [comment]
> Oh and one last question: On the old ETH Miner, you had to include (for Nanopool) the worker name + the email in the "Extra data" field. However, this changed, as now the data has to be included after "address.workername/email". The question is: For the email, you had to use "%40" for the "@" in between "xxxx @ mail.com". Is that still the case, or can I use "@" now?

It would basically look like (cropped version of mine to avoid data leaking) this:
0x5860FBA14b650180c1AD975.{COMPUTERNAME}/myprivatemail%40gmail.com

**Comment by UnamSanctam** [comment]
You can use either the "Extra data" or the "Wallet Address", both work. But if you enter it in the wallet address then you can use @, such as: 
`0x5860FBA14b650180c1AD975.{COMPUTERNAME}/myprivatemail@gmail.com`
You technically don't need an actual email either, so this would work as well:
 `0x5860FBA14b650180c1AD975.{COMPUTERNAME}/Password123`

**Comment by LokeYourLord** [comment]
> You can use either the "Extra data" or the "Wallet Address", both work. But if you enter it in the wallet address then you can use @, such as: `0x5860FBA14b650180c1AD975.{COMPUTERNAME}/myprivatemail@gmail.com` You technically don't need an actual email either, so this would work as well: `0x5860FBA14b650180c1AD975.{COMPUTERNAME}/Password123`

Thank you, that then solves everything for me, as this isn't entirely clear anymore and I wanted to avoid fiddling with it a few times before getting it right. I'd recommend adding this to the wiki too~
