### ISSUE TITLE
Why my miners are at 0 hashes

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#971]
They work somedays and somedays they are 0 hash, now i know this isnt because of gaming or other shit because even when they game they at least had some hashes. But right now even doing nothing they are at 0 hashes.

Do you have a explaination for this?

**Comment by Brainshot** [comment]
Even at idle no hashes. What the hell is happening? are my hashes being stolen i dont understand

**Comment by UnamSanctam** [comment]
0 hashes is almost always due to there being not enough VRAM, since it cannot generate the DAG to begin mining. Try with something like UBQ and see, since UBQ only requires 1.6GB of VRAM it the easiest one to check. If you get hashes with UBQ then it's due to there not being enough free VRAM to mine whatever other things you're trying to mine.

**Comment by Brainshot** [comment]
> 

Come on man i literally have best of GPUs 3080, 3070s all over 3GB Vram, and these PCs are idle without using any games, browsing anything yet dont mine anymore. Yesterday they were mining all fine and even when not idle, but now its not working they are at 0 hashes.

**Comment by Brainshot** [comment]
0 hashes but online and some are idle yet no mining, idle without any games in background just desktop for example. 

This is a big issue / bug or some hash stealing shit.

**Comment by UnamSanctam** [comment]
Try changing the pool then, I can't see your computer or miners so I can't really comment anything beyond common answers. I have nothing open on my computer right now except my browser and my GPU is still using 5GB/8GB of VRAM so it's not that uncommon.

>This is a big issue / bug

Could be but you'll have to check the computers, since it's not something that happens for me.

>some hash stealing shit.

It's obviously not that, since if anyone were to steal hashrate they would obviously fake the numbers and not leave them at 0.

**Comment by Brainshot** [comment]
> Try changing the pool then, I can't see your computer or miners so I can't really comment anything beyond common answers. I have nothing open on my computer right now except my browser and my GPU is still using 5GB/8GB of VRAM so it's not that uncommon.
> 
> > This is a big issue / bug
> 
> Could be but you'll have to check the computers, since it's not something that happens for me.
> 
> > some hash stealing shit.
> 
> It's obviously not that, since if anyone were to steal hashrate they would obviously fake the numbers and not leave them at 0.

I am using nanopool is that an issue? all my settings are right and sometimes they mine perfectly, also how is it possible for the GPU to use that much VRAM just like that?

**Comment by UnamSanctam** [comment]
Try changing it to something else, nanopool does sometimes have problems with their ETC pool (from what people have told me) if that's what you're mining. Which is also why I changed the examples from nanopool to 2miners. I would try 2miners and/or ethermine to see if there's any difference

Modern programs/systems waste a lot of resources, for example if I open a YouTube video then my VRAM usage goes up by 1GB, probably because I have a 4K monitor (to fit more windows on my screen).
