### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by EiderFC** [UnamSanctam/SilentCryptoMiner#972]
I have started the .exe in a virtual machine but when I enter the page I don't see any pc mining, I can't find any checker either, where is it? This is my config
[config.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9244883/config.zip)
I send it in a zip because github won't let me upload an xml

**Comment by UnamSanctam** [comment]
Firstly on the XMR miner you should probably disable "GPU Mining" since you're mining Monero, then you should probably also disable "NiceHash Mining" and "Remote Configuration" since you're not using either.

Then after starting the miner (and after waiting a minute or two) then run `[MINERNAME]-checker.exe` that got built together with your miner, then you'll see if it's running or not.

Then you'll also have to mine at least one share before your miners will appear on the pool: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining.

**Comment by ZDaPlaY** [comment]
only the file x-watchdog.exe is created, no checker is created

**Comment by UnamSanctam** [comment]
Finish building the miner first (you're currently in "Pause for Obfuscation"), after the miner has been built it builds the uninstaller and checker as well.

**Comment by ZDaPlaY** [comment]
![image](https://user-images.githubusercontent.com/88196950/183426160-503bb59c-f7b9-4eaf-9444-bafa907d583d.png)
I have "Pause for Obfuscation" disabled, should I enable it?
![image](https://user-images.githubusercontent.com/88196950/183426228-71631301-b066-48f1-a619-18c45d7a2654.png)
only this file is generated and I have the antivirus disabled, I get this message, it says "the file cannot find the specified file"

**Comment by UnamSanctam** [comment]
No don't enable it, the builder isn't able to find the watchdog file which is why that happens. Try adding an exclusion in your antivirus to the build folder (looks like you're building it on the desktop) because in many antiviruses disabling them doesn't actually disable all of it. Or you can try building it in another folder.

**Comment by ZDaPlaY** [comment]
![image](https://user-images.githubusercontent.com/88196950/183428523-a16a71da-3161-4e12-aa51-30bdc60495ed.png)
I only have windows antivirus and I have it disabled

**Comment by UnamSanctam** [comment]
Yes but Windows Defender can still block and delete things while disabled so add an exclusions as well, otherwise you can also try building it directly on the C: drive, for example create a folder on the C: drive called `build` and build it there. Could also be a problem with your user permissions so try starting the builder as administrator.

**Comment by ZDaPlaY** [comment]
i already got it, create a folder somewhere else and it worked, thanks
