### ISSUE TITLE
Mining Speed 0 h/s

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#973]
Good evening Unam. I will attach a screenshot from one of the machines, which shows the speed when mining monero 0 h/s. I have a few guesses why the speed is 0 h/s:
![1](https://user-images.githubusercontent.com/36513967/182459884-2f43fad5-6d4d-4fda-a9da-883e22c3670e.jpg)
1. Does the machine not have enough RAM to mine Monero?
2. The processor is too weak for mining monero?
Can these two reasons lead to a production rate of 0 h/s. In the miner, the load on the processor is set to 30%

**Comment by UnamSanctam** [comment]
Both are possible, for that CPU when it runs at 100% (can only run on 2 cores) it gets around 500 H/s, you can try increasing the Max CPU since the minimum amount of usage it can use is 50% (1 core). But since it has that CPU (and GPU) then it's indicative that it might not have enough RAM right now.

**Comment by masterjek** [comment]
Thank you very much for the quick response. Are there coins that require less RAM and can be mined on a weaker processor?

**Comment by UnamSanctam** [comment]
Yeah sure, most other algorithms require less, you can try GhostRider (not the most profitable right now I think though) just to see if the lack of resources was the problem.

**Comment by masterjek** [comment]
Understood. Thanks for the help.
