### ISSUE TITLE
How to Remove all installed miners 

### ISSUE THREAD

**Issue by sunqibuhuake** [UnamSanctam/SilentCryptoMiner#977]
Is there a way to remove all installed miners from the device?

I didn't save the uninstall program....

**Comment by UnamSanctam** [comment]
You'll have to find and remove them since they are hidden https://github.com/UnamSanctam/SilentCryptoMiner/wiki#how-do-i-remove-the-miner, if you have not changed the "Startup" settings then they are all in the default location and have the default entry name inside the registry and Task Scheduler. Easiest way is to 1) remove the entry inside the registry and/or Task Scheduler 2) Restart the computer to kill the watchdog without having to find it 3) Remove all the files.
