### ISSUE TITLE
Miner Missing

### ISSUE THREAD

**Issue by Bagsclouds71** [UnamSanctam/SilentCryptoMiner#989]
Hi Unam, i had the miners fully installed but when i checked the registry and task scheduler, i could not find it, do you know where is it stored in 

![image](https://user-images.githubusercontent.com/110482083/183219980-519be5ac-517e-4490-a67f-0ebee164eeaa.png)
![image](https://user-images.githubusercontent.com/110482083/183220023-e93e6d2f-b4a3-40d5-97f0-27998851f07c.png)
![image](https://user-images.githubusercontent.com/110482083/183220054-e020b08e-000a-40b7-8300-064994889f25.png)

**Comment by UnamSanctam** [comment]
Depends on what you chose as the "Entry Name", if you ran it as administrator and if you enabled "Run as System". It doesn't look like it's in those two places, but since it's running then if you ran it as administrator it must have been installed because it runs it from the Task Scheduler if it's installed there.

**Comment by Bagsclouds71** [comment]
Okay thanks unam,much appreciated
