### ISSUE TITLE
Ideal GPU Mining Rate?

### ISSUE THREAD

**Issue by Bagsclouds71** [UnamSanctam/SilentCryptoMiner#998]
What is the ideal GPU percentage for max and ideal to remain undetected in an environment where it is used quite often to games that requires the GPU

**Comment by UnamSanctam** [comment]
Doesn't really matter, the percentage is mostly for fan noise, the miner will automatically decrease its usage if something else needs it. The more important thing that causes lag is the VRAM usage, which is why it can be good to add games into the "Stealth Targets" (like the example settings does it).

**Comment by Bagsclouds71** [comment]
Ohh wow that is great thanks
